### ISSUE TITLE
Consistency of CLI and stack commands

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#102]
**Summary:** 

Usage of CLI and Stack binary are inconsistent.
Refs https://github.com/TheThingsNetwork/lorawan-stack/issues/103

**Why do we need this?**

Improved user experience

**What is already there? What do you see now?**

In cli e.g. for `end-devices`:
```
Usage:
  ttn-lw-cli end-devices [command]

Aliases:
  end-devices, end-device, devices, device, dev, ed, d

Available Commands:
  create      Create an end device
  delete      Delete an end device
  downlink    Application downlink commands
  get         Get an end device
  list        List end devices
  provision   Provision end devices using vendor-specific data
  update      Update an end device
```

And in `stack`:
```
Usage:
  ttn-lw-stack is-db [command]

Available Commands:
  create-admin-user   Create an admin user in the Identity Server database
  create-oauth-client Create an OAuth client in the Identity Server database
```

**What is missing? What do you want to see?**

CLI is fine, for `stack` - have `ttn-lw-stack oauth` and `ttn-lw-stack user`
`oauth` would look something like this:
```
Usage:
  ttn-lw-stack oauth [command]

Available Commands:
  create Create an OAuth client
  update Update an OAuth client
  delete Delete an OAuth client
```
**How do you propose to implement this?**

Same way as it's done for CLI

**Comment by johanstokking** [comment]
The commands in `ttn-lw-stack` are for bootstrapping only. User and client management will be done through the cli by a collaborator or administrator.
