### ISSUE TITLE
Getting started dead links and heading refs

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1029]
#### Summary

Dead links in Getting Started and unnecessary heading references.

#### Steps to Reproduce

1. Run `mage docs:server`
2. Go to http://localhost:1313/gettingstarted/configuration/

#### What do you see now?

Issues:

- Dead link; "configuration documentation"
- Dead link; "networking documentation"
- Potentially other dead links

Heading references (`a name` tags)

#### What do you want to see instead?

No dead links and no named headers.

#### How do you propose to implement this?

Clean up docs

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by htdvisser** [comment]
Let's make sure to always use Hugo's `relref` shortcode for internal references. Those are checked, and we'll see errors/warnings if they break.

**Comment by johanstokking** [comment]
Taking this one over
