### ISSUE TITLE
Configure NetID for OTAA and ABP generated DevAddr

### ISSUE THREAD

**Issue by pdubois22** [TheThingsNetwork/lorawan-stack#105]
**Summary:** 
I haven't seen a way to configure the NetID on the NS. I may have missed something stupid

**Why do we need this?**
Unless I missed something, by default the NetId is zero. Devices are registered in the 0x00/0x01 address range. We need a way to configure the NetId to set a LoRaWAN NetId. Ideally, it should be configurable.

**What is already there? What do you see now?**
I haven't seen anything

**What is missing? What do you want to see?**
configure the netid as an env variable or in the config file.

**How do you propose to implement this?**
use standard config

**Environment:**
lorawan-stack on a linux server

**What can you do yourself and what do you need help with?**

**Comment by johanstokking** [comment]
@pdubois22 thanks for reporting. This is already prepared in NS but not yet exposed through config. That's easy to fix.

For ABP, there's another concern, namely that you may want to use a different NetID for that. In fact, LoRa Alliance issues a separate, smaller NetID to contributor and sponsor members that is intended for ABP.

Now, in my personal opinion, ABP should not be used, except for rare circumstances. We may want to account for the above by having separate NetIDs for OTAA and ABP.

Finally, for ABP, the cli currently generates a DevAddr with NetID 0. If we allow custom NetIDs for ABP, then we need an rpc for the cli to let NS generate a DevAddr.
