### ISSUE TITLE
Console version of the Getting Started guide

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#1055]
#### Summary

We need a Console version of the Getting Started guide.

#### Why do we need this?

Since the Console can now be used for most of the Getting Started guide, it would be helpful to introduce it as a configuration medium in addition to the CLI.

#### What is already there? What do you see now?

There are no real mentions of the Console, but the Getting Started guide for the CLI has been well refined over time.

#### What is missing? What do you want to see?

While keeping the same structure as `/guides/getting-started/cli/`, the following sections should be added:
- Login
- Create Gateway
- Create Application
- Link Application
- Create end-device (OTAA + ABP + Multicast)

#### Environment

Not applicable.

#### How do you propose to implement this?

Documentation in the `docs` folder.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by htdvisser** [comment]
Let's do this ASAP and get it in for the next release
