### ISSUE TITLE
Update sigLen parameter in the CUPS HTTP response to 4 bytes

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#1069]
#### Summary

Update sigLen parameter in the CUPS HTTP response to 4 bytes.

#### Why do we need this?

This parameter has been updated in the [specification](https://doc.sm.tc/station/cupsproto.html#http-post-response).

#### What is already there? What do you see now?

sigLen is set to 2 bytes.

#### What is missing? What do you want to see?

sigLen should be 4 bytes.

#### Environment

`ttn-lw-stack v3.1.0`

#### How do you propose to implement this?

Simple change

#### Can you do this yourself and submit a Pull Request?

Yes

cc: @htdvisser

**Comment by johanstokking** [comment]
Why backlog?

**Comment by KrishnaIyer** [comment]
We don't support firmware updates yet.

**Comment by htdvisser** [comment]
It's an easy, non-important fix, so anyone can pick this up when they're bored and looking for something to do.
