### ISSUE TITLE
Keep form dirty state consistent via initial values

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#1085]
#### Summary

We do not have consistent way to define `initialValues` for the forms across the apps, for example [ApplicationAdd](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-add/index.js#L46-L50), [ApplicationGeneralSettings](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/application-general-settings/index.js#L136).
The main issue is in how `formik` handles setting field values. For example, any field value which is `undefined` is removed from the form state, see [formik setIn](https://github.com/jaredpalmer/formik/blob/master/src/utils.ts#L127). In combination with `yup` that casts values according to their schemas we get inconsistent field values in `initialValues`, `formik` state and submit values.

This causes `formik` to handle the `dirty` state incorrectly.

Reproduce:
1. Create a new application with only `id` specified.
2. Go to the general settings page of the application.
3. See the submit button being disabled (expected behaviour)
4. Update the name/description field
5.  See the submit button not being disabled (expected behaviour)
6. Clean up the fields
7. The submit buttons stays not disabled (shouldnt be the case)

#### Why do we need this?

1. Forms should be `dirty` only if field values that would be sent to the server change
2. The users should not be able to submit forms without any changes
3. We might want to add functionality to notify users when navigating from `dirty` forms without submitting.

#### What is already there? What do you see now?

`<FormSubmit/>` component that disables the submit button if the form is pristine

#### What is missing? What do you want to see?

Consistent way of defining and processing `initialValues` such that `dirty` is always `false` in forms which state is equal to initial values 

#### Environment

browser (console,oauth)

#### How do you propose to implement this?

First, we want to make sure that the field values always fallback to their initial value when being empty. This can be achieved by extending the field component with:
```
  sanitizeValue (currentValue) {
    const { name } = this.props
    const { initialValues } = this.context

    const initialValue = getIn(initialValues, name)
    const initialEmpty = isValueEmpty(initialValue)
    const currentEmpty = isValueEmpty(currentValue)

    // reset field value to the initial value or `undefined` if the current value
    // of the field is empty.
    if (initialEmpty && currentEmpty && currentValue !== initialValue) {
      return initialValue
    }

    return currentValue
  }

  extractValue (value) {
    let newValue = value
    if (typeof value === 'object' && 'target' in value) {
      const target = value.target
      if ('type' in target && target.type === 'checkbox') {
        newValue = target.checked
      } else if ('value' in target) {
        newValue = this.sanitizeValue(target.value)
      }
    } else {
      newValue = this.sanitizeValue(value)
    }

    return newValue
  }
```
This is applicable to `create` forms. 

Second,  we need to generate initial values:
```
import { setIn, getIn } from 'formik'

export const generateInitialValuesFromEntity = (entity, paths = []) => paths.reduce(
  (values, entryPath) => setIn(values, entryPath, getIn(entity, entryPath)), {}
)

// usage in application general settings page
const getInitialValues = application => generateInitialValuesFromEntity(
  application,
  [ 'name', 'description' ]
)

render () {
  ...
  const { application } = this.props
  const initialValues = getInitialValues(application)
  ...
}
```
Note, that this is not the most efficient implementation since `setIn` clones every object, however with this approach `initialValues` will always complient with the way `formik` handles its internal state.

#### Can you do this yourself and submit a Pull Request?

yes

cc @kschiffer what do you think?

**Comment by kschiffer** [comment]
Instead of adding this logic to the form field, couldn't this be solved by casting the initial values over the validation schema?
```js
const validationSchema = Yup.object().shape({
  name: Yup.string()
    .min(3, sharedMessages.validateTooShort)
    .max(50, sharedMessages.validateTooLong)
    .ensure(), // Ensure casting to string (undefined vs empty string)
  description: Yup.string()
    .max(150, sharedMessages.validateTooLong)
    .ensure(),
})

const rawInitialValues = generateInitialValuesFromEntity(…)
const initialValues = validationSchema.cast(rawInitialValues)

// in render():
<Form
  …
  initialValues={initialValues}
>
```
Now the empty string will be rightfully seen as initial value and prevent the submit.

I definitely second the idea of having a `generateInitialValuesFromEntity` function, but we need to make sure that it accounts for arbitrary entity → form value mappings, as we have them for the webhooks form. (Where value structures are transformed) Alternatively, we can continue using manual mapping in these cases.

> We might want to add functionality to notify users when navigating from dirty forms without submitting.

Indeed. Could you open an issue for this?
