### ISSUE TITLE
Stack env prints unnecessary characters for map type.

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#1103]
#### Summary

`ttn-lw-stack config --env ` prints unwanted  characters for map type.

#### Steps to Reproduce

1. Run ttn-lw-stack config --env
2. Check any env of type map. Ex: `TTN_LW_GS_FORWARD`

#### What do you see now?

`TTN_LW_GS_FORWARD="map[:[00000000/0]]"

#### What do you want to see instead?

`TTN_LW_GS_FORWARD=""=00000000/0`

#### Environment

`TTN_LW_GS_FORWARD==00000000/0` for the default option.

#### How do you propose to implement this?

Not sure.

#### Can you do this yourself and submit a Pull Request?

Nyet.

**Comment by htdvisser** [comment]
This isn't technical debt, it's broken.
