### ISSUE TITLE
Change default value for "revoke-all-access" flag on password change to "true"

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/lorawan-stack#1117]
#### Summary

References #1058 

#### Why do we need this?

Currently `--revoke-all-access` flag while changing user password is `false` by default.

From the returned discussion in #1058 , it makes more sense to revoke all access tokens by default upon changing user password.

Also, the flag definition is currently written in snake case, while majority of other flags are defined with dashes. Would be nice to keep it consistent.

#### What is already there? What do you see now?

`usersUpdatePasswordCommand.Flags().Bool("revoke_all_access", false, "revoke all sessions and access tokens after the password is updated")`

#### What is missing? What do you want to see?

`usersUpdatePasswordCommand.Flags().Bool("revoke-all-access", true, "revoke all sessions and access tokens after the password is updated")`

Then, if the user want to keep all their access tokens, they would explicitly specify
`--revoke-all-access=false`

#### Environment

Latest master

#### How do you propose to implement this?

As described above.

cc @johanstokking @htdvisser 

#### Can you do this yourself and submit a Pull Request?

Will do all and submit a PR.

**Comment by johanstokking** [comment]
Good issue, but for next time a quickfix PR is enough referring the discussion to save time
