### ISSUE TITLE
Label Docker images

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#112]
**Summary:** 

Docker images should be labeled. See http://label-schema.org/rc1/

**Why do we need this?**

Because it's good practice

**What is already there? What do you see now?**

No labels

**What is missing? What do you want to see?**

Labeled Docker images

**How do you propose to implement this?**

By passing the labels as arguments in `build_flag_templates` in `docker` section of `.goreleaser.yml` introduced in #109. See https://goreleaser.com/customization/#Docker for more info.

**Environment:**

CI

**Comment by htdvisser** [comment]
Is there any demand for this? Otherwise I think we should just close this.

**Comment by htdvisser** [comment]
Actually, this is really small, I'll see if I can do this today.
