### ISSUE TITLE
Restoring Deleted Applications

### ISSUE THREAD

**Issue by adamsondelacruz** [TheThingsNetwork/lorawan-stack#1121]
#### Summary
When you delete an application and decides to add it back, if fails because it complains that the ID already exists.

#### Steps to Reproduce

1. Remove existing application
2. Add it back using CLI or 
3. Add it back using API

#### What do you see now?
```
{
    "code": 6,
    "message": "error:pkg/identityserver/store:id_taken (ID already taken)",
    "details": [
        {
            "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
            "namespace": "pkg/identityserver/store",
            "name": "id_taken",
            "message_format": "ID already taken",
            "correlation_id": "e68a49d8b874408d97c8c57b15b0838e"
        }
    ]
}
```

#### What do you want to see instead?

Successfullly add back the application

#### Environment

amazon linux using TTN CLI and Postman using API Call

#### How do you propose to implement this?
When user try to insert a deleted application, update the deleted flag to false

#### Can you do this yourself and submit a Pull Request?

...

**Comment by htdvisser** [comment]
Related to https://github.com/TheThingsNetwork/lorawan-stack/issues/1120

**Comment by htdvisser** [comment]
We'd also need to check if 

1. the caller is a user or organization (not an application API key)
2. the caller was previously a member of the entity
3. the caller had sufficient rights on the entity (perhaps make RIGHT_APPLICATION_DELETE also restore)

When restoring the application, we should also consider that the deleted application may have had other members and API keys associated to it. The caller will need to indicate what to do with those, so this may actually require a dedicated API call.

**Comment by htdvisser** [comment]
Turns out we already have another issue for this: https://github.com/TheThingsNetwork/lorawan-stack/issues/604

**Comment by htdvisser** [comment]
Looks like I forgot to close this issue before. This is being tracked in #604.

**Comment by htdvisser** [comment]
This is implemented, and will land in `v3.12`.

**Comment by tomascharad** [comment]
This is happening to me, but for a gateway.

https://nam1.cloud.thethings.network/console/gateways/add

![image](https://user-images.githubusercontent.com/1534092/120079374-7ae3dd80-c081-11eb-988f-5260153deae4.png)

**Comment by htdvisser** [comment]
This is an expected error if a regular user removed a gateway and then a user tries to register a gateway with the same ID. 

When deleting a gateway, the EUI is released, but the ID remains reserved. See also https://www.thethingsindustries.com/docs/reference/id-eui-constraints/#deleted-entities

Only when an admin user "purges" the gateway, the ID is released.
