### ISSUE TITLE
Support specific JS-NS and JS-AS KEK labels and AS-ID

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1131]
#### Summary

Support specific JS-NS and JS-AS KEK labels and AS-ID

#### Why do we need this?

As we cannot (always) derive this from `application_server_address`

#### What is already there? What do you see now?

- KEK labels are now `{ns|as}:<{network|application}_server_address>`
- AS-ID is the host of `application_server_address`

#### What is missing? What do you want to see?

- Add `{network|application}_server_kek_label` to `EndDevice`
- Add `application_server_id` to `EndDevice`

#### How do you propose to implement this?

Add the aforementioned fields and use these fields if set, otherwise fallback to the current behavior of taking the host name for KEK label and AS-ID.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by bafonins** [comment]
what should be done to the console ui?

**Comment by johanstokking** [comment]
There will be three new fields in `EndDevice`:

- `application_server_kek_label`
- `application_server_id`
- `network_server_kek_label`

These need to be edited with the JS component, also in the Console.

**Comment by bafonins** [comment]
Could you file a new issue for this?
