### ISSUE TITLE
Make NS/AS KEK labels, AS-ID, NetID and claim authentication code editable

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1134]
#### Summary

Make NS/AS KEKs, AS-ID, home NetID and claim authentication code editable in the Console

#### Why do we need this?

User experience

#### What is already there? What do you see now?

No input fields

#### What is missing? What do you want to see?

Input fields in JS section for, AS address + ID + KEK label and NS address + KEK label, home NetID and claim authentication code.

This is only available in cluster-JS.

The fields are;

- `application_server_kek_label` (free-form <= 2 KB length)
- `application_server_id` (free-form, <= 100 length)
- `network_server_kek_label` (free-form, <= 2 KB length)
- `net_id` (6 digit hex, optional)
- `claim_authentication_code{.{valid_from|valid_to|value}}`

#### Can you do this yourself and submit a Pull Request?

No

@kschiffer please reassign if desired.

**Comment by htdvisser** [comment]
Blocked by #579

**Comment by johanstokking** [comment]
Mostly blocked by https://github.com/TheThingsNetwork/lorawan-stack/pull/1616

**Comment by johanstokking** [comment]
Added home NetID and claim authentication code fields

**Comment by johanstokking** [comment]
This is not entirely in progress by #1616; claim authentication code is not part of that (yet)

**Comment by bafonins** [comment]
Regarding `claim_authentication_code` should the users be able to set the date and time, or only the date? @johanstokking

**Comment by johanstokking** [comment]
@bafonins I think the date is fine, but internally it's a timestamp, so including time. If the user specifies 1-1-2021, it will be 1-1-2021 0:00:00, effectively 31-12-2020, so take care of that.
