### ISSUE TITLE
Mage fails on Go 1.13

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1210]
#### Summary

Our Mage tooling fails on Go 1.13 (release candidate)

#### Steps to Reproduce

0. With the current `master` in a Go 1.13-rc1 environment
1. Run `make init` (or `make mage`)

#### What do you see now?

`go run github.com/magefile/mage -compile` fails with 

```
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1
```

#### What do you want to see instead?

It should compile the mage tooling.

#### Environment

Go 1.13-rc1 on macOS Mojave

#### How do you propose to implement this?

By the looks of the error "failed to list non-mage gofiles" we should probably add a normal, empty Go file (`doc.go`) to the root of the repository.

#### Can you do this yourself and submit a Pull Request?

I can investigate some more and see how we can fix it, but if someone else has more time than me, feel free to pick this up.

**Comment by rvolosatovs** [comment]
Taking over this as discussed
