### ISSUE TITLE
Event Stream Cancellation should not be logged as Warning

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1213]
#### Summary

Cancelling event streams currently triggers a Warning in the server log, while this is normal flow, so it should be Info instead.

#### Steps to Reproduce

1. Start the stack
2. Open an event stream from the CLI or Console
3. Close it

#### What do you see now?

```
  WARN Finished streaming call                  duration=990.085699ms error=context canceled grpc_method=Stream grpc_service=ttn.lorawan.v3.Events namespace=grpc request_id=01DJW6DGKXTAGZK3Z082K83G11
```

#### What do you want to see instead?

It should be `INFO`

#### Environment

```
The Things Stack for LoRaWAN: ttn-lw-stack
Version:             v3.1.0-dev
Go version:          go1.13rc1
OS/Arch:             darwin/amd64
```

#### How do you propose to implement this?

For some reason `pkg/rpcmiddleware/rpclog` doesn't recognize the "context canceled" error.

#### Can you do this yourself and submit a Pull Request?

I can, but if anyone else has more time than me, feel free to pick this up.

**Comment by KrishnaIyer** [comment]
✋ 
I'd like to take this one when I have a bit of time..
