### ISSUE TITLE
Web UI support for OAuth Client Authorization and Access Token Management

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1217]
#### Summary

It should be possible to manage authorizations of OAuth Clients and active sessions (access tokens) with the web UI.

This issue only focuses on OAuth Access Tokens and not on User Sessions of the `/oauth` app.

#### Why do we need this?

- Users need to be able to revoke single sessions (access tokens)
- Users need to be able to revoke OAuth client authorizations and all associated sessions (access tokens)

#### What is already there? What do you see now?

We have existing API and CLI support.

#### What is missing? What do you want to see?

Web UI support (either in the Console app, or in the Account/OAuth app) for:

- Listing authorized OAuth Clients of the user
	- Listing Access Tokens of these OAuth Clients
	- Revoking individual Access Tokens
- Revoking these authorizations

#### Environment

Browser

#### How do you propose to implement this?

@kschiffer please think about UI/UX

See the CLI for the calls that need to be made:

- `ttn-lw-cli user oauth authorizations list --user-id admin`
- `ttn-lw-cli user oauth authorizations delete --user-id admin --client-id foobar`
- `ttn-lw-cli user oauth access-tokens list --user-id admin --client-id console`
- `ttn-lw-cli user oauth access-tokens delete --user-id admin --client-id console --token-id 2MUUBY2NSKLKDV47OXOLRE77743AEA4364UW24I`

**Comment by kschiffer** [comment]
Superseded by #3886
