### ISSUE TITLE
OTAA join fails

### ISSUE THREAD

**Issue by berrySkies** [TheThingsNetwork/lorawan-stack#1218]
#### Summary

The OTAA join request from my device fails. It appears that the join-accept message received by the app does not get forwarded to the gateway.

#### Steps to Reproduce

1. Use an OTAA join request from device. (My device is running software from LMIC MCCI library on TTGO module)
2. The join request is visible on the MQQT server and console
3. Look to see if join-accept is received by gateway
[stackConfig.txt](https://github.com/TheThingsNetwork/lorawan-stack/files/3529510/stackConfig.txt)

#### What do you see now?

![screenshot1](https://user-images.githubusercontent.com/5278164/63505880-b0a47b80-c517-11e9-9cf5-ee324618b196.jpg)
![screenshot2](https://user-images.githubusercontent.com/5278164/63505894-b732f300-c517-11e9-8c35-4400262b3f33.jpg)
https://pastebin.com/fTUFHnda...

#### What do you want to see instead?

...

#### Environment

The Things Network Command-line Interface: ttn-lw-cli
Version:             3.1.0
Go version:          go1.12.7
OS/Arch:             linux/amd64

Using MacOS and Docker
...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by berrySkies** [comment]
I'm going to close the issue. Following further investigations I've now managed to get downlink messages sent to gateway and wireless concentrator.

**Comment by Lucianovici** [comment]
Hi, can you please share with us how you fix the issue, I have a similar behaviour with a Multitech Conduit gateway. Please check: https://github.com/TheThingsNetwork/lorawan-stack/issues/1988

**Comment by johanstokking** [comment]
May be closed by #1989
