### ISSUE TITLE
Gateway activity update and wrong time rendering

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1225]
#### Summary

Gateway activity update is not updated and last active time rendering is wrong.

#### Steps to Reproduce

1. Go to one of the connected gateways in the demo environment, i.e. https://demo.thethings.industries/console/gateways/647fdafffe000162
2. See last activity time

#### What do you see now?

These issues are probably separate:

1. The time is shown as `-X`, where `X` is likely seconds. This seems regression; it worked before
2. Sometimes `X` stalls
3. Sometimes, when a gateway connects, events are shown correctly, but it keeps shown as **Disconnected**

<img width="1128" alt="Screenshot 2019-08-22 at 16 01 06" src="https://user-images.githubusercontent.com/13334001/63522323-6364e180-c4f8-11e9-8111-36301c309660.png">

#### What do you want to see instead?

1. The old behavior; i.e. `X seconds ago` 
2. Always keep incrementing `X`, or switch correctly to **Disconnected** state
3. Keep the **Connected** and **Disconnected** states updated

#### Environment

Latest `master` deployed currently at https://demo.thethings.industries

#### How do you propose to implement this?

Not sure

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by bafonins** [comment]
The issue seems to appear only when using Safari.

**Comment by KrishnaIyer** [comment]
@bafonins: I noticed this yesterday on Chrome as well.

**Comment by bafonins** [comment]
> Sometimes, when a gateway connects, events are shown correctly, but it keeps shown as Disconnected

moved to https://github.com/TheThingsNetwork/lorawan-stack/issues/1242
