### ISSUE TITLE
Stack panic when IS is not available

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#1231]
#### Summary

Stack panics and exits with code `2` when IS not available

#### Steps to Reproduce

1. `stack start ns as gs`
2. Generate some traffic e.g. by using simulator

#### What do you see now?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16608e4]

goroutine 99 [running]:
go.thethings.network/lorawan-stack/pkg/gatewayserver.(*GatewayServer).getRegistry(0xc0004611a0, 0x23a6d20, 0xc00136c8a0, 0x0, 0xc00136c8a0, 0x0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/gatewayserver.go:72 +0x84
go.thethings.network/lorawan-stack/pkg/gatewayserver.(*GatewayServer).FillGatewayContext(0xc0004611a0, 0x23a6d20, 0xc00136c8a0, 0x0, 0x0, 0xc001350600, 0xc000000000, 0xc001310d00, 0xc001310d18, 0xc0002c0bd0, ...)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/gatewayserver.go:246 +0x126
go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.(*srv).connect(0xc0006e63c0, 0x23a6d20, 0xc00136c7e0, 0x0, 0x0, 0x0, 0x0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:202 +0x416
go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.(*srv).handlePackets(0xc0006e63c0)
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:171 +0x325
created by go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp.Start
        /home/rvolosatovs/src/go.thethings.network/lorawan-stack/pkg/gatewayserver/io/udp/udp.go:101 +0x225
exit status 2
```

#### What do you want to see instead?

Log error, stating what went wrong and no panic.

#### Environment

Any

#### How do you propose to implement this?

If IS is the cause for this - check if IS is present, if not - log the error and stop execution of RPC. At a later stage we could buffer these by storing in e.g. Redis until the IS is up. Similar to what is going to happen for #560 

#### Can you do this yourself and submit a Pull Request?

Probably, but I guess @johanstokking or @KrishnaIyer can take over this?
@johanstokking I will asign you for now, please change assignment if/as required

**Comment by johanstokking** [comment]
@adriansmares there are 4-5 occurrences where we assume that `ENTITY_REGISTRY` is there, i.e. we call `GetPeer()` and we call it's `Conn()` inline. This panics if `GetPeer()` returns `nil`, which happens while IS is not connected yet.

Please check if `GetPeer()` returns `nil`, and if so, return a (new) error that IS is not available (`Unavailable` error code). Afaik we have similar behavior and errors for other peers, like JS and NS.
