### ISSUE TITLE
C-style array copy spacing

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1235]
#### Summary

C-style array copy spacing and copy braces improvements

#### Steps to Reproduce

1. Select the `< >` button near EUIs or keys
2. Click copy

#### What do you see now?

The clipboard contains, for example: ` 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08`

Notice the space at the start (and not at the end)

#### What do you want to see instead?

No spacing

#### How do you propose to implement this?

No idea, is probably quite simple

#### Can you do this yourself and submit a Pull Request?

Can review

@kschiffer please adjust milestone or assignment

**Comment by htdvisser** [comment]
Not having the curly braces is intentional. Not all languages use `{}` for arrays; some use `[]` instead.

**Comment by bafonins** [comment]
we removed braces here: https://github.com/TheThingsNetwork/lorawan-stack/pull/155

**Comment by kschiffer** [comment]
So what should we prefer: braces or no braces @johanstokking ?

**Comment by johanstokking** [comment]
OK let's leave the braces and then only fix the first space that gets copied. Mind the labels and the milestone; this is no priority at all

**Comment by johanstokking** [comment]
Updated OP
