### ISSUE TITLE
Expand Getting started document

### ISSUE THREAD

**Issue by mrpackethead** [TheThingsNetwork/lorawan-stack#124]
**Summary:** 
Expand the getting started a document with more detail on how to install the stack, and use the CLI, particularly using the CLI remotely. 

**Why do we need this?**
Without this information, its very difficult for someone who wants to stand up the stack ( who is not a stack developer ) for testing their devices/gateways against is very difficult. Its a little bit of a black hole. 

**What is already there? What do you see now?**
The getting started a document in the git repo

**What is missing? What do you want to see?**

(1) Expanding the documentation with more detail to install 
(2) Expanding information on how to use the CLI both locally and remotely. 
...

**How do you propose to implement this?**
If someone could walk me through the process, I would be happy to write 'sys-admin' level documents for people to install on *nix type systems. 

**What can you do yourself and what do you need help with?**
I can write / edit / expand on current documents.   I need some help with being shown how to do it once.   I have a system available running Debian 9, in AWS, which can be used.

**Comment by johanstokking** [comment]
Also adding class C example to the wish list.

**Comment by htdvisser** [comment]
As soon as a v3.0.0 release is tagged, we should stop recommending using the cli in Docker, but use the locally installed (with apt/brew/binary...) version instead.

**Comment by johanstokking** [comment]
I'm doing a quick clarification/typo roundup
