### ISSUE TITLE
Console - add device form - Device Id validation message should include no capitals

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-stack#1257]
#### Summary

Device ID validation message does not include 'only lowercase'

#### What do you see now?

Input errors because of capital letters but the user is not inform of how to fix.
message is "The value must be alphanumeric and contain no spaces"

#### What do you want to see instead?

message is "The value must be alphanumeric, lowercase and contain no spaces"

#### Environment

Browser

#### How do you propose to implement this?

Quick change to stored messages.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
@pgalic96 this is actually what I meant in #1705. Since @mjamescompton doesn't have much time, and this is pretty confusing for users, do you have time to look into this? If so, please reassign the issue to yourself.
