### ISSUE TITLE
Document frontend development workflow

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#129]
**Summary:** 

Frontend development workflow should be more thoroughly documented
References https://github.com/TheThingsNetwork/lorawan-stack/pull/109#discussion_r255879919

**Why do we need this?**

To give our users proper development documentation

**What is already there? What do you see now?**

Nothing

**What is missing? What do you want to see?**

Documented frontend workflow

**How do you propose to implement this?**

@bafonins or @kschiffer should write down what they do to develop console

**Comment by johanstokking** [comment]
Consider this part of #11

**Comment by htdvisser** [comment]
Blocked on #11.
