### ISSUE TITLE
Improve gateway sorting algorithm in NS

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#13]
**Summary:** 

Gateway sorting algorithm in NS can be improved

**Why do we need this?**

To make better gateway choices

**What is already there? What do you see now?**

A very simplistic gateway sorting algorithm

**What is missing? What do you want to see?**

A more efficient gateway sorting algorithm

**How do you propose to implement this?**

Based on experience with v2:

- SNR isn't the only metric; RSSI is also important.
- We may need to filter "incorrect data" (SNR=0, RSSI=0 for example)
- We may want to include gateway uplink utilization to avoid Tx on "valuable uplink gateways"
- We may want to include gateway downlink utilization to be a little bit smarter about downlink gtw 
selection than always selecting one with a full duty cycle
- We may benefit from a little bit of randomness

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/729 by @rvolosatovs

**Comment by johanstokking** [comment]
Prioritize gateway sources over Packet Broker

**Comment by nejraselimovic** [comment]
> Prioritize gateway sources over Packet Broker

@johanstokking is this implemented in the meantime by any chance? Looks like an important issue.

**Comment by johanstokking** [comment]
I don't think this is fully implemented. I'll reschedule for Q3 to revisit.
