### ISSUE TITLE
Generate DevAddr from a prefix

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#130]
**Summary:** 

NS should generate DevAddr from a supplied prefix with a fallback to NetID

**Why do we need this?**

@johanstokking wants this(https://github.com/TheThingsNetwork/lorawan-stack/pull/101#discussion_r255193262)

**What is already there? What do you see now?**

Generation of DevAddr from NetID only

**What is missing? What do you want to see?**

DevAddr from a supplied prefix with a fallback to NetID

**How do you propose to implement this?**

Store the prefix and use it to generate the DevAddr

**Comment by johanstokking** [comment]
I think we need to store the DevAddr in the cluster, or at least GS needs access to it to offload traffic to the Packet Broker.
