### ISSUE TITLE
Add organization general-settings page

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#1306]
#### Summary

The console should provide functionality to update existing oganizations.
References: https://github.com/TheThingsNetwork/lorawan-stack/issues/1205

#### Why do we need this?

The users should be able to update existing organizations in web ui.

#### What is already there? What do you see now?

- Organizations service in the js sdk
- Redux setup for creating/listing organizations

#### What is missing? What do you want to see?

- Add `update` and `delete` methods to the organization service
- Extend console api definitions for the `update` and `delete` methods
- Refactor `<OrganizationForm />` to support updating
- Extend `<SideNavigation />` to include the `General Settings` entry
- Contact information (?) cc @kschiffer @htdvisser 

#### Environment

browser (console)

#### How do you propose to implement this?

Similar to applications

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
Contact information still needs to be added to all entities, maybe better to do that all at once in its own issue/pr.
