### ISSUE TITLE
Change container width constraint

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#1327]
#### Summary

<img width="765" alt="Screenshot 2019-09-06 at 09 39 15" src="https://user-images.githubusercontent.com/16374166/64406397-5dd7d180-d08a-11e9-9307-2134148aaf3e.png">
<img width="765" alt="Screenshot 2019-09-06 at 09 40 05" src="https://user-images.githubusercontent.com/16374166/64406398-5dd7d180-d08a-11e9-9cd2-98b2118548cb.png">
<img width="765" alt="Screenshot 2019-09-06 at 09 40 19" src="https://user-images.githubusercontent.com/16374166/64406399-5dd7d180-d08a-11e9-9bd6-457b66d9eb26.png">

#### Why do we need this?

Dont jam table columns when possible.
We should utilize all available space.

#### What is already there? What do you see now?

* Table components
* Container constraints on list pages

#### What is missing? What do you want to see?

Something like this:
<img width="765" alt="Screenshot 2019-09-06 at 09 43 14" src="https://user-images.githubusercontent.com/16374166/64406559-c9ba3a00-d08a-11e9-9ade-c4462521f297.png">

#### Environment

browser (console)

#### How do you propose to implement this?

Change responsive grid sizes/constraints

#### Can you do this yourself and submit a Pull Request?

can review

**Comment by kschiffer** [comment]
> We should utilize all available space.

This was fixed via #1330.

> Dont jam table columns when possible.

Will do. Needs some planning via #1172.

**Comment by kschiffer** [comment]
Closing this since it has since been resolved. Table columns won't jam anymore since tables have a min-width in smaller screensizes and enable scrolling. More improvements will come for event views via #2893
