### ISSUE TITLE
Support absolute paths in fetch package

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#1340]
#### Summary

Fetch package should support absolute paths

#### Why do we need this?

There are use cases, where absolute paths are necessary to use, e.g. for usage of Docker secrets(which are available at `/run/secrets/<name>`). This is especially important for interop client configuration.

#### What is already there? What do you see now?

No absolute path support

#### What is missing? What do you want to see?

Support absolute paths without breaking configs

#### How do you propose to implement this?

Allow for fetchers to be rooted at a path, i.e. prepend the root path to requested path.
For a fetcher with a root path `r` and requested path `p`, the resulting path is:
```go
if r == "" {
   return p
}
return join(r, p) // specific to the fetcher implementation
```

Only add the basepath in basepath fetcher if requested path is not absolute.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Why is this not closed by #1341 ?
