### ISSUE TITLE
Basic Station xtime is truncated to 32 bit

### ISSUE THREAD

**Issue by beitler** [TheThingsNetwork/lorawan-stack#1351]
#### Summary

During processing of `updf` messages originating from a Basic Station gateway, the 48-bit timestamp part of `xtime` is truncated to 32 bit. As a result, class A downlink messages cannot be scheduled after the first 32 bit rollover of the microsecond counter. 

#### Steps to Reproduce

1. Append `ext |= ((sL_t)0xAA<<32);` to https://github.com/lorabasics/basicstation/blob/master/src/timesync.c#L383 in Basic Station to simulate multiple 32-bit rollovers.
2. Do a join request and observe the protocol messages:

*Station log*
```
2019-09-12 08:13:06.298 [S2E:VERB] RX 868.1MHz DR5 SF7/BW125 snr=13.8 rssi=0 xtime=0xC200AA0B2FA950 - jreq MHdr=00 JoinEui=ffff:ffbb:: DevEui=ffff:ffaa:e11:e552 DevNonce=2656 MIC=-735618026

2019-09-12 08:13:06.298 [AIO:XDEB] [3|WS] > {
  "msgtype": "jreq",
  "MHdr": 0,
  "JoinEui": "FF-FF-FF-BB-00-00-00-00",
  "DevEui": "FF-FF-FF-AA-0E-11-E5-52",
  "DevNonce": 2656,
  "MIC": -735618026,
  "RefTime": 1568275986.299598,
  "DR": 5,
  "Freq": 868100000,
  "upinfo": {
    "rctx": 0,
    "xtime": 54606875813980496,
    "gpstime": 0,
    "fts": -1,
    "rssi": 0,
    "snr": 13.75,
    "rxtime": 1568275986.298647
  }
}

2019-09-12 08:13:10.418 [AIO:XDEB] [3|WS] < {
  "msgtype": "dnmsg",
  "DevEui": "00-00-00-00-00-00-00-00",
  "dC": 0,
  "diid": 1380,
  "pdu": "20218d772c14f80f38ac0d75c893c3d9069a001e57fd0712df04dba14995f68c85",
  "RxDelay": 1,
  "RX1DR": 5,
  "RX1Freq": 868100000,
  "priority": 25,
  "xtime": 54606145673540176,
  "rctx": 0,
  "MuxTime": 1568275990.4194746
}

2019-09-12 08:13:10.418 [S2E:VERB] ::0 diid=1380 [ant#0] - class A has no more alternate TX time
```

*TTv3 Gateway Data Log*
```
{
  "raw_payload": "AAAAAAC7////UuURDqr///9gChZcJ9Q=",
  "payload": {
    "m_hdr": {},
    "mic": "Flwn1A==",
    "join_request_payload": {
      "join_eui": "FFFFFFBB00000000",
      "dev_eui": "FFFFFFAA0E11E552",
      "dev_nonce": "0A60"
    }
  },
  "settings": {
    "data_rate": {
      "lora": {
        "bandwidth": 125000,
        "spreading_factor": 7
      }
    },
    "coding_rate": "4/5",
    "frequency": "868100000",
    "timestamp": 187672912,
    "time": "2019-09-12T08:13:06.298646926Z"
  },
  "rx_metadata": [
    {
      "gateway_ids": {
        "gateway_id": "smtcpico",
        "eui": "000000FFFE001100"
      },
      "time": "2019-09-12T08:13:06.298646926Z",
      "timestamp": 187672912,
      "snr": 13.75,
      "uplink_token": "ChYKFAoIc210Y3BpY28SCAAAAP/+ABEAENDSvlk="
    }
  ],
  "received_at": "2019-09-12T08:13:06.318580779Z",
  "correlation_ids": [
    "gs:conn:01DMJ8B3EK1DPE8EHSXATKD5EY",
    "gs:uplink:01DMJ8GXWFNNPSXBT1GT91PYZM"
  ]
}


{
  "raw_payload": "ICGNdywU+A84rA11yJPD2QaaAB5X/QcS3wTboUmV9oyF",
  "scheduled": {
    "data_rate": {
      "lora": {
        "bandwidth": 125000,
        "spreading_factor": 7
      }
    },
    "data_rate_index": 5,
    "coding_rate": "4/5",
    "frequency": "868100000",
    "timestamp": 192672912,
    "downlink": {
      "tx_power": 16.15,
      "invert_polarization": true
    }
  },
  "correlation_ids": [
    "gs:conn:01DMJ8B3EK1DPE8EHSXATKD5EY",
    "gs:uplink:01DMJ8GXWFNNPSXBT1GT91PYZM",
    "ns:downlink:01DMJ8H1WFCCNHQ3R2JJBY5SD5",
    "ns:uplink:01DMJ8GXWFMP8H9M8XRDXFPY2M",
    "rpc:/ttn.lorawan.v3.GsNs/HandleUplink:01DMJ8GXWFZJ1NZRPCZMZSD3W2",
    "gs:conn:01DMJ8B3EK1DPE8EHSXATKD5EY",
    "rpc:/ttn.lorawan.v3.NsGs/ScheduleDownlink:01DMJ8H1WHH3B3EX9MT4HJ0TSY"
  ]
}
```

#### What do you see now?

The updf message xtime is `hex(54606875813980496) = 0xc200aa0b2fa950`
The dnmsg message xtime is `hex(54606145673540176) = 0xc200000b6cb250`
**Note** that `0xAA<<32` is omitted in the xtime of the dnmsg.

#### What do you want to see instead?

The dnmsg message xtime should be `hex(54606875817980496) = 0xc200aa0b6cb250`
**Note** that `0xAA<<32` MUST NOT be omitted in the xtime of the dnmsg.

The way the protocol was envisioned, is that `xtime` is an opaque value to the LNS. You just pass it along unchanged and control the scheduling time of class A downlinks with the `RxDelay` parameter.

#### Environment

* Basic Station 2.0.3
* TTNv3 Stack hosted on demo.thethings.indutries

#### How do you propose to implement this?

Not quite sure, but maybe these functions:
https://github.com/TheThingsNetwork/lorawan-stack/blob/aec3765261e7835132d712028112506b8125bb84/pkg/gatewayserver/io/io.go#L438
https://github.com/TheThingsNetwork/lorawan-stack/blob/7345f51812b5601aeb7e5aa1d078ae7e18d9c5e2/pkg/gatewayserver/scheduling/scheduler.go#L317
should take uint64 instead of uint32 as input.

Ideally, consider just passing xtime along the stack untouched, without parsing/converting it. Use the `RxDelay` parameter to control the downlink scheduling time.

#### Can you do this yourself and submit a Pull Request?

I'm sure you guys can handle this.

**Comment by beitler** [comment]
@KrishnaIyer, I looked at it in a bit more detail. The root cause if this phenomenon is that during message parsing the `xtime` field is already converted down to 32 bits:

https://github.com/TheThingsNetwork/lorawan-stack/blob/dc8fc5ab888f57c20657729b51760eca98452605/pkg/gatewayserver/io/basicstationlns/messages/upstream.go#L328

The rollover-tracking mechanism however, assumes the epoch to start at zero because RolloverClock.absolute is initialized with a 32 bit number:

https://github.com/TheThingsNetwork/lorawan-stack/blob/dc8fc5ab888f57c20657729b51760eca98452605/pkg/gatewayserver/scheduling/clock.go#L49

This assumption works in most cases, but it breaks for the case where the gateway which is establishing a connection has already been ticking for multiple epochs (as simulated by the reproduction steps above). This can happen for example, when the gateway re-initializes the connection without restarting the radio. Another scenario, triggering this condition, is that the first uplink is forwarded only after 71 minutes after establishing the connection.

**Comment by KrishnaIyer** [comment]
@beitler: Thanks for the info. The initial test that I did showed that the Upper 16 bit of the timestamp changed every time the connection was re-established. I see that this is not the case and will be fixed by #1787

**Comment by johanstokking** [comment]
> The initial test that I did showed that the Upper 16 bit of the timestamp changed every time the connection was re-established

I think the upper most word of `xtime` is what we interpret as session ID (i.e. changes on (re)connect) and that the next word is already part of the timestamp. This is indeed effective in #1787.

**Comment by beitler** [comment]
The issue still exists and can be triggered by the steps above.

jreq:xtime -> 0xd400**aa**496054d6
```
2020-03-06 08:13:30.434 [AIO:XDEB] [3|WS] > {
  "msgtype": "jreq",
  "MHdr": 0,
  "JoinEui": "xx-xx-xx-xx-xx-xx-xx-xx",
  "DevEui": "xx-xx-xx-xx-xx-xx-xx-xx",
  "DevNonce": 3682,
  "MIC": 452273186,
  "RefTime": 1583482410.434758,
  "DR": 5,
  "Freq": 868100000,
  "upinfo": {
    "rctx": 0,
    "xtime": 59673426438149334,
    "gpstime": 0,
    "fts": -1,
    "rssi": -85,
    "snr": 4.75,
    "rxtime": 1583482410.434790
  }
}
```

dnmsg:xtime -> 0xd400**00**499d5dd6
```
2020-03-06 08:13:34.468 [AIO:XDEB] [3|WS] < {
  "msgtype": "dnmsg",
  "DevEui": "00-00-00-00-00-00-00-00",
  "dC": 0,
  "diid": 13448,
  "pdu": "xxxxxxxxxx",
  "RxDelay": 1,
  "RX1DR": 5,
  "RX1Freq": 868100000,
  "priority": 25,
  "xtime": 59672696297709014,
  "rctx": 0,
  "MuxTime": 1583482414.4691372
}
```
