### ISSUE TITLE
Support multiple frequency plans in devices

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#1353]
#### Summary

NS shall allow multiple frequency plans to specified for a device.

#### Why do we need this?

See https://github.com/TheThingsNetwork/lorawan-stack/issues/761

#### What is already there? What do you see now?

Exactly 1, mandatory frequency plan can be specified

#### What is missing? What do you want to see?

Support for multiple frequency plans, at least 1.
On creation/update NS shall validate frequency plan compatibility according to https://github.com/TheThingsNetwork/lorawan-stack/issues/761#issuecomment-530150946

#### How do you propose to implement this?

Adapt band-dependent functionality to use the lowest common denominator between bands, such that behavior is compatible in all *n* bands
Deprecate `frequency_plan_id`, add `repeated string frequency_plan_ids` instead.
Validate in registry SET operation.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
Also need to consider already registered devices that are stored with a `frequency_plan_id`.

Perhaps it's simpler to just keep `frequency_plan_id` as well as its behavior, and add a new `additional_frequency_plan_ids` that can be appended to the one in `frequency_plan_id`.

**Comment by rvolosatovs** [comment]
I think that's confusing - a simple solution is to just set `frequency_plan_ids` whenever a device with `frequency_plan_id` is read.
Whenever a device with `frequency_plan_id` is written, we can set `frequency_plan_ids` instead.

**Comment by htdvisser** [comment]
I don't think it's that simple actually. Your solution would mean that in the API, `frequency_plan_id` is equivalent to `frequency_plan_ids[0]` (we can't stop accepting/returning `frequency_plan_id` until v4), we'd have to allow setting/getting both, but not at the same time. In stored devices we would have to look whether `frequency_plan_ids` exists, and fall back to `frequency_plan_id` if it doesnt.

**Comment by htdvisser** [comment]
Let's keep this in Backlog until we have more demand (👍's)
