### ISSUE TITLE
RPC correlation IDs not propagated to IS right calls

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#1362]
#### Summary

RPC correlation IDs are not propagated to IS right calls

#### Steps to Reproduce

1. Perform a `asns.LinkApplication` call
2. Observe a set `X` of correlation IDs generated for the `LinkApplication` RPC request
3. Observe a different set `Y` of correlation IDs generated and passed to `ListRights` RPC on IS

See https://github.com/rvolosatovs/lorawan-stack/commit/d0d82eb832e8981efce68ac461ec5e202b0b3c36#diff-ff0282aa536a2c5b91949a3916c24bbaR968

A set of correlation IDs passed to `ListRights` on the IS is different than the one received by NS in the context and passed to e.g. `cluster.GetPeer`
The `ListRights` RPC receives a set of correlation IDs, which contains a newly generated `.*ListRights.*` correlation ID, but lacks the original `.*LinkApplication.*`, which triggered the request

#### What do you see now?

Original RPC correlation IDs lost when `ListRights` RPC is performed

#### What do you want to see instead?

Original RPC correlation IDs merged with the `ListRights` correlation IDs when RPC is performed

#### How do you propose to implement this?

Not sure

#### Can you do this yourself and submit a Pull Request?

no

**Comment by htdvisser** [comment]
This isn't a bug. Correlation IDs weren't designed to do this. They are meant to correlate LoRaWAN traffic, and they aren't propagated by default on any RPC. The only way to propagate Correlation IDs is to put them in the request messages, like what we do with uplink/downlink messages.

Why would we need to do this?

**Comment by rvolosatovs** [comment]
My understanding of this was that we would use correlation IDs for tracing of all RPCs, e.g. we could see the full chain of `LinkApplication` -> `ListRights` -> ???.
Closing this for now, please reopen if you think it's necessary.

**Comment by htdvisser** [comment]
No, for distributed tracing of HTTP calls and RPCs we use OpenCensus (which is becoming OpenTelemetry)
