### ISSUE TITLE
Set Devices and Gateway location with map

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-stack#1380]
#### Summary

The location form for devices and gateways should include a map, allowing auto filling of location by clicking on map.

#### Why do we need this?

Simplify User Experience 

#### What is already there? What do you see now?

A form with text inputs.

#### Environment

Browser

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by pgalic96** [comment]
Closed via #2325
