### ISSUE TITLE
Manage claim authentication code

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1405]
#### Summary

Manage claim authentication code in Console

#### Why do we need this?

To allow users to edit the value and set to/from dates

#### What is already there? What do you see now?

Only CLI support

#### What is missing? What do you want to see?

Console support

References https://github.com/TheThingsNetwork/lorawan-stack/issues/579

#### How do you propose to implement this?

In the Join Server section, add optional settings for the claim authentication code

The entire `claim_authentication_code` field is optional. If set, `value` is mandatory. The `valid_from` and `valid_to` date/time is optional

Please show value as "password" (that you can show)

See API for validation rules

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by johanstokking** [comment]
@kschiffer @pgalic96 please coordinate who can pick this up

**Comment by kschiffer** [comment]
I'd like to do it. If it's not urgent, I would do it after my November issues.

**Comment by bafonins** [comment]
Closed via https://github.com/TheThingsNetwork/lorawan-stack/pull/2072
