### ISSUE TITLE
Add pagination to Redis registries

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#1428]
#### Summary

Add pagination (current page and the number of elements per page) to the `List*` RPCs of our Redis registries.

#### Why do we need this?

For scalability reasons - listing becomes rather troublesome if a high amount of entities has to be returned. 

#### What is already there? What do you see now?

Currently the database-backed (from Postgres/Cockroach) queries from the Entity Store allow pagination. After #1399 is merged, `pkg/redis` will have support for pagination (in the form of the `NewContextWithPagination` and `FindProtos` options such as `FindProtosWithAlpha` and `FindProtosWithOffsetAndCount` ). On a case by case basis, the pagination can be added.

#### What is missing? What do you want to see?

Pagination inside the `List` requests (and the support for them in the registries themselves) for the Redis registries.

#### How do you propose to implement this?

1. Add `page` and `limit` to the `List` requests.
2. Extend the `*Registry` interface with a pagination utility (i.e. `WithPagination(ctx, page, limit, total)`)
3. Add pagination support inside the registry using `FindProtos`/`FindProtosWithOffsetAndCount`.

#### Can you do this yourself and submit a Pull Request?

Yes, but I'd like to hear opinions regarding the index on which we paginate. In most cases lexicographic indexing based on the identifier (such as `application UID` or `device UID`) can be done. cc @johanstokking @htdvisser @rvolosatovs

**Comment by KrishnaIyer** [comment]
Replaced by https://github.com/TheThingsIndustries/lorawan-stack/issues/4441
