### ISSUE TITLE
Cache root CA

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1432]
#### Summary

Cache root CA

#### Why do we need this?

To avoid reading it every time building a TLS client configuration.

#### What is already there? What do you see now?

Reading `RootCA` file in `pkg/component.GetTLSClientConfig()` since #1431 

#### What is missing? What do you want to see?

Cache the file read.

#### How do you propose to implement this?

We could wire in the file fetcher and let the caching happen there.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by nejraselimovic** [comment]
@johanstokking can you pick this up? Is it important enough to schedule it for a timely milestone?
