### ISSUE TITLE
Optionally require authenticated gateway connection

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1436]
#### Summary

Optionally require authenticated links from gateways.

#### Why do we need this?

To disallow unauthenticated connections, like UDP.

#### What is already there? What do you see now?

GS keeps track of UDP source addresses which detects and disallows spoofing gateway EUIs while the real UDP-linked gateway is still connected.

#### What is missing? What do you want to see?

We should not allow any unauthenticated gateway links, i.e. UDP on a per-gateway setting basis.

#### How do you propose to implement this?

- Add a `require_authentication` bool to `Gateway`, store in IS
- Get this information when connecting the gateway in GS
- Check if the concerning frontend is authenticated. If not, and if `require_authentication` is set, stop the connecting procedure

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by KrishnaIyer** [comment]
Basic Station is now covered via #2948, updated description to match that.

**Comment by htdvisser** [comment]
I'll do the Identity Server part and then hand over to @KrishnaIyer / @adriansmares.
