### ISSUE TITLE
Expand sidebar entry by default, if sub-item is active

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#1460]
#### Summary
If a route is active whose link resides as a subentry of our sidebar component. The subentry should be expanded initially by default.

#### Why do we need this?
To improve contextual awareness for the user.

#### What is already there? What do you see now?
![image](https://user-images.githubusercontent.com/5710611/66739027-1e15be00-ee70-11e9-8f07-9f987b44cfad.png)
The entry is collapsed by default, when a subentry is currently active.

#### What is missing? What do you want to see?

![image](https://user-images.githubusercontent.com/5710611/66739038-266df900-ee70-11e9-99a7-9e55a074a14c.png)
The entry being expanded.

#### Environment
Console in browser.

#### How do you propose to implement this?
We need to make the sidebar component aware of the current route and use the info to open subentries if necessary.

#### Can you do this yourself and submit a Pull Request?
I can but maybe @bafonins is better suited as component author. Feel free to reassign.

**Comment by bafonins** [comment]
Not solved via https://github.com/TheThingsNetwork/lorawan-stack/pull/1519

1. Go to `/console/applications/<app-id>/integrations/webhooks/add`
2. Refresh the page
3. See the `Integrations` item not being expanded
