### ISSUE TITLE
Saving devices on NS/AS when they don't exist there fails

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1509]
#### Summary

Saving devices on NS/AS when they don't exist there fails

#### Steps to Reproduce

1. Create device only in IS and JS: `$ ttn-lw-cli dev create test-issue test-dev --network-server-enabled=false --application-server-enabled=false --with-root-keys --join-eui 0102030405060708 --dev-eui 0102030405060708`
2. Open this device in Console with all components enabled
3. Go to General Settings
4. Set some NS values, like MAC and PHY version
5. Click Save Changes

#### What do you see now?

Console tries to get `supports_join` from NS, which fails with a 404, and then stops creating:

```
Request URL: http://localhost:1885/api/v3/ns/applications/test-app/devices/test-device?field_mask=supports_join
Request Method: GET
Status Code: 404 Not Found
```

@kschiffer indicated that this get is necessary for knowing whether to hit the JS for saving changes. I think we have to do that by other means, i.e. by having `join_server_address` set.

#### What do you want to see instead?

In this case, the device needs to be set in NS and AS. Note that we deliberately decided to use get/set in JS/NS/AS registries, not a create or update.

Also, Console should prefill the NS and AS addresses.

#### Environment

v3.2.3

#### How do you propose to implement this?

- Bypass hitting NS on saving changes, or at least not failing on a 404
- Prefill addresses when they don't exist

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by bafonins** [comment]
> indicated that this get is necessary for knowing whether to hit the JS for saving changes. I think we have to do that by other means, i.e. by having join_server_address set.

So shall we check if `join_server_address` is present instead of relying on `supports_join` to check if a device is ABP?
