### ISSUE TITLE
Getting error when executing instructions to run things stack on ubuntu

### ISSUE THREAD

**Issue by emilppeter** [TheThingsNetwork/lorawan-stack#1514]
Hi, 
I was actually following the getting started instructions to run things stack on ubuntu 18.04 . When I tried executing the following instruction: 
docker-compose run --rm stack is-db create-admin-user \
  --id admin \
  --email your@email.com 
I got the following error:
error:cmd/ttn-lw-stack/commands:missing_flag (missing CLI flag `email`)
    flag=email
Any help would be appreciated.
Thanks in advance.

**Comment by rvolosatovs** [comment]
It sounds like you forgot the `\` at the end of the line.
The command should look like this:
```bash
docker-compose run --rm stack is-db create-admin-user \
  --id admin \
  --email your@email.com
```

Alternatively you can just put everything on one line and that should work fine:
```bash
docker-compose run --rm stack is-db create-admin-user --id admin --email your@email.com
```

Please let me know if this helps!

**Comment by emilppeter** [comment]
Thanks @rvolosatovs ! It worked for me.
