### ISSUE TITLE
Allow multiple uplinks to be sent to AS in a link

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#1523]
#### Summary

Allow multiple uplinks to be sent to AS in a link.

#### Why do we need this?

In many cases NS has multiple uplinks to send to AS, so it makes more sense to send a whole list of uplinks to AS and wait for them to be processed instead of sending them one by one and waiting after each one.
An example where this is important is, for example downlink queue invalidation(in LW<1.1):
1. Assume a downlink is queued with FCnt lower than `LastNFCntDown` for a 1.0.X device.
2. Assume an `FPort=0` downlink is generated and scheduled
3. When processing downlink NS will generate (at least) 2 application uplinks - 2 `DownlinkQueueInvalidated` where `FCnt` in last one will be 1 larger than the first.
4. After sending the first application uplink, NS will wait for AS to recalculate the queue
5. After sending the last application uplink, NS will wait once again for AS to recalculate the queue

If AS link allowed multiple application uplinks to be sent at once, NS would only need to wait once and (ideally) AS would be able to figure out that only 1 queue recalculation is necessary.

Note, in this specific case it's possible for NS be "smart" and only send 1 queue invalidation(last one), however this is not always possible in a generic case and NS still has to wait after each uplink.
If, for example, 10 application uplinks are generated as a consequence of downlink scheduling, that would result in 10 round-trips with possibly redundant actions taken by AS, since it has no way to know that more uplinks are "coming". 
Moreover, once #560 is done(https://github.com/TheThingsNetwork/lorawan-stack/pull/1524), NS will be able to batch application uplinks related to multiple events(e.g. device uplink *and* downlink) and the performance should benefit greatly from this feature.

#### What is already there? What do you see now?

Only being able to send 1 `ApplicationUp` at a time

#### What is missing? What do you want to see?

Being able to send more than 1 `ApplicationUp` at a time

#### Environment

Any

#### How do you propose to implement this?

Perhaps add `rpc LinkApplicationMultiple(stream google.protobuf.Empty) returns (stream ApplicationUps)`, where `ApplicationUps` contains `repeated ApplicationUp`
I suppose there's no way to alter current `LinkApplication` RPC to allow this(cc @htdvisser )
This is not a problem, however, since NS can implement both and most of the logic can be shared.

#### Can you do this yourself and submit a Pull Request?

I can do add the RPC to API and add the NS implementation

**Comment by johanstokking** [comment]
@adriansmares what do you think?
