### ISSUE TITLE
Embed documentation in releases

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1534]
#### Summary

We want to have embedded documentation in release builds.

#### Why do we need this?

This will make sure that the documentation for a release is always together with that release, which means that the console can start linking to documentation that is actually in sync.

#### What is already there? What do you see now?

Documentation published on thethingsstack.io

#### What is missing? What do you want to see?

It would be cool to bundle the documentation as static assets with the release builds, and make it available to users.

#### How do you propose to implement this?

WIP: https://github.com/TheThingsNetwork/lorawan-stack/tree/feature/embed-docs

**Comment by johanstokking** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/1537

Linking from Console is out of scope here
