### ISSUE TITLE
Unable to login using ttn-lw-cli login command

### ISSUE THREAD

**Issue by emilppeter** [TheThingsNetwork/lorawan-stack#1538]
Hi ,
I am trying to start up things network stack using the github repository on my ubuntu environment following the instructions on this link https://github.com/TheThingsNetwork/lorawan-stack/blob/master/DEVELOPMENT.md. So after building ttn-lw-cli, when I try to do a “go run ./cmd/ttn-lw-cli login” I get the following error:
ERROR Please login with the login command
INFO Opening your browser on https://localhost:8885/oauth/authorize?client_id=cli&redirect_uri=local-callback&response_type=code
INFO After logging in and authorizing the CLI, we’ll get an access token for future commands.
INFO Waiting for your authorization…
The webpage pops up but it doesn’t load. Could you please help me out on it? Please let me know what I am doing wrong. Thanks in advance.
Emil Peter

**Comment by rvolosatovs** [comment]
Have you successfully built the frontend before trying to login?
> mage js:build

**Comment by emilppeter** [comment]
Thanks for replying. Yes I have successfully rebuilt the frontend.

**Comment by johanstokking** [comment]
Does it work now?

The order is `mage js:build`, then `go run ./cmd/ttn-lw-stack start`, then `go run ./cmd/ttn-lw-cli login` in a different terminal.

**Comment by emilppeter** [comment]
Thanks @johanstokking . It worked!!

**Comment by emilppeter** [comment]
I am sorry. After logging in and proceeding further, when I try to execute the following command as described in getting started document: go run ./cmd/ttn-lw-cli gateways list-frequency-plans,I get the following error:
WARN grpc: addrConn.createTransport failed to connect to {localhost:8884 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority". Reconnecting...
Please help me out on this.Thanks in advance.

**Comment by johanstokking** [comment]
@emilppeter this is a separate issue. Please open a new issue.

To fix this, please set `TTN_LW_CA=cert.pem` in env or pass `--ca cert.pem` (or at least what you have configured as self-signed cert)
