### ISSUE TITLE
Show Key ID values with safe inspector in API key tables

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#1560]
#### Summary
The key id cell in our api key tables should be shown in a `<SafeInspector />`

#### Why do we need this?
Better display quality, easy copy, etc.

#### What is already there? What do you see now?
Rendering of Key IDs as plain text.

#### What is missing? What do you want to see?
Wrapping of the value around the safe inspector.

#### Environment
Console.

#### How do you propose to implement this?
Trivial.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by htdvisser** [comment]
API key IDs are not secret

**Comment by kschiffer** [comment]
Right, we want to show them in the safe inspector unhidden.
