### ISSUE TITLE
Validation errors on copy-pasted location values

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1574]
#### Summary

When I copy-paste a location value into the Latitude/Longitude of the gateway location, the console gives me (client side) validation errors.

#### Steps to Reproduce

1. Go to your gateway
2. Go to **Location**
3. Copy latitude `52.39528339` and longitude `4.87489745`
4. **Save Changes**

#### What do you see now?

<img width="693" alt="Screenshot 2019-11-11 at 10 50 17" src="https://user-images.githubusercontent.com/181308/68578054-8e186380-0471-11ea-9c56-6ad45b0c0c21.png">

#### What do you want to see instead?

The console should not complain.

#### Environment

v3.2.4, Firefox 70

**Comment by kschiffer** [comment]
I'm having trouble reproducing. Which browser are you using?

@pgalic96 this is likely fixed by changing the input type from `number` to `text`. But it might need a different validation schema then.

**Comment by htdvisser** [comment]
This was on Firefox 70 I think, updated issue.
