### ISSUE TITLE
File Descriptor Leak

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1596]
#### Summary

There seems to be a file descriptor leak somewhere.

#### Steps to Reproduce

1. Just let ttn-lw-stack run for a while

#### What do you see now?

<img width="660" alt="Screenshot 2019-11-15 at 12 24 35" src="https://user-images.githubusercontent.com/181308/68942574-35b2d000-07a9-11ea-8e4e-0408d0945e50.png">

#### Environment

ttn-lw-stack v3.2.4

#### How do you propose to implement this?

We first need to figure out where this is coming from, so if anyone else is experiencing this, please investigate and comment.

**Comment by KrishnaIyer** [comment]
This seems to have been fixed somewhere since `3.2.4.`. Haven't observed this since `3.7.x` (or that's when we have telemetry).

**Comment by htdvisser** [comment]
Yeah, let's close it.
