### ISSUE TITLE
Make console more personal

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1622]
#### Summary

It would be really nice to make the console more personal for the user.

#### Why do we need this?

Because it's nice

#### What is already there? What do you see now?

Looks like you already make a request to `/api/v3/users/<user-id>`

#### What is missing? What do you want to see?

I'd like to see the current user's real name and profile picture.

#### Environment

v3.2.6

#### How do you propose to implement this?

- Add `name` and `profile_picture` to the field mask of the request that gets the current user.
- If there's a non-empty `name` in the response, use that in the "Welcome back"
- If there's a `profile_picture` in the response, get the appropriate URL from `sizes` (0 is the original, there are usually sizes between 64 and 1024) and display that if that URL gives you a 200 (it may be a Gravatar URL that can 404 if not found or blocked by browser).

**Comment by kschiffer** [comment]
This has been fully implemented since https://github.com/TheThingsNetwork/lorawan-stack/pull/3900
