### ISSUE TITLE
DevStatusReq is sent too often

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1637]
#### Summary

NS sends `DevStatusReq` too often, draining gateway downlink capacity.

cc @ama9910

#### Steps to Reproduce

1. Activate device
2. Observe gateway downlink traffic over time

#### What do you see now?

`DevStatusReq` every 20 frames or every hour

Introduced here: https://github.com/TheThingsNetwork/lorawan-stack/commit/d3e6c340fdcb679b94ba60ac85f76b77978237a5#diff-fa23c3c73eb9a1b751ae8903f80ac916R30-R33

#### What do you want to see instead?

Unless otherwise specified via per-device settings or per-Network Server config, I'd suggest increasing this significantly, like every 24 hours and _from_ 20 frames.

That from N frames would mean not forcing `DevStatusReq` every Nth frame, but piggybacking on any downlink that's being scheduled.

#### How do you propose to implement this?

1. Change default settings
2. Change how the count is interpreted

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by virtualguy** [comment]
👍
