### ISSUE TITLE
 Set location settings via map #1565

### ISSUE THREAD

**Issue by riska8899** [TheThingsNetwork/lorawan-stack#1638]
#### Summary

...

#### Why do we need this ?

...

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?

...

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by kschiffer** [comment]
Hey @riska8899,
please follow our issue template, or else we won't be able to help you.
I suppose you want to be able to set gateway antenna / device locations via the map in the console. We already have an issue for that, you can find it here: https://github.com/TheThingsNetwork/lorawan-stack/issues/1380
