### ISSUE TITLE
Document MQTT and HTTP integrations with Console

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1669]
#### Summary

Document MQTT and HTTP integrations with Console

#### Why do we need this ?

This is easier than using the CLI.

#### What is already there? What do you see now?

Setup via CLI.

#### What is missing? What do you want to see?

Console guide with screenshots.

#### How do you propose to document this?

Console guide with screenshots.

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by adriansmares** [comment]
Closed by #1696.
