### ISSUE TITLE
ttn-lw-cli snap can't read config file

### ISSUE THREAD

**Issue by eggfriedrice** [TheThingsNetwork/lorawan-stack#1670]
#### Summary
ttn-lw-cli installed on via snap can't open the config file in ~/.ttn-lw-cli.yml, it errors with
```
$ ttn-lw-cli config         
open /home/al/.ttn-lw-cli.yml: permission denied
```
I've followed the installation guide here:
https://enterprise.thethingsstack.io/v3.3.1/guides/getting-started/installation/#command-line-interface-optional
and configuration here (modified for my instance)
https://enterprise.thethingsstack.io/v3.3.1/guides/getting-started/configuration/#command-line-interface

I can make ttn-lw-cli work passing the config file with -c, but only if the config file is named something else:
```
$ ttn-lw-cli config           
open /home/al/.ttn-lw-cli.yml: permission denied

$ ttn-lw-cli -c .ttn-lw-cli.yml config 
open .ttn-lw-cli.yml: permission denied

$ ttn-lw-cli -c ttn.yml config        
                         --allow-unknown-hosts="false"
                  --application-server-enabled="true"
 ...
```
My config file is good, and works when renamed and passed with -c. snap list shows:
```
ttn-lw-stack        3.3.1                       94    stable    rvolosatovs-ttn  -
```

#### Steps to Reproduce

1. Install the cli per the docs above
2. Add a .ttn-lw-cli.yml and see the permission denied error when running the cli

#### What do you see now?

...

#### What do you want to see instead?

...

#### Environment

Ubuntu 18.04

```
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.3.1
Build date:          2019-11-26T12:36:02Z
Git commit:          8bedf3f4e
Go version:          go1.13.4
OS/Arch:             linux/amd64

```

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by decentlab** [comment]
Probably the strict confinement is restricting access to hidden (dot) files. Maybe [personal-files-interface](https://snapcraft.io/docs/personal-files-interface) is a way to go.
