### ISSUE TITLE
database upgrade issue, "picture_id" column is missing...

### ISSUE THREAD

**Issue by alexbn71** [TheThingsNetwork/lorawan-stack#1679]
#### Summary

After the last upgrade I can no longer create new devices since it's missing the column "picture_id"

#### Steps to Reproduce

Upgrade to 3.3.1 then create a new device

#### What do you see now?

ERROR error/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/identityserver/store/store.go:70pq: column "picture_id" does not exist grpc_method=Create grpc_service=ttn.lorawan.v3.EndDeviceRegistry namespace=db request_id=01DV5DMX6FP2M4PKN2SCD7JG1Z
stack_1       
ERROR Finished unary call                      code=undefined_column duration=57.038605ms error=error:pkg/identityserver/store:database (database error) error_cause=pq: column "picture_id" does not exist error_correlation_id=0a310d58d1b14fe489c598078bcfc26a error_name=database error_namespace=pkg/identityserver/store grpc_code=Internal grpc_method=Create grpc_service=ttn.lorawan.v3.EndDeviceRegistry namespace=grpc request_id=01DV5DMX6FP2M4PKN2SCD7JG1Z
#### What do you want to see instead?

the new device created

#### Environment

v3.3.1

**Comment by htdvisser** [comment]
Your database requires migration. This was explained in the [release notes](https://github.com/TheThingsNetwork/lorawan-stack/releases) and the [CHANGELOG](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/CHANGELOG.md). We strongly recommend reading those when upgrading.
