### ISSUE TITLE
Minor improvements in Getting Started

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1688]
#### Summary

Minor improvements in Getting Started 

#### Why do we need this ?

To smoothen the first steps with The Things Stack

#### What is already there? What do you see now?

- Manual linking of AS to NS with creation of API key
- No separate guide for creating a device

#### What is missing? What do you want to see?

- Change Getting Started to use the automatic linking feature (enabled by default); remove obsolete steps
- Create a separate step or page for creating devices, to which we can link directly. This should also explain the MAC and PHY versions

#### How do you propose to document this?

See above

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by adriansmares** [comment]
First part is fixed by #1696.
