### ISSUE TITLE
Client side validation of user names

### ISSUE THREAD

**Issue by rish-c** [TheThingsNetwork/lorawan-stack#1692]
#### Summary

When creating an invalid username, the console shows an error which could be improved with a simple message.

...

#### Steps to Reproduce

Usernames such as `abc_123` plus other similar invalid usernames that are not allowed

#### What do you see now?

Screenshot
![image (2)](https://user-images.githubusercontent.com/17057057/70166716-986efb80-16c5-11ea-8bdc-032ec2c7dd11.png)

#### What do you want to see instead?

Display the format of a valid username

#### Can you do this yourself and submit a Pull Request?

@kschiffer @bafonins

**Comment by kschiffer** [comment]
Shouldn't the backend take care of providing more helpful error messages? We could add some mapping of error messages, but I think this should be a last resort only.
This one could already be improved greatly by a more expressive error message than `invalid identifiers`, e.g. `User ID contained invalid characters, please use {allowed characters} only`

**Comment by htdvisser** [comment]
The frontend already has the regex for valid IDs, so it can add that on the field.

**Comment by johanstokking** [comment]
Consider other similar fields too

**Comment by bafonins** [comment]
Already implemented.

<img width="652" alt="Screenshot 2020-10-05 at 16 46 08" src="https://user-images.githubusercontent.com/16374166/95087418-4f933380-072a-11eb-9e30-1b4568fe098f.png">
