### ISSUE TITLE
Add CSS styles to HTML emails

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#17]
**Summary:** 

Add CSS styles to HTML emails

**Why do we need this?**

**What is already there? What do you see now?**

Plaintext 

**What is missing? What do you want to see?**

Inline css for email markup.

**How do you propose to implement this?**

Inline the CSS from https://github.com/TheThingsIndustries/account-server/blob/master/src/email/email.css and test.

**What can you do yourself and what do you need help with?**

I can create a PR 

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/778 by @gomezjdaniel

**Comment by KrishnaIyer** [comment]
This is tracked here so closing this; https://github.com/TheThingsIndustries/lorawan-stack/issues/1973
