### ISSUE TITLE
Webhook Headers not being sent

### ISSUE THREAD

**Issue by ama9910** [TheThingsNetwork/lorawan-stack#1714]
#### Summary
Custom Webhook headers are not being sent, even though they can be added from the console

#### Steps to Reproduce
1. Add a Webhook Integration to an App
2. Select "Add header entry"
3. Add a key and value of your choice
4. Trigger an uplink from a device

#### What do you see now?
Example from TTI Webhook -> Node-RED HTTP In node:

{"host":"[redacted]","user-agent":"ttn-lw-application-server/3.3.2","content-length":"1042","content-type":"application/json","accept-encoding":"gzip"} 

#### What do you want to see instead?
Example from cURL -> Node-RED HTTP In node:
curl -X POST http://[redacted] -H "myheader:5"

{"host":"[redacted]","user-agent":"curl/7.54.0","accept":"*/*","myheader":"5"}

Note the "myheader" customer header.

#### Environment
Stack is TTI Enterprise 3.3.2

#### Can you do this yourself and submit a Pull Request?
Unfortunately not.

**Comment by johanstokking** [comment]
I can reproduce this. It works via CLI;

```bash
$ ttn-lw-cli app webhooks set test-app postbin --headers "X-Test=blabla"
```

But in Console, setting webhook headers is ineffective. If you set headers in the Console, save the webhook and go back to the webhook, they're not actually saved. However, if you set them in CLI, they show up correctly in the Console.

In Developer Tools, the headers are not part of the `field_mask`. Also, it seems that only a newly added header is part of the request body; this has to be all currently set headers. This also allows for removing headers.
