### ISSUE TITLE
Delete api-keys from the cli

### ISSUE THREAD

**Issue by Oliv4945** [TheThingsNetwork/lorawan-stack#172]
**Summary:** 
In the CLI we can create, list, update api-keys but there is no option to delete them

**Why do we need this?**
Revoke an api-key if it gets disclosed, unused

**What is already there? What do you see now?**
`ttn-lw-cli app api-keys --help` returns
```
Available Commands:
  create      Create an application API key
  list        List application API keys
  update      Update an application API key
```

**What is missing? What do you want to see?**
delete or remove

**How do you propose to implement this?**
I propose to ask @htdvisser :)

**Comment by htdvisser** [comment]
API keys (and collaborators) can be removed by updating them with an empty list of rights. I guess that it would make sense to add CLI commands for this for consistency with the other commands.

**Comment by Oliv4945** [comment]
From user point of view, at least "delete" command wrapper would be nice :)
