### ISSUE TITLE
Problems with management remote VPS server + static IP (ttn-lw-cli + webgui)

### ISSUE THREAD

**Issue by ecities** [TheThingsNetwork/lorawan-stack#1723]
#### Summary

I'm trying to install most recent version of the stack onto **ovh.eu** VPS server (debian 9 stretch) in order to direct connection to our cloud system "on the same dev".

Following your getting started manual (it looks ok when we do **docker-compose up**).

We stuck on trying to initiate configuration (**ttn-lw-cli login** + WEB authorization in the internet browser).

The page always redirect to **localhost**.

...

#### Steps to Reproduce

1. Complete installation of stack on remote server machine IP: **200.200.200.200** in this example via SSH (no desktop and without physical access to local screen). Probably can be reproduced on local server via remote installation without desktop.
2. Running stack successfully (docker-compose up)
3. Replacing most 'localhost', '127.0.0.1' in docker-compose.yml into physical ip address **200.200.200.200**
4. **ttn-lw-client login** alone or with IP (200.200.200.200) parameters
```
ttn-lw-cli login \
      	--network-server-grpc-address 200.200.200.200:8884 \
	--oauth-server-address https://200.200.200.200:8885/oauth \
	--allow-unknown-hosts \
      	--insecure \
      	--join-server-grpc-address 200.200.200.200:8884 \
      	--qr-code-generator-grpc-address 200.200.200.200:8884 \
      	--application-server-grpc-address 200.200.200.200:8884 \
	--device-claiming-server-grpc-address 200.200.200.200:8884 \
      	--device-template-converter-grpc-address 200.200.200.200:8884 \
      	--gateway-server-grpc-address 200.200.200.200:8884 \
      	--identity-server-grpc-address 200.200.200.200:8884 

```

5. Web autorisation always fails and returns to localhost

 ttn-lw-stack config
                                           --as.device-kek-label=""
                                        --as.interop.blob.bucket=""
                                          --as.interop.blob.path=""
                                      --as.interop.config-source=""
                                          --as.interop.directory=""
                                                 --as.interop.id=""
                                                --as.interop.url=""
                                                  --as.link-mode="all"
                                                --as.mqtt.listen=":1883"
                                            --as.mqtt.listen-tls=":8883"
                                        --as.mqtt.public-address="localhost:1883"
                                    --as.mqtt.public-tls-address="localhost:8883"
                                        --as.webhooks.queue-size="16"
                                            --as.webhooks.target="direct"
                               --as.webhooks.templates.directory=""
                           --as.webhooks.templates.logo-base-url=""
                                     --as.webhooks.templates.url=""
                                           --as.webhooks.timeout="5s"
                                           --as.webhooks.workers="16"
                                        --blob.aws.access-key-id=""
                                             --blob.aws.endpoint=""
                                               --blob.aws.region=""
                                    --blob.aws.secret-access-key=""
                                        --blob.aws.session-token=""
                                          --blob.gcp.credentials=""
                                     --blob.gcp.credentials-file=""
                                          --blob.local.directory="./public/blob"
                                                 --blob.provider="local"
                                           --cache.redis.address=""
                                          --cache.redis.database="0"
                                --cache.redis.failover.addresses=""
                                   --cache.redis.failover.enable="false"
                              --cache.redis.failover.master-name=""
                                         --cache.redis.namespace=""
                                          --cache.redis.password=""
                                                 --cache.service=""
                                               --cluster.address=""
                                    --cluster.application-server=""
                                         --cluster.crypto-server=""
                                        --cluster.gateway-server=""
                                       --cluster.identity-server=""
                                                  --cluster.join=""
                                           --cluster.join-server=""
                                                  --cluster.keys=""
                                                  --cluster.name=""
                                        --cluster.network-server=""
                                                   --cluster.tls="false"
                                                        --config="/root/.ttn-lw-stack.yml,/root/.ttn-lw-stack.yml,/root/.config/.ttn-lw-stack.yml"
                                                 --console.mount=""
                                   --console.oauth.authorize-url="http://localhost:1885/oauth/authorize"
                                       --console.oauth.client-id="console"
                                   --console.oauth.client-secret="console"
                                       --console.oauth.token-url="http://localhost:1885/oauth/token"
                                        --console.ui.as.base-url="http://localhost:1885/api/v3"
                                         --console.ui.as.enabled="true"
                                    --console.ui.assets-base-url="/assets"
                                  --console.ui.branding-base-url=""
                                      --console.ui.canonical-url="http://localhost:1885/console"
                                           --console.ui.css-file="console.css"
                                       --console.ui.descriptions=""
                                      --console.ui.edtc.base-url="http://localhost:1885/api/v3"
                                       --console.ui.edtc.enabled="true"
                                        --console.ui.gs.base-url="http://localhost:1885/api/v3"
                                         --console.ui.gs.enabled="true"
                                        --console.ui.icon-prefix="console-"
                                        --console.ui.is.base-url="http://localhost:1885/api/v3"
                                         --console.ui.is.enabled="true"
                                            --console.ui.js-file="console.js"
                                        --console.ui.js.base-url="http://localhost:1885/api/v3"
                                         --console.ui.js.enabled="true"
                                           --console.ui.language="en"
                                        --console.ui.ns.base-url="http://localhost:1885/api/v3"
                                         --console.ui.ns.enabled="true"
                                       --console.ui.qrg.base-url="http://localhost:1885/api/v3"
                                        --console.ui.qrg.enabled="true"
                                          --console.ui.site-name="The Things Stack for LoRaWAN"
                                          --console.ui.sub-title="Management platform for The Things Stack for LoRaWAN"
                                       --console.ui.support-link=""
                                        --console.ui.theme-color=""
                                              --console.ui.title="Console"
                                 --device-repository.blob.bucket=""
                                   --device-repository.blob.path=""
                               --device-repository.config-source=""
                                   --device-repository.directory=""
                                         --device-repository.url=""
                                                   --dtc.enabled=""
                                                --events.backend="internal"
                                      --events.cloud.publish-url=""
                                    --events.cloud.subscribe-url=""
                                          --events.redis.address=""
                                         --events.redis.database="0"
                               --events.redis.failover.addresses=""
                                  --events.redis.failover.enable="false"
                             --events.redis.failover.master-name=""
                                        --events.redis.namespace=""
                                         --events.redis.password=""
                                   --frequency-plans.blob.bucket=""
                                     --frequency-plans.blob.path=""
                                 --frequency-plans.config-source=""
                                     --frequency-plans.directory=""
                                           --frequency-plans.url="https://raw.githubusercontent.com/TheThingsNetwork/lorawan-frequency-plans/master"
                       --gcs.basic-station.allow-cups-uri-update="false"
                             --gcs.basic-station.default.lns-uri="wss://localhost:8887"
              --gcs.basic-station.owner-for-unknown.account-type=""
                   --gcs.basic-station.owner-for-unknown.api-key=""
                        --gcs.basic-station.owner-for-unknown.id=""
                     --gcs.basic-station.require-explicit-enable="false"
                                              --gcs.require-auth="true"
                   --gcs.the-things-gateway.default.firmware-url="https://thethingsproducts.blob.core.windows.net/the-things-gateway/v1"
                    --gcs.the-things-gateway.default.mqtt-server="mqtts://localhost:8881"
                 --gcs.the-things-gateway.default.update-channel="stable"
                           --grpc.allow-insecure-for-credentials="false"
                                                   --grpc.listen=":1884"
                                               --grpc.listen-tls=":8884"
                   --gs.basic-station.fallback-frequency-plan-id=""
                                       --gs.basic-station.listen=":1887"
                                   --gs.basic-station.listen-tls=":8887"
                      --gs.basic-station.use-traffic-tls-address="false"
                                                    --gs.forward="=00000000/0"
                                             --gs.mqtt-v2.listen=":1881"
                                         --gs.mqtt-v2.listen-tls=":8881"
                                     --gs.mqtt-v2.public-address="localhost:1881"
                                 --gs.mqtt-v2.public-tls-address="localhost:8881"
                                                --gs.mqtt.listen=":1882"
                                            --gs.mqtt.listen-tls=":8882"
                                        --gs.mqtt.public-address="localhost:1882"
                                    --gs.mqtt.public-tls-address="localhost:8882"
                                --gs.require-registered-gateways="false"
                                      --gs.udp.addr-change-block="15s"
                                     --gs.udp.connection-expires="5m0s"
                                  --gs.udp.downlink-path-expires="30s"
                                              --gs.udp.listeners=":1700="
                                          --gs.udp.packet-buffer="50"
                                        --gs.udp.packet-handlers="10"
                                     --gs.udp.schedule-late-time="800ms"
                                         --http.cookie.block-key=""
                                          --http.cookie.hash-key=""
                                            --http.health.enable="true"
                                          --http.health.password=""
                                                   --http.listen=":1885"
                                               --http.listen-tls=":8885"
                                           --http.metrics.enable="true"
                                         --http.metrics.password=""
                                             --http.pprof.enable="true"
                                           --http.pprof.password=""
                                         --http.redirect-to-host=""
                                          --http.redirect-to-tls="false"
                                             --http.static.mount="/assets"
                                       --http.static.search-path="public,/srv/ttn-lorawan/public"
                                            --interop.listen-tls=":8886"
                          --interop.sender-client-ca.blob.bucket=""
                            --interop.sender-client-ca.blob.path=""
                            --interop.sender-client-ca.directory=""
                               --interop.sender-client-ca.source=""
                                  --interop.sender-client-ca.url=""
                                     --interop.sender-client-cas=""
                                  --is.auth-cache.membership-ttl="10m0s"
                                               --is.database-uri="postgresql://root@localhost:26257/ttn_lorawan_dev?sslmode=disable"
                                  --is.email.network.console-url="http://localhost:1885/console"
                          --is.email.network.identity-server-url="http://localhost:1885/oauth"
                                         --is.email.network.name="The Things Stack for LoRaWAN"
                                             --is.email.provider=""
                                       --is.email.sender-address=""
                                          --is.email.sender-name=""
                                     --is.email.sendgrid.api-key=""
                                     --is.email.sendgrid.sandbox="false"
                                         --is.email.smtp.address=""
                                     --is.email.smtp.connections="0"
                                        --is.email.smtp.password=""
                                        --is.email.smtp.username=""
                                --is.email.templates.blob.bucket=""
                                  --is.email.templates.blob.path=""
                                  --is.email.templates.directory=""
                                   --is.email.templates.includes=""
                                     --is.email.templates.source=""
                                        --is.email.templates.url=""
                                  --is.end-device-picture.bucket="end_device_pictures"
                              --is.end-device-picture.bucket-url="/assets/blob/end_device_pictures"
                                                --is.oauth.mount=""
                                   --is.oauth.ui.assets-base-url="/assets"
                                 --is.oauth.ui.branding-base-url=""
                                     --is.oauth.ui.canonical-url="http://localhost:1885/oauth"
                                          --is.oauth.ui.css-file="oauth.css"
                                      --is.oauth.ui.descriptions=""
                                       --is.oauth.ui.icon-prefix="oauth-"
                                       --is.oauth.ui.is.base-url="http://localhost:1885/api/v3"
                                        --is.oauth.ui.is.enabled="true"
                                           --is.oauth.ui.js-file="oauth.js"
                                          --is.oauth.ui.language="en"
                                         --is.oauth.ui.site-name="The Things Stack for LoRaWAN"
                                         --is.oauth.ui.sub-title=""
                                       --is.oauth.ui.theme-color=""
                                             --is.oauth.ui.title=""
                                     --is.profile-picture.bucket="profile_pictures"
                                 --is.profile-picture.bucket-url="/assets/blob/profile_pictures"
                               --is.profile-picture.use-gravatar="true"
                  --is.user-registration.admin-approval.required="false"
         --is.user-registration.contact-info-validation.required="false"
                      --is.user-registration.invitation.required="false"
                     --is.user-registration.invitation.token-ttl="168h0m0s"
         --is.user-registration.password-requirements.max-length="1000"
         --is.user-registration.password-requirements.min-digits="1"
         --is.user-registration.password-requirements.min-length="8"
        --is.user-registration.password-requirements.min-special="0"
      --is.user-registration.password-requirements.min-uppercase="1"
                                           --js.device-kek-label=""
                                            --js.join-eui-prefix="0000000000000000/0"
                                            --key-vault.provider="static"
                                              --key-vault.static=""
                                                     --log.level="info"
                                            --ns.cooldown-window="1s"
                                       --ns.deduplication-window="200ms"
                            --ns.default-mac-settings.adr-margin="15"
                       --ns.default-mac-settings.class-b-timeout="1m0s"
                       --ns.default-mac-settings.class-c-timeout="15s"
                     --ns.default-mac-settings.desired-rx1-delay="5"
              --ns.default-mac-settings.status-count-periodicity="20"
               --ns.default-mac-settings.status-time-periodicity="1h0m0s"
                                          --ns.dev-addr-prefixes=""
                                           --ns.device-kek-label=""
                            --ns.downlink-priorities.join-accept="highest"
                           --ns.downlink-priorities.mac-commands="highest"
               --ns.downlink-priorities.max-application-downlink="high"
                                        --ns.interop.blob.bucket=""
                                          --ns.interop.blob.path=""
                                      --ns.interop.config-source=""
                                          --ns.interop.directory=""
                                                --ns.interop.url=""
                                                     --ns.net-id="000000"
                                                 --redis.address="localhost:6379"
                                                --redis.database="0"
                                      --redis.failover.addresses=""
                                         --redis.failover.enable="false"
                                    --redis.failover.master-name=""
                                               --redis.namespace="ttn,v3"
                                                --redis.password=""
                                                    --rights.ttl="2m0s"
                                                    --sentry.dsn=""
                                         --tls.acme.default-host=""
                                                  --tls.acme.dir=""
                                                --tls.acme.email=""
                                               --tls.acme.enable="false"
                                             --tls.acme.endpoint="https://acme-v02.api.letsencrypt.org/directory"
                                                --tls.acme.hosts=""
                                               --tls.certificate="cert.pem"
                                      --tls.insecure-skip-verify="false"
                                                       --tls.key="key.pem"
                                              --tls.key-vault.id=""
                                                   --tls.root-ca=""
                                                    --tls.source=""

#### What do you see now?

**after ttn-lw-cli login .............. with above command**
 ERROR Please login with the login command
  INFO Opening your browser on https://200.200.200.200:8885/oauth/authorize?client_id=cli&redirect_uri=local-callback&response_type=code
  WARN Could not open your browser, you'll have to go there yourself error=exec: "xdg-open": executable file not found in $PATH
  INFO After logging in and authorizing the CLI, we'll get an access token for future commands.
  INFO Waiting for your authorization...

...

#### What do you want to see instead?

When open in the browser `https://200.200.200.200:8885/oauth/authorize?client_id=cli&redirect_uri=local-callback&response_type=code `- sugested link
and entering credentials (user, password) the page redirects to **localhost**
`http://localhost:11885/oauth/callback?code=MF2XI.LGIFQXRTNA544GOBE52LGOREXVTA5GSGPHBFNLI.Z6QENLFFHFJVQ7GW55NWSWBPGL474FREMKSB6YM5H4NPVAINVWXA&state=`

#### Environment

VPS ovh - debian 9 stretch, gateway/devices is not an issue (not added yet)

ttn-lw-cli version
```
Version:             3.3.2
Build date:          2019-12-04T11:14:37Z
Git commit:          0b1a4d7b3
Go version:          go1.13.4
OS/Arch:             linux/amd64

```
~# ttn-lw-stack version
The Things Stack for LoRaWAN: ttn-lw-stack
```
Version:             3.3.2
Build date:          2019-12-04T10:57:50Z
Git commit:          0b1a4d7b3
Go version:          go1.13.4
OS/Arch:             linux/amd64

```

...

#### How do you propose to implement this?

**Is there another way to enable remote authorization without opening remote web page?** eg. **passing ttn-lw-cli login + user/password on the console?** to move on immediately

Fix redirection from localhost to the current server (relative paths).

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by htdvisser** [comment]
Have you seen https://thethingsstack.io/v3.3.2/guides/getting-started/cli/#login ?

Specifically the part that says

> During the login procedure, the CLI starts a webserver on `localhost` in order to receive the OAuth callback after login. If you are running the CLI on a machine that is not `localhost`, you can pass the `--callback=false` flag. This will allow you to perform part of the OAuth flow on a different machine, and copy-paste a code back into the CLI.

**Comment by ecities** [comment]
Hi, @htdvisser, Thanks for reply . I saw it .... but it seems I didn't process this information ;) .
I checked all parameters including **--callback false** (without **=** char) as other parameters are supplied.

Your solution,  move it a little forward - into certificates issue.
I have generated certificate with openssl.

**Comment by ecities** [comment]
Can the certificate be generated to work remotelly (By public IP) or (localhost) for 
ttn-lw-cli commands for adding gateways, devices, and so on.

**Comment by htdvisser** [comment]
If you're setting up The Things Stack on a server with a public IP, you should just point a (sub)domain to it and use our builtin support for requesting and using certificates from Let's Encrypt.

I recommend you to spin up a fresh new server, point some subdomain to it and see if this works for you: https://gist.github.com/htdvisser/4503f30699308a7fd9e0aa3ebc2f3eb4
