### ISSUE TITLE
Basic Station Integration: Server-side connection termination causing unreliable downlink scheduling

### ISSUE THREAD

**Issue by beitler** [TheThingsNetwork/lorawan-stack#1729]
#### Summary

The Basic Station protocol server integration on the community network`*` terminates the TCP connection if 60 seconds of inactivity is detected. In an event of such a server-side disconnect, Basic Station continues running the radio and tries to re-connect with an exponential back-off. The whole re-connection procedure can potentially take multiple seconds, during which uplink messages could be received and queued internally. After the connection is established again, the internal uplink buffer is pushed to the server and the radio is re-started with the configuration contained in the router_config message. Downlinks, which are scheduled in response to any of those uplinks will be rejected by Basic Station because the xtime session is not in sync (this is the whole purpose of the xtime session indicator). Therefore, the periodic disconnects are causing less reliable downlinks. In addition to that, if an uplink with a new xtime session is forwarded before the downlink in response to an uplink from the old xtime session is scheduled, we are running into issue #1707 which blocks the gateway for any future downlinks.

The v3 stack does not seem to implement the periodic server-side disconnects due to inactivity. So, it is unclear, why it is needed on the community network. Maybe the underlying problem which introduced the need for those disconnects can be met in another way?

`*` I'm posting the issue here because it looks to me that the actual code that drives the Basic Station integration on the community network is not available on github, but I assume it is a derivative of what is done in pkg/gatewayserver/*.

#### Steps to Reproduce
 1. Start Basic Station and make sure no uplinks are forwarded within 60 seconds
 2. After the server side disconnects start sending uplink packets
 3. Wait for Basic Station to re connect.

#### What do you see now?

 - Downlinks in response to uplinks received before the new connection was established, are rejected.
 - Downlinks in response to uplinks received after the new connection was established but before the downlink was scheduled by the server, will trigger issue #1707 and block the gateway for future downlinks.

#### What do you want to see instead?

I want to see a stable connection without server-side connection terminations even when no uplinks are received. Re-connects should be rare events because they introduce a switch from one xtime session to another, which makes it impossible to schedule downlinks across xtime sessions.

#### Environment

Basic Station (latest version), TTN community network.

(On the v3 stack those disconnects do not happen).

#### How do you propose to implement this?

This depends on the reason why the disconnects were introduced in the first place. To make downlink scheduling more reliable across disconnects one could think about an additional check in Basic Station: if the crc32 of the new radio_config is equal to the crc32 of the old radio_config, the radio is not re-initialized. This, however, may potentially introduce more problems since issue #1351 may be triggered, locking the gateway for any downlinks in the future.

If the reason for the disconnects is some sort of heuristic drop resources for 'dead' connections, then it should be reconsidered, how a 'dead' connection is detected. Basic Station relies on TCP keep alive to check for connection aliveness. Version 2.0.4 will finally also respond to WS PING, so you can use that as well.

In general, it should be considered that re-connects inevitably introduce a time window of unreliable message delivery. Therefore, re-connects should be avoided if possible.

**Comment by KrishnaIyer** [comment]
We haven't heard this issue after the deployment of the latest fixes. Please feel free to re-open if observed again.
