### ISSUE TITLE
Basic Station Integration: RX UTC time is scaled down by 1e-9

### ISSUE THREAD

**Issue by beitler** [TheThingsNetwork/lorawan-stack#1732]
#### Summary
In the community network, the uplink timestamp originating from Basic Station based gateways is scaled by the 1e-9.

#### Steps to Reproduce

1. Attach a Basic Station based gateway to the TTN community network.
2. Receive an uplink from a known device over that gateway.

#### What do you see now?
The received uplink is listed in the gateway traffic console with the correct timestamp:
```
{
  "gw_id": "eui-58a0cbfffe80xxxx",
  "payload": "QFsuASaACADIo6YgurFtFm6Ae4WLZeX+o7jXOnA=",
  "f_cnt": 8,
  "lora": {
    "spreading_factor": 7,
    "bandwidth": 125,
    "air_time": 66816000
  },
  "coding_rate": "4/5",
  "timestamp": "2019-12-16T11:18:20.238Z",
  "rssi": -75,
  "snr": 7.5,
  "dev_addr": "26012E5B",
  "frequency": 868500000
}
```
Here the reception time is correctly shown as `2019-12-16T11:18:20.238Z`. However, the same uplink shows a wrong reception time for that gateway in the application data console:
```
{
  "time": "2019-12-16T11:18:20.232576027Z",
  "frequency": 868.5,
  "modulation": "LORA",
  "data_rate": "SF7BW125",
  "coding_rate": "4/5",
  "gateways": [
    {
      "gtw_id": "eui-58a0cbfffe80xxxx",
      "timestamp": 110710299,
      "time": "1970-01-01T00:00:01.5764951Z",
      "channel": 0,
      "rssi": -75,
      "snr": 7.5
    }
  ]
}
```
Note that
```
$ python3.7 -c 'from datetime import datetime as dt; print(dt.utcfromtimestamp(dt.fromisoformat("2019-12-16T11:18:20.238").timestamp() * 1e-9))'
1970-01-01 00:00:01.576492
```
So, obviously, there is mistakenly some 1e-9 scaling going on in the protocol bridge.

#### What do you want to see instead?
The per-gateway reception time for Basic Station based gateways should contain the exact same value as shown in the gateway console.

#### Environment
Basic Station, TTN community network

**Comment by KrishnaIyer** [comment]
I believed this is fixed in #2141. Please re-open if necessary.
