### ISSUE TITLE
PubSub MQTT input field validation is too strict

### ISSUE THREAD

**Issue by reissjason** [TheThingsNetwork/lorawan-stack#1737]
#### Summary
When configuring an MQTT PubSub Integration valid entries for client-id or username are blocked by UI validation. Using http://www.dioty.co/mqtt provides an email address for username. This was not allowed. client-id or username containing uppercase letters are also not allowed.

#### Steps to Reproduce

1. Select an Application
2. Add a new PubSub Integration
3. Select MQTT as type
4. Enter "aaaBBB" as client-id or username

#### What do you see now?

![image](https://user-images.githubusercontent.com/1387696/71009071-45c31580-20af-11ea-9a67-7a634ad48648.png)

#### What do you want to see instead?

Less restrictive validation should be used.

#### Environment

v3.3.2

#### How do you propose to implement this?

Review validation requirements.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by htdvisser** [comment]
This seems to be a restriction imposed by the frontend, as the backend only has a maximum length defined.

**Comment by htdvisser** [comment]
Source: `pkg/webui/console/components/pubsub-form/validation-schema.js`
