### ISSUE TITLE
Unable to edit existing PubSub integration

### ISSUE THREAD

**Issue by reissjason** [TheThingsNetwork/lorawan-stack#1740]
#### Summary
PubSub Integration screen displays an error. MQTT and NATS integrations both display the error.

...

#### Steps to Reproduce

1. Create a new PubSub integration with dummy values
2. Try to edit the created PubSub integration.
3. ...

#### What do you see now?

![image](https://user-images.githubusercontent.com/1387696/71018481-2da6c280-20be-11ea-8733-000270134188.png)

#### What do you want to see instead?

The edit form should be displayed.

#### Environment

v3.3.2

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

No

**Comment by htdvisser** [comment]
Error in Devtools: `ReferenceError: "PageTitle is not defined"`

**Comment by kschiffer** [comment]
This has been fixed already via #1603.
