### ISSUE TITLE
Enforce EUI and ID uniqueness in device registries

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#175]
**Summary:** 

Component registries should enforce uniqueness of IDs and EUIs.
This is already done in Network Server, but not in JS.

**Why do we need this?**

To avoid clashes

**What is already there? What do you see now?**

EUI uniqueness enforcement in JS, but not ID uniqueness

**What is missing? What do you want to see?**

Enforce uniqueness of ID and EUI pairs in registries

**How do you propose to implement this?**

Adapt from NS(https://github.com/TheThingsNetwork/lorawan-stack/blob/f1377b316a85ae3709a84db5b5f9a46faafba3a0/pkg/networkserver/redis/registry.go#L218-L233)
@johanstokking is AS relevant here too? If not, please remove the label.

**Comment by johanstokking** [comment]
@rvolosatovs let's leave AS out of scope; the AS doesn't really care about EUIs.

**Comment by johanstokking** [comment]
Let's do this for AS as well. Even if it was just as sanity check; it's an EUI.
