### ISSUE TITLE
Make figure shortcode error on pictures that were not found

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1759]
#### Summary

We should make the `figure` shortcode in the documentation check if a file actually exists.

#### What is already there? What do you see now?

Right now the figure shortcode just puts the `src` into an `img` tag.

#### What is missing? What do you want to see?

The shortcode should check if the picture is available in the page resources, and otherwise error.

#### How do you propose to implement this?

Probably just copy-paste the `figure` shortcode from Hugo and add

```
{{- if not (.Page.Resources.GetMatch (.Get "src")) -}}
{{ errorf "asset %s not found in page bundle" (.Get "src") }}
{{- end -}}
```

#### Can you do this yourself and submit a Pull Request?

Sure

**Comment by benolayinka** [comment]
Moved to https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/83
