### ISSUE TITLE
Fail to update the gateway eui via cli

### ISSUE THREAD

**Issue by virtualguy** [TheThingsNetwork/lorawan-stack#1807]
#### Summary
When trying to just set the gateway eui the field wont update. ~~A work around is to set an additional field (such as --name) at the same time and then the command takes affect.~~

#### Steps to Reproduce
1. ttn-lw-cli gateway create example_gateway
2. ttn-lw-cli gateway update example_gateway --gateway-eui 00800000a0999999
3. Observe that the gateway eui is not set

#### What do you see now?
ttn-lw-cli gateway update example_gateway --gateway-eui 00800000a0999999
  WARN No fields selected, won't update anything

#### What do you want to see instead?
ttn-lw-cli gateway update example_gateway --gateway-eui 00800000a0999999
{
  "ids": {
    "gateway_id": "example_gateway",
    "eui": "00800000a0999999"
  },
  "created_at": "2020-01-06T23:07:14.624Z",
  "updated_at": "2020-01-06T23:11:44.343Z",
  "version_ids": {

  }
}

#### Environment
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.4.1
Build date:          2019-12-30T12:14:16Z
Git commit:          283798f88
Go version:          go1.13.5
OS/Arch:             linux/amd64

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by neoaggelos** [comment]
Thanks @virtualguy for reporting this. This is indeed a bug with the cli. I have tracked the cause and currently working on a solution.

**Comment by virtualguy** [comment]
Thanks @neoaggelos to confuse matters if I specify an eui then it reponds back with the eui set but does not actually update the database. So the above mentioned workaround does not help
