### ISSUE TITLE
Use Error instead of Fatal in tests goroutines

### ISSUE THREAD

**Issue by M-Gregoire** [TheThingsNetwork/lorawan-stack#182]
**Summary:** 

`Fatal` from `testing` is used in the testing of the device registry of the JS and NS where  `t`  is passed from the context. This shouldn't happen and causes a deadlock  whenever fatal is called.

**Steps to Reproduce:** 

1. Modify a test so that it fails and `Fatal` is called
2. Run test

**What do you see now?**

A use of `Fatal` in goroutines other than where the test function itself is running.

**What do you want to see instead?**
Use of `Error` instead.

**What can you do yourself and what do you need help with?**
Fix the issue.

**Comment by johanstokking** [comment]
Make part of #192
