### ISSUE TITLE
Support Multiple Frequency Plans in Scheduler

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#1824]
#### Summary

Support Multiple Frequency Plans in Scheduler (refs #761)

#### Why do we need this?

Enable downlinks on multiple concentrators.

#### What is already there? What do you see now?

Branch `feature/761-multi-fplan-gtw` contains the rest of the items discussed in #761.

#### What is missing? What do you want to see?

Use the supported `FrequencyPlans` struct in the scheduler and use the `frequency_plan_id` as part of the `TxRequest` to choose the correct downlink parameters.

#### Environment

ttn-lw-stack v3.4.1

#### How do you propose to implement this?

Better left to the expert.

#### Can you do this yourself and submit a Pull Request?

Can review and test if necessary.

**Comment by johanstokking** [comment]
Can you see if you can pick this up? Would be great as a separate PR and not part of #1826.

**Comment by KrishnaIyer** [comment]
Ok. I'll take this.

**Comment by KrishnaIyer** [comment]
To summarise our discussions here:
- For now the FPs have to be from the same band.

As for combining frequency plans in the scheduler
- The timeOffAir parameter should be the same (same value or unset) across the FPs?
- As for sub bands, it would be a **union** of the frequencies right? The sub-bands encapsulate the difference in duty cycling so creating sub-bands based on the union of the FPs should work right?

**Comment by johanstokking** [comment]
> * The timeOffAir parameter should be the same (same value or unset) across the FPs?

Yes. If they don't match we can safely error.

> * As for sub bands, it would be a **union** of the frequencies right? The sub-bands encapsulate the difference in duty cycling so creating sub-bands based on the union of the FPs should work right?

That would be best. There are three scenarios then;

1. There are no FR sub-bands defined, which is great
2. The same sub-band for all FPs is configured, this is also good
3. The sub-bands of the given frequency plans do not overlap, this is also fine
4. The sub-bands of the given frequency plans are not the same and overlap. This is not good

**Comment by KrishnaIyer** [comment]
closed via #1859
