### ISSUE TITLE
Messages stop being sent to connected mqtt clients when re-linking application

### ISSUE THREAD

**Issue by virtualguy** [TheThingsNetwork/lorawan-stack#1831]
#### Summary
When a existing mqtt or grpc client is connected and the application link is updated (to the same value) the existing client stops receiving messages for all topics. The client does continue to stay connected and gets keep alive messages (pingresp). On restarting the mqtt client the traffic returns to normal

#### Steps to Reproduce
1. Create an application as per the getting started guide
2. Create api key and use to connect via mqtt
3. Validate that uplink messages arrive as expected
4. Re link the application using the same api key as when it was created
5. Observe that uplinks arrive on the web console but not to the mqtt client

The same behaviour happens when using 
ttn-lw-cli applications subscribe

#### What do you see now?
Uplink traffic stops when the application link is re set

#### What do you want to see instead?
Traffic to momentarily stop while the application link is 'unlinked' and the restore for all connected and subscribed clients when the link is restored

#### Environment
Stack and cli version: 3.4.2

**Comment by virtualguy** [comment]
@htdvisser @johanstokking  thoughts?

**Comment by johanstokking** [comment]
@adriansmares existing subscriptions on links (like MQTT) need to be restored somehow when the link disappears. I think this has to be initiated by the subscriber, i.e. MQTT frontend, to start watching the link become available while it has clients connected.
