### ISSUE TITLE
Restrict create rights of users

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1890]
#### Summary

We should add an option to restrict the rights of users to create entities in their account.

#### Why do we need this?

A network operator may want to prevent users from creating entities in their own account, and only allow creating entities in organizations they have access to. This feature could also be used to prevent users from requesting OAuth clients.

#### What is already there? What do you see now?

- `is.authInfo` gets the user entity when using a User API key or OAuth access token
- `is.getRights` returns the rights of `is.authInfo` when a user lists their rights on their own user.

#### What is missing? What do you want to see?

~Intersecting the rights with the `rights` field in the User~

#### How do you propose to implement this?

See comments below

**Comment by laurensslats** [comment]
To clarify, requested feature is to set rights for:
Creating/modifying applications
Creating/deleting devices
Creating/deleting gateways

**Comment by benolayinka** [comment]
> To clarify, requested feature is to set rights for:
> Creating/modifying applications
> Creating/deleting devices
> Creating/deleting gateways

And in addition to this, using organizations to manage these permissions for groups of users.
So for example, a "read-only" organization could be used to easily create and group accounts without rights to create anything.

**Comment by htdvisser** [comment]
@benolayinka I don't think that is feasible, as it would require changes to our entire rights model.

The easiest way to implement the requirements listed by @laurensslats is to add network-wide configuration to prevent regular (non-admin) users from creating applications/gateways/organizations. Instead, admins will create those, and add users as members on those entities.

@laurensslats ACK?

**Comment by laurensslats** [comment]
@htdvisser yes, this sounds perfect.

Let's focus on devices, applications, gateways and organizations. 
Admins can pose restrictions on users to create/modify/delete any of these.

By default, all users should have all the rights when creating an account.

**Comment by htdvisser** [comment]
- This would apply to Applications, Gateways, Organizations and OAuth clients. End Device rights are managed through application membership rights, so no need to build something custom for that.
- It would be configuration for the entire network, that applies to all non-admin users.
- The default value for the option would indeed be the same as the current behavior (allowed).

**Comment by htdvisser** [comment]
Closed by #2918
