### ISSUE TITLE
Multiple scrollbars in desktop view

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#1924]
#### Summary

There are pages in the Console that have multiple scrollbars in the desktop view

#### Steps to Reproduce

1. Go to the pubsub create page
2. See 2 scrollbars that in certain cases make it problematic to scroll the page seamlessly

#### What do you see now?

2 scrollbars in the pubsub create page

#### What do you want to see instead?

just a single scrollbar

#### Environment

Google Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
The Things Stack: v3.5.0

#### Can you do this yourself and submit a Pull Request?

yes, but i think it makes sense to add this fix into the responsiveness related prs

**Comment by kschiffer** [comment]
This is related to this change:
https://github.com/TheThingsNetwork/lorawan-stack/commit/f5e5a3d4b62bda89a3f0ccef6bb6086200c8f2ac

Do you recall the context?

**Comment by bafonins** [comment]
Looks like the issue is fixed
