### ISSUE TITLE
Bad payload decryption after a new join when using external JS

### ISSUE THREAD

**Issue by Oliv4945** [TheThingsNetwork/lorawan-stack#1928]
#### Summary
When a device joins with external JS for the 2nd time or more the payload is not decrypted correctly, it seems that session keys used by the LNS are wrong

#### Steps to Reproduce
1. Create a device using[ Semtech's join server](https://www.loracloud.com)
2. Join network
3. Send a payload => In MQTT uplink, payload is ok
4. Reset the device
5. Join the netwok
6. Send a payload => In MQTT uplink, payload is not ok

Reproduced in self hosted v3.5.0 and TTI v3.5.1-rc1

#### What do you want to see instead?
Device payload decrypted correctly each time

#### Can you do this yourself and submit a Pull Request?
No

**Comment by johanstokking** [comment]
@Oliv4945 can you confirm that this regression is since v3.5.0; or is v3.4.2 also not working correctly?

**Comment by Oliv4945** [comment]
Issue is also in v3.4.2, I tested it yesterday on a clean install

**Comment by Oliv4945** [comment]
I confirm the fix, thank you😃
