### ISSUE TITLE
Support Downlinks via the Console

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#1948]
#### Summary

Support Downlinks via the Console

#### Why do we need this?

To be on par with V2, also non-technical individuals can't be expected to setup the CLI (or use HTTP/MQTT hooks) only to send Downlinks.

#### What is already there? What do you see now?

Downlinks only via API (HTTP/MQTT) or CLI.

#### What is missing? What do you want to see?

Support Downlink operations via the Console

#### Environment

`ttn-lw-stack v.3.5.1`

#### How do you propose to implement this?

🤷‍♂ 

#### Can you do this yourself and submit a Pull Request?

I can help deploy and test.

**Comment by bafonins** [comment]
What are the APIs to be used?
Any propositions on where is the right place for this?
How important is this feature?
Can we use the v2 console UI as a reference?
<img width="845" alt="Screenshot 2020-02-05 at 14 28 47" src="https://user-images.githubusercontent.com/16374166/73841775-fafa8a00-4823-11ea-9ed6-1df9f9fbe735.png">


cc @johanstokking

**Comment by adriansmares** [comment]
Regarding the API used for downlink queue operations - use [`AppAs`](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#service-appas) - The console already uses it partially in the integrations page for the `GetMQTTConnectionInfo` method.

**Comment by johanstokking** [comment]
Let's indeed start with simple push and replace operations, with a single message that you can enter as hex. That feature matches with V2.

We can add listing the downlink queue later. That's a super nice feature too.

**Comment by willhelmx** [comment]
Really nice if you Implement this features guy´s
Also for developments purposes it would be very nice to have the possibility to se the Payload/ decoded payload in a terminal window like in the public TTN instead of having to click and look at the entire data in every instance

BR
/A

**Comment by bafonins** [comment]
@willhelmx We already consider displaying decoded payload and other useful entity/event fields in the events pane for each event. You can find the discussion in https://github.com/TheThingsNetwork/lorawan-stack/issues/1962, do not hesitate to join and express your needs/opinions.

**Comment by kschiffer** [comment]
Closed via #2338
