### ISSUE TITLE
move the abp activated device one application to another application error 

### ISSUE THREAD

**Issue by DurgaPrasadWebDev** [TheThingsNetwork/lorawan-stack#1957]
details contail the old device details it also an ABP device 
echo $details | ttn-lw-cli end-devices create --abp

Could not create end device, rolling back... error=error:pkg/networkserver:field_value (invalid value of field `ids.dev_addr`) field=ids.dev_addr

**Comment by johanstokking** [comment]
@DurgaPrasadWebDev please use the issue template.

For ABP, please see the docs: https://thethingsstack.io/v3.5.1/guides/getting-started/cli/ (see ABP)
