### ISSUE TITLE
Event error payloads are not shown

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#1963]
#### Summary

Event error payloads are not shown

#### Steps to Reproduce

1. Subscribe to gateway or application events in the Console
2. Observe failure or packet drop events; they are not shown
3. Subscribe to the same events in CLI; they are shown

#### What do you see now?

Console doesn't show error payloads:

<img width="1096" alt="Screenshot 2020-02-07 at 13 32 10" src="https://user-images.githubusercontent.com/13334001/74030437-55742180-49af-11ea-905f-83539b99adb7.png">

#### What do you want to see instead?

Error payloads, like CLI:

```json
{
  "name": "gs.up.drop",
  "time": "2020-02-07T12:30:40.588851469Z",
  "identifiers": [
    {
      "gateway_ids": {
        "gateway_id": "kerlink-ifemtocell",
        "eui": "7276FF003903007D"
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
    "namespace": "pkg/gatewayserver",
    "name": "host_handle",
    "message_format": "host `{host}` failed to handle message",
    "attributes": {
        "host": "cluster"
      },
    "cause": {
      "namespace": "pkg/networkserver",
      "name": "device_not_found",
      "message_format": "device not found",
      "correlation_id": "df971dc6e7c5402596576816401ade98",
      "code": 5
    },
    "code": 5
  },
  ...
}
```

#### Environment

Console

#### How do you propose to implement this?

- Remove a filter somewhere that suppresses error payloads (?)
- Render the error nicely. Would be nice to show a tree of causes

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by pgalic96** [comment]
@johanstokking Does this entail also non uplink/downlink related event errors (such as failed link, failed pubsub etc.)?

**Comment by htdvisser** [comment]
This concerns all events with a `"data"` object that has `"@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails"`
