### ISSUE TITLE
Webhook configured URL trailing slash dropped

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#1995]
#### Summary

When you configure a Webhook via the console, and the URL ends in a / the / is dropped when the actual call is made.

#### Steps to Reproduce

Webhook is configured as in this example:

![image](https://user-images.githubusercontent.com/948278/74600882-2725ce80-50a0-11ea-9928-eb0eb738add3.png)

#### What do you see now?

In the docker-compose logs:
```
stack_1      | 2020-02-16T07:33:49.240509848Z  DEBUG Process message                          application_uid=jpm-crickets hook=ttnmapper namespace=applicationserver network_server=ace3b78e8707 url=http://private.ttnmapper.org/integrations/ttn/v3/uplink_message
```

Because the POST is done to an incorrect URL, the server will redirect the call to the correct one that does have a trailing slash. The original call was a POST, but according to the HTTP specs the retry to the correct URL should be a GET. The problem is that the GET does not contain the JSON payload. The server therefore sees an empty request body.

#### What do you want to see instead?

In the logs I want to see:
`url=http://private.ttnmapper.org/integrations/ttn/v3/uplink_message/`

#### Environment

The Things Stack v3.5.3 Docker image

#### How do you propose to implement this?

Webhooks should use the specified URL as is, without stripping the trailing slash.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by anush0247** [comment]
+1 we also faced this issue, implemented an internal work around

**Comment by johanstokking** [comment]
Thanks for reporting

**Comment by adriansmares** [comment]
This is caused by our usage of `path.Join` which is meant for file system paths (which cannot have a trailing slash). 

I'll move this logic (and other usages) to `url.ResolveReference`, which should fix the cause. See https://play.golang.org/p/JhXy_xjAJ6b for an example.
