### ISSUE TITLE
Two-factor Authentication

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2]
**Summary:** 
Add two-factor authentication

**Why do we need this?**
Better security

**What is already there? What do you see now?**
Only single-factor authentication

**What is missing? What do you want to see?**
Support Authenticator app and u2f + recovery codes

**How do you propose to implement this?**
As suggested on Slack and on the Forum: add support for FIDO U2F. This library seems to implement it in Go: https://github.com/tstranex/u2f

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/99 by @htdvisser

**Comment by nejraselimovic** [comment]
@bafonins open this issue in TheThingsID repo

**Comment by kschiffer** [comment]
@johanstokking does this need to be reprioritized?

**Comment by johanstokking** [comment]
I prioritized https://github.com/TheThingsIndustries/the-things-id/issues/63 instead.

This issue is only relevant for The Things Stack Open Source really; Enterprise supports OpenID Connect providers. We may want to bring that to Open Source so people can also use The Things ID here.

@NicolasMrad what do you think?

**Comment by NicolasMrad** [comment]
I think we can prioritise https://github.com/TheThingsIndustries/the-things-id/issues/63 and keep OpenID Connect for enterprise users only at the moment as an added value.

**Comment by johanstokking** [comment]
For background, 2FA isn't easy because:

1. We need users to get those codes. We could render a QR that they can scan with their favorite authenticator app and/or we could send text messages.
2. We need to validate the codes. This, and the previous point, are probably the easiest things.
3. We need a recovery process in case users lost their phone, changed their number or whatever. High level, we can have different things, or a combination:
   - Recovery codes that the users must keep safe. This would lead to password reset and 2FA reset and is fully self service. The problem is that it is very likely that people do not record or lose these recovery codes
   - Reset the account and require recovery and password + 2FA reset via a text message, i.e. NOT the email that the user uses to login
   - Reset the account and require recovery and password + 2FA reset via email. If we do this, we might as well send an email challenge once in a while on login
   - Depending on The Things Stack configuration, require administrators to reset user accounts (and optionally do not allow reset via email or text message)

This process, plus all the frontend work related to this, is quite something. I don't really see all this identity and account security management part of the scope of The Things Stack, so we have OpenID Connect in Enterprise and for The Things Stack Community we use that with The Things ID.

Let's remove this from this milestone and leave this open until we decide otherwise.

**Comment by johanstokking** [comment]
We are reconsidering when and where this will be implemented. This is closed until further notice.
