### ISSUE TITLE
Basic Station WS Ping-Pong

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#2003]
#### Summary

Implement WS Ping for Basic Station frontend.

#### Why do we need this?

To prevent our proxy from dropping WS connections due to inactivity of the gateway.
Refs: #1729 

#### What is already there? What do you see now?

No Ping sent.

#### What is missing? What do you want to see?

Send WS pings periodically (configurable).

#### Environment

`ttn-lw-stack v3.5.2`

#### How do you propose to implement this?

Add periodic pings to BS frontend.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by johanstokking** [comment]
This is not supported by all Minihub firmwares; afaik not in any publicly released firmware. Enable this only on reported version.

**Comment by KrishnaIyer** [comment]
Yes that's true but the server sending a ping (and ignoring pong on versions that don't support it) prevents the proxy from disconnecting the gateways after 60s(now 600s) of inactivity.

**Comment by johanstokking** [comment]
OK, as long as we don't expect the pongs!
