### ISSUE TITLE
Support multiple gateway antennas

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#2006]
#### Summary

Support multiple antennas for a single gateway

#### Why do we need this?

Some gateways may have more than one antennas

#### What is already there? What do you see now?

Support for a single antenna per gateway. Even if multiple antennas exist, only the first one is used and the rest are ignored.

Relevant issues #48, #1820

#### What is missing? What do you want to see?

Handle all gateway antennas.

#### Environment

3.5.3

#### How do you propose to implement this?

Update code in the relevant TODO sections where this issue is referenced

#### Can you do this yourself and submit a Pull Request?

Cannot pick up currently, adding to backlog

**Comment by johanstokking** [comment]
This issue is specific to automatically updating the antenna locations based on status messages or uplink metadata. I don't think we really need this.

**Comment by johanstokking** [comment]
As this is easy to fix, let's do fix it.
