### ISSUE TITLE
Add "Create" to User Management in Console

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2019]
#### Summary

We should add functionality to let admins create other users from the Console.

#### Why do we need this?

Because now users have to go through the registration flow and wait for an admin to approve them.

#### What is already there? What do you see now?

#1706 added user management, but without create functionality.

#### What is missing? What do you want to see?

A button to create a user that would show something similar to the "edit user" form, but with some additional fields (password, email address validated)

#### Environment

Console

#### How do you propose to implement this?

The API is the same as for the account app, except that we make an authenticated request

**Comment by bafonins** [comment]
Already implemented
