### ISSUE TITLE
Add "Invite" to User Management in Console

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2020]
#### Summary

We should add functionality to let admins invite other users from the Console.

#### Why do we need this?

Because now this is only possible with the CLI.

#### What is already there? What do you see now?

Implementation in the CLI: https://github.com/TheThingsNetwork/lorawan-stack/blob/master/cmd/ttn-lw-cli/commands/users_invitations.go
#1706 added user management, but without invite functionality.

#### What is missing? What do you want to see?

An "invite a user" button, enter email address, click "invite".

Nice to have: managing invitations (listing+deleting).

#### How do you propose to implement this?

API: https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#ttn.lorawan.v3.UserInvitationRegistry

**Comment by kschiffer** [comment]
I see this as a separate tab "Invitations" in the admin's user management view.

The table would show `email`, `send at`, `status`, and a delete button to delete pending invitations. New invitations can then be issued with a `Invite user` button that leads to a form that asks for the email address. Iirc, invitations can also be disabled altogether via stack configuration (cc @htdvisser). In that case we need to pass that info to the Console as well so the invitation tab can be hidden.
