### ISSUE TITLE
Message references are not working between sections

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2027]
#### Summary

Proto message references in the API reference section of the documentation cannot be clicked if the message is not part of the current section.

#### Steps to Reproduce

1. Go to `Reference` - `Application Webhook APIs`
2. Go to the `ApplicationWebhookIdentifiers` message.
3. Click on the `ApplicationIdentifiers` message type.

#### What do you see now?

The link does not work since the message is not defined in the current document.

#### What do you want to see instead?

The link should lead me to the correct message definition.

#### Environment

1d5aec3

#### How do you propose to implement this?

I'm not sure what would be the best here. cc @htdvisser 

#### Can you do this yourself and submit a Pull Request?

Once we clarify how we can achieve this.

**Comment by htdvisser** [comment]
Just add those messages to the page?

**Comment by adriansmares** [comment]
If you feel that duplicating them between the sections I'm ok with this :+1:

**Comment by htdvisser** [comment]
Yeah we also do that on the other reference pages, for example with the Collaborator message.

**Comment by johanstokking** [comment]
@KrishnaIyer is this still relevant?

**Comment by KrishnaIyer** [comment]
Nope. I followed the reproduction steps and this is no longer relevant. This is fixed in the docs.
