### ISSUE TITLE
Validate credentials in PubSub

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2045]
#### Summary

PubSub providers that use a username and password pair should ensure that partial credentials cannot be used (specifying only password or only the username).

#### Steps to Reproduce

1. Attempt to update a PubSub provider using the CLI/Console/API and set only the username or only the password.

#### What do you see now?

No error.

#### What do you want to see instead?

An error stating that partial credentials are not allowed.

#### How do you propose to implement this?

Since at a request level this cannot be fully decided (if only the password path exists maybe the username is already in the store), it must be handled at store level after the update has been merged with the stored provider.

#### Can you do this yourself and submit a Pull Request?

Yes. cc @bafonins

**Comment by htdvisser** [comment]
For MQTT it's perfectly legal to only have a username, and no password. In MQTT 5 (which we currently don't support yet, but will in the future) it's even legal to only use a password, and no username.
