### ISSUE TITLE
Enum values in API call set inconsistent with CLI values and API call get

### ISSUE THREAD

**Issue by pdubois22** [TheThingsNetwork/lorawan-stack#205]
**Summary:** 
In API call (for ex /api/v3/ns/applications/xxx/devices/yyy), the enum values have to be specified using a format which is inconsistent with the values used in the CLI interface, and also inconsistent with the get:

in API / Post:
"lorawan_phy_version":"PHY_V1_0_2_REV_B"

in API / Get:
"lorawan_phy_version":"1.0.2-b"

in CLI:
--lorawan-phy-version=1.0.2-b

**Steps to Reproduce:** 
post a json for a device on the ns set API with "lorawan_phy_version":"1.0.2-b" : value is ignored, and a missing field error is returned.
post a json with "lorawan_phy_version":"PHY_V1_0_2_REV_B": value accepted.

**What do you see now?**
inconsistent values

**What do you want to see instead?**
"lorawan_phy_version":"1.0.2-b" accepted in post. 

**How do you propose to implement this?**

Value is unmarshalled by the gogo/protobuf based on enum values.

in jsonpb.go l 988:
```
	if inputValue[0] == '"' && prop != nil && prop.Enum != "" {
		vmap := proto.EnumValueMap(prop.Enum)
		// Don't need to do unquoting; valid enum names
		// are from a limited character set.
		s := inputValue[1 : len(inputValue)-1]
		n, ok := vmap[string(s)]
		if !ok {
			return fmt.Errorf("unknown value %q for enum %s", s, prop.Enum)
		}

```

Not sure where the culpirit is, but could it be the ttnpb/lorawan.pb.go ? 

```
var PHYVersion_name = map[int32]string{
	0: "PHY_UNKNOWN",
	1: "PHY_V1_0",
	2: "PHY_V1_0_1",
	3: "PHY_V1_0_2_REV_A",
	4: "PHY_V1_0_2_REV_B",
	5: "PHY_V1_1_REV_A",
	6: "PHY_V1_1_REV_B",
}
var PHYVersion_value = map[string]int32{
	"PHY_UNKNOWN":      0,
	"PHY_V1_0":         1,
	"PHY_V1_0_1":       2,
	"PHY_V1_0_2_REV_A": 3,
	"PHY_V1_0_2_REV_B": 4,
	"PHY_V1_1_REV_A":   5,
	"PHY_V1_1_REV_B":   6,
}

```
**Environment:**
api call / http 

**What can you do yourself and what do you need help with?**
I tried to debug as much as I could. Not sure about the impact on any change tough.

**Comment by johanstokking** [comment]
For the API, we're following the [JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) of Protocol Buffers. See example there; enums are marshalled as string `"FOO_BAR"`.

In the CLI, we support both a human friendly and the JSON format.

The A in API makes that we do not have to make it human friendly, basically. And most of all compatible with the JSON mapping, so that if clients use generated code based on our protos, they don't have to implement custom marshalers.
