### ISSUE TITLE
Webhook headers do not get saved on webhook update

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2061]
#### Summary

The webhook headers do not get saved on webhook save, in the Console.

#### Steps to Reproduce

1. Create a webhook
2. Open the webhook through the integrations menu
2. Add a header (I've tested this with `tstst` : `tststst`)
3. Save the webhook

#### What do you see now?

The headers do not get saved (after refresh they are not visible).

#### What do you want to see instead?

The headers should get saved.

#### Environment

3.6.0-rc1
I've been able to reproduce this successfully in CH.

#### Can you do this yourself and submit a Pull Request?

Not in time for the 3.6.0 release.

**Comment by bafonins** [comment]
Can confirm. Regression after https://github.com/TheThingsNetwork/lorawan-stack/pull/1965
