### ISSUE TITLE
Output debug message when gateway status is dropped

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#2076]
#### Summary

Related to #2074

It was difficult realizing #2074 was a bug, because no debug output message was seen in the log. Maybe we should add something when verbosity is set to debug?

#### Why do we need this?

Debugging and fault finding.

#### What is already there? What do you see now?

I don't see any mention of dropped status messages in the debug log.

#### What is missing? What do you want to see?

I want to see a message that a status is dropped with the reason why it is dropped. Just like we have a message when an unplink packet is dropped.

#### Environment

ttn-lw-stack 3.6.0.

#### How do you propose to implement this?

Add a if(DEBUG) fmt.println(reason)

#### Can you do this yourself and submit a Pull Request?

Maybe, will have to check the code.

**Comment by KrishnaIyer** [comment]
@jpmeijers: Status messages are dropped because no one in the upstream (Network Server/Packet Broker) currently needs/uses it.
