### ISSUE TITLE
Cache Redis configuration (namespace)

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#2091]
#### Summary

The cache Redis does not have a namespace by default

#### Why do we need this?

The key naming scheme for the Stack dictates that all Redis keys should exist under a specific namespace. 

#### What is already there? What do you see now?

Default Cache Config is null, so `RootNamespace` is also set to null.

Components that use the cache Redis (e.g. GS and IS) do nothing to check that the Redis config is empty.

#### What is missing? What do you want to see?

- DefaultCacheConfig.Service should probably default to "redis" (which is also the only supported service at the moment.
- DefaultCacheConfig.Redis can be empty by default. However, the components that want to use it should check whether the config is empty (using `conf.IsZero()`), and fallback to the default Redis configuration if this is the case.

#### Environment

3.6.0-dev

#### How do you propose to implement this?

- For default cache config, we could add `DefaultCacheConfig{Service: "redis"}`

- For cache Redis namespace: (1) Update all components that use the cache Redis to fallback to the default Redis configuration if needed, or (2) Make this into a `NewRedisCache(config)` and update existing components to use that one. This appears to be a bit more future-proof.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
@htdvisser apparently this behavior is consistent with IS. Do we not use the prefix for caching?

**Comment by htdvisser** [comment]
There is indeed no default config for the cache (or for events).

In `cmd/internal/shared/events.go` we have the following logic to deal with this:

```go
switch config.Events.Backend {
// ...
case "redis":
	if !config.Events.Redis.IsZero() {
		events.SetDefaultPubSub(redis.NewPubSub(config.Events.Redis))
	} else {
		events.SetDefaultPubSub(redis.NewPubSub(config.Redis))
	}
	return nil
	// ...
```

We could do something similar for the cache:

```go
switch config.Cache.Service {
// ...
case "redis":
	if config.Cache.Redis.IsZero() {
		config.Cache.Redis = config.Redis
	}
	// ...
```

**Comment by johanstokking** [comment]
@htdvisser this is specifically about the namespace, i.e. keys not starting with `ttn:v3:...`

**Comment by htdvisser** [comment]
The `ttn:v3` namespace comes from the default config: https://github.com/TheThingsNetwork/lorawan-stack/blob/master/cmd/internal/shared/config.go#L83

We don't have that default in the other Redis configs

**Comment by neoaggelos** [comment]
I think it would make sense to have a default namespace for the cache as well.

**Comment by johanstokking** [comment]
I think so too. And since it's cache, it's a non-breaking change.
