### ISSUE TITLE
Implement user session API handlers

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2092]
#### Summary
The stack is currently missing handlers for the user session service. These handlers are needed to enable session management via the API.

#### Why do we need this?
It's necessary for the user session management of the account app (#1422, #1217)

#### What is already there? What do you see now?
- API protobuff definitions
- Management of authorizations

#### What is missing? What do you want to see?
- Handlers for the rpcs of the `UserSessionRegistry` service (`List` and `Delete`)

#### Environment
v3.6.0

#### How do you propose to implement this?
Trivial.

#### Can you do this yourself and submit a Pull Request?
I could do it, though I'd suggest some of the backenders doing it to be faster

**Comment by htdvisser** [comment]
I don't think I'll have time for this in March, so either it's later, or someone else needs to take this.

**Comment by kschiffer** [comment]
I'll do then.
