### ISSUE TITLE
Basic Station Integration: Timing out of sync if first seen xtime is larger than 2^32-1

### ISSUE THREAD

**Issue by beitler** [TheThingsNetwork/lorawan-stack#2097]
This is a follow-up on #1351 . Reproduction steps are the same.

#### Summary

During processing of `updf` messages originating from a Basic Station gateway, the 48-bit timestamp part of `xtime` is truncated to 32 bit. The server tracks 32 bit rollovers over time. However, if the first seen timestamp has already rolled over, this leads to a permanent misalignment.
As a result, class A downlink messages cannot be scheduled after that point. Scenarios in which this can occur are environments with low activity, where it might take more than 71 minutes between when the radio is started and the first uplink is seen.

#### Steps to Reproduce

1. Append `ext |= ((sL_t)0xAA<<32);` to https://github.com/lorabasics/basicstation/blob/master/src/timesync.c#L383 in Basic Station to simulate multiple 32-bit rollovers.
2. Do a join request and observe the protocol messages:

*Station log*
jreq:xtime -> 0xd400**aa**496054d6
```
2020-03-06 08:13:30.434 [AIO:XDEB] [3|WS] > {
  "msgtype": "jreq",
  "MHdr": 0,
  "JoinEui": "xx-xx-xx-xx-xx-xx-xx-xx",
  "DevEui": "xx-xx-xx-xx-xx-xx-xx-xx",
  "DevNonce": 3682,
  "MIC": 452273186,
  "RefTime": 1583482410.434758,
  "DR": 5,
  "Freq": 868100000,
  "upinfo": {
    "rctx": 0,
    "xtime": 59673426438149334,
    "gpstime": 0,
    "fts": -1,
    "rssi": -85,
    "snr": 4.75,
    "rxtime": 1583482410.434790
  }
}
```

dnmsg:xtime -> 0xd400**00**499d5dd6
```
2020-03-06 08:13:34.468 [AIO:XDEB] [3|WS] < {
  "msgtype": "dnmsg",
  "DevEui": "00-00-00-00-00-00-00-00",
  "dC": 0,
  "diid": 13448,
  "pdu": "xxxxxxxxxx",
  "RxDelay": 1,
  "RX1DR": 5,
  "RX1Freq": 868100000,
  "priority": 25,
  "xtime": 59672696297709014,
  "rctx": 0,
  "MuxTime": 1583482414.4691372
}
```

Error Message
```
2020-03-06 08:13:35.435 [S2E:VERB] ::0 diid=13448 [ant#0] - class A has no more alternate TX time
```
The error message arises because Station realizes that it cannot send the downlink in the requested xtime (it is already in the past). This kicks-off a [routine](https://github.com/lorabasics/basicstation/blob/c29b8502f8c715daecec6666835da6e981dc820a/src/s2e.c#L409) which checks for alternative downlink opportunities (RX2, back-off in case of Class C, etc). Upon realization that no alternative downlink opportunities exist for this frame, the downlink is dropped and the message is printed.

#### What do you see now?

The jreq message xtime is `hex(59673426438149334) = 0xd400aa496054d6`
The dnmsg message xtime is `hex(59672696297709014) = 0xd40000499d5dd6`
**Note** that `0xAA<<32` is omitted in the xtime of the dnmsg.

#### What do you want to see instead?

The dnmsg message xtime should be `hex(59673426442149334) = 0xd400aa499d5dd6`
**Note** that `0xAA<<32` MUST NOT be omitted in the xtime of the dnmsg.

The way the protocol was envisioned, is that `xtime` is an opaque value to the LNS. You just pass it along unchanged and control the scheduling time of class A downlinks with the `RxDelay` parameter.

#### Environment

* Basic Station 2.0.3
* TTN community network

#### How do you propose to implement this?

TBD

**Comment by johanstokking** [comment]
Thanks for the extensive report @beitler – it should be fixed in #2141
