### ISSUE TITLE
Support google.org/x/auth2 magic behavior

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#212]
**Summary:** 

Logging in the CLI after a full stack erasure, while still having the old access token, triggers an 500 error

**Steps to Reproduce:** 

1. Init the stack (`make dev.stack.init`)
2. Attempt to login using `ttn-lw-cli login`

**What do you see now?**

```
adriansmares@A98BCD2222F1:~/go/src/go.thethings.network/lorawan-stack$ ttn-lw-cli login
  WARN No valid access token present            error=oauth2: cannot fetch token: 500 Internal Server Error
Response: {"code":2,"message":"error:pkg/errors/web:http (HTTP error: Client authentication not sent)","details":[{"@type":"type.googleapis.com/ttn.lorawan.v3.ErrorDetails","namespace":"pkg/errors/web","name":"http","message_format":"HTTP error: {message}","attributes":{"message":"Client authentication not sent"}}]}

  INFO Please go to http://localhost:1885/oauth/authorize?client_id=cli&redirect_uri=http%3A%2F%2Flocalhost%3A11885%2Foauth%2Fcallback&response_type=code
  INFO Waiting for your authorization...     
```

**What do you want to see instead?**

No 500 Internal Server Error.

**Environment:**

`master` f501af78810982988835e80773bca280de92c229

**What can you do yourself and what do you need help with?**

I can create this issue.

**Comment by htdvisser** [comment]
I'll still submit a PR for this today :smirk:
