### ISSUE TITLE
Confusing error message: code: 5 - device not found

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2132]
#### Summary
Confusing error message. The message was received and shown in the console. Yet, an error message is displayed that the message is dropped. 

I suppose the same message arrive via the packetbroker a fraction later that results in this error message.

...

#### Steps to Reproduce

1. Check: https://tti.eu1.cloud.thethings.industries/console/applications/tti-playground/devices/the-things-node/data
2. Wait for a new uplink
3. ...

#### What do you see now?
```
{
  "namespace": "pkg/networkserver",
  "name": "outdated_data",
  "message_format": "data is outdated",
  "cause": {
    "namespace": "pkg/networkserver",
    "name": "device_not_found",
    "message_format": "device not found",
    "code": 5
  },
  "code": 5
}
```

<img width="1043" alt="Screenshot 2020-03-11 at 17 57 40" src="https://user-images.githubusercontent.com/17290639/76443474-bcc42d80-63c2-11ea-9063-7b5adfabb155.png">

...

#### What do you want to see instead?
Don't display this error message if the same message did arrive already.

...

#### Environment
v3.6.0

...

#### How do you propose to implement this?
Remove the error message if the same message arrives via the packetbroker 

...

#### Can you do this yourself and submit a Pull Request?
@kschiffer 
...

**Comment by rvolosatovs** [comment]
Closing this.
1. Network Server events changed quite a bit in https://github.com/TheThingsNetwork/lorawan-stack/pull/2221
2. The issue seems to be due to deduplication here, which was fixed in `3.7.0`
3. Console should not hide any events - it should group them by correlation IDs though, which should improve the representation.
