### ISSUE TITLE
Inconsistent usage of AppEUI and JoinEUI

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2139]
#### Summary
While adding a device, the term `JoinEUI` is used. In the **General Settings** page, `AppEUI` is used.

Let's be consistent and use one term. Also, the description of AppEUI is incorrect.

In addition, not everyone is familiar with the term JoinEUI, so this requires clarification.

...

#### Steps to Reproduce
1. Add a device - check the field `JoinEUI`
2. Go to the **General Settings** page of the device, and look for the `AppEUI` (the JoinEUI is not there)

#### What do you see now?

<img width="715" alt="Screenshot 2020-03-12 at 10 51 59" src="https://user-images.githubusercontent.com/17290639/76509004-91d3eb00-644f-11ea-9568-c8bdf1b12e85.png">

<img width="727" alt="Screenshot 2020-03-12 at 10 51 36" src="https://user-images.githubusercontent.com/17290639/76509017-95677200-644f-11ea-8901-4d7bfa0bc16b.png">

...

#### What do you want to see instead?
Add the description: *JoinEUI is the same as the AppEUI*

<img width="698" alt="Screenshot 2020-03-12 at 10 57 36" src="https://user-images.githubusercontent.com/17290639/76509456-571e8280-6450-11ea-8c38-98e45ba586c1.png">

In the **General Settings** page, change `AppEUI` to `JoinEUI` and add the description: *JoinEUI is the same as the AppEUI*

<img width="707" alt="Screenshot 2020-03-12 at 11 01 13" src="https://user-images.githubusercontent.com/17290639/76509868-f93e6a80-6450-11ea-8c86-8fdb89829d1e.png">

...

#### Environment
v3.6.0

...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by bafonins** [comment]
We use `AppEUI` and `JoinEUI` interchangeably in the device general settings. `AppEUI` is used for device with `lorawan_version` 1.0.0-1.0.3, `JoinEUI` for 1.0.4+, that is per specification.

According to https://github.com/TheThingsNetwork/lorawan-stack/pull/1616#issuecomment-561234789 `AppEUI identifies the Join Server` is not correct description. I guess we can change it to something like `AppEUI typically identifies an application`.

**Comment by laurensslats** [comment]
Ok. Proposing the following changes:

```
The AppEUI is a global application ID that uniquely identifies the owner of the ­device. AppEUI is used for devices with LoRaWAN version 1.0x, JoinEUI for 1.1x
```

<img width="730" alt="Screenshot 2020-03-26 at 10 57 06" src="https://user-images.githubusercontent.com/17290639/77633981-8d7bf780-6f50-11ea-84dd-5da52c0bd943.png">


```
AppEUI is used for devices with LoRaWAN version 1.0x, JoinEUI for 1.1x
```

<img width="702" alt="Screenshot 2020-03-26 at 11 00 09" src="https://user-images.githubusercontent.com/17290639/77634279-fcf1e700-6f50-11ea-99e7-928a87ecb3dc.png">

**Comment by johanstokking** [comment]
Technically, in 1.0.4 it's named `JoinEUI` already

**Comment by bafonins** [comment]
Yeah, sorry. We display `App EUI` for devices with lw version >1.0.4, and `Join EUI` for 1.0.4+

**Comment by johanstokking** [comment]
Yeah the thing is though that we need the LoRaWAN version for that, which is an NS field.

In JS-only, we don't know this

**Comment by bafonins** [comment]
So, shall we default to `App EUI` then?

**Comment by johanstokking** [comment]
I think we can do both; **AppEUI / JoinEUI**
