### ISSUE TITLE
Application Link management

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#214]
**Summary:** 

Add support for linking applications to the NS.

Part of umbrella issue https://github.com/TheThingsNetwork/lorawan-stack/issues/24

**Why do we need this?**

The AS needs to link to a NS in order to exchange traffic. Additionally, the link can specify (fallback) payload formatters that apply to all devices in the application.

**What is already there? What do you see now?**

- The Applications section in the console
- The API for link configuration:
  - `GetLink` (`GET /as/applications/<id>/link`)
  - `SetLink` (`PUT /as/applications/<id>/link`)
  - `DeleteLink` (`DELETE /as/applications/<id>/link`)
  - Fields: 
    - `network_server_address` (string; empty implies same cluster)
    - `api_key` (string, required)
    - `default_formatters` (MessagePayloadFormatters, optional)
- The API for link statistics
  - `GetLinkStats` (`GET /as/applications/<id>/link/stats`)
  - Fields: `linked_at` (time), `network_server_address` (string), `last_up_received_at` (time), `up_count` (number), `last_downlink_forwarded_at` (time), `downlink_count` (number)

**What is missing? What do you want to see?**

- Support for the Link API in the SDK
- The "Link" subsection of Application in the console. Under normal circumstances this section shows the current link configuration, and the link statistics.
  - The link configuration can be created if not set.
  - The link configuration can be updated if set.
  - The link configuration can be deleted if set.

**How do you propose to implement this?**

@htdvisser came up with the following mockup:

![console](https://user-images.githubusercontent.com/181308/53642754-bc7f4700-3c32-11e9-8eca-5a4549562d26.png)

The implementation of the SDK is straightforward, just some GET/PUT/DELETE calls.

The minimum viable management view would be a form containing only the API key of the link, a "Save" button and an "Unlink" (or "Delete") button if the link is present.

**What can you do yourself and what do you need help with?**

I can start with the SDK implementation.
I'd like @kschiffer to come up with some screen designs. Perhaps work with @htdvisser to make sure we're building the right thing.

**Comment by kschiffer** [comment]
I understand there might be some expectation from the user that this linking process will be done automatically upon creating the application (as it is now in v2).
I know we talked about this process regarding avoiding to carelessly do things automatically, but wouldn't it make sense to add a checkbox in the create new application form ("Also link application to network server") which would be checked by default? This is likely what a vast majority of users would want to do right?
What do we gain from making this step explicit only, @htdvisser?

**Comment by htdvisser** [comment]
We have to implement the explicit management anyway. The implicit flow would only be a convenience so that users don't have to create an API key and copy-paste that into the link configuration.

The reason I think we should only implement the explicit steps now, and implement the implicit flow later is simple: time.

**Comment by johanstokking** [comment]
Let's consistently keep calling this `application upstream messages` (i.e. join-accept and uplink messages with FPort > 0) and `application downlink messages`. I'm fine omitting `application` if that is clear in this context.
