### ISSUE TITLE
Clear list Frequency Plan when adding GWs

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2140]
#### Summary
Unclear what frequency plan to use when connecting gateways due to options that shouldn't be displayed. 

<img width="864" alt="Screenshot 2020-03-10 at 09 17 41" src="https://user-images.githubusercontent.com/17290639/76295374-cb242380-62b4-11ea-966f-c284cec48ebd.png">

#### Why do we need this?
Clarify gateway configuration and avoid support questions.

#### What is already there? What do you see now?
See img above

#### What is missing? What do you want to see?
Remove all the fields that contain (TTN) - these options are only relevant for configuring devices. 

#### How do you propose to implement this?
> Filter when there's no `radio`. Fastest is a setting in the index. We need that anyway to avoid fetching the plan to check radio
-- see: https://thethingsindustries.slack.com/archives/C8SCJ2GG1/p1583828355008900

**Comment by laurensslats** [comment]
See: https://github.com/TheThingsIndustries/lorawan-stack/issues/2001

**Comment by htdvisser** [comment]
> Filter when there's no radio.

This will give incorrect results. For example, it would hide `AS_923_925_TTN_AU` which would impact the duty cycle settings of the gateway.

> Fastest is a setting in the index.

Then we would also need to add an extra filter to the API in addition to the `base_frequency` (which isn't used by the console either by the way). I would suggest something like an "applicability" enum where the 0-value is the current behavior (match all), and we have 1 and 2 for gateways and end devices.

**Comment by kschiffer** [comment]
> Then we would also need to add an extra filter to the API in addition to the `base_frequency` (which isn't used by the console either by the way). I would suggest something like an "applicability" enum where the 0-value is the current behavior (match all), and we have 1 and 2 for gateways and end devices.

Who should pick this up, @htdvisser ? I can then take care of using that in the Console.

**Comment by htdvisser** [comment]
I don't know if we should still do this. The only two frequency plans that are currently still equivalent for Gateways and End Devices are `EU_863_870` and `EU_863_870_TTN`. Those are now displayed as `Europe 863-870 MHz (SF12 for RX2)` and `Europe 863-870 MHz (SF9 for RX2 - recommended)`.

I'm afraid that hiding `EU_863_870_TTN` (SF12) would be confusing for users who do want to use SF12.

Do we really still need this, @laurensslats?

**Comment by johanstokking** [comment]
Ping @laurensslats

**Comment by laurensslats** [comment]
Let's snooze this for now. 

When we implement this, we also need to change the name, as it should only display `Europe EU863-870 MHz`
