### ISSUE TITLE
Document instructions for package managers in releases

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#218]
**Summary:** 

Document instructions for package managers in releases.

**Why do we need this?**

We refer to the releases pages in the documentation (Getting Started for example). The instructions to install packages should be there.

**What is already there? What do you see now?**

The downloads of source and binaries, as well as pulling Docker images.

**What is missing? What do you want to see?**

Instructions for package managers. For brew, for example, it should be something like;

```
$ brew tap TheThingsNetwork/lorawan-stack
$ brew install ttn-lw-stack
```

**How do you propose to implement this?**

Not sure; it should be generated though.

**Environment:**

Any

**What can you do yourself and what do you need help with?**

Review

**Comment by htdvisser** [comment]
Related to https://github.com/TheThingsNetwork/lorawan-stack/issues/178
