### ISSUE TITLE
Show payload for all events in the Console

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2195]
#### Summary

Currently, the Console shows payload for a certan number of events, see [here](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/components/event/types/index.js#L38-L58) and https://github.com/TheThingsIndustries/lorawan-stack/issues/1909#issuecomment-601094814

#### Why do we need this?

The users should be able to examine event payload

#### What is already there? What do you see now?

Only certain events allow examining payloads

#### What is missing? What do you want to see?

Check for `data` in the event payload for all events

#### Environment

v3.6.1	

#### How do you propose to implement this?

Check for `data` in the event payload for all events. Do not consider only the `name` entry

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Yep, this is important
