### ISSUE TITLE
Add repo-scoped linters

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#22]
**Summary:** 

Guideline conformity verification should be automated as much as possible. However, we currently only use global Go linters for our Go code - which means that those linters do not reflect repo-specific rules, such as our guidelines.

We may also want to inverstigate protocol buffer linting(e.g. https://github.com/ckaznocha/protoc-gen-lint)

**Why do we need this?**

To ensure consistency and do so efficiently

**What is already there? What do you see now?**

~`gometalinter` generic linter rules~ Generic `revive` rules

**What is missing? What do you want to see?**

Custom linting rules

**How do you propose to implement this?**

~Investigate https://github.com/mgechev/revive~
Investigate https://github.com/ckaznocha/protoc-gen-lint (last time I checked, `MHDR` and `FHDR` fields did not "pass" the lint checks)

**Ideas of guidelines to lint:**

+ Variable names: e.g. [single-word entities](https://github.com/TheThingsIndustries/ttn/blob/master/CONTRIBUTING.md#single-word-entities)
+ Conventions on struct usage
+ Event definitions: no capitalizing, event names in `snake_case.with.dots.allowed`
    + Ensure the event name follows the `component.entity.action(=verb)` format
+ Error definitions: no capitalizing, no `could_not`, no `failed`, error names in `snake_case`
    + Give a warning on `errors.New`
+ [Formatting that isn't handled by regular linters](https://github.com/TheThingsIndustries/ttn/blob/master/CONTRIBUTING.md#formatting)
+ Comments

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/900 by @egourlao

**Comment by htdvisser** [comment]
As discussed, get rid of gometalinter, we're switching to revive 🎉

**Comment by rvolosatovs** [comment]
Migration to `revive` is done, up next are the custom linting rules

**Comment by nejraselimovic** [comment]
@htdvisser can you please explain in simple words what is left to do here and why it is (not) important to schedule for a timely implementation?

**Comment by htdvisser** [comment]
I don't think we really need this. I don't remember spending a lot of time pointing out guideline "violations" in reviews recently. Definitely not enough to justify the time we'd spend on implementing linters.

So I think we can just close this. If anyone disagrees, feel free to re-open.
