### ISSUE TITLE
Admin users should be able manage collaborators in organizations

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2204]
#### Summary
Admin users cannot manage collaborators in organizations via the console.

#### Steps to Reproduce
@kschiffer 

1. I've made you an admin user in the tti tenant.
2. Go to: https://tti.eu1.cloud.thethings.industries/console/organizations
3. Try clicking on `Collaborators` button
4. Nothing happens

#### What do you see now?
Not possible to click `Collaborators` button

<img width="948" alt="Screenshot 2020-03-20 at 10 14 43" src="https://user-images.githubusercontent.com/17290639/77150948-3e881b00-6a95-11ea-8f6d-1507e4447714.png">

#### Environment
V 3.6.1

**Comment by kschiffer** [comment]
Likely related to #2170
