### ISSUE TITLE
Console overview page content flashing

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2218]
#### Summary

The overview page changes its title/choosers content when the page loaded:
![overview-flashing](https://user-images.githubusercontent.com/16374166/77315181-c11c0f00-6d0f-11ea-9261-feed89da82f3.gif)

#### Steps to Reproduce

1. Go to the overview page and refresh
2. See titles/choosers change

When throttling network requests it becomes even worse

#### What do you see now?

Content changing while the page is available

#### What do you want to see instead?

No content changes

#### Environment

v3.6.2	

#### Can you do this yourself and submit a Pull Request?

@kschiffer @pgalic96

**Comment by kschiffer** [comment]
I've looked into this already for a while. There's two separate issues:
- [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content); particularly fonts taking a while to load
- The overview page not waiting correctly until the `GET_APPLICATIONS_LIST` and `GET_GATEWAYS_LIST` has finished

As far as FUOC goes, we can look into libraries like [webfontloader](https://www.npmjs.com/package/webfontloader), to hide text until it is rendered with the correct font. There's also another issue I've identified: the icon font will only be rendered once it is used in an element (e.g. in our mobile menu), so if you open the mobile menu for the first time and there have been no other icons rendered yet, you will see a short flash until the icon font is loaded and rendered. The preload API might be a way to fix that: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content , preferably the ones invoked via script.


The other issue is likely easily solved by changing the rendering conditions of the overview component.
