### ISSUE TITLE
Add DevAddr prefix to cluster configuration

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#222]
**Summary:** 

Add DevAddr prefixes to cluster configuration. Note that we should support multiple here.

**Why do we need this?**

- To split traffic at GS level to NS and PP
- To generate DevAddr in the right range - #130

**What is already there? What do you see now?**

NetID configuration only.

**What is missing? What do you want to see?**

DevAddr prefixes.

**How do you propose to implement this?**

Add configuration on the cluster level, i.e. `ServiceBase`.

**Environment:**

Any

**What can you do yourself and what do you need help with?**

Review

**Comment by htdvisser** [comment]
@johanstokking says it's part of peering
