### ISSUE TITLE
Add Auth Method + ID and Remote IP to CRUD event data

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2227]
#### Summary

We should add the Auth Method and API Key / Access Token ID to CRUD events. It would also be good to add the remote IP.

#### Why do we need this?

For audit logging

#### What is missing? What do you want to see?

We should extract both the auth (rpcmetadata) and remote address (peer) from the context when creating an event.

#### How do you propose to implement this?

- Add fields to the Event definition (api)
- In `events.New`, set those fields.
- Can use `peer.FromContext` to extract the remote IP. Propbably also need to consider `x-forwarded-for` headers.
- Can use `rpcmetadata.FromIncomingContext` to extract the `AuthType` (usually `Bearer`) and `AuthValue`. Use `auth.SplitToken` on the latter to extract the `tokenType` and `tokenID`. The `tokenKey` should **NEVER** be added to events.

**Comment by htdvisser** [comment]
I think this is relatively easy (with the instructions above), so if anyone else wants to take over, let me know.

**Comment by neoaggelos** [comment]
Picking this one up
