### ISSUE TITLE
Downlink scheduling in console

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2233]
#### Summary
We should provide a downlink scheduling feature in the console.

#### Why do we need this?
- To allow users to send downlinks to their devices using the console
- To close v2/v3 feature gap

#### What is already there? What do you see now?
API handlers `AppAs.DownlinkQueue{Push|Replace}`

#### What is missing? What do you want to see?
A feature in the console that makes use of this API.

#### Environment
v3.7.0

#### How do you propose to implement this?
v2 implementation can be a first inspiration to come up with a new interface for this:
![image](https://user-images.githubusercontent.com/5710611/77529517-1d7b5c00-6ed3-11ea-88b7-68b221daebbf.png)

#### Can you do this yourself and submit a Pull Request?
Yes but anyone please feel free to pick up.

**Comment by bafonins** [comment]
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/1948
