### ISSUE TITLE
Improve event handling in Network Server

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2238]
#### Summary

Improve event handling in Network Server
Refs #2167 

#### Why do we need this?

For easier debugging

#### What is already there? What do you see now?

Several events, but we can do better

#### What is missing? What do you want to see?

- [ ] Uplink event improvements (#2221)
	- Trigger an event when uplink is received
	- Trigger an event when uplink is successfully processed
	- Trigger an event when NS sends the join-request to *a* JS
	- Trigger an event when NS receives a response from JS
	- Trigger an event when NS sends an application uplink to AS

- [ ] Downlink event improvements
	- Trigger an event when errors from GS are received including errors per-gateway

#### How do you propose to implement this?

Add events and handling

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
cc @kschiffer @bafonins

**Comment by bafonins** [comment]
Sounds good.

> Trigger an event when uplink is received

Would be nice if this event has a different description from `as.up.data.receive`, namely `receive uplink data message` as it might be confusing for the users to get several of those. We currently do not distinguish events dispatched by as/ns anyhow in the Console.
I think the only option to do this is by checking the `name` field of the event. @kschiffer @johanstokking do you think it is worth adding the source of the event (stack component)? It could be an icon/abbreviation. We can elaborate that in https://github.com/TheThingsNetwork/lorawan-stack/issues/1962

**Comment by rvolosatovs** [comment]
> Sounds good.
> 
> > Trigger an event when uplink is received
> 
> Would be nice if this event has a different description from `as.up.data.receive`, namely `receive uplink data message` as it might be confusing for the users to get several of those. We currently do not distinguish events dispatched by as/ns anyhow in the Console.
> I think the only option to do this is by checking the `name` field of the event. @kschiffer @johanstokking do you think it is worth adding the source of the event (stack component)? It could be an icon/abbreviation. We can elaborate that in #1962

Good one, I already changed this for forwarding in https://github.com/TheThingsNetwork/lorawan-stack/pull/2221, so the event will now state that the respective message is forwarded to AS, don't think we should change the description of NS events though.
I think having a small box with abbreviated component name (e.g. `NS`, `AS, etc.) on each event would be extremely helpful. You could, in fact, just take the string before first `.`, make it uppercase and print in this "box". The first part of event name always indicates the component, where it comes from.
