### ISSUE TITLE
Support unsetting values in CLI

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2250]
#### Summary

CLI should support unsetting `nil`-able values

#### Why do we need this?

To be able to unset values

#### What is already there? What do you see now?

Only set of `nil`-able values
```
 --mac-settings.desired-rx1-delay string                           RX_DELAY_5|RX_DELAY_9|RX_DELAY_15|RX_DELAY_3|RX_DELAY_11|RX_DELAY_14|RX_DELAY_10|RX_DELAY_6|RX_DELAY_7|RX_DELAY_8|RX_DELAY_12|RX_DELAY_0|RX_DELAY_1|RX_DELAY_2|RX_DELAY_4|RX_DELAY_13
```

#### What is missing? What do you want to see?

Support for unsetting `nil`-able values
```
 --mac-settings.desired-rx1-delay string                           RX_DELAY_5|RX_DELAY_9|RX_DELAY_15|RX_DELAY_3|RX_DELAY_11|RX_DELAY_14|RX_DELAY_10|RX_DELAY_6|RX_DELAY_7|RX_DELAY_8|RX_DELAY_12|RX_DELAY_0|RX_DELAY_1|RX_DELAY_2|RX_DELAY_4|RX_DELAY_13|null
```

#### How do you propose to implement this?

Allow `null` as a value for nillable fields

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by neoaggelos** [comment]
Closed with #2301
