### ISSUE TITLE
Replace usage of api tree in console with SDK instance

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2263]
#### Summary
We currently use an unnecessarily complicated and verbose logic to refer to functions of our SDK in the console. Every method of the SDK is mapped to a big API object, and the SDK service classes need to be bound to the object methods to retain the `this` value.
Instead of all this, we should instanciate the SDK client and access this instance as singleton module.

#### Why do we need this?
- Less verbose
- Less complicated

#### What is already there? What do you see now?
- JS SDK instance
- API object `console/api/index.js`

#### What is missing? What do you want to see?
An SDK instance exported as singleton module.

#### Environment
v3.7.0

#### How do you propose to implement this?
Simply refactor all uses of the API object, to use SDK instance directly.

#### Can you do this yourself and submit a Pull Request?
Yes, but help welcome.

cc @bafonins

**Comment by bafonins** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/4939
