### ISSUE TITLE
Device deletion does not return error on failure in JS SDK

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2273]
#### Summary

The JS SDK ignores errors when deletion in one of the components fails

#### Steps to Reproduce

1. Simulare an error in `requestWrapper`
2. See no errors returned

#### What do you see now?

No errors on failed delete operations

#### What do you want to see instead?

An error

#### Environment

3.7.0-rc2	

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by kschiffer** [comment]
Isn't this resolved now?
