### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2280]
#### Summary

Switch to GitHub Actions by getting rid of Travis CI.

#### Why do we need this?

GitHub Actions has proven reliable and fast enough to move away from Travis. Travis is slow and costly.

#### What is already there? What do you see now?

We currently have a GitHub action that replaces the Travis run type `go.test` only.

#### What is missing? What do you want to see?

We still need GitHub actions that replace the run types `js`, `go.lint` and `release`, as well as deployment of documentation to GitHub pages.

While we're at it, we might want to have a specific release action just for a Docker image.

The end goal is to remove Travis and discontinue the Travis subscription.

#### Environment

CI

#### How do you propose to implement this?

Add GitHub actions

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by rvolosatovs** [comment]
https://github.com/TheThingsNetwork/lorawan-stack/issues/2903
https://github.com/TheThingsNetwork/lorawan-stack/issues/2797

Are still TODO, otherwise, this is done.
