### ISSUE TITLE
Uplink message documentation comments unclear about gateway time and timestamp

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#2293]
#### Summary

The time and timestamp field inside the `uplink_message`=>`settings` object is non clearly explained. Especially the difference between these and the time and timestamp fields that are provided per gateway.

#### Why do we need this ?

Remove any doubt.

#### What is already there? What do you see now?

Comments that are unclear.

#### What is missing? What do you want to see?

I want to know what is the difference between the time and timestamps that are provided per gateway, versus the time and timestamp that is provided in the settings object.

#### How do you propose to document this?

Fix the comment.

#### Can you do this yourself and submit a Pull Request?

Unfortunately not because the situation is unclear to me.

See:
https://github.com/TheThingsNetwork/lorawan-stack/blame/master/doc/content/reference/application-server-data/data-formats/_index.md#L103

And compare that to:
https://github.com/TheThingsNetwork/lorawan-stack/blame/master/doc/content/reference/application-server-data/data-formats/_index.md#L120

**Comment by benolayinka** [comment]
Finally figured this one out, sorry for the holdup @jpmeijers .

The timestamp in the `uplink_message`=>`settings` object is from the accepted uplink, so if more than one gateway receives the uplink, it should be the timestamp of the first.

There will be an `uplink_message`=>`rx_medata` object for each gateway that receives the message, each with its own timestamp.
