### ISSUE TITLE
Basic Station: router_config should not return antenna_gain

### ISSUE THREAD

**Issue by robertlie** [TheThingsNetwork/lorawan-stack#2320]
#### Summary
LNS returns sx1301_conf.antenna_gain
However the basic station code returns a warning because it does not expect the antenna_gain parameter here.
See:
https://github.com/lorabasics/basicstation/blob/v2.0.3/src/sx1301conf.c#L176
The basic station code expects the antenna_gain to be at SX1301_conf.radio_N.antenna_gain
But antenna_gain should not returned at all by LNS.
It is hardware specific and if it is returned at SX1301_conf.radio_N.antenna_gain it will overwrite the station.conf settings.
It is the same problem as mentioned in https://github.com/TheThingsNetwork/lorawan-stack/issues/2130

**Comment by KrishnaIyer** [comment]
appended this to the original issue. @robertlie , please fill out our issue template next time.
