### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2358]
#### Summary

Change doc structure from
- Guides
- Concepts
- Components
- Reference

to
- Getting started
- Devices
- Gateways
- The Things Stack
- Integrations
- Reference

#### Why do we need this ?

Restructure docs to
- Reflect how users search for help
- Flatten hierarchy
- Match conceptual flow of data
- Add some useful sections

#### Current structure

- Guides
	- getting started
		- installation
		- certs
		- configuration
		- running the tts stack
		- console
			- create gateway
			- create app
			- create end device
		- command-line interface
		- working with data
	- connecting gateways
	- basic user management
	- working with events
	- downlink queue operations
	- class c and multicast
	- generate qr code
	- web ui branding
- Concepts
	- end device templates
	- email templates
	- webhook templates
- Components
	- identity server
	- gateway server
	- network server
	- application server
	- join server
	- console
	- qr code generator
	- command-line interface
	- device template converter
	- gateway configuration server
- Reference
	- api
	- configuration
	- application server data
	- application packages
	- email templates
	- end device templates
	- webhook templates
	- interoperability repo
	- networking

#### Proposed structure

- Getting started
	- installation
		- certs
		- configuration
		- running the tts stack
	- console
		- create gateway
		- create app
		- create end device
	- command-line interface
	- working with data
	- connecting gateways
	- basic user management
	- working with events
	- downlink queue operations
	- class c and multicast
	- generate qr code
	- web ui branding
- Devices
	- device registration
	- working with data
	- device templates
- Gateways
	- connect a gateway
	- common gateways
- The Things Stack
	- components
	- cli
	- console
	- ...
- Integrations
	- webhook templates
	- email templates
	- mqtt
	- data formats
	- application packages
- Reference
	- api
	- configuration
	- interoperability
	- glossary
	- port allocations

#### How do you propose to document this?

This is a change to documentation.

#### Can you do this yourself and submit a Pull Request?

Yes. Feedback appreciated, especially @htdvisser @johanstokking @wienke @laurensslats

**Comment by johanstokking** [comment]
I think this is a good suggestion. We can still do this since we haven't been publishing the docs to stable URLs yet.

**Comment by benolayinka** [comment]
> I think this is a good suggestion. We can still do this since we haven't been publishing the docs to stable URLs yet.

i'll create a branch with the changes then. besides fixing internal links, is there anything i should look out for?

@kschiffer @pgalic96 is this going to affect anything on your end?

**Comment by benolayinka** [comment]
Proposition to drop (or rename) 'The Things Stack,' nav menu
- Basic usage is all covered in 'Getting started'
- It's confusing as a nav option PLUS the title of the page (clicking the logo takes you home, clicking the nav item takes you to a sub menu)
- Components subsection can move to reference
- Gives visual space between Reference and Forum nav items

With:
<img width="1297" alt="Screenshot 2020-04-16 at 14 18 28" src="https://user-images.githubusercontent.com/6963436/79456178-55ffe880-7fee-11ea-9354-67f8ce9683d3.png">

Without:
<img width="1479" alt="Screenshot 2020-04-16 at 14 29 24" src="https://user-images.githubusercontent.com/6963436/79456368-aecf8100-7fee-11ea-8899-736e70399c91.png">

@kschiffer @johanstokking

**Comment by johanstokking** [comment]
I agree

**Comment by kschiffer** [comment]
> @kschiffer @pgalic96 is this going to affect anything on your end?

No. We didn't use any links yet, so that's fine.
