### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2359]
#### Summary

Add glossary to docs with terms/abbreviations and definitions.

#### Why do we need this ?

We can make these terms available as context tooltips in the console, so users can see the definitions of fields when they are adding devices, gateways, applications, etc.

#### What is already there? What do you see now?

No glossary.

#### What is missing? What do you want to see?

A glossary section under the reference section of docs. Hover-over tooltips in the console providing definitions for terms.

<img width="633" alt="Screenshot 2020-04-14 at 15 22 11" src="https://user-images.githubusercontent.com/6963436/79229678-b878ad80-7e63-11ea-91ca-905ac5e902df.png">

<img width="1129" alt="Screenshot 2020-04-09 at 14 46 55" src="https://user-images.githubusercontent.com/6963436/79229471-5c158e00-7e63-11ea-8161-10e87038d36f.png">

![Image d’iOS](https://user-images.githubusercontent.com/6963436/79229455-55871680-7e63-11ea-93c2-fcd1a3c6a846.jpg)

#### How do you propose to document this?

This is an addition to the documentation.

#### Can you do this yourself and submit a Pull Request?

Yes, need help from @kschiffer @pgalic96 for markdown templates and link to docs from console.

**Comment by pgalic96** [comment]
Linking docs from console is already an issue (see #2254 )

**Comment by kschiffer** [comment]
> Linking docs from console is already an issue (see #2254 )

Yeah, this is a separate issue, where we want to (maybe automatically) connect text in the console with entries from the glossary of the docs.

**Comment by benolayinka** [comment]
pushed branch `issue/#2359-add-glossary` with an unstyled `/reference/glossary`

data in `doc/data/glossary/glossary.yml`

added `term`, `term-alt`, and `term-abbr` classes to the partial at `doc/themes/tts/layouts/partials/proto/glossary-term.html` so we can style them.. anyone with an opinion about how to css those up please chime in @htdvisser @kschiffer  @pgalic96 @laurensslats @pierrephz
