### ISSUE TITLE
Invalid band channel data rate limits

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2371]
#### Summary

Some of band channel data rate limits are invalid

#### Steps to Reproduce

1. Look at https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/band/au_915_928.go#L42-L43

#### What do you see now?

Invalid DR limits in AU915

#### What do you want to see instead?

Valid limits in all bands

#### How do you propose to implement this?

Validate the limits and fix inconsistencies across all spec versions and bands

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by rvolosatovs** [comment]
Setting `prio/medium`, because without this in some bands NS does not accept uplinks

**Comment by htdvisser** [comment]
This needs to be fixed in https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.7.0/pkg/band/downgrades.go#L54-L61 as the current DRs are valid for PHY 1.0.2rA, but not for 1.0.2rB.
