### ISSUE TITLE
Avoid showing form submit buttons as disabled initially

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2389]
#### Summary
We currently show the submit buttons of our forms as disabled by default. This is [bad UX](https://ux.stackexchange.com/a/76306/80506) and it also introduces some side effects, such as [not being able to submit a form as it is](https://github.com/TheThingsNetwork/lorawan-stack/pull/2338#pullrequestreview-397233753) (if the validation rules allow it).

#### What do you see now?
Submit button being disabled until any input has been made

#### What do you want to see instead?
Submit button being enabled by default and showing relevant validation messages after submitting, if necessary.

#### Environment
console v.3.7.1

#### How do you propose to implement this?
Trivial

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/2432
