### ISSUE TITLE
Console ignores errors in entity title section

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2392]
#### Summary

The Console ignores failed requests when fetching data for the entity title section. This results in an infinite loading indicator.

<img width="396" alt="Screenshot 2020-04-22 at 11 33 23" src="https://user-images.githubusercontent.com/16374166/79959817-3c96ea80-848d-11ea-99b2-020117533f7d.png">
<img width="396" alt="Screenshot 2020-04-22 at 11 33 33" src="https://user-images.githubusercontent.com/16374166/79959819-3dc81780-848d-11ea-80d5-9e15e0eeaac1.png">
<img width="306" alt="Screenshot 2020-04-22 at 11 32 26" src="https://user-images.githubusercontent.com/16374166/79959806-3acd2700-848d-11ea-956b-8d429bb12d32.png">

#### Steps to Reproduce

1. Simulate api-keys requests for the entity title section
2. No error UI

#### What do you see now?

Infinite loading indicator

#### What do you want to see instead?

Error UI, or skipped entity count for failed requests

#### Environment

v3.7.1

#### How do you propose to implement this?

Selects errors and change the way the loading state is determined for the entity title section

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by bafonins** [comment]
@kschiffer any suggestions on how it should look?

**Comment by kschiffer** [comment]
I think the section should try to show all values that have been fetched successfully, for unretrievable values, it should show e.g. `API Keys n/a` using the `warning` icon instead of the entity icon, everything rendered in `$tc-error`.

Hope that's clear enough, otherwise I can do a mock-up.

**Comment by bafonins** [comment]
Blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/2740. I want to refactor the whole thing altogether
