### ISSUE TITLE
End device subview crashes when the AppSKey is deleted

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2402]
#### Summary
The end device can not be examined anymore in the console after the AppSKey has been deleted for ABP end devices.

#### Steps to Reproduce
1. Create an ABP end device
2. Go to the general settings Application Layer Settings tab
3. Remove the AppSKey
4. Refresh the page
5. See an error `Bad request - Invalid slice length`

#### What do you see now?
Error for ABP end devices without AppSKey

#### What do you want to see instead?
No error.

#### Environment
v3.7.1

#### How do you propose to implement this?
The error is coming from the AS. I can't tell whether this is a legitimate error or this should be handled differently. Based on that we either need to catch the error in the frontend/sdk or fix the logic in the AS for devices without AppSKey.

#### Can you do this yourself and submit a Pull Request?
I suggest @bafonins but feel free to reassign.

**Comment by bafonins** [comment]
Fixed in https://github.com/TheThingsNetwork/lorawan-stack/pull/2494
