### ISSUE TITLE
Improve UX for ByteInputs without fixed value length

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2404]
#### Summary
Our `ByteInput` component is not really working well for getting byte values without length restriction.

#### Why do we need this?
We need to get byte values without length restriction in the schedule downlink secrtion.

#### What is already there? What do you see now?
ByteInput component enabling inputs without length restriction.

#### What is missing? What do you want to see?
A better behavior of such input: don't show the masked input dots.

#### Environment
v3.7.1

#### How do you propose to implement this?
I think it's best to refactor the byte input into its own component. We currently have it as variation of the normal `<Input />` component, which makes it hard to maintain and extend and it also arbitrarily mixes prop types between the two.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by bafonins** [comment]
@pgalic96 is this closed?

**Comment by pgalic96** [comment]
yes.
