### ISSUE TITLE
Don't show gateway as disconnected if they are connected in a different region

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2406]
#### Summary
Gateways that are connected to a different region than the user is currently looking at seem offline, though they are online.

...

#### Why do we need this?
It seems like false information. 
...

#### What is already there? What do you see now?
The gateway is connected to `nam1` and I'm looking at the `eu1` console.

You do see: `Other Cluster` in the specific gateway view, but not in the list with all gateway. See printscreens below.

<img width="505" alt="Screenshot 2020-04-23 at 10 53 03" src="https://user-images.githubusercontent.com/17290639/80079550-ba6ffa00-8550-11ea-9056-8310de5ea1eb.png">

<img width="1115" alt="Screenshot 2020-04-23 at 10 46 17" src="https://user-images.githubusercontent.com/17290639/80079388-84327a80-8550-11ea-9880-31010ffd1b62.png">

...

#### What is missing? What do you want to see?
Change `Other Cluster` to `Other Region`. Show this in the gateway list and in the gateway page. See printscreens below:

<img width="1114" alt="Screenshot 2020-04-23 at 10 50 40" src="https://user-images.githubusercontent.com/17290639/80079411-8ac0f200-8550-11ea-8dcd-a24a83d72e62.png">

<img width="491" alt="Screenshot 2020-04-23 at 10 52 54" src="https://user-images.githubusercontent.com/17290639/80079687-e68b7b00-8550-11ea-8e39-06cae786829c.png">

...

#### How do you propose to implement this?
Easy fix.

...

**Comment by laurensslats** [comment]
I'd say **Other Region** is clearer than **Other Cluster**. Let me know if you think otherwise.

**Comment by bafonins** [comment]
> The gateway is connected to `nam1` and I'm looking at the `eu1` console.

We show the `Other Cluster` indicator only if `gateway_server_address` configured for the gateway is not the same as the one in the current deployment. To be more specific hostname of `eu1` is `tti.eu1.cloud.thethings.industries` while `gateway_server_address` is configured to `tti.nam1.cloud.thethings.industries`

> Show this in the gateway list and in the gateway page. 

Indeed, we should do that.

@htdvisser what about changing `Other Cluster` to `Other Region`? Im fine with this. Here is the initial discussion regarding this: https://github.com/TheThingsNetwork/lorawan-stack/issues/243#issuecomment-489601891

**Comment by htdvisser** [comment]
The correct term is "Cluster". We can have `eu1` and `eu2` clusters that are the same region, but not the same cluster.
