### ISSUE TITLE
doc: Hidden nav item css breakpoints

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2415]
#### Summary

After doc restructuring #2368 , nav items don't fit on small screens 
![image](https://user-images.githubusercontent.com/6963436/80193409-08e8cb80-8619-11ea-84f3-2dacf566df50.png)

#### Steps to Reproduce

1. Pull the master branch and run the docs server.
2. Resize your window to approx 1050px wide

#### What do you see now?

![image](https://user-images.githubusercontent.com/6963436/80193409-08e8cb80-8619-11ea-84f3-2dacf566df50.png)

#### What do you want to see instead?

Maybe burger menu? 

<img width="1532" alt="Screenshot 2020-04-24 at 10 52 35" src="https://user-images.githubusercontent.com/6963436/80193890-dd1a1580-8619-11ea-83e4-c5c6d59de255.png">

#### Environment

Chrome 80

#### How do you propose to implement this?

Css breakpoints?

#### Can you do this yourself and submit a Pull Request?

Not cleanly. @kschiffer @htdvisser @pgalic96 ideas?

**Comment by htdvisser** [comment]
Changing the breakpoint is easy (see below), but I don't think it improves the user experience. Maybe we should reconsider whether we really want the "Github", "Forum" and "Get The Things Stack" links in the top bar, or if those can actually be removed. The "Github" and "Forum" links are also in the footer, and we also have a huge "hero" on the homepage with a "Get The Things Stack" link.

This is how you change the breakpoint (default is `960px + (2 * $gap)`):

```diff
diff --git a/doc/themes/the-things-stack/assets/css/theme.scss b/doc/themes/the-things-stack/assets/css/theme.scss
index 5b146d66f..c5a984c5f 100644
--- a/doc/themes/the-things-stack/assets/css/theme.scss
+++ b/doc/themes/the-things-stack/assets/css/theme.scss
@@ -56,6 +56,8 @@ $table-cell-border: 1px solid $white-ter;
 $table-cell-border-width: 1px 1px 1px;
 $table-cell-padding: 1.2em 0.75em;
 
+$desktop: 1024px + (2 * $gap);
+
 @import "bulma/sass/utilities/functions.sass";
 @import "bulma/sass/utilities/derived-variables.sass";
 @import "bulma/sass/utilities/animations.sass";

```

**Comment by benolayinka** [comment]
> Changing the breakpoint is easy (see below), but I don't think it improves the user experience. Maybe we should reconsider whether we really want the "Github", "Forum" and "Get The Things Stack" links in the top bar, or if those can actually be removed. The "Github" and "Forum" links are also in the footer, and we also have a huge "hero" on the homepage with a "Get The Things Stack" link.
> 
> This is how you change the breakpoint (default is `960px + (2 * $gap)`):
> 
> ```diff
> diff --git a/doc/themes/the-things-stack/assets/css/theme.scss b/doc/themes/the-things-stack/assets/css/theme.scss
> index 5b146d66f..c5a984c5f 100644
> --- a/doc/themes/the-things-stack/assets/css/theme.scss
> +++ b/doc/themes/the-things-stack/assets/css/theme.scss
> @@ -56,6 +56,8 @@ $table-cell-border: 1px solid $white-ter;
>  $table-cell-border-width: 1px 1px 1px;
>  $table-cell-padding: 1.2em 0.75em;
>  
> +$desktop: 1024px + (2 * $gap);
> +
>  @import "bulma/sass/utilities/functions.sass";
>  @import "bulma/sass/utilities/derived-variables.sass";
>  @import "bulma/sass/utilities/animations.sass";
> ```

It's tough. I think Github and Forum are important links for top bar nav - I always click these when I visit docs.

Get The Things Stack could become Download (i guess it was before since that's the slug it redirects to). I prefer Download, but maybe there were reasons for changing this CTA.

**Comment by kschiffer** [comment]
> It's tough. I think Github and Forum are important links for top bar nav - I always click these when I visit docs.

I agree. These should stay there IMO. We might rather get rid of the version tag next to the logo, since we'll be getting rid of versioned docs soon (if I understood correctly) and we can also display that in the footer.

> Get The Things Stack could become Download

Agreed.

**Comment by benolayinka** [comment]
Enterprise docs don't have the Download button and everything fits nicely - maybe we (re)move that button?

<img width="1185" alt="Screenshot 2020-05-13 at 11 09 27" src="https://user-images.githubusercontent.com/6963436/81794798-9ed29080-950b-11ea-875d-710b427d6441.png">

**Comment by benolayinka** [comment]
Closed by https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/2
