### ISSUE TITLE
Rename PHY and MAC in console

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2424]
#### Summary

It's unclear for newbies what MAC and PHY are in the console. The LoRaWAN terms for these are (i think)
MAC: LoRaWAN specification or version
PHY: Regional parameters

#### Why do we need this ?

To make it easy to add devices in the v3 console (these terms are also unfamiliar for those upgrading from v2, where they were not required)

#### What is already there? What do you see now?

<img width="799" alt="Screenshot 2020-04-28 at 12 47 28" src="https://user-images.githubusercontent.com/6963436/80478864-744ed800-894e-11ea-9f9b-68d1cc08f11a.png">

#### What is missing? What do you want to see?

MAC and PHY replaced with terms used by LoRa Alliance / other device documentation

<img width="741" alt="Screenshot 2020-04-28 at 12 49 49" src="https://user-images.githubusercontent.com/6963436/80479078-c7288f80-894e-11ea-8ae4-15d61a738e0f.png">

#### How do you propose to document this?

This is a change to documentation

#### Can you do this yourself and submit a Pull Request?

No, @kschiffer @pgalic96 ?

@htdvisser @johanstokking can you double check my LoRa terminology

**Comment by johanstokking** [comment]
I would go with:

- **LoRaWAN version**
- **Regional Parameters version**

**Comment by pgalic96** [comment]
Closed by #2451
