### ISSUE TITLE
Determine end device statuses

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2436]
#### Summary
The console should provide a status indication of an end device.

#### Why do we need this?
- To facilitate and speed up situational awareness for end devices of an application
- To close feature gap with the v2 console

#### What is already there? What do you see now?
- End device list
- End device event stream

#### What is missing? What do you want to see?
Some logic to inform a discrete end device status and displaying that in the end device overview and end device list

#### How do you propose to implement this?
The question is what we want to display as a status and how we want to determine that status. It is not trivial to generate an end device status from the data that it holds. In v2, we determined a certain time span of not sending a message as an indication of the device being down. However, this must not be the case. Devices can very well go without sending or receiving data for a long time depending on the usage scenario.

Let's discuss what would be a good way to provide end device statuses.

#### Can you do this yourself and submit a Pull Request?
After we have found a strategy, yes.

**Comment by htdvisser** [comment]
Issues can only be in Next Up if they are ready to be picked up. This issue still needs discussion.

**Comment by htdvisser** [comment]
I don't think there is such a thing as "device status". Best thing we can do is display a "time ago" and perhaps a signal quality for the last uplink

**Comment by laurensslats** [comment]
When we know the last uplink in the application, let's replace `Linked` with `Last seen` in the application view (similar to the gateway overview page).

<img width="537" alt="Screenshot 2020-05-13 at 11 51 55" src="https://user-images.githubusercontent.com/17290639/81798606-86b14000-9510-11ea-9c54-4ff7507c81c3.png">

**Comment by johanstokking** [comment]
@kschiffer to which extent does #4132 (partly) close this issue?

**Comment by kschiffer** [comment]
Yes I think this is practically solved by #4132, since we cannot really properly determine any "device status" and the best we can do is forwarding this consideration to the user by providing them with the "Last seen".

I'll set #4132 to close this issue.
