### ISSUE TITLE
Show the end device's EUIs in the end device list

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2437]
#### Summary
The console should show the end device DevEUI and JoinEUI (for OTAA end devices) in the end device list.

#### Why do we need this?
This is a vital information that should be accessible on the end device list view already. It also closes a feature gap between v2 and v3 console.

#### What is already there? What do you see now?
- End device list
- EUI displayed in the end device overview

#### What is missing? What do you want to see?
EUIs being a column in the end device list

#### How do you propose to implement this?
Trivial. Extend the end device list container.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/2460
