### ISSUE TITLE
Allow setting frame counter widths of end devices in the Console

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2438]
#### Summary
The console should allow setting the frame counter widths that an end device uses.

#### Why do we need this?
- It's a basic setting
- To close v2/v3 console feature gap

#### What is already there? What do you see now?
No such setting.

#### What is missing? What do you want to see?
A simple setting to switch between 16 and 32 bit frame counter widths.

#### How do you propose to implement this?
Given the respective API, this should be trivial. The setting could be part of the Network Layer tab in the end device settings.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
@rvolosatovs is the `supports_32_bit_f_cnt` field the one needed for this feature?

**Comment by rvolosatovs** [comment]
Yes

**Comment by pgalic96** [comment]
@kschiffer @bafonins Should this setting be part of the add end device wizard, or should we keep it in the general settings to keep the wizard simple (I assume the default value is `false` then).

**Comment by pgalic96** [comment]
@rvolosatovs looping you in on the question regarding `supports_32_bit_f_cnt` in the add device wizard. I see that in the v2 console it is not part of the add device form, only settings. Should we keep it in general settings only in v3 console as well?

**Comment by kschiffer** [comment]
This should be part of the network layer settings in the wizard and the general settings form.
