### ISSUE TITLE
Setting gateway automatic update behavior in the Console

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2439]
#### Summary
The console should allow setting the automatic update behavior of a gateway. Complementary to the v2 setting:
![image](https://user-images.githubusercontent.com/5710611/80563042-acc0e580-8a24-11ea-9259-c0632494bf56.png)

#### Why do we need this?
- Basic setting
- Closing v2/v3 feature gap

#### What is already there? What do you see now?
No such setting.

#### What is missing? What do you want to see?
A setting to enable/disable automatic updates of a gateway.

#### How do you propose to implement this?
Given the respective API this should be trivial. The setting should be part of the general settings of the gateway.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by bafonins** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/1876

<img width="1173" alt="Screenshot 2020-05-11 at 08 13 11" src="https://user-images.githubusercontent.com/16374166/81526237-c08f1480-935f-11ea-9d89-092a7915a281.png">
