### ISSUE TITLE
Hide advanced settings in console when adding devices

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2445]
#### Summary

Simplify the device-creation by hiding advanced settings that most users don't understand, nor need to set.

#### Why do we need this?

Most of the users don't understand these fields, in most cases these fields don't have to be set.

#### What is already there? What do you see now?

![Screenshot 2020-04-29 at 12 14 37](https://user-images.githubusercontent.com/17290639/80585233-42537980-8a13-11ea-8fd4-3dd66ab5c012.png)

#### What is missing? What do you want to see?

Hide these settings and allow the user to expand these fields. Something like this:  
 

![Artboard 2](https://user-images.githubusercontent.com/17290639/80585862-50ee6080-8a14-11ea-9a17-2b7655061f09.png)

**Comment by kschiffer** [comment]
This issue is overlapping with #579.
