### ISSUE TITLE
Support resetting device state in Network Server

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2446]
#### Summary

Support resetting device state in Network Server

#### Why do we need this?

To support resetting the state after e.g. ABP device reset

#### What is already there? What do you see now?

Only possibility is to set stuff explicitly via device registry SET

#### What is missing? What do you want to see?

Functionality to reset the state in NS, just like it does on device creation.

#### How do you propose to implement this?

Just like NS already does when creating an ABP device

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
This prevents some users from migrating from v2 to v3, so setting medium priority.

**Comment by rvolosatovs** [comment]
@johanstokking coming back to the discussion we had during sync, this issue addresses specifically decreasing FCnt via device registry and resetting MAC state in response to that, such that a button in the console would then set the FCnt of the device to 0 or other value for reset

**Comment by rvolosatovs** [comment]
After taking another look at this, it makes much more sense to introduce a separate RPC for this. PR's coming soon!
