### ISSUE TITLE
Convert common/well-known errors to defined errors

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2448]
#### Summary

We should convert some common and well-known errors to defined errors.

#### Why do we need this?

To give more insight into what is going on when an error is returned.

#### What is already there? What do you see now?

If during OAuth token exchange a DNS error, timeout or other network error occurs, an internal server error is returned without details.

#### What is missing? What do you want to see?

Some details about the network error. Maybe DNS couldn't be resolved? Maybe the TCP connection timed out? Maybe the TLS expired? ...

#### How do you propose to implement this?

We could make `errors.From` recognize some common errors and return rich errors with attributes (built from definitions).

#### Can you do this yourself and submit a Pull Request?

Yes, but if anyone else would like to do this, just comment and re-assign.

**Comment by neoaggelos** [comment]
Picking this one up

**Comment by neoaggelos** [comment]
Closed with #2582
