### ISSUE TITLE
Add missing field validations

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#245]
**Summary:** 

Currently there is a bunch of fields in our API, which lack validation options.
E.g. https://github.com/TheThingsNetwork/lorawan-stack/blob/4f5dc70c4a3068aa2169d8a8e69d7c99507294db/api/end_device.proto#L144-L147
Refs #51 #69 

**Why do we need this?**

To make sure we don't store garbage

**What is already there? What do you see now?**

Possible garbage in fields

**What is missing? What do you want to see?**

Validation

**How do you propose to implement this?**

Add the validators.
For the exact case linked I propose `(validate.rules).enum.defined_only = true`
and `(validate.rules).enum.not_in = [0]`
See https://github.com/lyft/protoc-gen-validate#enums

**Comment by rvolosatovs** [comment]
Blocked by #194

**Comment by rvolosatovs** [comment]
I added a bunch of missing validations in #194, however those were mostly NS or JS-related and obvious ones, like email.
Let's go component-by-component and ensure that all the fields that need validation are validated.
NS and JS should be fine, however we should still look through GS, AS and IS. I'll assign package maintainers.
@johanstokking 	please check AS and GS-related messages
@htdvisser 	please check IS-related messages

**Comment by htdvisser** [comment]
Unblocked since #194 was merged

**Comment by johanstokking** [comment]
@rvolosatovs checked both, only addition necessary seems to be in #297
