### ISSUE TITLE
Document pub/sub integrations

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2454]
#### Summary

Document application pub/sub integrations

#### Why do we need this ?

To complete the application data integrations

#### What is already there? What do you see now?

MQTT Server and HTTP Webhooks

#### What is missing? What do you want to see?

PubSub integrations

#### How do you propose to document this?

Add section like MQTT Server and Webhooks

It's good to mention also that we have two sorts of MQTT integrations; we have a builtin server (MQTT Server), and we have a client (via PubSub)

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by benolayinka** [comment]
Working on this now. Is there any way to test the PubSub integration without your own NATS server?
In the Webhook guide we suggest using Postbin, is there something like that for NATS?

**Comment by benolayinka** [comment]
> Working on this now. Is there any way to test the PubSub integration without your own NATS server?
> In the Webhook guide we suggest using Postbin, is there something like that for NATS?

@adriansmares

**Comment by johanstokking** [comment]
I'd go with a local MQTT server (Mosquitto) or NATS. It's pretty easy to setup.
