### ISSUE TITLE
DeviceTimeAns must use network time

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2471]
#### Summary

DeviceTimeAns must use network time

#### Steps to Reproduce

1. Look at implementation

#### What do you see now?

NS using gateway time in `DeviceTimeAns`

#### What do you want to see instead?

NS using it's own clock in `DeviceTimeAns`

#### How do you propose to implement this?

Use NS clock

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Closed by #2478
