### ISSUE TITLE
Document v3 MAC settings

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#2501]
#### Summary

Document v3 MAC settings for end devices.  Came up during #2467

#### Why do we need this ?

Document v3 MAC settings and possible use cases for them. 

#### What is already there? What do you see now?

`ttn-lw-cli end-devices update --help` lists the available MAC settings. There is a short description in the API reference page.

#### What is missing? What do you want to see?

Use cases for important MAC settings. Better documentation for when and how they should be set (e.g. https://github.com/TheThingsNetwork/lorawan-stack/pull/2467#discussion_r422088779)

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

no. assigning @rvolosatovs  and @benolayinka, re-assign as needed.

**Comment by benolayinka** [comment]
@laurensslats is this the issue you mentioned in the last doc sync?
