### ISSUE TITLE
Document connecting Node-RED

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2510]
#### Summary

Document connecting Node-RED

#### Why do we need this ?

For users to quickly prototype use cases and dashboards using [Node-RED](https://nodered.org/).

#### What is already there? What do you see now?

- Explanation of how to connect to the AS builtin MQTT server
- In V2 we have specific Node-RED nodes

#### What is missing? What do you want to see?

I don’t think we should be maintaining our own nodes again, at least not on the short term

Instead, we can write a guide to connect with builtin nodes to subscribe to uplink and publish downlink messages.

#### How do you propose to document this?

1. Refer to Node-RED docs to install it
2. Connect using MQTT input node, use TLS (with SNI), refer to instructions for AS MQTT username and API key
3. Convert to JSON function
4. Maybe some dashboard thing or at least a debug node. Accompanied by screenshots
5. Trigger node for sending a downlink message via MQTT publish

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by willhelmx** [comment]
Excellent idea Johan

The documentation for Node-Red is poor at the moment, so a release in any form regarding up and downlink instructions via MQTT for v3 would be helpful.
However i beleive that for the cummunity it would be nice to issue a v2 modified simple up and downlink MQTT node for v3 to access in the Palette import
These nodes can be implemented with instructions and/or link to to the upcoming instructions

BR
/Anders
