### ISSUE TITLE
Change CSRF middleware to gorilla/csrf

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2528]
#### Summary

In #2382 we started migrating away from Echo, but there are still some parts that need to be changed. This issue focuses on replacing the CSRF middleware.

#### Why do we need this?

1. Because we are dropping Echo (see also https://github.com/TheThingsNetwork/lorawan-stack/pull/2382#issuecomment-621032344)
2. Because the current implementation has some shortcomings (i.e. it doesn't use `SameSite` cookies).

#### What is already there? What do you see now?

CSRF is used in `pkg/console` and `pkg/oauth`.

#### What is missing? What do you want to see?

We need to replace the existing CORS middleware with `gorilla/cors`.

#### How do you propose to implement this?

My proposal would be to make `pkg/web.(*Server)` return a CORS MiddlewareFunc based on the HTTP config (including the cookie keys). This middleware can then be used in `RegisterRoutes`.

In `pkg/console` and `pkg/oauth` we can use `echo.WrapMiddleware()` until we've migrated them away from Echo.

**Comment by kschiffer** [comment]
I'm actually working on this as part of enabling cookie authorization for the account app. See #1422 .
