### ISSUE TITLE
Remove leading slash from PubSub subtopics, standardize Pub/Sub

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2534]
#### Summary

- Remove leading slashes from subtopic prompts (Adding slashes to topics produces strange output, and makes these integrations unusable. Slashes are automatically appended somewhere in the plumbing when they need to be and NATS doesn't use slashes anyway)
- Change PubSub and Pub-sub to Pub/Sub

#### Steps to Reproduce

Use the PubSub integration in the console

#### What do you see now?

**Topic slashes produce buggy topics**
Doing this (see prompt):
<img width="374" alt="Screenshot 2020-05-12 at 17 51 18" src="https://user-images.githubusercontent.com/6963436/81716305-874ac780-9479-11ea-8324-5cb07c4aa906.png">

produces this (should be base-topic.nack) :
`[#27] Received on [base-topic./nack]`

**Inconsistent pub-sub / PubSub:**
<img width="126" alt="Screenshot 2020-05-12 at 17 46 29" src="https://user-images.githubusercontent.com/6963436/81715445-86fdfc80-9478-11ea-81c2-8839dc9a9ae4.png">
<img width="405" alt="Screenshot 2020-05-12 at 17 47 58" src="https://user-images.githubusercontent.com/6963436/81715637-bca2e580-9478-11ea-851e-dc8814a84aee.png">

#### What do you want to see instead?

- Consistent Pub/Sub label
- Remove leading slash from sub topic prompt

#### Environment

TTS V3.8

#### Can you do this yourself and submit a Pull Request?

@kschiffer

**Comment by kschiffer** [comment]
This is addressed via https://github.com/TheThingsNetwork/lorawan-stack/pull/2525.
Please verify and close issue if applicable.

**Comment by johanstokking** [comment]
If we change everything to "Pub/Sub", include error messages and CLI as well

**Comment by benolayinka** [comment]
> If we change everything to "Pub/Sub", include error messages and CLI as well

I was thinking that if we have to go through and fix `pub-sub` everywhere, we may as well standardize it the way everyone else (i.e. [google](https://cloud.google.com/pubsub/docs/overview) does it.. but I'm also okay with saving ourselves the pain of finding and replacing in the cli etc..

also if we change to Pub/Sub we have to standardize an alternate format (should be PubSub) for filenames where / is not a valid character

**Comment by johanstokking** [comment]
Up to you guys, as long as it is consistent everywhere

**Comment by benolayinka** [comment]
> Up to you guys, as long as it is consistent everywhere

Pub/Sub it is. PubSub in paths+urls. Will create an issue to track it down in console.

**Comment by benolayinka** [comment]
Closed by #2525
