### ISSUE TITLE
Change PubSub to Pub/Sub in Console strings and cli error messages

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2548]
#### Summary

With https://github.com/TheThingsNetwork/lorawan-stack/pull/2525 we standardized PubSub and Pub-sub as Pub/Sub, so we need to clean up console and cli messages to reflect this. 

So for messages and strings -> `Pub/Sub`
Internally, and in paths and urls, we can keep `PubSub`

#### Why do we need this ?

Present messages in a consistent and professional way.

#### What is already there? What do you see now?

Stuff like this

<img width="721" alt="Screenshot 2020-05-14 at 17 00 27" src="https://user-images.githubusercontent.com/6963436/81950600-6e225200-9604-11ea-971b-f3cc364392c0.png">

#### Can you do this yourself and submit a Pull Request?

No. Putting this in backlog if anyone wants it.

**Comment by johanstokking** [comment]
What is left here?

**Comment by benolayinka** [comment]
> What is left here?

I haven't worked on this at all, but I created it as a note to chase down any lingering PubSub or Pub-sub strings in cli or console.

**Comment by benolayinka** [comment]
Closing this issue as nothing depends on it
