### ISSUE TITLE
Relax console MQTT PubSub address validation

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2554]
#### Summary

The MQTT PubSub address validation in the Console should allow `tcp`, `ssl`,`tls`,`ws` and `wss` address schemas.

#### Why do we need this?

A large amount of users are used to Paho's de-facto `tcp` and `ssl` schemas. We also support websockets through `ws` and `wss` but such schemas are no considered valid by the console.

#### What is already there? What do you see now?

Only `mqtt` and `mqtts` are considered valid.

#### What is missing? What do you want to see?

`tcp`, `ssl`, `tls`, `ws` and `wss` should be valid as well.

#### Environment

077f48fb7d845560291460c6147d3d613a840d5b

#### How do you propose to implement this?

Relax the following regex https://github.com/TheThingsNetwork/lorawan-stack/blob/077f48fb7d845560291460c6147d3d613a840d5b/pkg/webui/console/lib/regexp.js#L22

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by i3mSuperMan** [comment]
The MQTT PubSub address validation in the Console is now allowing `tcps` address schema in v3.8.3 CH.
