### ISSUE TITLE
3.8.1 docker image is not published

### ISSUE THREAD

**Issue by kurtmc** [TheThingsNetwork/lorawan-stack#2559]
#### Summary

Hello, I think that the docker image for 3.8.1 has not been published.
#### Steps to Reproduce

```
$ docker pull thethingsnetwork/lorawan-stack:3.8.1
Error response from daemon: manifest for thethingsnetwork/lorawan-stack:3.8.1 not found: manifest unknown: manifest unknown
```

#### What do you see now?

Image not found.

#### What do you want to see instead?

Image downloads.

#### Environment

N/A

#### How do you propose to implement this?

N/A

#### Can you do this yourself and submit a Pull Request?

No.

**Comment by johanstokking** [comment]
That's right; we have pulled the 3.8.1 release due to some issues. The [latest is 3.7.2](https://github.com/TheThingsNetwork/lorawan-stack/releases). Apologies!
