### ISSUE TITLE
Uncheck External Join Server

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2593]
#### Summary
External Join Server - unclear why this is enabled by default.

Linked to: #2529

![image](https://user-images.githubusercontent.com/17290639/82881919-9da85700-9f40-11ea-948e-f2d8399acaab.png)

...

#### Why do we need this?
Unclear to people how to configure a device to a 3rd party join server
...

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?
Uncheck the box by default.
...

#### Environment
v3.8.1+

...

#### How do you propose to implement this?
Ask our console-master Bogdans
...

#### How do you propose to test this?
- Login to the stack
- Create a new device 
- Check that the "External Join Server" is not checked by default in an old application
- Check that the "External Join Server" is not checked by default in a new application
- [Regression] Test that checking the box still works as before (i.e., requests are routed to an external join server).

...

**Comment by KrishnaIyer** [comment]
@laurensslats: 
```
How do you propose to test this?
Staging environment?
```

This section is actually **how** to test and not **where**. We expect a test scenario here. If that's not clear in the template, please let us know and we can update that.

Consider the following;
```
How do you propose to test this?
- Login to the stack
- Create a new device 
- Check that the "External Join Server" is not checked by default.
- [Optional: Regression] Test that checking the box still works as before (i.e., requests are routed to an external join server).
```

**Comment by bafonins** [comment]
From https://github.com/TheThingsNetwork/lorawan-stack/issues/579#issuecomment-553347858:

> Checkbox whether to use external JS (default checked)

cc @johanstokking

**Comment by johanstokking** [comment]
@bafonins Indeed, I changed my mind!
