### ISSUE TITLE
Add Basic Station connection guide

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#2594]
#### Summary

Add a guide to connect Basic Station gateways to TTS. References #1140 

#### Why do we need this ?

Many vendors now support Basic Station. Having a common guide for them with separate sub-guides for vendor specific things makes it easier to use them.

#### What is already there? What do you see now?

No Doc on Basic Station

#### What is missing? What do you want to see?

Document how to connect to TTS CUPS/LNS.

#### How do you propose to document this?

Create a doc and add some examples.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by benolayinka** [comment]
Closed by #2700
