### ISSUE TITLE
LoRaCloud DAS package uplinks error management

### ISSUE THREAD

**Issue by Oliv4945** [TheThingsNetwork/lorawan-stack#2606]
#### Summary
LoRa Cloud DAS application package is currently not forwarding errors to the user. It would be helpful for issue troubleshooting.

Two kind of error should be reported:
1. HTTP errors like `Unauthorized` (not a JSON, which currently crash the parser)
2. High levels `errors` array is not redirected to the user, [documentation](https://www.loracloud.com/documentation/device_management?url=v1.html#request-response-formats)

#### What is missing? What do you want to see?
As discussed with @adriansmares it would be great to have it in the events and service data.

**Comment by adriansmares** [comment]
We've been emitting events (for a while now) via:

https://github.com/TheThingsIndustries/lorawan-stack/blob/77acc1f835a0945f3565c6d7d443690e063fd835/pkg/applicationserver/io/packages/loradms/v1/package.go#L78-L82

This issue is stale and should have been closed.
