### ISSUE TITLE
Add RAK7240 guide to gateways section

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2613]
#### Summary

Add RAK7240 guide to gateways section as part of #1140 

#### Why do we need this ?

Make it easy to connect popular gateways

#### What is already there? What do you see now?

https://thethingsstack.io/v3.8.1/gateways/

https://github.com/TheThingsNetwork/lorawan-stack/tree/master/doc/content/gateways

#### What is missing? What do you want to see?

...

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by johanstokking** [comment]
Please reopen in `lorawan-stack-docs` if this is still to be done.
