### ISSUE TITLE
Unexpected ADR behaviour leading to increased SF

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2616]
#### Summary
(Received issue from TTES user)
Unexpected ADR behaviour causing some nodes to operate at SF10/11/12 while having exemplary signal.

Nodes within 30cm of each other are sitting at vastly different SF when their signal characteristics are very similar.

Here is a real world example, A00058 and A00054 are 30cm from each other and only ~12 metres from a gateway. Same for A00004 and A00003 - both physically located together.

Node | SF | RSSI | SNR
-- | -- | -- | --
A00058 | 8 | -94 | 11.8
A00054 | 12 | -92 | 10.8
A00004 | 7 | -68 | 9.8
A00003 | 11 | -72 | 10

...

#### Steps to Reproduce

1. Set up a device and gateway using Frequency plan Australia 915-928, FSB 1 
2. Wait for the devices to receive ADR commands
3. ...

#### What do you see now?

...

#### What do you want to see instead?

...

#### Environment
AWS Marketplace AMI version 3.7.2

...

#### How do you propose to implement this?

...

#### How do you propose to test this?
1. Reproduce issue
2. Optimize ADR flow
3. Test locally & on staging with different devices, using different frequency plan
...

#### Can you do this yourself and submit a Pull Request?
John, could you please provide:
- TTES version
- Frequency plan used
- Device used

@rvolosatovs to look into the issue

**Comment by johanstokking** [comment]
@laurensslats please reopen if this is still relevant.
