### ISSUE TITLE
Remove dependency on Echo

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2627]
#### Summary

This issue tracks the removal of our dependency on Echo. We've already done some work, but we didn't have an issue to track it.

#### Why do we need this?

https://github.com/TheThingsNetwork/lorawan-stack/pull/2382#issuecomment-621032344

#### What is already there? What do you see now?

A lot of work already done in https://github.com/TheThingsNetwork/lorawan-stack/pull/2382 and https://github.com/TheThingsNetwork/lorawan-stack/pull/2561

More upcoming removals in https://github.com/TheThingsNetwork/lorawan-stack/pull/2564

Some other pull requests removing other parts

#### What is missing? What do you want to see?

Complete removal

**Comment by htdvisser** [comment]
Let's add this to the quarterly milestone. We haven't been able to upgrade Echo since v4.1.2 (released Apr 29, 2019) which is a really long time. At the same time, we don't actually _need_ Echo, because we also use Gorilla mux router, so let's just remove what's left of Echo.

**Comment by johanstokking** [comment]
So we have:

- `pkg/account`, `pkg/oauth`, `pkg/web/oauthclient`: @kschiffer
- `pkg/basicstation/cups`: @KrishnaIyer 
- `pkg/console` and `pkg/webui`: @pgalic96 (touched these files last week and usage is very minimal)
- `pkg/gatewayserver/io/ws`: @KrishnaIyer 
- `pkg/web/middleware`: @pgalic96 (needs non-echo variants)

General cleanup, may depend on the above (?)
- `pkg/errors/web`: @htdvisser 
- `pkg/ratelimit`: @htdvisser (this is probably just deleting the middleware that has become obsolete)
- `pkg/util/test/assertions`: @htdvisser (independent; the test assertions aren't being used)
- `pkg/web`: @htdvisser and/or @johanstokking (definitely depends on removing usage above)

**Comment by htdvisser** [comment]
> `pkg/web/middleware`: @pgalic96 (needs non-echo variants)

Those should all already exist in `pkg/webmiddleware`.

**Comment by adriansmares** [comment]
>     * `pkg/basicstation/cups`: @KrishnaIyer
>     * `pkg/gatewayserver/io/ws`: @KrishnaIyer

I'll steal this.
