### ISSUE TITLE
Support LoRa Cloud Geolocation integration

### ISSUE THREAD

**Issue by ajovertoom** [TheThingsNetwork/lorawan-stack#2630]
#### Summary

Add support for LoRa Cloud Geolocation in Application Server, so that users can easily enable and obtain device location updates in their application. See also #37 

#### Why do we need this?

Save time and resources for users by offering a preconfigured integration.

#### What is already there? What do you see now?

Data type `LocationSource` already contains values that can be provided by the LoRa Cloud Geoloc service, such as `SOURCE_LORA_TDOA_GEOLOCATION`

#### What is missing? What do you want to see?

The bridge to LoRa Cloud Geolocation. 
Ability to enable the integration from the console, under menu item `Integrations`

#### Can you do this yourself and submit a Pull Request?

@adriansmares @kschiffer

**Comment by johanstokking** [comment]
> What is already there? What do you see now?

Adding to the above; we have the ability for application packages to publish messages to be sent upstream, like ServiceData. We have LocationSolved too; it would be a matter of the LoRa Cloud package to recognize the response and publish that message type

We have locations for end devices, but at the moment we do not support updating those in the entity registry from the Application Server. This is related to gateway locations that Gateway Server updates in the Entity Registry. Looping in @neoaggelos to comment on that.

**Comment by Oliv4945** [comment]
Hi,

Be careful that the current application package is for the DAS ([Device & Application Services](https://www.loracloud.com/documentation/device_management)) server, while the RSSI/TDOA requests should be send to GLS ([GeoLocation Service](https://www.loracloud.com/documentation/geolocation)). URL, tokens and API are not the same

**Comment by johanstokking** [comment]
> Be careful that the current application package is for the DAS ([Device & Application Services](https://www.loracloud.com/documentation/device_management)) server, while the RSSI/TDOA requests should be send to GLS ([GeoLocation Service](https://www.loracloud.com/documentation/geolocation)). URL, tokens and API are not the same

Good point. I was under the impression that DAS would include the LR1110 geolocation services, like GNSS and WiFi scans.

Is that going to be separate, or is GLS the only platform for geolocation?

**Comment by johanstokking** [comment]
@adriansmares what is the status here?

**Comment by adriansmares** [comment]
> @adriansmares what is the status here?

I have a working design in a local branch. I'll polish it this month and publish for review.

**Comment by johanstokking** [comment]
OK. This is non-blocking for 3.11.3; I'm also OK with 3.12.
