### ISSUE TITLE
Add telemetry to pkg/log

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2634]
#### Summary

It would be nice to have some observability in `pkg/log`.

#### Why do we need this?

If we'd have some Prometheus metrics that count logs for a certain level, we could get some insights into how many warnings/errors we're logging. We can also set up alerts to notify us when error rates increase.

#### How do you propose to implement this?

A log middleware that registers a `metrics.ContextualCounterVec` to keep track of log messages per level. Maybe also per `namespace`.

#### How do you propose to test this?

Can easily verify this on localhost:1885/metrics

**Comment by neoaggelos** [comment]
Closed with #2677
