### ISSUE TITLE
Duplicating pub/sub IDs in the Console results in pub/sub overrides

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2658]
#### Summary

If a new pub/sub integration is created with an already existing ID, it will override the already existing integration.

#### Steps to Reproduce

(using the Console)

1. Create a pub/sub with ID `ps1` - maybe add some message to distinguish this integration
2. Create a new pub/sub with ID `ps1`, but with different configuration (another message)
3. Check that at the end there is only one `ps1`, containing the latest configuration

#### What do you see now?

Only one pub/sub integration (the latest).

#### What do you want to see instead?

A warning that saving this new integration will override the already existing one.

#### Environment

d3983f5

#### How do you propose to implement this?

Not sure.

#### How do you propose to test this?

Repeat the reproduction steps and check that the warning exists.

#### Can you do this yourself and submit a Pull Request?

No, but I can review.

#### Some background

This occurs since the pub/sub registry only has a `Set` method, which conflates create and update. I guess the Console uses this without any checks (this is consistent with CLI anyway). I believe the warning would be better than just denying the behavior since at least it would stay consistent with CLI.

**Comment by bafonins** [comment]
I think calling the `Get` RPC of [ApplicationPubsubRegistry](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#service-applicationpubsubregistry ) is the easiest way to check if the id is in use. This should be used with our JS SDK (https://github.com/TheThingsNetwork/lorawan-stack/blob/develop/sdk/js/src/service/pubsubs.js#L84-L101).

UI-wise, I suggest showing a modal when the user submits the form. This should warn the user that the pubsub integration with provided id already exists and prompt the user if he/she wants to override existing integration with the current form values.
