### ISSUE TITLE
Revoke all User Sessions and OAuth Access Tokens on password change

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#267]
**Summary:** 

Users should get the possibility to revoke all User Sessions and OAuth Access Tokens on a password change.

**Why do we need this?**

In case a user login gets compromised we need to be able to revoke access.

**What is already there? What do you see now?**

We already have the password reset flow.

**What is missing? What do you want to see?**

- A `revoke_all_access` boolean in `UpdateUserPasswordRequest` to indicate that all existing sessions and access tokens should be revoked.
- Code in the IS's UpdatePassword handler to revoke sessions and access tokens if the user wants that. 

**How do you propose to implement this?**

1. Add the field to `UpdateUserPasswordRequest`
2. Add code to `updateUserPassword` in the Identity Server that deletes sessions and access tokens if the field is true. You can use `FindSessions`+`DeleteSession` of the `UserSessionStore` and `ListAccessTokens`+`DeleteAccessToken` of the `OAuthStore` for this.
3. Add a `--revoke_all_access` flag to `ttn-lw-cli update-password`

**What can you do yourself and what do you need help with?**

I can do this

**Comment by furtiman** [comment]
@htdvisser I recall you wanted to format this issue in some way?

**Comment by htdvisser** [comment]
Updated

**Comment by furtiman** [comment]
@htdvisser 

> Add a --revoke_all_access flag to ttn-lw-cli logout

You meant `ttn-lw-cli user update-password`, right?

**Comment by htdvisser** [comment]
Yes, that's what I meant. Updated.
