### ISSUE TITLE
Setting console.ui.branding-base-url

### ISSUE THREAD

**Issue by walleyworld** [TheThingsNetwork/lorawan-stack#2671]
#### Summary

Trying to change the branding logo displayed in Cloud Hosted v3 stack (currently 3.8.2) via the CLI Console after following the documentation https://enterprise.thethingsstack.io/v3.8.3/reference/configuration/console/
and
https://enterprise.thethingsstack.io/v3.8.3/reference/branding/

#### Steps to Reproduce

1. Installed the console CLI on both Windows and Linux boxes
2. Configured the .ttn-lw-cli.yml config file with my Cloud Hosted NAM1 instance
3. ttn-lw-cli login (including oauth) was successful
4. ttn-lw-stack start console --console.ui.branding-base-url "https://new_branding_url_location"
5. ERROR: Could not start gRPC server
6. checked "ttn-lw-stack config" and still old localhost references for "console.ui.branding-base-url"

#### What do you see now?

...

#### What do you want to see instead?

...

#### Environment

3.8.3

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

No, based on TTI Cloud Hosted so need TTI help.

**Comment by htdvisser** [comment]
Hi @walleyworld, sorry that this issue slipped through. If this is related to the configuration of a tenant on TTI Cloud Hosted, please contact support@thethingsindustries.com. That way you'll get a quick response instead of us only noticing your issue weeks later.
