### ISSUE TITLE
Task Backoff Never Resets

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2679]
#### Summary

The backoff of some long-running tasks (such as the application link task) never resets.

#### Steps to Reproduce

1. Take a multi-instance deployment
2. Set up some application links
3. Restart the Network Server
4. Let the link task recover
5. Restart the Network Server again
6. Check the backoff of the link task

#### What do you see now?

The link task has no way of indicating to the "task manager" that it's stable, so the "manager" only sees the "Unavailable" errors from when the Network Server restarts. This means that it keeps incrementing the `invocation` counter and keeps increasing the backoff.

#### What do you want to see instead?

If a task is running for a certain amount of time without returning an error (let's say a minute, but maybe @johanstokking has a different duration in mind), we can assume that it's stable, and we can clear the `invocation` counter so that the backoff resets.

#### Environment

This only happens in multi-instance deployments, because in single-instance deployments the Application Server is also restarted, which resets the counter.

#### How do you propose to implement this?

In `pkg/component/tasks.go` we should keep track of when we start a task, and compute the run duration of that task when it returns. If the task has been up for the duration I mentioned above, we can reset the number of invocations to 0.

#### How do you propose to test this?

It's relatively easy to unit test this. You start a task that returns an error before the "limit" and verify that the next time it starts is after a certain backoff. You start another task that returns an error after the "limit" and verify that the next time it starts does not have that backoff.

Since this is a time-related test, I'm not sure we should do this as part of CI, because it could become a bit flaky (and we'd be using delays, which we don't want on CI).

**Comment by johanstokking** [comment]
> (let's say a minute, but maybe @johanstokking has a different duration in mind)

I think this is a sane default
