### ISSUE TITLE
Unset RxMetadata timestamps in NS

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2684]
#### Summary

Unset RxMetadata timestamps in NS - https://github.com/TheThingsNetwork/lorawan-stack/pull/2657

#### Steps to Reproduce

1. See https://github.com/TheThingsNetwork/lorawan-stack/pull/2657

#### Can you do this yourself and submit a Pull Request?

@rvolosatovs

**Comment by johanstokking** [comment]
So this is for after deduplication

**Comment by rvolosatovs** [comment]
@benolayinka please either fill in the template or remove unused sections in the future

**Comment by htdvisser** [comment]
Invalid issue, not enough information.
