### ISSUE TITLE
Ability to add device location through cli

### ISSUE THREAD

**Issue by ktsolakas** [TheThingsNetwork/lorawan-stack#2689]
#### Summary
I would like to be able to add a devices location through cli. Manually adding lat and long values to hundreds of device is painful.
#### Why do we need this?
This is needed to more efficiently manage devices
#### Environment
Version 3.8.3
#### How do you propose to implement this?
Add the ability to cli to add/update a device location settings
#### How do you propose to test this?
By updating devices location and viewing the location on the console as well as in the cli
#### Can you do this yourself and submit a Pull Request?
No

**Comment by neoaggelos** [comment]
Closed with #2706
