### ISSUE TITLE
Improve handling stack component addresses in the Console

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2694]
#### Summary

Currently, the UI for setting stack component addresses can be ambiguous to novice users.

#### Why do we need this?

Hide specifics under default options such that new users do not have to deal with ttn stack specifics.

#### What is already there? What do you see now?

1. Usage of `{component} Server address`
2. Application link, device general settings, gateway creation, gateway general settings - requires the users to specify stack component addresses

#### What is missing? What do you want to see?

1. Use `{component} server host` instead of  `{component} server address` as we require the users to specify only host names and not full addresses.
2. Hide input fields under a checkbox with title `Use default {component} Server host` which is initially checked. Reveal the input and allow the user to specify custom host only when the checkbox is unchecked.

#### Environment

v3.8.3

#### How do you propose to implement this?

Extend validation schema to process checkbox values.
Conditionally render text inputs on checkbox value changes

#### How do you propose to test this?

Setup application link, create gateway, edit gateway, edit end device, create end device

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by bafonins** [comment]
Blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/2813

**Comment by kschiffer** [comment]
#3522 includes a fix for the end device registration process and the same behavior can be used for the general settings as well. The updated gateway registration will likely use the same mechanic, but this is still in planning.

I'll remove the `blocked` and `needs/ux` labels, since this is now actionable as part of #3522 at least for end devices.

**Comment by johanstokking** [comment]
@bafonins what is the status here?

**Comment by bafonins** [comment]
@johanstokking See my [comment](https://github.com/TheThingsNetwork/lorawan-stack/issues/3522#issuecomment-788715945) regarding JS address handling in DR form

**Comment by kschiffer** [comment]
See also #3947

**Comment by bafonins** [comment]
Blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/3947
