### ISSUE TITLE
Lock-based concurrency in registries

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2696]
#### Summary

Replaces #33 
Lock values in registries on SET.

#### Why do we need this?

To ensure correctness and optimal performance.

#### What is already there? What do you see now?

In all registries except NS(after #2662) we use optimistic concurrency, where the modified keys are `WATCH`'ed and in case the transaction fails, we simply fail it without retrying.
In #2662 an efficient Redis mutex lock implementation is added. It is essentially a drop-in replacement for `redis.Watch`. The implementation only locks 1 key, but can be extended to support multiple easily if there's a use case for it.

#### What is missing? What do you want to see?

Use `redis.LockedWatch` from #2662 (and, perhaps, lock other important keys depending on the implementation) to avoid possibility of transaction failure and remove the need for retrying transactions. Failed transactions in this case represent an implementation error.
Regarding the "transaction failures only happen in NS" or "the request count is small enough, that such issues rarely happen"(e.g. for JS) argument: concurrency-induced transaction failures shall not be possible. The overhead of locking is extremely small and so there's no reason not to do it.
At scale it ensures performance (versus the optimistic concurrency and retry solution) and correctness. At small scale it ensures correctness and has a negligible effect on performance.
Consider the case where the device would be updated in JS registry at the same time a join-request arrives - perfect example of a component, where clashes are very rare - with current implementation one of the operations would fail, but there's no reason for that to happen. Even though it's improbable for this to happen - it *can* happen and the more customers we have, the higher possibility of such. Even accidental concurrent set to a registry is a possible occasion and we can easily handle this case gracefully and give the user expected output instead of failing.

Please also see table at https://redislabs.com/ebook/part-2-core-concepts/chapter-6-application-components-in-redis/6-2-distributed-locking/6-2-4-fine-grained-locking/

#### How do you propose to implement this?

Use `redis.LockedWatch`, go through each implementation probably adding additional locking logic. See #2662 for an example of NS part.

#### How do you propose to test this?

Integration testing, flow tests

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Yes I agree that this is a good idea to implement in places where we watch keys at the moment.
