### ISSUE TITLE
Update Redis library to v8

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2698]
#### Summary

Update Redis library to v8

#### Why do we need this?

To remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377 and be up-to-date
Perhaps `context.Context` in all commands is also useful for us

#### What is already there? What do you see now?

v7 in #2662

#### What is missing? What do you want to see?

v8

#### How do you propose to implement this?

Update and adapt to API changes. Remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377

#### How do you propose to test this?

Integration testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by adriansmares** [comment]
FTR v8 has been released https://github.com/go-redis/redis/releases/tag/v8.0.0 (and the moment this comment was written `8.1.3` is already out).

**Comment by rvolosatovs** [comment]
I'll address this after #2837 is merged
