### ISSUE TITLE
Document payload formatters

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2713]
#### Summary

Document payload formatters.

#### Why do we need this ?

We provide several options for the users on how device payload are decoded/encoded. 

#### What is already there? What do you see now?

Functionality to set formatters in the Console

<img width="1182" alt="Screenshot 2020-06-11 at 17 24 55" src="https://user-images.githubusercontent.com/16374166/84398367-85a32980-ac08-11ea-92d6-8f5cf6d7d566.png">

<img width="1168" alt="Screenshot 2020-06-11 at 17 23 41" src="https://user-images.githubusercontent.com/16374166/84398358-8340cf80-ac08-11ea-80ac-dea83d942ddf.png">

It is also possible to set payload formatters via the CLI

#### What is missing? What do you want to see?

1. Describe each formatter (javascript, grpc, cayennelpp and repository).
	* Having some examples would be nice.
	* for `javascript` it would be great to mention what js runtime we use in the AS, so that the users dont try using unavailable js API, cc @johanstokking 
	* for `repository` mention that it is up to device manufacturers and it might be available.
2. Describe differences between device level and application level formatters. 
	* Why would one use application level formatters?
	* How to reset device level formatters and fallback to formatters in the application link?
3. Describe how to set formatters via the Console and CLI
	

We might want to wait until https://github.com/TheThingsNetwork/lorawan-stack/issues/2234 is implemented to describe how one can quickly test their formatters.
#### Can you do this yourself and submit a Pull Request?

cc @benolayinka @nejraselimovic

**Comment by johanstokking** [comment]
Blocked by:

- #2234
- https://github.com/TheThingsNetwork/lorawan-stack/issues/2670

**Comment by laurensslats** [comment]
Removed blocked. This is about documentation, not about testing.

This is of medium priority, people are completely in the dark on how to create payload formatters.

**Comment by johanstokking** [comment]
This is still blocked by #2670 as we're changing the message processor API.

I'm fine documenting it the way it is now, but it's gonna change.

**Comment by benolayinka** [comment]
The cayenneLPP integration seems to cause an error. @adriansmares @johanstokking ?

<img width="1094" alt="Screenshot 2020-06-30 at 18 43 02" src="https://user-images.githubusercontent.com/6963436/86153185-8c370980-bb01-11ea-8258-2e68c5f4aedd.png">

**Comment by johanstokking** [comment]
That binary payload doesn't look like valid CayenneLPP

**Comment by benolayinka** [comment]
> That binary payload doesn't look like valid CayenneLPP

Okay, so the sketch needs to be changed to send CayenneLPP compatible binary payloads.

**Comment by benolayinka** [comment]
@adriansmares suggested the GRPC payload formatter is a placeholder, and the implementation does not exist yet (or is at least not specified). Has anyone tested or successfully implemented a GRPC payload formatter? Are there implementation details somewhere? @johanstokking  @laurensslats

**Comment by johanstokking** [comment]
> Has anyone tested or successfully implemented a GRPC payload formatter? Are there implementation details somewhere?

No, don't use and document (for now).

**Comment by bafonins** [comment]
@benolayinka Can we close this?

**Comment by benolayinka** [comment]
Closed by #2836
