### ISSUE TITLE
Add troubleshooting section

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2714]
#### Summary
Guide people in the troubleshooting process when gateways, devices and/or integrations are not working.

#### Why do we need this ?
In many cases, people have issues when first connecting gateways, devices or integrations.

#### What is already there? What do you see now?
We got some troubleshooting articles on Confluence: https://thethingsindustries.atlassian.net/wiki/spaces/TKB/pages/655362/Troubleshooting+articles

#### How do you propose to document this?
1. Define what to add
2. Write docs

#### Can you do this yourself and submit a Pull Request?
Will call in some help from @benolayinka

**Comment by laurensslats** [comment]
Let's start with event logs (this is what I found on Jira)

**Gateway logs**
- Start recording the gateway event logs by `ttn-lw-cli events subscribe --gateway-id <gateway ID>`

**Device logs**
Start recording the device event logs by `ttn-lw-cli events subscribe --application-id <application ID> --device-id <device ID>`

Get output of ttn-lw-cli devices `get <app-id> <dev-id> --mac-state --pending-mac-state`

**Comment by benolayinka** [comment]
Also to add: Checklist of what to do when a data is not received

**Comment by benolayinka** [comment]
Lots of problems and solutions in slack: https://thethingsnetwork.slack.com/archives/CFVF7R4AH/p1593571134031100

**Comment by benolayinka** [comment]
Entity not found error

**Comment by benolayinka** [comment]
Packet broker peering: https://www.thethingsnetwork.org/forum/t/packet-broker-ttn-to-tti-ttn-v2-eu/38036/6

**Comment by benolayinka** [comment]
Token exchange refused - ssl errors https://www.thethingsnetwork.org/forum/t/issues-with-login-and-self-signed-certificates/37893

**Comment by KrishnaIyer** [comment]
@benolayinka. Please use a single comment with `TODO` checklists and sub-issues if necessary. You can also open a thread on discourse and add the finalised items here.
