### ISSUE TITLE
Flaky Redis lock test

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2718]
#### Summary

Flaky Redis lock test

#### Steps to Reproduce

1. Run CI
2. Flip a coin

#### What do you see now?

```
--- FAIL: TestMutexLock (1.05s)
##[error]    redis_test.go:831: LockMutex returned before previous caller unlocked: %!s(<nil>)
FAIL
FAIL	go.thethings.network/lorawan-stack/v3/pkg/redis	1.194s
```

#### What do you want to see instead?

No test failure

#### Environment

GitHub Actions

#### How do you propose to implement this?

Not sure

#### How do you propose to test this?

Not sure

#### Can you do this yourself and submit a Pull Request?

No

**Comment by rvolosatovs** [comment]
Closed by #2720
