### ISSUE TITLE
Streamline entity title sections in the Console

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2740]
#### Summary

Currently, entity title section in the Console are inconsistent.

#### Why do we need this?

Consistent UI across the Console.

#### What is already there? What do you see now?

Application title section:
![Screenshot 2020-06-15 at 17 17 56](https://user-images.githubusercontent.com/16374166/84669175-3d984580-af2d-11ea-8167-a676f57ad4b4.png)

Device title section:
![Screenshot 2020-06-15 at 17 18 11](https://user-images.githubusercontent.com/16374166/84669177-3e30dc00-af2d-11ea-8bc1-b051d768c312.png)

Gateway title section:
![Screenshot 2020-06-15 at 17 18 23](https://user-images.githubusercontent.com/16374166/84669181-3ec97280-af2d-11ea-9594-2beebf9dc16d.png)

Organization title section:
![Screenshot 2020-06-15 at 17 18 42](https://user-images.githubusercontent.com/16374166/84669185-3f620900-af2d-11ea-80b4-7c05da3fdde8.png)

#### What is missing? What do you want to see?

1. Creation date is missing in the device title section, while it is present title sections for other entities. Im not sure if we really need this, since we display `Created at` in the overview pages for each entity.
2. Missing `ID` sub-title:
![68497283-7e700380-0254-11ea-8c01-0907a8e4e909](https://user-images.githubusercontent.com/16374166/84669699-d29b3e80-af2d-11ea-9509-ae6f96891b25.png)
I find this quite helpful.
3. Inconsistent status location and messages (gateway and device title pages).
4. Description location (device title section displays description in a different way than title sections for other entities)

cc @kschiffer 

#### Environment

3.8.4

#### How do you propose to implement this?

Refactor `<EntityTitleSection />` and its usage for applications/devices/gateways and organizatons, as well as `<GatewayConnectionStatus />`

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by kschiffer** [comment]
Please wait with the implementation until I followed up with new designs for the title sections. Will try to squeeze that in this month.

**Comment by kschiffer** [comment]
@bafonins I've added the new designs to Zeplin.

**Comment by bafonins** [comment]
Blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/2333

**Comment by bafonins** [comment]
@johanstokking Do you think that adding uplink and downlink counts on the application overview page is needed? Currently, we display the counts only on end device/gateway overview pages.

**Comment by johanstokking** [comment]
> @bafonins Do you think that adding uplink and downlink counts on the application overview page is needed?

No, I think we shouldn't do that until we have proper aggregates from the Event Server.

**Comment by bafonins** [comment]
Then this issue can be closed
