### ISSUE TITLE
Document Gateway Server MQTT V3 messages

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2743]
#### Summary

Document Gateway Server MQTT V3 messages

#### Why do we need this ?

For users to know how to interact via MQTT with Gateway Server, using V3-enabled forwarders.

#### What is already there? What do you see now?

The application-layer integration: https://thethingsstack.io/v3.8.4/integrations/mqtt/

#### What is missing? What do you want to see?

Similar documentation for interacting with the Gateway Server via MQTT.

#### How do you propose to document this?

Authentication, message format, topic structure and some example messages for uplink, downlink and status.

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by johanstokking** [comment]
@KrishnaIyer please reassign and coordinate if needed, but let's aim for this month.

**Comment by neoaggelos** [comment]
Picking this one up
