### ISSUE TITLE
Add links to Documentation in the console

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2770]
#### Summary
Add links to our Documentation.

#### Why do we need this?
People don't know/forget the right link to our docs. 

#### What is missing? What do you want to see?
Add an extra line at the landing page.
<img width="555" alt="Screenshot 2020-06-19 at 09 26 28" src="https://user-images.githubusercontent.com/17290639/85107903-fc46b500-b20e-11ea-846f-66ca2e2c52f7.png">

And in the footer:
<img width="320" alt="Screenshot 2020-06-19 at 09 23 39" src="https://user-images.githubusercontent.com/17290639/85107670-a3771c80-b20e-11ea-9cb6-4969b93563db.png">

TTS link: https://thethingsstack.io/
TTES link: https://enterprise.thethingsstack.io/
Get support link: https://www.thethingsindustries.com/support

#### Environment
v3.8.3

#### How do you propose to implement this?
Add the link

#### How do you propose to test this?
Test on local setup.

**Comment by kschiffer** [comment]
Note that this likely needs to be a config passed to the frontend, just like the "Get Support" link.

**Comment by bafonins** [comment]
So, I guess documentation+support links are applicable for ttes.
Shall we add documentation link to tts? @laurensslats

**Comment by laurensslats** [comment]
It can be exactly the same in all deployments (enterprise as well as open source).

Documentation: https://thethingsstack.io/
Support: https:/thethingsindustries.com/support

**Comment by johanstokking** [comment]
Let's do this when we have a stable URL: https://www.thethingsindustries.com/docs

Blocked by https://github.com/TheThingsIndustries/thethingsindustries.com/issues/245

**Comment by kschiffer** [comment]
I'm confused now. [TheThingsedustries/thethingsindustries.com#245](https://github.com/TheThingsIndustries/thethingsindustries.com/issues/245) is closed but https://www.thethingsindustries.com/docs is still a 404.

How to proceed with this? cc @laurensslats @johanstokking

**Comment by johanstokking** [comment]
@michalborkowski96
