### ISSUE TITLE
Stop serving versioned documentation

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#2778]
#### Summary

Let's drop the version number from our hosted documentation.

#### Why do we need this ?

- Breaks links
- Bad for SEO
- Bad for search #2588 

#### What is already there? What do you see now?

Version numbers e.g https://thethingsstack.io/v3.8.4/

#### What is missing? What do you want to see?

Everything at https://thethingsstack.io/...

#### Can you do this yourself and submit a Pull Request?

Yes. @johanstokking to give the ok?

**Comment by johanstokking** [comment]
Yes, please!
