### ISSUE TITLE
CI for 32-bit architectures

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2797]
#### Summary

Run CI for 32-bit architectures

#### Why do we need this?

To support various embedded device like RPi

#### What is already there? What do you see now?

Only 64-bit CI

#### What is missing? What do you want to see?

32-bit CI

#### How do you propose to implement this?

Not sure, `GOARCH` ?

#### How do you propose to test this?

CI

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
We'd prefer static checks here, maybe we can check for misaligned struct fields (for atomic) or unexpected overflows of `int`/`uint`.

**Comment by rvolosatovs** [comment]
@johanstokking why was this closed?

**Comment by johanstokking** [comment]
Because we're not going to support this anytime soon.
