### ISSUE TITLE
Warn users about empty `frequency_plan_id` in the Console

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2805]
#### Summary

After https://github.com/TheThingsNetwork/lorawan-stack/pull/2785 we allow creating/updating gateways without `frequency_plan_id` in the Console. While leaving empty `frequency_plan_id` is allowed we should warn the users about consequences.

#### Why do we need this?

Make users aware of limitations when creating/updating gateways without `frequency_plan_id`

#### What is already there? What do you see now?

The `frequency_plan_id` field which is not required:

<img width="879" alt="Screenshot 2020-06-28 at 20 32 50" src="https://user-images.githubusercontent.com/16374166/85954221-911f8000-b97e-11ea-9391-4b2c3c27137d.png">

#### What is missing? What do you want to see?

@KrishnaIyer what are general limitations when creating gateways without `frequency_plan_id` ?

#### How do you propose to implement this?

I think the easiest is to show a warning that includes field description and the limitations. Once a frequency plan is selected we can remove the warning and show a regular description.

#### How do you propose to test this?

Check the `frequency_plan_id` field w/ and w/o value set.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by KrishnaIyer** [comment]
> what are general limitations when creating gateways without frequency_plan_id ?

Basically the GS needs the `frequency_plan_id` to fetch the band and look up stuff like Data Rate. Without this the GS cannot send downlinks and for some frontends (ex: basic station) cannot receive uplinks/configure the gateway.

A warning like "Without choosing a `frequency_plan_id `, the packets from the gateway will not be correctly processed" would work I guess.
