### ISSUE TITLE
Reorganize gateway general settings form into collabsible sections

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2807]
#### Summary
The general settings form for gateways is becoming quite large. We should reorganize it into collapsible sections like we do for end devices.

#### Why do we need this?
- better information architecture
- also helps us organizing validation schemas and constraints in our code

#### What is already there? What do you see now?
Collapse component as part of the end device general settings

#### What is missing? What do you want to see?
The settings being organized by category, just like we do for end devices

#### Environment
v3.8.4

#### How do you propose to implement this?
Complementary to our refactors for end device settings.

#### How do you propose to test this?
Good opportunity to add some end-to-end tests 🌈 

#### Can you do this yourself and submit a Pull Request?
I suggest @bafonins but feel free to reassign.

**Comment by bafonins** [comment]
@pgalic96 I think here we you can add 2 sections (basic and lorawan options). So everything from `General settings` and `Gateway updates` sections goes to `Basic settings`, `Lorawan options` stays the same.
