### ISSUE TITLE
Removing attributes from a form results in unnecessary validation error

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2812]
#### Summary
When adding an attribute and removing it straight away, a validation error is shown. `All attribute entry values are required. Please remove empty entries.`

![image](https://user-images.githubusercontent.com/5710611/86077048-3a24c280-bac6-11ea-81a1-bffb6b5eab9f.png)

#### Steps to Reproduce

1. Create a new application (or gateway)
2. Add an attribute
3. Remove the entry again
4. See a faulty validation error

#### What do you see now?
Faulty validation message.

#### What do you want to see instead?
No validation issue.

#### Environment
v3.8.4

#### How do you propose to implement this?
I haven't looked into the code but suppose that this is an issue with the validation schema.

#### How do you propose to test this?
By hand.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by pgalic96** [comment]
I haven't been able to replicate this, neither with gateways, application, or device attributes.

**Comment by kschiffer** [comment]
Please try on `develop`.

**Comment by pgalic96** [comment]
Could you check once more? Haven't been able to reproduce this in both master and develop. Also checked with @bafonins who couldn't reproduce it as well.

**Comment by kschiffer** [comment]
Appears to have been resolved since.
