### ISSUE TITLE
Revisit end device general settings page

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#2832]
#### Summary

We should revisit end device general settings page and adjust its UI and validation.

#### Why do we need this?

Consistency with device wizard and verified user flow when managing end devices.

#### What is already there? What do you see now?

End device general settings page with a bunch of forms for each stack omponent

#### What is missing? What do you want to see?

1. Consistent validation with device wizard.
2. Usage of validation context instead of passing dummy `_{dummy_field_name}` fields.
3. Fix for submission issue for ABP/Multicast devices when `root_keys` appear after submitting the identity server form
4. Remove direct imports of config selectors
5. Add validation schema tests

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by bafonins** [comment]
Moving this to `Next up` as there are more important issues to work on. Also, for such refactoring having some e2e tests in place (https://github.com/TheThingsNetwork/lorawan-stack/pull/3065) is required.

**Comment by NicolasMrad** [comment]
outdated issue. otherwise please re-open it.
