### ISSUE TITLE
Improve sentry error fingerprints for frontend errors

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2849]
#### Summary
We currently see a lot of sentry errors being grouped in an unhelpful way. We need to use better fingerprints to ensure that grouped events actually account for the same type of error.

#### Steps to Reproduce
See sentry issues like these: https://sentry.io/organizations/the-things-industries/issues/1739012974/events/d441eb3ca15d4897be4be5a8bdce8b6b/?project=2682566&referrer=github_integration

Going through the individual error events, it can be seen that all the errors are grouped on the grounds of being logged as: `Non-Error exception captured with keys: code, details, message`
However, a lot of different backend errors can ultimately result in this error message. See also: https://github.com/TheThingsNetwork/lorawan-stack/issues/2824#issuecomment-654559983

#### What do you see now?
Sentry events being grouped in an unhelpful way.

#### What do you want to see instead?
Sentry events being grouped correctly.

#### Environment
v3.8.5

#### How do you propose to implement this?
I've found [this article](https://blog.sentry.io/2019/01/17/debug-tough-front-end-errors-sentry-clues) which has some helpful suggestions.

We should also make sure that we wrap the backend error into a proper `Error()` constructor.

#### How do you propose to test this?
Manually.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by pgalic96** [comment]
This should be closed now, possibly reopening it when other errors need better grouping as well.
