### ISSUE TITLE
Personal access tokens

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2892]
#### Summary

Allow login via personal access tokens

#### Why do we need this?

To allow safe limited access to users/organizations resources to use in scripts, for example

#### What is already there? What do you see now?

Only username/password login possible

#### What is missing? What do you want to see?

Access token generation service and a way to use them to login

#### How do you propose to implement this?

Add an RPC to IS, where a logged in user can generate an access token.
The access token could be treated as a user/organization with a subset of users/organizations rights internally.

#### How do you propose to test this?

unit tests, integration testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by nejraselimovic** [comment]
@bafonins V2 had this feature, right? For which kind of users is this needed?
