### ISSUE TITLE
Make better use of horizontal space in the console (increase event container size)

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2893]
#### Summary
The console currently uses a fixed width for all views. In some views, like event data views, it makes sense to make use of all horizontal space available to prevent unnecessary truncation.

#### Why do we need this?
Increase the usability of our data views, by avoiding unnecessary cut-offs.

#### What is already there? What do you see now?
- Our grid system

#### What is missing? What do you want to see?
More thoughtful, individual usage of free horizontal space, when it would increase the UX

#### Environment
v3.8.5

#### How do you propose to implement this?
We can probably simply get rid of the grid scaffold in some views, however it might be necessary to change the width of the breadcrumb container as well in such cases.
For the event view, we could fix the whole size container to the parent container as well.

#### How do you propose to test this?
Manual testing.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
Some what related https://github.com/TheThingsNetwork/lorawan-stack/issues/1327. Close if not relevant or fixed already
