### ISSUE TITLE
Non-interactive login

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2894]
#### Summary

Support logging in non-interactively

#### Why do we need this?

For using CLI in scripts, for example - e.g. in CI

#### What is already there? What do you see now?

Login via browser

#### What is missing? What do you want to see?

Support login via CLI exclusively non-interactively

#### How do you propose to implement this?

Implement command, which would support this: `cat password | ttn-lw-cli -u username`

#### How do you propose to test this?

`cat password | ttn-lw-cli -u username` should login the user

#### Can you do this yourself and submit a Pull Request?

I think so

**Comment by htdvisser** [comment]
Accepting username/password like this is not going to happen. Username/password login will (in the future) be behind CAPTCHA and 2FA, and will be pretty much impossible in the CLI, and definitely in a non-interactive way.

Instead, we'll go for #3518, and use `ttn-lw-cli login --api-key XXX` to do non-interactive CLI logins.
