### ISSUE TITLE
Frequency plan list doesn't fetch `frequency-plans.yml`

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#2896]
#### Summary
Outdated frequency plan list is shown.

#### Steps to Reproduce

1. Add a device, see dropdown of frequency plans

It is working on `staging1` as well as on a local production, yet it is not updated on TTI CH.

#### What do you see now?
![Screenshot 2020-07-13 at 15 09 35](https://user-images.githubusercontent.com/17290639/87308324-5dfef400-c51b-11ea-9007-e9d359385bc4.png)

#### What do you want to see instead?
It should correspond to the names in: https://github.com/TheThingsNetwork/lorawan-frequency-plans/blob/master/frequency-plans.yml

#### Environment
v3.8.5

#### How do you propose to implement this?
Fetch the right file.

#### How do you propose to test this?
I'll leave that to @bafonins

**Comment by johanstokking** [comment]
@laurensslats always set a milestone please.

This is an operational issue also.

**Comment by laurensslats** [comment]
@johanstokking so is this fixed now?

**Comment by johanstokking** [comment]
It is fixed but it depends on the infrastructure that you're looking at whether it's deployed. The Things Industries Cloud Hosted EU1, for example, will be updated Monday to make this effective.
