### ISSUE TITLE
Add auto-complete configuration on release packages (Snap, Brew, Deb, RPM)

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#2907]
#### Summary

Brew and snap have built-in configuration for auto-completion. We should use that.

#### Why do we need this?

Users can simply download from snap or brew and get auto-completion out of the box, instead of having to configure auto-completion themselves.

#### What is already there? What do you see now?

Auto-complete support and documentation to enable it.

#### What is missing? What do you want to see?

Add configuration for auto-completion to be enabled by default when installing the CLI via snap or brew.

#### Environment

master 3.8.5

#### How do you propose to implement this?

Look up documentation and update our build scripts to include the auto completion configuration script.

#### How do you propose to test this?

Test locally 

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by rvolosatovs** [comment]
FYI, the Brew part would go here: https://github.com/TheThingsNetwork/lorawan-stack/blob/008bc54e7a9f5169f0ca235f4dbb77deaa92a76e/.goreleaser.yml#L173-L174
