### ISSUE TITLE
Per-application uplink queue buffer size

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2908]
#### Summary

Use the configured buffer size as a max cutoff point, but trim Redis streams to only store non-processed uplinks.
Note, we have a stream per-application
Refs #2904 

#### Why do we need this?

To minimize memory usage for things we don't need to store

#### What is already there? What do you see now?

Currently all applications use the same configurable constant uplink queue buffer size

#### What is missing? What do you want to see?

Perhaps a more reasonable approach would actually be to have an absolute cap on this and dynamically adjust it at runtime.

#### Environment

production

#### How do you propose to implement this?

 maintain the amount of enqueued uplinks and amount of processed uplinks and set stream size to `min(bufferSize, enqueued-processed)` or simply delete the processed entries, but I'm not sure of what the implications of this are on performance - we need to research and profile this. Redis streams are an append-only data structure - so if e.g. the cap is 20k, then we would store last 20k uplinks per application regardless of whether they are processed or not and that's not ideal.

#### How do you propose to test this?

integration testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Indeed we need to optimize this and grow the buffer as needed. 

Also, when we're under memory pressure, we might store to disk.

If that doesn't work, or maybe in general, NS may keep at least the latest join-accept(s) and downlink queue invalidation message(s) so that AS has a valid session to work with.

**Comment by adriansmares** [comment]
We can also `XDEL` after `XACK`, albeit we lose some debugging capacity. Note that this is not entirely kosher and assumes that the NS is the only subscription group (not a shaky assumption).

References https://github.com/redis/redis/issues/6403
References https://github.com/redis/redis/issues/6640

**Comment by rvolosatovs** [comment]
Yes, that's what I meant by
> or simply delete the processed entries

However, it's not the intended use case for `XDEL`, hence why I suggest using `XTRIM` instead

**Comment by rvolosatovs** [comment]
Raising priority to `high`, since this is causing major troubles in production. (in particular, this https://github.com/TheThingsIndustries/lorawan-stack-aws/issues/189#issuecomment-658414583 happened)
