### ISSUE TITLE
Add `mac-settings.mac-commands-in-class-b-c`

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#2909]
#### Summary

Add and respect `mac-settings.mac-commands-in-class-b-c`

#### Why do we need this?

To allow configuring whether NS would send MAC commands in class B/C downlinks or not

#### What is already there? What do you see now?

MAC requests only sent in class A downlink slots

#### What is missing? What do you want to see?

Introduce `mac-settings.mac-commands-in-class-b-c`, which is `false` by default and would allow MAC requests to be sent in class B/C downlinks

#### How do you propose to implement this?

Add field to proto
When the flag is set to `true` - allow bypassing MAC command handling in class B/C

#### How do you propose to test this?

Unit tests, integration testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by rvolosatovs** [comment]
Updated issue according to the changes in https://github.com/TheThingsNetwork/lorawan-stack/pull/3103

**Comment by johanstokking** [comment]
I highly doubt whether we want this. From LoRaWAN 1.0.4, MAC commands are always in class A. Adding discussion so that we don't forget to discuss this before planning it.

**Comment by rvolosatovs** [comment]
> I highly doubt whether we want this. From LoRaWAN 1.0.4, MAC commands are always in class A. Adding discussion so that we don't forget to discuss this before planning it.

Indeed, I also would prefer not doing this, the issue is there to account for this feature being available before https://github.com/TheThingsNetwork/lorawan-stack/pull/3103

**Comment by johanstokking** [comment]
OK, let's close it then.
