### ISSUE TITLE
Ready only access to gateway doesn't work in console

### ISSUE THREAD

**Issue by loganmc10** [TheThingsNetwork/lorawan-stack#2921]
#### Summary

I am trying to grant someone read-only/view access to a gateway via the console, here are the collaborator rights:
![image](https://user-images.githubusercontent.com/848146/87621440-0d83c400-c6de-11ea-99cc-d6a93b17eef3.png)

However, when the user clicks on the gateway, they are just silently redirected to the "Overview" page, without any error message.

#### Steps to Reproduce

Create a gateway collaborator without any write/modify rights. Try to view that gateway in the console using that user.

#### Environment

3.8.7 running on Docker. Chrome for browser. Gateway is a Things Kickstarter Gateway

**Comment by bafonins** [comment]
Hey @loganmc10! Thanks for reporting this. I fixed the issue in https://github.com/TheThingsNetwork/lorawan-stack/pull/2922 and the fix will land in the next release.
