### ISSUE TITLE
Problem with recreating deleted user with same email and username again

### ISSUE THREAD

**Issue by thevirtualdj** [TheThingsNetwork/lorawan-stack#2924]
Problem with recreating deleted user with same email and username again: 
Previously I deleted this user and want to add it again. 
Did I misconfigured again or ? 

![image](https://user-images.githubusercontent.com/102127/87666462-f50cbb80-c768-11ea-9d6a-ca3c3e24706b.png)

**Comment by htdvisser** [comment]
Invalid issue (does not respect issue template).

Duplicate of #604
