### ISSUE TITLE
Device import by manifest

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2938]
#### Summary

Device import format

#### Why do we need this?

For device makers to share a manifest with their customers, which contains all information for The Things Stack to provision the end devices. The manifest acts as a proof of ownership.

The manifest may contain root keys, but these should be wrapped in the (existing) key envelope.

#### What is already there? What do you see now?

Device Template Converter infrastructure to convert files to end device templates. There is support in the Console and CLI to upload files. The Console executes the templates and can create the end devices immediately, the CLI does that too and supports intermediate steps.

#### What is missing? What do you want to see?

1. [x] Design manifest file format (this is TTN JSONPB)
2. [ ] Add RPC to generate a KEK
3. [x] Add CLI commands to templates to create the manifest file: existing device templates
4. [x] Add converter to DTC

#### How do you propose to implement this?

2. Extend API

Apart from this, mostly documentation

#### How do you propose to test this?

Local

#### Can you do this yourself and submit a Pull Request?

Yes, can do, but feel free to pick this up

**Comment by neoaggelos** [comment]
Is this related to/duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/3769?

**Comment by johanstokking** [comment]
Not really; that's more about proof of ownership in files. I'm closing this because we can work with our JSON format, which is well documented.
