### ISSUE TITLE
Pub/Sub integration providers are not retrieved in the Console

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2964]
#### Summary

Pub/Sub integration information page (so the Pub/Sub form when you first enter a Pub/Sub for editing) does not retrieve the provider fields (MQTT/NATS).

References https://github.com/TheThingsIndustries/lorawan-stack-support/issues/89

#### Steps to Reproduce

1. Create a Pub/Sub integration
2. Fill in the provider information (use MQTT for example).
3. Leave the page, go to the Pub/Sub list and select your integration.
4. You won't see the provider information.

#### What do you see now?

The provider information is not visible.

#### What do you want to see instead?

The provider information should be visible.

#### Environment

Cloud Hosted, `3.8.7`

#### How do you propose to implement this?

I've ran some tests and if I use the `provider` field mask as opposed to the two `provider.mqtt` and `provider.nats`, I do get the information. This means:

`https://<edited>.industries/api/v3/as/pubsub/<edited>/brbrbr?field_mask=base_topic,format,provider.nats,provider.mqtt,downlink_ack,downlink_failed,downlink_nack,downlink_push,downlink_queued,downlink_replace,downlink_sent,join_accept,location_solved,uplink_message` - does not retrieve the MQTT provider.

`https://<edited>.eu1.cloud.thethings.industries/api/v3/as/pubsub/<edited>/brbrbr?field_mask=base_topic,format,provider,downlink_ack,downlink_failed,downlink_nack,downlink_push,downlink_queued,downlink_replace,downlink_sent,join_accept,location_solved,uplink_message` - does retrieve the MQTT provider.

#### How do you propose to test this?

Check if the console correctly displays the provider information after leaving and entering the page again.

#### Can you do this yourself and submit a Pull Request?

I can review this.

**Comment by johanstokking** [comment]
I cannot reproduce.

> 4\. You won't see the provider information.

Please explain.

<img width="1792" alt="Screenshot 2020-07-28 at 12 36 00" src="https://user-images.githubusercontent.com/13334001/88655348-ea3e1900-d0ce-11ea-8f3f-a2718558c23f.png">

This contains provider information right?

**Comment by adriansmares** [comment]
For reference, this issue was not reproducible in `v3.9`, so we consider it to be fixed for now.
