### ISSUE TITLE
Application Server panic while running the JavaScript message decoder

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2966]
#### Summary

The Application Server may panic while running the JavaScript message decoder. This is obviously not the intended behavior but tracking the bug has proven to be non-trivial.

References https://github.com/TheThingsIndustries/lorawan-stack/issues/2262

#### Steps to Reproduce

1. Run an uplink through the JavaScript message decoder.
2. Have a particularly bad day.
3. The AS panics and no recovers help it anymore.

#### What do you see now?

As part of the `panic` report, the following frames stand out:
```
1595501567843,runtime: unexpected return pc for go.thethings.network/lorawan-stack/v3/pkg/messageprocessors/javascript.(*host).Decode called from 0x0,ttes/ttes/267215b77e66421386fdaf295b67b1e0
```
```
1595501567843,fatal error: unknown caller pc,ttes/ttes/267215b77e66421386fdaf295b67b1e0
```

#### What do you want to see instead?

No panic, obviously.

#### Environment

Cloud Hosted, `3.8.7`

#### How do you propose to implement this?

I don't have a good reproduction for this, so no good fix for this. 

Go `1.14` introduced [some optimizations](https://go-review.googlesource.com/c/go/+/200081) regarding `defers` . A follow up to these changes has been https://github.com/golang/go/issues/37664, which describes an issue that looks like ours: a `defer`/`recover` chain, which we do have as part of the JavaScript message processor:

https://github.com/TheThingsNetwork/lorawan-stack/blob/f53fefca326a01ebc9bf757113ae2f209c1013d3/pkg/scripting/javascript/javascript.go#L61-L81
(this sequence is used for execution time limits, and it's encouraged by `otto` - https://github.com/robertkrimen/otto#halting-problem)

The (temporary) fix there was to disable optimizations, by compiling the binaries using `-gcflags="all=-N"`. Note that we can make this part of `goreleaser`:
```diff
diff --git a/.goreleaser.yml b/.goreleaser.yml
index 4bf53dbb4..7070cee86 100644
--- a/.goreleaser.yml
+++ b/.goreleaser.yml
@@ -16,6 +16,8 @@ builds:
     - -X go.thethings.network/lorawan-stack/v3/pkg/version.BuildDate={{.Date}}
     - -X go.thethings.network/lorawan-stack/v3/pkg/version.GitCommit={{.ShortCommit}}
     - -X go.thethings.network/lorawan-stack/v3/pkg/version.TTN={{.Version}}
+    gcflags:
+      - all=-N
     env:
       - CGO_ENABLED=0
     goos:
```

https://github.com/golang/go/issues/37664 has been closed and fixed as part of `go 1.14.1`, and `3.8.7` has been compiled with `go 1.14.5`, which means that we are probably encountering another issue. But https://github.com/golang/go/issues/35158 claims some remnants still exist, so I'm not sure if it's fully fixed - if we encounter this crash too often we may want to experiment with optimizations-disabled builds. https://github.com/prysmaticlabs/prysm/issues/5131#issuecomment-601838539 is another reference.

#### How do you propose to test this?

This is a heisenbug. Unless we have a good reproduction system we cannot really test it reliably. 

#### Can you do this yourself and submit a Pull Request?

Yes, when additional information becomes available (more crashes, more details from the Go team due to someone else encountering this).

**Comment by johanstokking** [comment]
References #2670; this problem might disappear when we switch from `otto` to `goja`
