### ISSUE TITLE
Update base Docker image

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#2967]
#### Summary

We should upgrade the Docker base image of our stack to `alpine:3.12` (or whatever the latest version is at the time of fixing).

#### Why do we need this?

`v3.10` is currently receiving only security bug fixes until `2021-05-01`. While definitely not a high priority given the large time span, I'd still wish to rule out any bugs related to the base image.

#### What is already there? What do you see now?

`Dockerfile` is using `alpine:3.10`.

#### What is missing? What do you want to see?

`Dockerfile` should be using `alpine:3.12`.

#### Environment

`3.8.7`

#### How do you propose to implement this?

Upgrade the version in the `Dockerfile`.

#### How do you propose to test this?

Run a `3.12` build in a staging environment.

#### Can you do this yourself and submit a Pull Request?

Yes. cc @htdvisser

**Comment by johanstokking** [comment]
Triaging this issue costs more time than doing it.
