### ISSUE TITLE
Alias EndDevice flags for LoRaWAN 1.0.x terms

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#298]
**Summary:** 

We should try to create flag aliases for EndDevice fields that have different names in LoRaWAN 1.0.x and LoRaWAN 1.1, such as AppEUI (instead of JoinEUI), NwkSKey instead of FNwkSIntKey.

**Why do we need this?**

These flag aliases would help users transition from LoRaWAN 1.0.x to 1.1.

**What is already there? What do you see now?**

The `--join-eui` and `--f-nwk-s-int-key` flags.

**What is missing? What do you want to see?**

`--app-eui` and `--nwk-s-key` flags that inform (warn) users about the correct flag names, but still set those values.

**How do you propose to implement this?**

The `pflag` library doesn't seem to have builtin support for aliases, so we may have to implement this by hand.

**What can you do yourself and what do you need help with?**

I can do this.

**Comment by johanstokking** [comment]
Would be an alias for **F**NwkSIntKey. The confusion is real.

**Comment by htdvisser** [comment]
Updated description
