### ISSUE TITLE
Show all event info in expanded event details

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#2980]
#### Summary
The expanded details section of the console currently only shows the `data` prop of the event. However, there is other relevant data in the root of the event object that should be shown too.

#### Why do we need this?
The user should be able to inspect all available data of an event if he/she wishes to

#### What is already there? What do you see now?
Only the `data` prop of the event object being shown

#### What is missing? What do you want to see?
The whole event object being shown instead.

@bafonins @johanstokking has there been any discussion that led to this decision that I might have missed?

#### Environment
v3.8.x

#### How do you propose to implement this?
Just change the details component to show `event` instead of `event.data`

#### How do you propose to test this?
Trivial.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by johanstokking** [comment]
> @bafonins @johanstokking has there been any discussion that led to this decision that I might have missed?

Not that I'm aware of. More information is always better. What do you have in mind to show?

**Comment by kschiffer** [comment]
We can just show the whole event object instead of just `event.data`. Then we can also make all regular events expandable instead of just the ones that have a `data` prop.
