### ISSUE TITLE
PubSub/MQTT - "Provider `<nil>` is not implemented"

### ISSUE THREAD

**Issue by ZeroSum24** [TheThingsNetwork/lorawan-stack#2985]
#### Summary

We've been working to have the TTN applications subscribe to an external MQTT server. This is because we require different QoS levels than the internal TTN MQTT component allows.

There has been an issue when setting the PubSub field for TTN Applications, with the same error resulting from use of either the HTTP API or the CLI. This error is presented on the console after the pubsub has been successfully set (a 'Set pubsub' message is presented on the console) with a repeated error being presented - 'Provider `<nil>` is not implemented'.

#### Steps to Reproduce

1. Create a TTN application
2. Link some devices with the application and have them send data to it
3. Use either the CLI or HTTP/gRPC API to set the pubsub config of the application to an external MQTT server
4. Look at the Applications -> Data screen on the console and see the resulting issue
 

**Console command:**

> ttn-lw-cli applications pubsubs set --application-id bonnyrigg2 --pubsub-id example-name —-mqtt --mqtt.server-url mqtt://example-domain:8883 --base-topic bonnyrigg2 --mqtt.publish-qos AT_LEAST_ONCE

**HTTP API (python) command:**

> 		request = {
> 			'pubsub': {
> 				'ids': {'application_ids': {'application_id': "bonnyrigg2"},
> 				        'pub_sub_id': pubsub_id},
> 				'mqtt': {
> 					'server_url': mqtt_server_address,
> 					'publish_qos': qos_level,
> 					'use_tls': tls_enabled,
> 					'username': username,
> 					'password': password,
> 				},
> 				'base_topic': base_topic
> 			}
> 		}

#### What do you see now?

The TTN console error message has been attached to illustrate the provider error in the application. I've also attached the CLI and HTTP output following pubsub setting in case this is helpful too.

**TTN Console Error Message:**
![TTN Console Example](https://user-images.githubusercontent.com/20759118/88551992-6bd46f00-d01b-11ea-9a55-6116c0912668.png)

**CLI Command + Output:**
![CLI Screenshot](https://user-images.githubusercontent.com/20759118/88553516-46e0fb80-d01d-11ea-9623-914be75d125f.png)

**HTTP Response Code + Output:**
![HTTP Response Screenshot](https://user-images.githubusercontent.com/20759118/88553804-9a534980-d01d-11ea-8fe9-424895fe4ea5.png)

#### What do you want to see instead?

It seems there is no reference in the [docs](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.9/api/api.md#ttn.lorawan.v3.ApplicationPubSub) to a 'provider-id' field. Therefore a fix for the issue would be ideal and/or an update to the documentation to help with clarity please.

#### Environment

The TTN stack and CLI versions are both set to 3.8.7

#### How do you propose to implement this?

At a guess, the error message (raised in this [file](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.9/pkg/applicationserver/io/pubsub/provider/provider.go)) suggests the issue is because this field has not been set. After some experimentation setting this field as part of other object like the 'id' field or the 'mqtt' field does not help.

It seems like removing the requirement for this field might help, but otherwise I don't know.

#### How do you propose to test this?

Retry the process to recreate the issue and evaluate whether pubsub messages are being sent to the mqtt server (by subscribing to the topic, and if not possible using netcat to listen for requests). 

#### Can you do this yourself and submit a Pull Request?

No I wish I could, your help would be very much appreciated with resolving this issue!

##### Other Questions?

As a complete aside from this issue, am I right in thinking the TTN PubSub interface is designed to allow the TTN app to publish to more than one pubsub?

**Comment by adriansmares** [comment]
Hello, thank you for your report.

> This error is presented on the console after the pubsub has been successfully set (a 'Set pubsub' message is presented on the console) with a repeated error being presented - 'Provider <nil> is not implemented'.

This error occurs when the pub/sub provider (MQTT/NATS) settings are not saved correctly. It means that the provider settings are non-existing basically.

> ttn-lw-cli applications pubsubs set --application-id bonnyrigg2 --pubsub-id example-name —-mqtt --mqtt.server-url mqtt://example-domain:8883 --base-topic bonnyrigg2 --mqtt.publish-qos AT_LEAST_ONCE

If you look at `—-mqtt` you will see that the first dash is actually `—` and not `-`. If you use two dashes, `--`, you get:
```
{
  "ids": {
    "application_ids": {
      "application_id": "app1"
    },
    "pub_sub_id": "example-name"
  },
  "created_at": "2020-07-29T09:53:25.341161291Z",
  "updated_at": "2020-07-29T09:53:54.052873161Z",
  "mqtt": {
    "server_url": "mqtt://example-domain:8883",
    "publish_qos": "AT_LEAST_ONCE"
  },
  "base_topic": "bonnyrigg2"
}
```
Using the cursed dash, I do reproduce your issue (no `mqtt` reference):
```
{
  "ids": {
    "application_ids": {
      "application_id": "app1"
    },
    "pub_sub_id": "example-name"
  },
  "created_at": "2020-07-29T09:53:25.341161291Z",
  "updated_at": "2020-07-29T09:53:25.341161291Z",
  "base_topic": "bonnyrigg2"
}
```

> HTTP API (python) command:

While the body of the `pubsub` object seems correct, you are sending an incomplete request. The service you are using is [ApplicationPubSubRegistry](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.9/api/api.md#service-applicationpubsubregistry), specifically the `Set` method (see the HTTP bindings). The documentation there mentions that the request body should be an [SetApplicationPubSubRequest](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.9/api/api.md#message-setapplicationpubsubrequest) message - your request body misses the `field_mask` field, which specifies which fields of the `pubsub` object you are updating. Without specifying the field mask, the server considers that you are not updating any* fields. 

While this is not any way a good substitute for a more clear documentation, I'd recommend you check out the requests that the Console sends to the server. Please let us know if fixing the dash and adding the field mask fixes your issues.
