### ISSUE TITLE
When clicking All (Admin) on the gateway section I get an unexpected error

### ISSUE THREAD

**Issue by wienke** [TheThingsNetwork/lorawan-stack#2994]
<img width="743" alt="Schermafbeelding 2020-07-28 om 16 07 33" src="https://user-images.githubusercontent.com/3216553/88770979-dc47d100-d17e-11ea-9466-03acad09e9b4.png">

**Comment by htdvisser** [comment]
Also refs #2993

**Comment by bafonins** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/2993
