### ISSUE TITLE
Improve `lorawan_phy_version` validation in NS

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3026]
#### Summary

Allow setting `lorawan_phy_version` only with matching `lorawan_version`. See https://github.com/TheThingsNetwork/lorawan-stack/issues/2784#issuecomment-648735723.

#### Why do we need this?

See https://github.com/TheThingsNetwork/lorawan-stack/pull/3017#issuecomment-669071434

#### What is already there? What do you see now?

No validation. The users can use any combination of `lorawan_version` and `lorawan_phy_version`.

#### What is missing? What do you want to see?

1. Enforced server side validation for `lorawan_phy_version` as mentioned in [this comment](https://github.com/TheThingsNetwork/lorawan-stack/issues/2784#issuecomment-648735723) in NS. @rvolosatovs 
2. Client side validation in the device general settings page. @bafonins 

#### Environment

v3.9

#### How do you propose to implement this?

NS - @rvolosatovs 
Console implementation similar to https://github.com/TheThingsNetwork/lorawan-stack/pull/3017

#### How do you propose to test this?

Test all available `lorawan_versions`

#### Can you do this yourself and submit a Pull Request?

Console part - yes
NS part - @rvolosatovs

**Comment by rvolosatovs** [comment]
NS part is done in #3146
