### ISSUE TITLE
TTN returns HTTP status 400 (bad request) when trying to add new application or device

### ISSUE THREAD

**Issue by Nihad32** [TheThingsNetwork/lorawan-stack#3083]
#### Summary
I'm trying to add application/device to The Things Stack from my  .Net Core 3 web app using HTTP post but I get 400 status code.
`ContentType = "application/json";`
Bearer token is used for authorization with all current and future rights.
`Method = "POST";`
`URL = "https://ex.example.com/api/v3/users/admin/applications"` as instructed per [THIS](https://thethingsstack.io/reference/api/application/)

JSON i'm posting =
```
{
   "application":
      {
      "name":"appName",
      "ids":{"application_id":"appID"},
      "attributes":{},
      "description":"testDesc"},
   "collaborator":
      {
         "user_ids":
         {"user_id":"admin","email":"info@web.com"}
      }
}
```
for JSON formatting I was using [THIS](https://thethingsstack.io/reference/api/application/) source
I also tried [THIS](https://www.thethingsnetwork.org/docs/applications/manager/api.html) but no success.

I got the same error when trying to add new device over HTTP POST

...

#### Steps to Reproduce

1. host The Things Stack on CentOS 7
2. create new .Net Core 3 app
3. 
```
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://ex.example.com/api/v3/users/admin/applications");
            request.Method = "POST";
            request.PreAuthenticate = true;
            request.Headers.Add("Authorization", "bearer *token goes here it's set in my code*");
            request.ContentType = "application/json";
var data = Encoding.ASCII.GetBytes(JsonString);
            request.ContentLength = data.Length;
            using (var stream = request.GetRequestStream())
            {
                stream.Write(data, 0, data.Length);
            }
using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
            {
                Stream dataStream = response.GetResponseStream();
                StreamReader reader = new StreamReader(dataStream);
                test = reader.ReadToEnd();
                reader.Close();
                dataStream.Close();
            }
```
4. Run
5. Get error: System.Net.WebException: 'The remote server returned an error: (400) Bad Request.'

**Comment by neoaggelos** [comment]
Hi @Nihad32

The JSON you are posting is not correct. See a curl example:

```
$ curl https://ex.example.com/api/v3/users/admin/applications -XPOST -H "Authorization: Bearer $API_KEY" -d '{"application":
      {
      "name":"appName",
      "ids":{"application_id":"my-application-id"},
      "attributes":{},
      "description":"testDesc"}
     }'
```

Also note: The `application_id` cannot contain underscores or capital letters.
