### ISSUE TITLE
Create generic docs on UDP packet forwarder

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#3085]
#### Summary
Create generic documentation for UDP packet forwarder.

#### Why do we need this ?
In case people use a gateway we don't have documentation for, we need a generic piece of documentation which among others elaborates on how to get the globalconf.json file. 

#### What is already there? What do you see now?
Only specific gateway documentation, and generic documentation on Basics Station.

**Comment by benolayinka** [comment]
Closed by https://github.com/TheThingsIndustries/lorawan-stack-docs/commit/99c308bf0a90bb0c240d26626038ff4864a314ad
