### ISSUE TITLE
Enable test generation for customized protos

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#31]
**Summary:** 

We should enable test generation for protos, for which we define `MarshalJSON`, `MarshalText` and similar

**Why do we need this?**

Custom marshaling logic we add may break things.

**What is already there? What do you see now?**

No tests

**What is missing? What do you want to see?**

Tests for customized protocol buffers

**How do you propose to implement this?**

Enable tests in `gogoproto`, for customized protocol buffers

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1104 by @rvolosatovs

**Comment by htdvisser** [comment]
I think this is already there (in `pkg/ttnpb/ttnpb_encoding_test.go`).
