### ISSUE TITLE
Integrations with MQTT Client

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#3106]
#### Summary
Document commonly used MQTT clients

#### Why do we need this ?
Make TTS easy to integrate with any platform.

#### What is already there? What do you see now?
Generic MQTT info: https://enterprise.thethingsstack.io/integrations/mqtt/

#### What is missing? What do you want to see?
Documentation on:
- [x] HiveMQ (see [YouTube video](https://www.youtube.com/watch?v=Zra18wuSGwY) for reference)
- [x] Eclipse Paho
- [x] Eclipse Mosquitto
- [x] MQTTBox

#### How do you propose to document this?
TBD by @nejraselimovic 

#### Can you do this yourself and submit a Pull Request?
@adriansmares any other MQTT clients you know that are commonly used?

**Comment by adriansmares** [comment]
I use [MQTT.fx](https://mqttfx.jensd.de/) but it's quite niche so low priority.
