### ISSUE TITLE
Packetbroker agent flaky test

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3115]
#### Summary

`TestForwarder` test seems to be flaky.

#### Steps to Reproduce

bad luck I guess 🤷‍♂️

#### What do you see now?

```
 --- FAIL: TestForwarder (0.38s)
    --- FAIL: TestForwarder/Uplink (0.13s)
        --- FAIL: TestForwarder/Uplink/0 (0.13s)
            agent_test.go:314: Expected uplink message from Forwarder
FAIL
coverage: 11.1% of statements
FAIL    go.thethings.network/lorawan-stack/v3/pkg/packetbrokeragent     0.438s
```

#### What do you want to see instead?

The test should not accidentally fail and then pass with no changes.

#### Environment

v3.9.1

#### Can you do this yourself and submit a Pull Request?

nope

**Comment by johanstokking** [comment]
This one came back: https://github.com/TheThingsIndustries/lorawan-stack/pull/2522/checks?check_run_id=1734976443#step:14:180
