### ISSUE TITLE
ttnctl snap does not open browser to log in

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#3122]
#### Summary

I installed ttnctl on linux using the snap commands.

When trying to log in using ttnctl, an error and a warning is printed. The system default browser does not open to allow me to log in.

#### Steps to Reproduce

Clean Ubuntu 20.04 install. Then run the following commands in a terminal.
```
$ sudo snap install ttn-lw-stack
$ sudo snap alias ttn-lw-stack.ttn-lw-cli ttn-lw-cli
$ ttn-lw-cli use jpmeijers.eu1.cloud.thethings.industries --user
$ ttn-lw-cli login
```

#### What do you see now?

```
$ ttn-lw-cli login
 ERROR Please login with the login command     
  INFO Opening your browser on https://jpmeijers.eu1.cloud.thethings.industries/oauth/authorize?client_id=cli&redirect_uri=local-callback&response_type=code
  WARN Could not open your browser, you'll have to go there yourself error=fork/exec /usr/bin/xdg-open: permission denied
  INFO After logging in and authorizing the CLI, we'll get an access token for future commands.
  INFO Waiting for your authorization...
```

#### What do you want to see instead?

The system default browser should open and load the login page.

#### Environment

Ubuntu 20.04
Chrome

#### How do you propose to implement this?

...

#### How do you propose to test this?

Use a clean Ubuntu 20.04 VM and follow the commands above. If a browser window opens that loads the login page, the test passes.

#### Can you do this yourself and submit a Pull Request?

No, not sure if the issue is with ttnctl, snap permissions, or system settings.

**Comment by neoaggelos** [comment]
Hi @jpmeijers

This is an issue with snap permissions. The `ttn-lw-stack` snap is installed in strict confinement, which means that it cannot call any external executable (including `xdg-open`, which would open the default browser).

You can still open the link on any browser to login.

NOTE 1: If you are running `ttn-lw-cli` on a remote VM (and not your local machine), you might need `ttn-lw-cli login --callback=false` 

NOTE 2: `ttnctl` is the cli for the V2. The CLI for the V3 is called `ttn-lw-cli`

**Comment by jpmeijers** [comment]
Trying the snap package again today, and running into a similar issue:
```
jpmeijers@jpmeijers-XPS13-9333:~$ sudo snap install ttn-lw-stack
ttn-lw-stack 3.22.1 from The Things Network (rvolosatovs-ttn) installed
jpmeijers@jpmeijers-XPS13-9333:~$ sudo snap alias ttn-lw-stack.ttn-lw-cli ttn-lw-cli
Added:
  - ttn-lw-stack.ttn-lw-cli as ttn-lw-cli
jpmeijers@jpmeijers-XPS13-9333:~$ ttn-lw-cli login
open /home/jpmeijers/.ttn-lw-cli.yml: permission denied
```

Edit:
I've deleted my `.ttn-lw-cli` from my home directory and ran the login command again:
```
jpmeijers@jpmeijers-XPS13-9333:~$ ttn-lw-cli use eu1.cloud.thethings.network
INFO	Configuring for The Things Stack Community Edition	{"cluster_id": "eu1"}
INFO	Set OAuth Server address	{"address": "https://eu1.cloud.thethings.network/oauth"}
INFO	Set Identity Server gRPC address	{"address": "eu1.cloud.thethings.network:8884"}
error:cmd/ttn-lw-cli/commands:fail_write (failed to write `.ttn-lw-cli.yml`)
    file=.ttn-lw-cli.yml
    correlation_id=837266af6e944508ba56ea8bc61bdc2d
--- open .ttn-lw-cli.yml: permission denied
```
ttn-lw-cli still tries to access the config file in a location that it doesn't have permissions for.

**Comment by jpmeijers** [comment]
Duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/1670
Related to https://github.com/TheThingsNetwork/lorawan-stack/issues/523
