### ISSUE TITLE
Gateway device MQTT integration for subscribing gateway status

### ISSUE THREAD

**Issue by singyiu** [TheThingsNetwork/lorawan-stack#3132]
#### Summary

Enable gateway device MQTT integration, such that organization user can subscribe to the MQTT broker and get gateway status update of all the gateway devices that the organization owns.

#### Why do we need this?

To provide an easy way for monitoring hundreds of gateway devices in the field programmatically.

#### What is already there? What do you see now?

With existing implementation, the gateway MQTT API is meant for compliant MQTT gateways to connect but is not meant for fetching information. The support team suggest us to use the gateway events instead. Ref: https://enterprise.thethingsstack.io/v3.8.7/getting-started/events/

#### What is missing? What do you want to see?

The suggested approach of using the gateway event is not deal as the cli tools is not designed for programmatic access. 
We prefer to have similar MQTT integration for gateway devices, similar to the end devices.

#### Environment

...

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by KrishnaIyer** [comment]
1. MQTT is not designed as monitoring protocol and as such is not very useful for this action. 
2. We are working on ways to make the events more easily accessible/scalable.

Since we already have internal issues for this, closing this now.
