### ISSUE TITLE
Include created_at and updated_at when setting entities

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#315]
**Summary:** 

Include `created_at` and `updated_at` when setting entities.

**Why do we need this?**

To make behavior consistent when getting entities.

Also Identity Server fills them out when setting entities already.

**What is already there? What do you see now?**

When setting a device, for example:

```
$ ttn-lw-cli dev set test-app simulation3 --supports-class-c=false
{
  "ids": {
    "device_id": "simulation3",
    "application_ids": {
      "application_id": "test-app"
    },
    "dev_eui": "4200000000000002",
    "join_eui": "4200000000000000"
  },
  "created_at": "0001-01-01T00:00:00Z",
  "updated_at": "0001-01-01T00:00:00Z"
}
```

These values are blanked out.

**What is missing? What do you want to see?**

The `created_at` and `updated_at` fields filled out.

**How do you propose to implement this?**

Add the fields, like `ids`.

**Environment:**

Any.

**What can you do yourself and what do you need help with?**

Review.

**Comment by htdvisser** [comment]
What value should the CLI display in the response? Does it make sense to take the oldest `CreatedAt` and newest `UpdatedAt`?

**Comment by johanstokking** [comment]
I guess this is very intuitive right?

- on create, `created_at` and `updated_at` are the same server time
- on update, `created_at` doesn't change and is the original value, and `updated_at` is the new server time

**Comment by htdvisser** [comment]
My point was that with `EndDevice`s, we have a `created_at` and `updated_at` in all of the registries, and we can only display one of those values in the CLI response, because it merges the responses from all registries into a single `EndDevice` struct.

**Comment by johanstokking** [comment]
Ah, I understand, yeah good suggestion.

**Comment by htdvisser** [comment]
Created issue for that: https://github.com/TheThingsNetwork/lorawan-stack/issues/338
