### ISSUE TITLE
Add sorting functionality to list requests

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#316]
**Summary:** 
RPC call returning a list should support a sort option, to sort by a specific field either ascending or descending.

**Why do we need this?**
Sorting only by the id is not always desirable. Console users will likely also want to sort by creation date or something else.

**What is already there? What do you see now?**
The list protos already have an interface for this:
```
  // Order the results by this field path (must be present in the field mask).
  // Default ordering is by ID. Prepend with a minus (-) to reverse the order.
  string order = 3;
  // Limit the number of results per page.
  uint32 limit = 4;
  // Page number for pagination. 0 is interpreted as 1.
  uint32 page = 5;
```

**What is missing? What do you want to see?**
However, setting the sort value does not appear to have any effect yet. (While limit and page values work as expected)

**How do you propose to implement this?**
@htdvisser 

**Environment:**
Making requests via the http bridge of gRPC.

**What can you do yourself and what do you need help with?**
Help.

**Comment by htdvisser** [comment]
Implementation wise this would involve translating the field mask path (which is the value of the `order` field) to the database column name and passing that to the SQL `ORDER` instead of `ids`.

**Comment by johanstokking** [comment]
Pushing to Backlog. Let's consider this again based on user feedback

**Comment by rish-c** [comment]
Sorting gateways would be good to add in the console. Possible fields could be
- Connected / Not connected
- Data added
- Owner
- labels (location, site, indoor, outdoor etc.)

cc @kschiffer

**Comment by htdvisser** [comment]
It's relatively easy to implement sorting on:

- ID
- EUIs (Gateways, End Devices)
- Name
- Created At

It's more work to implement sorting on:

- Attributes

It's currently **not** possible to sort on:

- Owner: we don't have the concept of owner in v3. We have (multiple) members with (different) rights and we can't sort on those.
- Connected (Gateways): This is not known by the Entity Registry.
- Last Seen (Gateways, End Devices): This is not known by the Entity Registry.

**Comment by kschiffer** [comment]
Frontend-wise it's more or less a matter of re-activating our logic for sorting in our list views, so this is mostly blocked on the backend side.
