### ISSUE TITLE
Improve documentation for AS and GS services and methods

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#3166]
#### Summary

Subtask of #252 

From the umbrella issue:

- Improved documentation on methods (for example, explaining that As.SetLink does not return whether the actual linking is successful, perhaps explaining how many resources a method call consumes)
- Improved documentation on services (for example, being more clear about which components expose the services, which fields are accepted).

#### What is already there? What do you see now?

https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.9/api/applicationserver.proto#L60

#### What is missing? What do you want to see?

See https://github.com/TheThingsNetwork/lorawan-stack/pull/3015/files for reference

#### Can you do this yourself and submit a Pull Request?

No. @johanstokking please take a little time to share your knowledge :) It's probably best to just bite the bullet and get this one out of the way quickly

**Comment by johanstokking** [comment]
OK, so this is specifically AS and proto documentation?
