### ISSUE TITLE
Improve documentation for configuration_services and end_device protos

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#3167]
#### Summary

@rvolosatovs  , please look through these API protos and add descriptions where they are missing. It looks like many of the messages need an additional description.

`/api/configuration_services.proto`
`/api/end_device.proto`

Sub task of #252

See this PR for a gold standard API comments reference -> https://github.com/TheThingsNetwork/lorawan-stack/pull/3181/files#diff-aa11ad1a94ecc7c1db3ead25d3372bdd39c6a25dd998a2902da6e4c1cb3b8fdbR129

For example,

- Improved documentation on messages (for example, explaining what the effects of field masks are in UpdateXXXRequest messages)
- Improved documentation on methods (for example, explaining that As.SetLink does not return whether the actual linking is successful, perhaps explaining how many resources a method call consumes)
- Improved documentation on services (for example, being more clear about which components expose the services, which fields are accepted by the different EndDevice registries).
- Improved documentation on events that are published by components (for example, explaining that AS reports `as.link.start`, `as.link.stop` and `as.link.fail`, GS reports similar events, etc)

**Comment by johanstokking** [comment]
> No. @rvolosatovs please take a little time and just get this out of the way quickly

@benolayinka you can do this yourself. Please let us know if you need help!

**Comment by benolayinka** [comment]
Reassigning to @rvolosatovs https://github.com/TheThingsNetwork/lorawan-stack/issues/252#issuecomment-729164178
