### ISSUE TITLE
Support a master MQTT account that can subscribe all topics

### ISSUE THREAD

**Issue by garylee008** [TheThingsNetwork/lorawan-stack#3184]
#### Summary

request to setup a master MQTT account that can subscribe all topics in an on-perm installation
...

#### Why do we need this?

To enable an application with admin rights to read all MQTT topics
...

#### What is already there? What do you see now?

can subscribe to topics on a per application basis only
...

#### What is missing? What do you want to see?

Allow user with admin rights to read all MQTT topics 
...

#### Environment

...

#### How do you propose to implement this?

add rights to link to Network Server traffic (uplink and downlink) of all application owned by Organization using Organization Login and API key
...

#### How do you propose to test this?

Console
...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by johanstokking** [comment]
Please configure the MQTT server pub/sub integration to achieve this. This way, the Application Server is a client to an MQTT server, like Mosquitto, HiveMQ, AWS IoT MQTT, CloudMQTT, etc, and you can control access there. See https://thethingsstack.io/integrations/mqtt/
