### ISSUE TITLE
Add application_name in the payload from mqtt

### ISSUE THREAD

**Issue by cnoork** [TheThingsNetwork/lorawan-stack#3189]
#### Summary
With v3 I miss the application name. In v2 I could get it from the topic but now there is only a id. We use the name to do some identivication from the sensors.

...

#### Why do we need this?
We use the name for identify the sensor type

...

#### What is already there? What do you see now?
I see now only the id in msg.payload.end_device_ids.application_id

...

#### What is missing? What do you want to see?
I would like that there is also a msg.payload.end_device_ids.application_name

...

#### Environment
It is within tti v3

...

#### How do you propose to implement this?
Add the application name in the payload

...

#### How do you propose to test this?
This could be seen with every message

...

#### Can you do this yourself and submit a Pull Request?
no, I can only test if it is added

...

**Comment by johanstokking** [comment]
We're not sending the human friendly name as part of every uplink message. The reason is that it adds lots of redundant data, it's not unique and it may change over time. To identify an application, please use the application ID because that is stable.
