### ISSUE TITLE
Automated end-to-end testing

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#3202]
#### Summary

Automated end-to-end testing.

#### Why do we need this?

Regression testing in CI.

#### What is already there? What do you see now?

- Automated frontend testing: https://github.com/TheThingsNetwork/lorawan-stack/issues/2605
- CLI for simulating join-requests and uplink messages

#### What is missing? What do you want to see?

Scripting common use cases, i.e. creating a gateway, application and device in the Console, sending a simulated join-request via CLI, asserting events displayed in Console, scheduling downlink message, asserting that the downlink message arrives as response to a simulated uplink message via CLI, etc.

#### Environment

CI

#### How do you propose to implement this?

Not sure, please provide input

#### How do you propose to test this?

CI

#### Can you do this yourself and submit a Pull Request?

No

**Comment by rvolosatovs** [comment]
Adding me and @KrishnaIyer as we discussed this on last sync

**Comment by rvolosatovs** [comment]
Refs #3606

**Comment by KrishnaIyer** [comment]
Refs https://github.com/TheThingsIndustries/lorawan-stack/issues/2652

**Comment by KrishnaIyer** [comment]
This needs to get moving. I've bumped https://github.com/TheThingsNetwork/lorawan-stack/issues/3202 to `v3.12.1`. I'll do the necessary groundwork and list the results here.

I'll then create issues per function and assign members from this list so we can make some progress.

**Comment by kschiffer** [comment]
Key issue to move on with this is this one: #3611 

I started working on that already but had to stop for other issues.

**Comment by johanstokking** [comment]
What is the status here?

**Comment by KrishnaIyer** [comment]
Replaced by https://github.com/TheThingsIndustries/lorawan-stack/issues/2742
