### ISSUE TITLE
Add windows commands to documentation

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#3204]
#### Summary

We provide windows binaries, so we should also provide windows friendly instructions where it's relevant

#### What is already there? What do you see now?

Just unix

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by nejraselimovic** [comment]
@benolayinka Since I encountered no issues in executing commands from [getting-started](https://thethingsstack.io/getting-started/installation/), I guess you can close this issue? Btw, I used PowerShell all the way, not cmd
