### ISSUE TITLE
Limit application downlink queue size

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#3220]
#### Summary

Limit application downlink queue size

#### Why do we need this?

To avoid that there are too many downlink messages queued in the registry

#### What is already there? What do you see now?

- No limit on number of stored application downlink messages in the queue
- No limit on the number of downlink messages that you can enqueue

#### What is missing? What do you want to see?

- Limit the number of messages that are stored (configurable per deployment)
- Limit the number of messages in a downlink queue replace or push request

#### How do you propose to implement this?

- Check stored number of downlink messages. For migration, if this exceeds the maximum, take only the first N
- Add API level limit on number of downlink messages that can be pushed or replaced

#### How do you propose to test this?

Unit testing

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by rvolosatovs** [comment]
closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/3236
