### ISSUE TITLE
FCnt gap too high message misleading in case of retransmission

### ISSUE THREAD

**Issue by pdubois22** [TheThingsNetwork/lorawan-stack#325]
**Summary:** 
When the device send multiple times the same message (retransmission), the error message is FCnt gap too high when in fact it should be FCnt too low, skipping

**Steps to Reproduce:** 
get a device which transmit multiple times

**What do you see now?**
FCnt gap too high

**What do you want to see instead?**
FCnt too low or any other message specifiying that the message is dropped per the LoraWan spec. (something like "FCnt identical, ignoring retransmission..." ?)

**How do you propose to implement this?**
pkg/networkserver/grpc_gsns.go:195 should be 

`		case !supports32BitFCnt, fCnt >= dev.matchedSession.LastFCntUp, fCnt == 0:
`
instead of 

`		case !supports32BitFCnt, fCnt > dev.matchedSession.LastFCntUp, fCnt == 0:
`
for a 32 bit device, and I guess line 196 should be adjusted too for a 16 bit.

Ideally if the message could / should be adjusted, l 221 should be changed too (I am not a golang dev - not sure about the code style)

```
			if fCnt == dev.matchedSession.LastFCntUp {
				logger.Debug("FCnt identical, ignoring retransmission...")
				continue outer
			} else if fCnt < dev.matchedSession.LastFCntUp {
				logger.Debug("FCnt too low, skipping...")
				continue outer
			}

```

**Environment:**
any

**What can you do yourself and what do you need help with?**

**Comment by rvolosatovs** [comment]
The log message is now fixed:
https://github.com/TheThingsNetwork/lorawan-stack/blob/3baedc7a26d8c175b7b4b24862f8d39be23874a8/pkg/networkserver/grpc_gsns.go#L219

Actual support for retransmissions will be added in #356
