### ISSUE TITLE
Provide a static error HTML template for non-react handled routes

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3261]
#### Summary
Following up from https://github.com/TheThingsNetwork/lorawan-stack/issues/233 we still need a Go HTML template that will render a generic and static error page for all errors that are not in Console or OAuth app context. See also: https://github.com/TheThingsIndustries/lorawan-stack/issues/1315#issuecomment-440656553

#### Why do we need this?
To display proper error pages for backend errors that are not in the scope of Console or OAuth app. E.g. https://github.com/TheThingsIndustries/lorawan-stack/issues/2268

#### What is already there? What do you see now?
Error page designs and error boundaries that render error views for routes that are handled by our frontend react apps.

#### What is missing? What do you want to see?

Templates that render static HTML/CSS for any route that is not handled by our frontend react apps.

#### How do you propose to implement this?
Implementing the design that we currently use for the react apps as static HTML/CSS template that renders for error responses.

#### How do you propose to test this?
Manual.

#### Can you do this yourself and submit a Pull Request?
Yes but anyone please feel free to pick up.

**Comment by kschiffer** [comment]
Blocking: https://github.com/TheThingsIndustries/lorawan-stack/issues/1813

**Comment by kschiffer** [comment]
@pierrephz We need a generic error page for TTS. I think you designed something like that already a while back. Can you post a recent design here? Such design should be pretty simple and contain:

*   Text for the error title
*   Text for resolution instructions
*   Some icon/visual signalling "error", with proper TTS branding
*   A link leading back to a homepage
*   A link to documentation
*   A link to support (Enterprise)

**Comment by NicolasMrad** [comment]
@kschiffer can you please advise on how this error page will look like?

**Comment by kschiffer** [comment]
Yes, so we should essentially use the same design that we currently use for the react handled errors (`<FullViewError />`):

![image](https://user-images.githubusercontent.com/5710611/133310583-38ee119c-bd53-48e1-8d5b-0fe93e33a380.png)

We can use a simplified footer without the buttons on the right. Also, support buttons cannot be rendered in these cases, since the config is only available in the Account app / Console.
