### ISSUE TITLE
Make JS aware of JoinEUI ranges

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#327]
**Summary:** 

Make the Join Server aware of its JoinEUI ranges and make this available to clients.

**Why do we need this?**

To validate the created devices and inform clients which JoinEUIs are supported.

**What is already there? What do you see now?**

No information about JoinEUIs for the JS.

**What is missing? What do you want to see?**

Reporting of;
- JoinEUI ranges (`[]types.EUI64Prefix`) of accepted join-requests
- JoinEUI ranges (`[]types.EUI64Prefix`) of accepted new devices

**How do you propose to implement this?**

Add configuration, extend API, implement RPC server.

**What can you do yourself and what do you need help with?**

Can do, can review.

**Comment by johanstokking** [comment]
@rvolosatovs don't we have this already?

**Comment by rvolosatovs** [comment]
Done in https://github.com/TheThingsNetwork/lorawan-stack/pull/803
