### ISSUE TITLE
Make GCS API available via gRPC

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3280]
#### Summary
The Gateway Configuration Server currently does not use gRPC so it's API is plain HTML. In the JS SDK we somewhat rely on functionality being available as RPC so adding GCS functionality requires us to break out of our usual implementation.

#### Why do we need this?
- Retain implementation consistency in the JS SDK
- Avoid harcoded API routes and arbitrary implementations

#### What is already there? What do you see now?
gRPC API of all other stack components

#### What is missing? What do you want to see?
gRPC API for the GCS

#### How do you propose to implement this?
Likely recreate the implementation for the other stack components.

#### How do you propose to test this?
Unit tests.

#### Can you do this yourself and submit a Pull Request?
No, @KrishnaIyer @adriansmares please reassign as appropriate.

**Comment by KrishnaIyer** [comment]
This is a nice technical debt thing to do, though atm the GCS doesn't expose any functionality to console.

**Comment by KrishnaIyer** [comment]
GCS doesn't actually expose any functionality to the console. Do you use the GCS APIs in the console/SDK somewhere @kschiffer?

**Comment by adriansmares** [comment]
The download gateway configuration button is from the GCS.

**Comment by nicholaspcr** [comment]
Comment left by @htdvisser on PR and is a good question for the discussion
>I wasn't involved in the original discussion about building this feature, so this may be a bit late, but still. I don't think that "in the JS SDK we expect everything to be gRPC" is a good argument for forcing something that should be a simple file download into a gRPC API. Are we sure we really need to do this here? Why can't the SDK just support the file downloads that we already have?

From the @kschiffer description it seems to be just a question of breaking out of the standard implementation but might be best to have his response on the subject

**Comment by kschiffer** [comment]
It's not like it would not work the way it is. It just forces us to [hardcode the API endpoint in the SDK](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.18/sdk/js/src/service/gateways.js#L256-L259) and also to break out of our regular HTTP request logic, while everywhere else we rely on the gRPC API definition to source API paths. I thought it was odd that the configuration download is not part of the gRPC API, like everything else. I don't have any very strong feelings about this otherwise than practicality and retaining consistency in the JS SDK.

**Comment by htdvisser** [comment]
I'd very much prefer having the SDK(s) support the necessary The Things Stack APIs than trying to create a gRPC API for everything, even when that isn't appropriate.

cc: @johanstokking

**Comment by johanstokking** [comment]
Actually I think in this case it makes sense to have a gRPC API to generate configuration and return that.

The reason that we started with the HTTP API is that gateways were able to download their own configuration file directly, if they are configured with their gateway ID and a gateway API key. We did not make it HTTP because the result happens to be a JSON file in all of the current cases.
