### ISSUE TITLE
Enforce MAC/PHY version coherence

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#329]
**Summary:** 

Enforce that MAC/PHY versions are coherent.

**Why do we need this?**

To avoid mixing MAC and PHY versions that should not be mixed.

**What is already there? What do you see now?**

Users can set a MAC and PHY version independently. They will probably not be troublesome as LoRaWAN device stacks enforce compatible versions, but we let's avoid some weird side effects in the LoRaWAN stack because of mixing incompatible versions.

**What is missing? What do you want to see?**

Enforce that the version is the same. The only thing that's variable in PHY is the revision.

**How do you propose to implement this?**

Check the versions on create and update.

**What can you do yourself and what do you need help with?**

Review.

**Comment by rvolosatovs** [comment]
Closed by #3146
