### ISSUE TITLE
Retry failed registry transactions

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#33]
**Summary:** 

Components should retry failed registry transactions if possible

**Why do we need this?**

To gracefully handle errors

**What is already there? What do you see now?**

The RPC fails

**What is missing? What do you want to see?**

Retries of the transaction

**How do you propose to implement this?**

Depends on the concrete case

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1163 by @rvolosatovs

**Comment by johanstokking** [comment]
@rvolosatovs please break this down in issues for specific cases.

**Comment by rvolosatovs** [comment]
Closing in favor of #2696
