### ISSUE TITLE
"Change location settings ->" link in end-device view redirects to a wrong URL

### ISSUE THREAD

**Issue by TheIronNinja** [TheThingsNetwork/lorawan-stack#3400]
#### Summary
The URL where it sends you is wrong. It should be `/applications/{app-id}/devices/{dev-id}/location` but it is `applications/{dev-id}/devices/{app-id}/location`. The id's are swapped. This results in the page not found error.

#### Steps to Reproduce
1. Open the console
2. Go to any application end-device
3. Click on the little link on the right hand side, just above the map and below the "Live data" window.

#### Environment
The Things Stack for LoRaWAN: ttn-lw-stack
Version:             3.9.4
Build date:          2020-09-23T09:56:19Z
Git commit:          c4be55c
Go version:          go1.15.2
OS/Arch:             linux/amd64

**Comment by bafonins** [comment]
Hi @TheIronNinja! This issue is fixed in `v3.10` (https://github.com/TheThingsNetwork/lorawan-stack/pull/3275).
