### ISSUE TITLE
Sending gateway PUT request with empty diff results in an error

### ISSUE THREAD

**Issue by pgalic96** [TheThingsNetwork/lorawan-stack#3406]
#### Summary

When being in entity general settings, we allow submitting PUT requests with no changes for applications. Currently submitting the same PUT request with empty payload for gateways results in a backend error:

#### Steps to Reproduce

1. Submit a request with to `http://localhost:1885/api/v3/gateways/<gateway_id>` with request payload `{"gateway":{},"field_mask":{"paths":[]}}`
2. Observe the error returned

#### What do you see now?

```json
{
  "code": 3,
  "message": "error:pkg/errors:validation (invalid `gateway`: embedded message failed validation)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/errors",
      "name": "validation",
      "message_format": "invalid `{field}`: {reason}",
      "attributes": {
        "field": "gateway",
        "name": "UpdateGatewayRequestValidationError",
        "reason": "embedded message failed validation"
      },
      "correlation_id": "27e3f23d15f946f5a0e32d3988310944",
      "cause": {
        "namespace": "pkg/errors",
        "name": "validation",
        "message_format": "invalid `{field}`: {reason}",
        "attributes": {
          "field": "version_ids",
          "name": "GatewayValidationError",
          "reason": "embedded message failed validation"
        },
        "cause": {
          "namespace": "pkg/errors",
          "name": "validation",
          "message_format": "invalid `{field}`: {reason}",
          "attributes": {
            "field": "model_id",
            "name": "GatewayVersionIdentifiersValidationError",
            "reason": "value does not match regex pattern \"^[a-z0-9](?:[-]?[a-z0-9]){2,}$\""
          },
          "code": 3
        },
        "code": 3
      },
      "code": 3
    }
  ]
}
```

#### What do you want to see instead?

Success like with submitting exactly the same payload for application PUT request

#### Environment

- `v3.10.0-rc1` 

#### How do you propose to implement this?

Don't know exactly

#### How do you propose to test this?

Testing in console

#### Can you do this yourself and submit a Pull Request?

I think that would take too much time

**Comment by htdvisser** [comment]
This is actually working according to the [specification of a field mask](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#field-masks-in-update-operations). If an update request doesn't specify the fields to update, the operation applies to all fields. In this case, validation fails for one of the (implied) fields to update.

**Comment by pgalic96** [comment]
Then I guess the application validation does not work as intended? Since the same request payload succeeds

**Comment by htdvisser** [comment]
I guess you mean gateway.

If you update all fields of a gateway, you also update the "model ID", which must follow a specific pattern, and apparently an empty string is not valid.

**Comment by pgalic96** [comment]
> When being in entity general settings, we allow submitting PUT requests with no changes for applications. Currently submitting the same PUT request with empty payload for gateways results in a backend error:

The following PUT request for applications succeeds, with preserving all fields:
`http://localhost:1885/api/v3/applications/my-new-app`

Payload: `{"application":{},"field_mask":{"paths":[]}}`

The response is following:

`{"ids":{"application_id":"my-new-app"},"created_at":"2020-07-06T13:55:28.598Z","updated_at":"2020-10-27T11:30:14.240Z"}`

I expected the same behavior for the gateway PUT requests, but as you said, the validation fails for one of the fields. Is it working as intended for both gateways and applications or is the validation not consistent?

**Comment by htdvisser** [comment]
I suspect that for the application, all fields are allowed to be empty.

Maybe we should actually reject update requests with empty field masks. In any case the Console should avoid making requests with empty field masks.

**Comment by htdvisser** [comment]
Adding @johanstokking and @rvolosatovs (as code owners of the API) for discussion.

Should we update our validation to **require** a field mask to be set on update requests?

The problem is that it technically breaks API, but I think it's justified as a bugfix, since the current behavior is confusing, and could lead to unexpected results when we add fields in newer versions, while a client remains at an old version, and may unintentionally zero out a field by supplying it in the "body" with an empty field mask.

**Comment by pgalic96** [comment]
The change will break application general settings, so that needs to be taken into account.

**Comment by pgalic96** [comment]
So, this is handled differently for pretty much every entity general settings form in the Console. @bafonins pointed it out in #3364 , but actually submitting a form with no fields changed in the organization general form also results in an error (albeit a different one because of a different field mask `[""]` ):

![Screenshot 2020-10-27 at 3 23 11 PM](https://user-images.githubusercontent.com/19795814/97315171-b955b780-1868-11eb-9c8d-c41ac039f6c1.png)

The way it is handled in the device general settings is correct imo, where JS SDK handles this with a request tree. If there is no updated fields, no requests are sent at all. So we either change the SDK to handle this in the same way for all the entities, or another solution would be to disable the submit button if no fields are changed, which sounds like a way simpler fix, that is also satisfying UX requirements. cc @kschiffer

**Comment by johanstokking** [comment]
> @htdvisser  and could lead to unexpected results when we add fields in newer versions, while a client remains at an old version, and may unintentionally zero out a field by supplying it in the "body" with an empty field mask.

If the field mask is empty, the value should not be taken from the body, right?

I think that supplying an empty field mask should be a no-op on update. It could be used by clients to ensure the entity exists and/or that there's valid auth to make an actual change.

The issue reported by @pgalic96 seems to be that we require certain fields on `PUT`, but I don't think that we should be doing that.

**Comment by htdvisser** [comment]
> If the field mask is empty, the value should not be taken from the body, right?
> [...]
> I think that supplying an empty field mask should be a no-op on update

This would violate the protobuf specification of a field mask which says that if an update request doesn't specify the fields to update, the operation applies to all fields.

Our validation middleware respects the protobuf specification, and therefore validates the fields specified in the field mask, or all fields if the field mask is empty.

**Comment by johanstokking** [comment]
But you are suggesting to deviate from protobuf specification, right, by not allowing empty field masks?

There may be other issues when not supporting empty field mask, especially on create, i.e. when there are no fields to be set.

**Comment by htdvisser** [comment]
Requiring a field mask is allowed by the specification:

> Note that in the presence of schema evolution, this may mean that fields the client does not know and has therefore not filled into the request will be reset to their default. If this is unwanted behavior, a specific service may require a client to always specify a field mask, producing an error if not.

**Comment by nejraselimovic** [comment]
@htdvisser @johanstokking what is the conclusion here, anything left for discussion? Who is picking up this issue at the end? Can we move it from Backlog?

**Comment by johanstokking** [comment]
@pgalic96 is this still an issue?

**Comment by pgalic96** [comment]
It does still occur in organization general settings if you submit without changing anything. For gateway general settings the attributes field is always included in the field mask even when not changed so there is no error but I suppose the issue is not fixed exactly.

**Comment by johanstokking** [comment]
> another solution would be to disable the submit button if no fields are changed, which sounds like a way simpler fix, that is also satisfying UX requirements

This seems like the best approach then.
