### ISSUE TITLE
Document that location is only updated automatically for authenticated gateways

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#3410]
#### Summary

Followup for #3326 

#### Why do we need this ?

Gateway location can only be updated automatically from status messages when the gateway is authenticated, which excludes gateways connecting over UDP.

#### What is already there? What do you see now?

Comment on the API proto field `update_location_from_status`, noting that it does not work for UDP gateways

#### What is missing? What do you want to see?

Document this behaviour in the docs and the console (also see comment https://github.com/TheThingsNetwork/lorawan-stack/pull/3326#discussion_r511057626)

#### Can you do this yourself and submit a Pull Request?

No, assigning @benolayinka, re-assign as needed.

**Comment by benolayinka** [comment]
@kschiffer it would be nice to add a note in the console for this

**Comment by benolayinka** [comment]
Proto comments go in the stack definition. Moving this issue.

**Comment by benolayinka** [comment]
@htdvisser can you add the proto comment

**Comment by htdvisser** [comment]
No, you can do this yourself.

**Comment by benolayinka** [comment]
Comment is already there https://github.com/TheThingsNetwork/lorawan-stack/blob/cb3838f1778850bc069ac8486297db7683836ac3/api/gateway.proto#L133.

This is probably more important for people to see in the console, assigning @kschiffer

**Comment by kschiffer** [comment]
@bafonins can you add this to the respective tooltip in #4157

**Comment by kschiffer** [comment]
Will be fixed by #4157. Closing this already.
