### ISSUE TITLE
Add HTTP client timeout to the LoRaCloud DAS client

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#3455]
#### Summary

The HTTP client used by LoRaCloud DAS needs HTTP read/write timeouts.

#### Why do we need this?

As the client is shared between applications and tenants, the underlying connection pool can be consumed by invalid endpoints.

#### What is already there? What do you see now?

The package uses `http.DefaultClient`.

#### What is missing? What do you want to see?

The client should use an `http.Client` with a timeout (similar to the webhooks).

#### Environment

`v3.10.0`

#### How do you propose to implement this?

Update the package to use a custom client.

#### How do you propose to test this?

Unit tests.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by neoaggelos** [comment]
Related #2533
