### ISSUE TITLE
Documentation link validation in the Console

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3460]
#### Summary
The documentation was recently moved to a separate repository. This makes it harder for us to validate the validity of documentation references we have in the Console, e.g. via `<DocLink />`. It would be good to have some automated process in place as part of the CI to avoid dead links to the documentation.

#### Why do we need this?
To avoid dead links to the documentation in the Console.

#### What is already there? What do you see now?
- `<DocLink />` component and utilities
- TTS documentation repository

#### What is missing? What do you want to see?
- A process that ensures validity of links to the documentation

#### How do you propose to implement this?
To be discussed.

#### How do you propose to test this?
To be discussed.

**Comment by benolayinka** [comment]
I think we determined this wasn't feasible
