### ISSUE TITLE
Fix field styling

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3469]
#### Summary

After https://github.com/TheThingsNetwork/lorawan-stack/pull/3162 the login screen looks like this:
<img width="716" alt="Screenshot 2020-11-12 at 13 26 43" src="https://user-images.githubusercontent.com/16374166/98934497-d76b1b00-24ea-11eb-9042-c00b7c264664.png">

#### Steps to Reproduce

1. Go to the login screen on the main branch

#### What do you see now?

Broken field  styling

#### What do you want to see instead?

<img width="403" alt="Screenshot 2020-11-12 at 13 28 56" src="https://user-images.githubusercontent.com/16374166/98934598-07b2b980-24eb-11eb-883d-602c1603de09.png">

#### Environment

v3.10

#### Can you do this yourself and submit a Pull Request?

@kschiffer @benolayinka

**Comment by bafonins** [comment]
I also noticed that the glossary icon placement varies between desktop and mobile screens:
<img width="154" alt="Screenshot 2020-11-12 at 13 57 07" src="https://user-images.githubusercontent.com/16374166/98937470-1d29e280-24ef-11eb-85f1-727cc7427b22.png">
<img width="242" alt="Screenshot 2020-11-12 at 13 57 37" src="https://user-images.githubusercontent.com/16374166/98937475-1e5b0f80-24ef-11eb-8903-aeb4d70f1af5.png">

**Comment by kschiffer** [comment]
Appears like @benolayinka rebased, force-pushed and merged his outdated local branch instead of the updated one.

**Comment by bafonins** [comment]
Additionally, with https://github.com/TheThingsNetwork/lorawan-stack/pull/3162 we no longer can use `cy.findByLabelText` directly. For fields with the glossary icon we must must regex, e.g. instead of `cy.findByLabelText('LoRaWAN Version')`, `cy.findByLabelText(/LoRaWAN Version/)` must be used.

**Comment by kschiffer** [comment]
That can be fixed by adjusting the markup and styling a little so that the label content stays pure. However, I don't have time to work on that now.
