### ISSUE TITLE
Remove default UDP address change block

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#3490]
#### Summary

Remove default UDP address change block

References #1436 

#### Why do we need this?

Because the remote address of the UDP client has proven to be unstable and can even change for each session (upstream and downstream)

#### What is already there? What do you see now?

A default value. The connection is kept warm by the active session (e.g. upstream), so the other session (e.g. downstream) will never be setup.

#### What is missing? What do you want to see?

Set the default value to 0 and update documentation.

#### How do you propose to implement this?

Change default config.

#### How do you propose to test this?

N/A

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by neoaggelos** [comment]
The UDP firewall interface deals with `encoding.Packet`, so it is probably not too straightforward to update.

Is it better to add a separate check instead, as part of #1406? (see https://github.com/TheThingsNetwork/lorawan-stack/commit/80e9527c70fad4b38f3fba014d87b3bb005d4642)

**Comment by johanstokking** [comment]
> The UDP firewall interface deals with `encoding.Packet`, so it is probably not too straightforward to update.

That is because it currently deals with both the remote IP and the EUI.

> Is it better to add a separate check instead, as part of #1406? (see [80e9527](https://github.com/TheThingsNetwork/lorawan-stack/commit/80e9527c70fad4b38f3fba014d87b3bb005d4642))

That is what is meant with:

> We need to take that apart: one firewall for address change detection and one for detecting a message flood and filtering traffic.

Or do I miss your point here?

**Comment by johanstokking** [comment]
Since this relaxes the security of UDP gateways, and can lead to anyone connecting a gateway by EUI, we need #1436.

**Comment by neoaggelos** [comment]
Is this already addressed with #3906?

**Comment by johanstokking** [comment]
Closed by #3906
