### ISSUE TITLE
Support all Ping Slot Period values from the Device Repository

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#3531]
#### Summary

Support all Ping Slot Period values from the Device Repository in TTS.

#### Why do we need this?

#3433 

#### What is already there? What do you see now?

`enum PingSlotPeriod` supports values up to `PING_EVERY_128S`.

#### What is missing? What do you want to see?

`pingSlotPeriod` in [LoRaWAN Devices Schema](https://lorawan-schema.org/draft/devices/1/) is an enum with values up to 4096 seconds. Add these values to the `PingSlotPeriod` enum (and do any other required changes).

#### Environment

3.10

#### How do you propose to implement this?

Not familiar.

#### How do you propose to test this?

Unit tests

#### Can you do this yourself and submit a Pull Request?

No, unless it's as simple as adding the new enum values.

**Comment by rvolosatovs** [comment]
The schema is invalid, see https://github.com/lorawan-schema/draft-devices/pull/9
