### ISSUE TITLE
Convert functions to arrow functions

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3540]
#### Summary
We recently introduced an eslint warning for not using arrow functions. We should resolve such warnings in one big refactor PR, so that the warning output of eslint becomes unclogged.

#### Why do we need this?
- Annoying verbose and noisy warning output of `eslint`
- Annoying warnings and markings in IDEs
- Noise in PRs when these conversions are committed on top of changes

#### What is already there? What do you see now?
Eslint config update and the decision to move to arrow functions exclusively.

#### What is missing? What do you want to see?
All applicable functions being converted to arrow functions and hence eslint warnings about arrow functions being resolved.

#### How do you propose to implement this?
There are tools to help doing this automatically, e.g. https://github.com/cmstead/js-refactor
We might want to use such tools to streamline other code styling inconsistencies as well.

#### How do you propose to test this?
Unnecessary.

#### Can you do this yourself and submit a Pull Request?
@bafonins please pick this up or reassign.

**Comment by bafonins** [comment]
>  We should resolve such warnings in one big refactor PR, so that the warning output of eslint becomes unclogged.

I dont think that global refactor is required. IMO, this should be refactored gradually.

> Annoying warnings and markings in IDEs

You can disable this in your ide.

> Noise in PRs when these conversions are committed on top of changes

In most cases refactoring plain function to arrow function is 2 line diff. I do not consider this to be a big issue.

Overall, we should move towards using arrow functions gradually and changed within feature/fix PR's. Also, this should be a joint effort of everyone working on `webui`.
