### ISSUE TITLE
Expand nested side navigation entries on focus

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3551]
#### Summary

Currently, when navigating via keyboard the 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16374166/100627904-4b515400-3330-11eb-83d7-94f42d71d87f.gif)

#### Why do we need this?

Focused element must be visible.

#### What is already there? What do you see now?

Currently, the user can focus on the main entry and press `<space>` to expand the dropdown with nested items. However, if the user continues navigating focused items are hidden.

#### Environment

v3.10.2 `ttn-lw-stack`

#### How do you propose to implement this?

I see 2 options:
1. If the user focuses on nested and hidden item in the side navigation, the entry should expand.
2. Set `tabIndex` to `-1` on nested items when the dropdown is collapsed. 

#### How do you propose to test this?

Manually

#### Can you do this yourself and submit a Pull Request?

@asmulko

**Comment by kschiffer** [comment]
> Set `tabIndex` to `-1` on nested items when the dropdown is collapsed.

This is what we should do.
