### ISSUE TITLE
Add support for LoRaWAN Regional Parameters RP2 1.0.{0,1,2}

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3578]
#### Summary

We need to add support for the new regional parameters documents that go with LoRaWAN 1.0.4.

See https://github.com/TheThingsNetwork/lorawan-stack/issues/2784#issuecomment-648735723 for the story about the naming scheme

#### How do you propose to implement this?

PDFs are available on Drive or from the LoRa Alliance website.

#### How do you propose to test this?

🤷

**Comment by kschiffer** [comment]
Duplicate of #3513
