### ISSUE TITLE
Use Redis 6.2.0 features

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#3592]
#### Summary

Use `COPY`, `XAUTOCLAIM` and `SET GET`once Redis 6.2.0 released and deployed

#### Why do we need this?

To avoid using `restore` and `dump` hacks, as well as race condition-suspectible command sequences and custom lua

#### What is already there? What do you see now?

`restore` and `dump` hack for copying and combination of `SET NX` with a following `GET`

#### What is missing? What do you want to see?

Use `COPY`, `XAUTOCLAIM` and `SET GET`

#### How do you propose to implement this?

Once 6.2.0 is released and deployed, change all usages of `restore` and `dump` hacks to `COPY` as well as use `SET GET`

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by nejraselimovic** [comment]
@adriansmares you can take this one, right? I see Redis 6.2.0 is released, so I guess this is no longer blocked. I'll schedule it for Q3 as I think it's not too important (apparently we have some "hacks" that do the work), but let me know if you have any thoughts about this.
