### ISSUE TITLE
Migrate to Go 1.16 file embedding

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#3618]
#### Summary

Migrate to Go 1.16 file embedding
Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/3603#discussion_r549270901

#### Why do we need this?

To lower maintenance cost and simplify process

#### What is already there? What do you see now?

For example, lua script generator in `pkg/redis`

#### What is missing? What do you want to see?

No custom file embedding logic

#### How do you propose to implement this?

Wait for go 1.16 and migrate

#### How do you propose to test this?

The output should stay the same

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by nejraselimovic** [comment]
@htdvisser we're no longer waiting for Go 1.16.x, so I guess this can be implemented now?
