### ISSUE TITLE
up.Settings.TimeStamp not initialised from up packet causing wrong scheduling

### ISSUE THREAD

**Issue by pdubois22** [TheThingsNetwork/lorawan-stack#362]
**Summary:** 

in gatewayserver/io/io.go : 113

```
if up.Settings.Time != nil {
		c.scheduler.SyncWithGateway(up.Settings.Timestamp, up.ReceivedAt, *up.Settings.Time)
	} else {
		c.scheduler.Sync(up.Settings.Timestamp, up.ReceivedAt)
	}
```

scheduler is synced against up.Settings.Timestamp for a gw that does not send time.
Pb is that at that time, up.Settings.Timestamp is 0 => causes problems with scheduling

in ttnpb/udp/translation.go : 152

```
func convertUplink(data Data, rxIndex int, md UpstreamMetadata) (ttnpb.UplinkMessage, error) {
	up := ttnpb.UplinkMessage{}
	rx := *data.RxPacket[rxIndex]
	up.Settings = ttnpb.TxSettings{
		Frequency:           uint64(rx.Freq * 1000000),
		GatewayChannelIndex: uint32(rx.Chan),
	}

```

TimeStamp not initialized

**Steps to Reproduce:** 

**What do you see now?**
Problems with scheduling

**What do you want to see instead?**
sync ok even with non GPS gateways

**How do you propose to implement this?**

```
func convertUplink(data Data, rxIndex int, md UpstreamMetadata) (ttnpb.UplinkMessage, error) {
	up := ttnpb.UplinkMessage{}
	rx := *data.RxPacket[rxIndex]
	up.Settings = ttnpb.TxSettings{
		Frequency:           uint64(rx.Freq * 1000000),
		GatewayChannelIndex: uint32(rx.Chan),
		Timestamp: rx.Tmst,
}
```

**Environment:**
any

**What can you do yourself and what do you need help with?**
report

**Comment by htdvisser** [comment]
This will be fixed by #333
