### ISSUE TITLE
Redirect to /console after log in to TTS community edition

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#3624]
#### Summary
When I log in to our new eu1 community cluster, I get redirected to [https://eu1.cloud.thethings.network/oauth/?](https://eu1.cloud.thethings.network/oauth/?) and there is no way to move forward to the Console. 

#### What do you see now?
![Screen Shot 2020-12-29 at 10 33 29](https://user-images.githubusercontent.com/65215579/103274945-36b1bb80-49c3-11eb-8f3c-08c2c01d2794.png)

#### What do you want to see instead?
A redirection to [https://eu1.cloud.thethings.network/console/](https://eu1.cloud.thethings.network/console/).

#### Can you do this yourself and submit a Pull Request?
No

@laurensslats for now, this is the only thing I spotted while going through the onboarding process

**Comment by nejraselimovic** [comment]
@kschiffer is this something you're covering?

**Comment by kschiffer** [comment]
Yes. It will be part of the Account App, though I will branch this fix off today to make it available already.
