### ISSUE TITLE
Frequency in json is a string not a number

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#3631]
#### Summary

The uplink message json that is reported via MQTT contains metadata with the frequency as a string.

```
      "settings":{
         "data_rate":{
            "lora":{
               "bandwidth":125000,
               "spreading_factor":7
            }
         },
         "data_rate_index":5,
         "coding_rate":"4/5",
         "frequency":"867700000",
         "timestamp":4036323499
      },
```

#### Steps to Reproduce

1. Subscribe to uplink message on MQTT

#### What do you see now?

`"frequency":"867700000",`

#### What do you want to see instead?

`"frequency":867700000,`

#### Environment

eu1.cloud.thethings.industries

v3.10.5

#### How do you propose to implement this?

Change frequency from a String to an Unsigned Long.

#### How do you propose to test this?

A simple verification via MQTT.

It might however be a breaking change for downstream users of metadata.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by rvolosatovs** [comment]
This is expected behavior, see https://developers.google.com/protocol-buffers/docs/proto3#json
As a 64-bit number, frequency is marshaled as a string
