### ISSUE TITLE
Device Repository API field validation

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#3694]
#### Summary

Add validations for all Device Repository API

#### Why do we need this?

We want to have strict field validations across the whole API

#### What is already there? What do you see now?

With #3530. validation for identifiers and a few select fields of the request messages. 

#### What is missing? What do you want to see?

Validation rules for all fields.

#### Environment

v3.11

#### How do you propose to implement this?

Validate all API field according to the LoRaWAN Devices Schema https://lorawan-schema.org/draft/devices/1/

#### How do you propose to test this?

Existing unit tests cover API functionality. End to end tests initialize the device repository index, so they will cover failures with data from the Device Repository

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by htdvisser** [comment]
Since @neoaggelos isn't going to finish this before the v3.14.1 deadline, I'll move it to v3.14.2.
