### ISSUE TITLE
Integrate location solvers

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#37]
**Summary:** 

After handling an uplink message, solve the location of the message.

**What is already there? What do you see now?**

Nothing.

**What is missing? What do you want to see?**

- Configuration in application link on which location solvers to use
- Interface for calling the location solvers, like message processors
- Send results in `ApplicationUp`; message already exists

**Discussion:**

We need to figure out if the AS, which in principle only has link rights, may update the end device's location in the Entity Registry.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1221 by @johanstokking

**Comment by johanstokking** [comment]
Consider adding the API key to the solver configuration and make it optional to provide an API key to store the locations.

**Comment by ajovertoom** [comment]
@johanstokking pls consider prioritising this integration, starting with LoRa Cloud Geoloc.
cc @adriansmares

**Comment by johanstokking** [comment]
@ajovertoom please file separate issue for LoRa Cloud geolocation support. That should be fairly straight-forward with the current infrastructure.

**Comment by adriansmares** [comment]
Location Solvers will be implemented by application packages, and both LoRaCloud based packages implement this functionality.
