### ISSUE TITLE
Allow users to change their primary email address

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3711]
#### Summary

We should allow non-admin users to change their primary email address.

#### How do you propose to implement this?

When contact info management is fully implemented in the frontends, we can let users "promote" one of their contact addresses to their primary email address.

**Comment by kschiffer** [comment]
I guess we can close this, or at least reword.

**Comment by htdvisser** [comment]
Yeah, let's close this. Can you create a new issue with the flow for "promoting" email addresses in existing contact info?

**Comment by kschiffer** [comment]
#3725
