### ISSUE TITLE
Allow Escape key to close the Event Details window in Live Data views

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#3717]
#### Summary
In Console Live Data view allow `Escape key` to close the Event Details window.

#### Why do we need this?
This allows to use the keyboard for closing the Event Details window, which can be more practical and faster than using the mouse and contributes to preventing RSSI.
Closing the Event Details window currently can only be done with the mouse.

#### What is already there? What do you see now?
Currently only possible to close the Event Detals window with the mouse.

**Comment by kschiffer** [comment]
Merged into #3719
