### ISSUE TITLE
Check for address mismatches in SDK device registry calls

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#372]
**Summary:** 
The js SDK needs to check for mismatches in the `stackConfig` setting with the address settings in device requests. For example, a device can be handled by a join server on a different host than what is configured in `stackConfig` during initialization. In such cases, the SDK should not try to call the Join Server as per `stackConfig` because we know it would result in 404.

**Why do we need this?**
Better developer experience.

**What is already there? What do you see now?**
We introduced a complementary feature in the CLI via #371 . The SDK should follow the behavior there.

**What is missing? What do you want to see?**
A feature to check and warn/error in mismatch cases.

**Environment:**
Browser / node.js

**How do you propose to implement this?**
We already retrieve the registry record of the IS first before possible other registry calls. Before doing these, we could check the address fields.

**Can you do this yourself and submit a Pull Request?**
I can do this.

**Comment by bafonins** [comment]
This is already implemented.
