### ISSUE TITLE
Unable to change Activation mode after device has been created, is read-only

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#3722]
#### Summary
In the console the Activation mode (OTAA, ABP, Multicast) shown for an existing device is read-only. 
Unable to change Activation mode for existing devices.

#### Steps to Reproduce
Add a new device to an application, select create to add it. Afterwards try to change its Activation mode.

#### What do you see now?
Activation mode parameter is read-only.

#### What do you want to see instead?
Activation mode read-write so it can be changed.

#### Environment
[The Things Network V3 Console](https://eu1.cloud.thethings.network/console/).

#### How do you propose to implement this?
Make Activation mode changeable.

**Comment by htdvisser** [comment]
This is working as intended. In The Things Stack OTAA and ABP devices are really different things, and it's no longer possible to switch between the two. Also, an ABP device can't suddenly turn into a multicast group or vice versa.
