### ISSUE TITLE
Change ID regex to allow IDs with length of 2

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3723]
#### Summary

I propose to change our ID regex to allow IDs with a minimum length of 2 instead of the current 3.

#### Why do we need this?

Because there are quite a few existing TTN users with usernames of 2 characters. These users can currently not create v3 accounts and it would also be quite a lot of work to rename all of those users. At the same time, I can't think of a good reason not to make this change.

#### What do you see now? What do you want to see?

```diff
- ^[a-z0-9](?:[-]?[a-z0-9]){2,}$
+ ^[a-z0-9](?:[-]?[a-z0-9]){1,}$
```

#### How do you propose to implement this?

Find/Replace.

Also, be sure to update the docs - https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/238

#### How do you propose to test this?

Same as always.

#### Can you do this yourself and submit a Pull Request?

I can.

**Comment by benolayinka** [comment]
Be sure the docs are updated before closing this: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/238
