### ISSUE TITLE
Clarify inconsistent usage of gateway ID in global_conf.json in the documentation

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#3777]
#### Summary
Found this on our forum: https://www.thethingsnetwork.org/forum/t/v3-download-global-conf-json/43973/3

![Screenshot from 2021-02-10 12-55-18](https://user-images.githubusercontent.com/65215579/107507227-8b8a4980-6b9f-11eb-8a6e-e837e3102b0c.png)

#### What do you see now?
Gateway EUI from the Console is stored as `gateway_ID` in `global_conf.json` file that's downloadable from the Console. Gateway ID in the Console is the mnemonic name of the gateway.

#### What do you want to see instead?
Can this be reworded somehow? It's simple, but I guess it can create a confusion. If not, should we do any action to clarify this in the documentation or something?

#### Can you do this yourself and submit a Pull Request?
No. @kschiffer I assigned you, please reassign if it's not your area

**Comment by kschiffer** [comment]
Maybe @rvolosatovs can make a comment on this. I suppose though that we cannot change the structure of the `global_conf.json`. Changing the name of the gateway ID would create only more confusion I'd say. So I guess our best bet is to clarify this in the docs. If there's a doc page for the gateway conf already, we can link it there with a help icon.

**Comment by nejraselimovic** [comment]
> Maybe @rvolosatovs can make a comment on this. I suppose though that we cannot change the structure of the `global_conf.json`. Changing the name of the gateway ID would create only more confusion I'd say. So I guess our best bet is to clarify this in the docs. If there's a doc page for the gateway conf already, we can link it there with a help icon.

I also saw Krishna's response on the forum after, it's some legacy stuff, so I guess I'll just take this one and clarify it in the documentation.

**Comment by KrishnaIyer** [comment]
Indeed I responded to a similar query on the forum; https://www.thethingsnetwork.org/forum/t/v3-download-global-conf-json/43973/6
