### ISSUE TITLE
Console lacks context sensitive help

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#3785]
#### Summary
The console lacks context sensitive help.
Add consistent context sensitive help.

#### Why do we need this?
Many fields in the console (e.g. during adding/configuring Gateways, Applications and Devices) lack any form of help leaving the user puzzled and unclear whether (s)he should fill in the field or not, what it's for and what possible values are.
For some fields this is obvious and/or dropdowns with possible values are shown but for many other fields it is not (e.g. add device | advanced network settings | factory preset frequencies, but that is only one example).

The small descriptive sentence below the field is often not sufficient (at all).
The forms should contain _context sensitive_ help. For entering a DevEUI one can click a question mark button which then shows "See DEVEUI in the Glossary". That is not context sensitive help but a 'textual pointer', not a clickable link and provides poor UX.
Many other fields do not even have that option and all that resides is a small link bottom right on the page to the main The Things Stack Documentation site root. That is not very helpful at all and often frustrating.
Results in poor UX that needs major improvement.

#### What is already there? What do you see now?
See above. All form fields should be checked.

#### What is missing? What do you want to see?
Context sensitive help.
Clickable element (eg. like the question mark icon) that shows a popup with a larger help description (not limited to a single line) about the field _and_ include a link where the subject is fully explained in the documentation (the link can be shown in the popup).

#### Environment
V3 Console in general.

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by lnlp** [comment]
See:

https://github.com/TheThingsNetwork/lorawan-stack/issues/2813#issuecomment-652635759

> This is going to change drastically once we have the device repository in place. It will be a matter of selecting the vendor, the model, and potentially the region and (if applicable) the firmware version. That's it.
> 
> So even though we should make things easy to input, the best thing is to avoid users to input this stuff in the first place.

That's not "That's it" for TTN V3 with a community with many DIY devices.

This will not work for DIY devices. And 'devices' (manual settings) is one of the console areas that needs context sensitive help.

**Comment by kschiffer** [comment]
Thanks for filing this issue @lnlp.

We are aware of this issue and already have tooltips with contextual help in our pipeline and their content is also already been provided by @benolayinka. It will be part of an overall form UX overhaul, which we're currently in the process of implementing for end devices (#3522). I'll make sure that the priorities are updated to have this issue resolved timely.

> *   We will add tooltip toggles for all LoRaWAN fields and many other fields that need explanation for novice users

**Comment by johanstokking** [comment]
Let's make sure we explain the "factory preset frequencies" too; and probably all the other ABP settings.

**Comment by johanstokking** [comment]
Rescheduling to March. Let's start with the low hanging fruit.

**Comment by kschiffer** [comment]
Superseded by #3809.

@lnlp please follow this issue to track our progress on this.
