### ISSUE TITLE
Use skeleton screens instead of loading spinners where applicable

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#38]
**Summary:** 
Spinners often result in suboptimal UX, because they leave the user in the dark about what to anticipate from a loading event (among other things, [see e.g. here for more info](https://medium.com/gronda/the-illusion-of-speed-loading-states-with-react-1c676ccce484))
It's often times better to provide a skeleton of the component/content/view that is being loaded, possibly in conjunction with a spinner or similar animation that indicates loading.

**What is already there? What do you see now?**
- A loading spinner

**What is missing? What do you want to see?**
- Skeleton graphic/markup for components that load frequently
- A flag on these components that will result in the skeleton being rendered (for loading events)

cc @bafonins 

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1223 by @kschiffer

**Comment by kschiffer** [comment]
I don't think this will ever have enough importance to be tackled and it's really a cosmetic thing only. I'll close it and maybe reopen if I should deem this more relevant in the future.
