### ISSUE TITLE
Add cluster hints to Applications

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3830]
#### Summary

I think it would be helpful to add cluster hints to applications.

#### What is already there? What do you see now?

With explicit linking gone, Applications in v3 are no longer explicitly linked (between Application Server and Network Server) in a specific cluster. This means that Applications can now contain devices in different clusters. This unfortunately also makes it easier to make mistakes, for example by registering some devices in `eu1`, and some devices in `nam1`. I've solved this by creating different applications for different clusters:

<img width="1280" alt="Screen Shot 2021-02-19 at 08 58 17" src="https://user-images.githubusercontent.com/181308/108475150-9e340b00-7290-11eb-8ef5-d07a97babe33.png">

#### What is missing? What do you want to see?

In such a setup, it may be useful to set the `network_server_address`, `application_server_address` and `join_server_address` in the Application, so that the Console can give hints to inform the user that an application is in a different cluster.

#### Environment

The Things Network, The Things Stack Cloud

#### How do you propose to implement this?

- Add those fields to the Application database model
- Add those fields to the Application API
- Make the Console ask for those fields when registering an application (they are optional)
- Make the Console display hints when listing / viewing applications

#### Can you do this yourself and submit a Pull Request?

Let's discuss this first, maybe @kschiffer has some useful UX insights before we just start implementing this.

**Comment by kschiffer** [comment]
We can implement this complementary to #4977. For this we'd need to extend the application model though to include  `network_server_address`, `application_server_address` and `join_server_address` as pointed out by @htdvisser. Then we can check those and hide such applications from the list, when all of the servers point to different clusters.

@htdvisser can you make the start with extending the application model or delegate this accordingly?

**Comment by htdvisser** [comment]
API and database models completed in [`issue/3830-app-server-address`](https://github.com/TheThingsNetwork/lorawan-stack/compare/issue/3830-app-server-address). 

@ryaplots you can continue working on that branch. Let me know if you need anything else.

**Comment by htdvisser** [comment]
Since this unfortunately didn't make it into v3.18.0, and this requires a database migration, we have to postpone it until the v3.19.0 release in April.

BTW: The branch was a bit outdated, so I rebased it.

**Comment by kschiffer** [comment]
Does anything speak against making this `network_server_address`, `application_server_address` and `join_server_address` assignment implicit in the creation form? Meaning that these fields will be set automatically without allowing any modification.

I feel like adding these fields explicitly to the application form will make it more confusing (even when hiding it in a advanced settings section). Also, I don't see any use case where a user would want to create an application for a different cluster.

**Comment by htdvisser** [comment]
No, that's totally fine.

**Comment by ryaplots** [comment]
> API and database models completed in [`issue/3830-app-server-address`](https://github.com/TheThingsNetwork/lorawan-stack/compare/issue/3830-app-server-address).
> 
> @ryaplots you can continue working on that branch. Let me know if you need anything else.

I pushed my work to the branch already

**Comment by htdvisser** [comment]
I'll rebase this and open a pull request for v3.19 after v3.18.2 is out.
