### ISSUE TITLE
Add cluster hints to End Devices

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3831]
#### Summary

I think it would be helpful to add cluster hints to end device lists and pages.

Related to https://github.com/TheThingsNetwork/lorawan-stack/issues/3830

#### What is already there? What do you see now?

With explicit linking gone, Applications in v3 are no longer explicitly linked (between Application Server and Network Server) in a specific cluster. This means that Applications can now contain devices in different clusters.

This cluster information is already known, as it's registered in the Identity Server. However, the Console doesn't display this information in places where I think it should. From what I can see, the only place where this information is used, is the "general settings" view:

<img width="1280" alt="Screen Shot 2021-02-19 at 09 12 18" src="https://user-images.githubusercontent.com/181308/108476649-937a7580-7292-11eb-9817-aa2546544ad5.png">

The End Device lists and overview pages, don't show this information:

| **List** | **Single** |
| --- | --- |
| <img alt="Screen Shot 2021-02-19 at 09 10 39" src="https://user-images.githubusercontent.com/181308/108476466-58784200-7292-11eb-94d3-211e756b9379.png"> | <img alt="Screen Shot 2021-02-19 at 09 12 38" src="https://user-images.githubusercontent.com/181308/108476676-9ecda100-7292-11eb-965f-a83f8dc67b3f.png"> |

While the Gateway views use this information better:

| **List** | **Single** |
| --- | --- |
| <img alt="Screen Shot 2021-02-19 at 09 15 21" src="https://user-images.githubusercontent.com/181308/108477028-008e0b00-7293-11eb-9e42-1e24a2f7b4fb.png"> | <img alt="Screen Shot 2021-02-19 at 09 15 49" src="https://user-images.githubusercontent.com/181308/108477085-10a5ea80-7293-11eb-8082-24b10b611e82.png"> |

#### What is missing? What do you want to see?

- It would be nice if we could show "Other cluster" in the End Device list, like we do for Gateways.
- Instead of "Last seen info unavailable", I'd like to see "Other cluster", like we do for Gateways.

#### Environment

The Things Network, The Things Stack Cloud and other multi-cluster deployments.

#### How do you propose to implement this?

I guess some copy-paste from the Gateway UI?

**Comment by kschiffer** [comment]
What needs to be done here (as a short term improvement) is:

1.  On device lists, gray out the device ID for devices on other clusters (also disable clicks)
2.  Show `Other host` as a status
3.  Add a tooltip to the status reading. See text below.
4.  Do not allow deleting or restoring such end devices
5.  Do not allow navigating manually to such end devices (redirect back to applications)

The tooltip should read:

> This end device is registered on a different cluster or host. It cannot be accessed using this Console. To access this device, use the Console of the cluster that this device was registered on.

The tooltip should also include a link to the documentation about clusters: https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/

**Comment by htdvisser** [comment]
> This end device is registered on {host}. It can not be accessed using this Console. To access this device, use the Console of {host}.
