### ISSUE TITLE
Show last seen in end device list

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3832]
#### Summary

There have been requests to show the "last seen" of an end device on the list page.

#### Why do we need this?

To get a quick overview of devices and when they were last active

#### What is already there? What do you see now?

The gateway list shows statuses, the device list shows created_at which is less useful.

#### What is missing? What do you want to see?

The device list to show a last_seen

#### How do you propose to implement this?

I guess it should be similar to what we do with the Gateway list, so for each row, we need a way to quickly get the `last_seen` of an end device (if it's active in the current cluster).

We may need new API and possibly database changes to accomplish this, as this may not be very performant with the current database models in the Network Server and Application Server.

What's explicitly out of scope is things like sorting and filtering on this `last_seen` as it would have to join the Identity Server database with the Network Server or Application Server database, which may be in a different cluster.

#### Can you do this yourself and submit a Pull Request?

@rvolosatovs please propose the most efficient way to get this data

**Comment by kschiffer** [comment]
See also #2436
