### ISSUE TITLE
Add UsedAt field to ContactInfoValidation

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#3833]
#### Summary

It would be helpful to add a `used_at` field to the `ContactInfoValidation` model so that we can tell the difference between "token not found" and "token already used".

#### What is already there? What do you see now?

Right now users are confused, because the Account app (?) tells them that "the validation token was not found" and that they should "contact an administrator".

Refs https://github.com/TheThingsIndustries/lorawan-stack-support/issues/318

#### What is missing? What do you want to see?

We should show users a different error message depending on whether the validation token was not found or already used.

#### How do you propose to implement this?

- Add a `used` field to the database model
- Check that before validating the contact info in `contactInfoStore.Validate`
- Set it after validating the contact info in `contactInfoStore.Validate`
- Maybe update the console, as this seems to be a custom error message (i.e. the Console doesn't just forward the error from the backend).

#### How do you propose to test this?

Unit tests

#### Can you do this yourself and submit a Pull Request?

For the Identity Server part, yes, for the Console, no.

**Comment by htdvisser** [comment]
Identity Server changes are in https://github.com/TheThingsNetwork/lorawan-stack/compare/v3.12...feature/3833-validation-token-used. Handing over Console part to @kschiffer.

**Comment by asmulko** [comment]
Looks like console handles this error correctly @htdvisser 

![image](https://user-images.githubusercontent.com/72162194/112015782-cc796480-8b34-11eb-920d-76763e532b0b.png)
