### ISSUE TITLE
Token refresh refused when leaving console open for long time

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#3838]
#### Summary

![Screenshot from 2021-02-21 10-08-02](https://user-images.githubusercontent.com/948278/108619391-3bc44180-742d-11eb-83f4-2d43f6eb0459.png)

#### Steps to Reproduce

1. Log into the console
2. Go to a device's details page
3. Leave this tab open for a couple of hours

#### What do you see now?

The screenshot above, after which I need to refresh the page to see something again.

#### What do you want to see instead?

Don't log me out while I have the tab open.

#### Environment

TTN v3.11.0

#### How do you propose to implement this?

...

#### How do you propose to test this?

Open a tab and leave it open for a day.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by jpmeijers** [comment]
I'm not sure if this is realted, but I had both TTN v3 and a private V3 instance open in my browser since about the same time yesterday afternoon. This morning both showed the same error screen:

![Screenshot from 2021-02-27 09-59-44](https://user-images.githubusercontent.com/948278/109381349-97397800-78e2-11eb-9f73-031aa11769b3.png)

Developer console shows an error:
![image](https://user-images.githubusercontent.com/948278/109381505-79204780-78e3-11eb-9850-0b70bac6fdb2.png)
![image](https://user-images.githubusercontent.com/948278/109381513-85a4a000-78e3-11eb-8a3b-e51754087ce3.png)


Logs from the private stack attached in case it's useful.
[stack-logs-202002271005.txt](https://github.com/TheThingsNetwork/lorawan-stack/files/6053939/stack-logs-202002271005.txt)

**Comment by johanstokking** [comment]
This looks pretty stale, let's triage

**Comment by johanstokking** [comment]
Please reopen if this issue still exists. There are more error details available in newer versions. Please paste the new error details as well.
