### ISSUE TITLE
Need to reauthorized every time I log in

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#3845]
#### Summary

Every couple of days I get logged out of the TTNv3 console. When I try to log in again, I have to re-authorize. Is this correct?

![image](https://user-images.githubusercontent.com/948278/108814891-42cd8a00-75bc-11eb-976c-ad003528e4c3.png)

#### Steps to Reproduce

1. Log into the console
2. Wait a couple of days
3. Try to go to the console and see you are logged out
4. Try to log in again

#### Environment

TTN v3.11.1

#### How do you propose to implement this?

Just document if this is the intended behaviour.

#### Can you do this yourself and submit a Pull Request?

I can update the docs if I know what the intended behaviour should be.

**Comment by bafonins** [comment]
This should be fixed now. With the latest update TTID wont request user consent for scopes and claims, but rather pre-authorize first party clients (lorawan-stack in this case). Please reopen if necessary.
