### ISSUE TITLE
How to send value without real device

### ISSUE THREAD

**Issue by Anjali-NEC** [TheThingsNetwork/lorawan-stack#3895]
Hi Team,

I want to test iotagent LoRaWAN with my dummy device data. I have followed the steps described in the below document.
https://fiware-lorawan.readthedocs.io/en/latest/users_manual/index.html
https://github.com/FIWARE-GEs/iotagent-lorawan/blob/master/docs/tutorialStm32TTN.md

Install iotagent-LoRaWAN using docker
Provisioning a device with attribute: temperature,
Now I want to check the flow is working correctly by sending the temperature value.
But I don't have the real device/sensor. I want to send data using my dummy device.

Please guide me how I can test with my dummy device?

**Comment by descartes** [comment]
Resolved on the forum - recommend closure as not an issue.
