### ISSUE TITLE
Validate the field mask per component in API implementation

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#39]
**Summary:** 

Validate the field mask per component in API implementation.

**What is already there? What do you see now?**

No checks.

**What is missing? What do you want to see?**

This issue is specifically about enforcing in the RPC service implementation that the given field mask is valid for the concerning component.

This is really per gRPC call. We can't use component-level checks, because the component may work with fields that it doesn't expose through the API. We can't use service-level checks, because some fields are valid for getters and not for setters.

I'm proposing the following:

```go
// Get implements ttnpb.AsEndDeviceRegistryServer.
func (as *ApplicationServer) Get(ctx context.Context, req *ttnpb.GetEndDeviceRequest) (*ttnpb.EndDevice, error) {
	if err := fieldmask.Validate(ctx, req.FieldMask, ttnpb.AsEndDeviceRegistryServerGetMask); err != nil {
		return nil, err
	}
...
```

Here, `fieldmask.Validate()` would return an error if the second parameter is not a subset of the second.

In this case, `ttnpb.AsEndDeviceRegistryGetMask` would be `[]string{"formatters"}`.

CC @htdvisser 

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1226 by @johanstokking

**Comment by htdvisser** [comment]
Closed by #167
