### ISSUE TITLE
V3 console Live Data event details - 404 url - please see our Data Formats

### ISSUE THREAD

**Issue by V999TEC** [TheThingsNetwork/lorawan-stack#3943]
#### Summary
If I use the v3 console to look at the Event Details within Live Data
there is a handy link to Data Formats following the text
"For more information on event message types, please see our Data_Formats"

Unfortunately the link is not so handy because it points to... 

https://thethingsindustries.com/docs/docs/reference/data-formats/ 
This gives 404 :-(

The link should be...
https://www.thethingsindustries.com/docs/reference/data-formats/

...

#### Steps to Reproduce

1. Load v3 console
2. Select an application
3. View the Live Data
4. Click on an event to see the Event details expanded on right panel
5. Scroll to bottom and there is a fault url to Data_Formats

**Comment by johanstokking** [comment]
@V999TEC thanks for reporting. If you want to make yourself immortal as a The Things Stack contributor, please submit a pull request. The concerning file is `pkg/webui/console/components/events/details/index.js`
