### ISSUE TITLE
Remove titles for checkbox inputs

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3945]
#### Summary
We moved to a vertical form layout via #3529. With this, it's no longer necessary to use titles for checkboxes but to only use the label.
#### Why do we need this?
This will reduce the cognitive load of forms and also shrink them in size.

#### What is already there? What do you see now?
Checkboxes like these:
![image](https://user-images.githubusercontent.com/5710611/111611224-817deb00-87dc-11eb-9fe7-5ee1597d7fc6.png)

#### What is missing? What do you want to see?
Checkboxes like these:
![image](https://user-images.githubusercontent.com/5710611/111611782-1ed91f00-87dd-11eb-9e5f-93d8ad9ae84d.png)

#### How do you propose to implement this?
Trivial. Mostly this comes down to replacing the `title` prop with the `label` prop. However the wording needs to be double checked. It needs to be in imperative tense and describe what the result of checking the checkbox is. To help with this, take the following sentence and complete it with the checkbox label:
`When this option is enabled, we will …`
e.g. `When this option is enabled, we will -> Enforce duty cycles`

#### How do you propose to test this?
Not necessary, this is not a functional change. We'll likely have to update some of the visual e2e tests with new labels.

#### Can you do this yourself and submit a Pull Request?
@asmulko please take the lead.

**Comment by kschiffer** [comment]
While at it, please also check the descriptions of checkbox inputs. They are sometimes misleading, e.g. 

![](https://user-images.githubusercontent.com/5710611/111613091-72983800-87de-11eb-9835-2e3658710959.png)

This could be misunderstood in a way that this is already activated. This should rather be `Controls whether the status of this gateway may be publicly displayed`. I think there are more of such issues throughout our forms.

**Comment by kschiffer** [comment]
Note that wrt to tooltips, this also means that since tooltips are usually displayed next to the field title, that we need to add a way for tooltips to be displayed next to the checkbox label instead.

**Comment by NicolasMrad** [comment]
this has to be done individually while updating the forms. it cannot be generalised that easy, as mentioned by @kschiffer
