### ISSUE TITLE
Use of application class B/C settings in Rx 1

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#396]
**Summary:** 

Use of application class B/C settings in Rx 1. These are only applicable to Rx 2; there is no uplink token so GS does not have the required timestamp.

**Steps to Reproduce:** 

1. Schedule class C application downlink with `class_b_c` settings without `absolute_time`

**What do you see now?**

NS attempt to schedule in Rx 1

**What do you want to see instead?**

- No attempt to schedule in Rx 1; this is Rx 2 only
- The fixed downlink path is optional; if those are not specified, the downlink path from recent uplink messages should be taken

**How do you propose to implement this?**

Remove scheduling in NS.

**Can you do this yourself and submit a Pull Request?**

Yes, at least a proposal

**Comment by htdvisser** [comment]
https://github.com/TheThingsNetwork/lorawan-stack/pull/410#discussion_r270768792
