### ISSUE TITLE
Location settings are broken

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#3983]
#### Summary
Setting locations for end devices or gateways is currently not possible when the entity has had no location before.

#### Steps to Reproduce
1. Go to a device or gateway without location
2. Go to the location tab
3. Observe the loading spinner for the map loading infinitely

#### What do you see now?
Locations cannot be set correctly.

#### What do you want to see instead?
Location settings working correctly.

#### Environment
v3.11.3

#### How do you propose to implement this?
Not sure, haven't looked into this in detail.

#### How do you propose to test this?
We have E2E that test setting locations with the map. I think they are not realistic enough currently, since they currently don't fail.

#### Can you do this yourself and submit a Pull Request?
@asmulko

**Comment by nejraselimovic** [comment]
@kschiffer @asmulko what is the status here? Does this issue still exist?

**Comment by kschiffer** [comment]
Issue is not present anymore.
