### ISSUE TITLE
Improve error message for failed initialization of Storage Integration

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#3984]
#### Summary
A customer reported failing initialization of the Storage Integration for TTS Open Source deployment. Storage Integration is not supported for this version of TTS, but we might think of accepting the suggestion to improve the error message to reflect that it's not an error, but that it is not supposed to work.

Ref: #3963 

#### What do you see now?
`unknown command "storage-db" for "ttn-lw-stack"
ERROR: 255`

#### What do you want to see instead?
Something more descriptive perhaps? @neoaggelos what do you think?

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by htdvisser** [comment]
As we just decided: we'll create a placeholder command that informs the user that the storage integration is not included in the open source edition of The Things Stack.
