### ISSUE TITLE
There is a typo in https://www.thethingsnetwork.org/docs/the-things-stack/migrate-to-v3.html

### ISSUE THREAD

**Issue by HouzuoGuo** [TheThingsNetwork/lorawan-stack#3992]
#### Summary
Hey! There's a typo on this article: https://www.thethingsnetwork.org/docs/the-things-stack/migrate-to-v3.html

"For OTAA device, you can simply do it by deleting your device from V2, however, this is not recommended - you might loose some data." should have read "might lose some data".

**Comment by nejraselimovic** [comment]
Addressed here: https://github.com/TheThingsNetwork/docs/pull/443
