### ISSUE TITLE
Add ISM2400 band support for Packet Broker

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsNetwork/lorawan-stack#3993]
#### Summary
Currently, Packet Broker doesn’t route traffic on `ISM2400` band. Request to support it.
#### Why do we need this?
Extend PB support for `ISM2400` too.
#### What is already there? What do you see now?

- PB supports the frequency bands listed here. Ref: https://github.com/TheThingsNetwork/lorawan-stack/blob/77f9c699f5f0b1b017c7d11cee377ab8cdd26615/pkg/packetbrokeragent/translation.go#L50-L61
- For `ISM_2400_3CH_DRAFT2`, currently, there is **Host `packetbroker` failed to handle message: Unknown band `ISM_2400`** error in the Gateway live data.

#### What is missing? What do you want to see?
Support for `ISM2400` frequency band via the packet broker.
#### Environment
TTS v3.11.3
#### How do you propose to implement this?
Modify the [Frequency band list](https://github.com/TheThingsNetwork/lorawan-stack/blob/77f9c699f5f0b1b017c7d11cee377ab8cdd26615/pkg/packetbrokeragent/translation.go#L50-L61) of the packet-broker accordingly. Not sure if any other changes required.
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by johanstokking** [comment]
This is fixed by https://github.com/TheThingsNetwork/lorawan-stack/pull/3982 and will land in 3.12.0.
