### ISSUE TITLE
Uplink DataRate should be nullable

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#3997]
#### Summary

Uplink DataRate should be nullable

#### Why do we need this?

To avoid storing redundant fields and improve API usage experience

#### What is already there? What do you see now?

Currently it is not, hence NS is forced to store it and clients are forced to set it (we only actually need the index)

#### What is missing? What do you want to see?

Make DataRate nullable, remove validation requirement

#### How do you propose to implement this?

Probably as part of #2798 , the value should be made nullable and the validation should be removed

#### How do you propose to test this?

Test all components affected with integration testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by htdvisser** [comment]
We don't need a separate issue for this specific option; we can indeed remove nullable=false as part of the GoGo issue.
