### ISSUE TITLE
Add option for C-Style uint32_t `0x00000000` representation for device address field

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#4014]
#### Summary
In the Console for a device, for the 'Device address' field add the uint32_t format 0x000000 as option.

In the Console for a device the 'Device address' field can be copied.
In C/C++ code the device address is usually defined as uint32_t type which requires the format 0x000000.
But this format is currently not available as one of the options.

#### Why do we need this?
Users coding in C/C++ cannot use a copy/pasted device address value because it is in the wrong format so they have to manually change the the format of the pasted device address value after each copy/paste action.
This is very impractical. Copy/paste should just work without having to make any manual changes after the paste.

#### What is already there? What do you see now?
By default the device address is shown as a sequence of bytes separated by a space:
![capture 2021-04-02 14·00·42](https://user-images.githubusercontent.com/40600181/113414015-41159400-93bc-11eb-8458-96b4929a32f9.png)

It is also possible to display and copy it in C/C++ msb and lsb formats:
![capture 2021-04-02 14·00·47](https://user-images.githubusercontent.com/40600181/113414091-728e5f80-93bc-11eb-8fbf-e8552fd8c0f3.png)

![capture 2021-04-02 14·00·50](https://user-images.githubusercontent.com/40600181/113414096-75895000-93bc-11eb-9f2c-10fcf916ced7.png)

#### What is missing? What do you want to see?
Add a format option for uint32_t type with a value looking like: 0x26011FD6

#### Environment
_Not relevant._

#### How do you propose to implement this?
Add the format option as described.

#### How do you propose to test this?
\-

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by kschiffer** [comment]
Thanks for filing this issue @lnlp 

I think what we can do here is to allow a third representation for the format toggle. This would mean that the format toggle would cycle through hex, array, and uint32\_t notation. This third option should be disabled by default, so we can overwrite the setting for the device address only.

**Comment by lnlp** [comment]
> This third option should be disabled by default, so we can overwrite the setting for the device address only.

It's not clear what you mean. There is nothing that needs to be _disabled_.  Maybe you just mean that the uint32_t type should not be the format that is shown as default?


> This would mean that the format toggle would cycle through hex, array, and uint32_t notation.

Yes. But there is nothing to '_disable_ by default' here.

**Comment by kschiffer** [comment]
Sorry, these were more implementation notes for ourselves.

What I mean is that it should not be possible to toggle into the `uint32_t` notation by default, but only for specific fields, such as the device address.

**Comment by lnlp** [comment]
> but only for specific fields, such as the device address.

This relates to the device address only because only the device address fits in a scalar C/C++ data type.
The other keys all require use of an array.
