### ISSUE TITLE
Store recent data application uplinks in the Application Server

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4018]
#### Summary

The Application Server should store, in a FIFO fashion, the application data uplinks sent by the end device.

#### Why do we need this?

Certain integrations may want to query the last received data uplinks. Since we would like to avoid enabling the storage integration just for this, we could bring back the `recent_uplinks` field of `ttnpb.EndDevice`:

https://github.com/TheThingsNetwork/lorawan-stack/blob/e37d779528c17aabf33d9149c5603e31e9206217/api/end_device.proto#L534

#### What is already there? What do you see now?

The storage integration keeps these uplinks in long term storage.

#### What is missing? What do you want to see?

The Application Server should store, either as part of the end device, or of the session, the last 16 application data uplinks.

#### Environment

`v3.12`

#### How do you propose to implement this?

Add the API field, save the uplinks as part of `as.handleUplink`, and allow frontends to query the recent uplinks via `io.Server`.

#### How do you propose to test this?

Send some real uplinks from and end device and check that they are stored.

#### Can you do this yourself and submit a Pull Request?

Yes. cc @johanstokking

**Comment by adriansmares** [comment]
Blocking https://github.com/TheThingsNetwork/lorawan-stack/issues/4019

**Comment by htdvisser** [comment]
Since https://github.com/TheThingsNetwork/lorawan-stack/issues/4019 is now planned for 3.12.2, this one can also be moved
