### ISSUE TITLE
WiFi query support for LoRaCloud GLS

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4020]
#### Summary

References https://www.loracloud.com/documentation/geolocation?url=v2.html#singleframe-wi-fi-tdoa-request

We should support the v2 LoRa WIFI query type.

#### Why do we need this?

In order to support WiFi queries as part of our integration.

#### What is already there? What do you see now?

Only v3, single-frame, queries using `TOARSSI`.

#### What is missing? What do you want to see?

1. A new query type, `WIFITDOA`, that should do a single frame v2 WiFi request.
2. `api` package support for this type of request.

#### Environment

`v3.12`

#### How do you propose to implement this?

Add the new query type, implement the WiFi request query (so structs + API function), and use it on uplink handling.

#### How do you propose to test this?

This is tricky. We'll need to lookup some example queries and use them.

#### Can you do this yourself and submit a Pull Request?

Yes. cc @johanstokking

**Comment by htdvisser** [comment]
Since @adriansmares is off today, and it isn't in progress yet, this isn't going to make today's deadline, so moved to v3.12.2.
