### ISSUE TITLE
Space after username fails to log in

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#4048]
#### Summary

If I use my email address to log in (The Things ID), and my browser's auto fill added a space after the email address, I fail to log in. Deleting the space after the email address works. This happens sometimes on a mobile phone where the keyboard automatically adds a space after every work.

#### Steps to Reproduce

1. Log out
2. Try and log in, but add an extra space after the username
3. ...

#### What do you see now?

Fails to log in

#### What do you want to see instead?

Strip whitespace and let me log in

#### Environment

TTS Community Edition v3.11.3

#### How do you propose to implement this?

Strip whitespace around username

#### How do you propose to test this?

Same as how I reproduces this

#### Can you do this yourself and submit a Pull Request?

No

**Comment by nejraselimovic** [comment]
@bafonins please do this in TheThingsID repo
