### ISSUE TITLE
Make gateway & application names searchable

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#4056]
#### Summary
As of now, you can only search on GatewayID or ApplicationID, not on the Name of Gateways of Applications.

#### Why do we need this?
Easy to find gateways or applications

#### What is already there? What do you see now?
Search for GatewayID or Application ID

#### What is missing? What do you want to see?
Search for Gateway name or Application name

#### Environment
V3.12

#### How do you propose to implement this?
Extend searchable fields

**Comment by benolayinka** [comment]
+1 from customer feedback for this. I think this is worth adding a milestone to, since functionality already exists in the backend. @kschiffer @bafonins ?

**Comment by benolayinka** [comment]
Also in the long term, making all attributes and fields searchable would be really helpful.

**Comment by pgalic96** [comment]
I remember a discussion about searching through all fields. The issue was that a search for a different field results in a somewhat different api call, and this needed some UX thought before implementation, cc @kschiffer

**Comment by kschiffer** [comment]
Yes, so we currently cannot search by ID **and** name, so the only way forward is implementing an advanced search feature that allows searching by different properties. This can be tracked here: #1825

**Comment by htdvisser** [comment]
We've been discussing multiple things:

1. The "advanced search" functionality where users can search on fields other than the ID, which would be implemented in the Console as something like GMail's advanced search:
 
<img width="705" alt="Screen Shot 2021-10-11 at 13 35 42" src="https://user-images.githubusercontent.com/181308/136783607-6645d703-7fdb-4727-878f-b9dd57eb6669.png">

This would just fill the fields of the existing search requests.

This is basically what's tracked in #1825.

---

2. The "universal search" functionality where a single Spotlight-like search input (in the top of the Console) would magically search for all applications, gateways, end devices, etc. that contain the given text in any of their fields (id, euis, name, description, attributes, ...).

I don't think we have an issue for this yet.

**Comment by pgalic96** [comment]
Closed because separate issues are merged together #1825

**Comment by pgalic96** [comment]
Closed because separate issues are merged together #1825
