### ISSUE TITLE
Error when installing CLI using homebrew

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-stack#4062]
#### Summary
After running:
`$ brew install TheThingsNetwork/lorawan-stack/ttn-lw-stack`

This error occurs:

```
ERROR: An exception occurred within a child process 
 Errno: :ENOENT: No such file or directory - public
```

#### Steps to Reproduce

1. Run: brew install TheThingsNetwork/lorawan-stack/ttn-lw-stack

#### What do you see now?
![Screenshot 2021-04-15 at 17 11 26](https://user-images.githubusercontent.com/17290639/114989886-3406a380-9e98-11eb-8b5d-0cfa863ae547.png)

#### What do you want to see instead?
Successful installation of the CLI

#### Environment
v3.12

#### How do you propose to implement this?
1. Find the cause of this issue. 
2. Update the homebrew installation, or update the documentation if this issue relates to the user

#### How do you propose to test this?
Reinstalling the CLI

**Comment by htdvisser** [comment]
This was fixed in v3.12.1 (https://github.com/TheThingsNetwork/lorawan-stack/pull/4040)
