### ISSUE TITLE
Users without Edit device key rights don't realize why they can't add an AppKey

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#4071]
#### Summary

https://www.thethingsnetwork.org/forum/t/adding-a-device-in-tts-3-11-2-cannot-add-appkey/46208/10

It's not very clear why users can't add device keys if they don't have key rights in an application.

**Comment by nejraselimovic** [comment]
@kschiffer what is the plan on implementing this? Will it be just some kind of banner saying "You need Edit device key rights to add an AppKey" or something bigger?

**Comment by kschiffer** [comment]
Indeed, the device key input should not be hidden but disabled together with a warning explaining why that is.

Assigning this to @bafonins

**Comment by kschiffer** [comment]
I also suggest to bump this to a timely milestone. @nejraselimovic
