### ISSUE TITLE
Error when send downlink to device with Class A and Class C.

### ISSUE THREAD

**Issue by viethoa14** [TheThingsNetwork/lorawan-stack#4094]
#### Summary

Now when we use cellular network for TTN, we saw sometime error when NS send downlink to end-device on class A but with class C, we saw many error. Show log on gateway, we saw error report "Packet REJECTED, timestamp seems wrong, too much in advance"
...

#### Steps to Reproduce

1. Make "Schedule downlink" to end-device class C
2. Show log on "console server"
3. No response from end-device to NS  

#### What do you see now?

this is log when we show on Kerlink gateway 

Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> Downlink message (0017) received
Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> Received downlink message:
Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> | lora downlink (00000017), payload 16 B, required 1, preamble 8 B, header enabled, crc disabled, polarity inverted
Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> | Unconfirmed Data Down, DevAddr FC005357, FCtrl [ADR], FCnt 1969, FPort 2
Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> |  - radio (00000000), channel 921.4 MHz, bw 125 kHz, sf 10, cr 4/5, power 20 dB
Apr 28 10:04:41 Wirnet local1.info lorafwd[1226]: <6> |   - transmission (00000000), priority 1, on counter 3138729107
Apr 28 10:04:41 Wirnet local1.info lorad[868]: <6> Received downlink message
Apr 28 10:04:41 Wirnet local1.err lorad[868]: <3> Packet REJECTED, timestamp seems wrong, too much in advance (current=3138816049, packet=3138729107, type=0)
Apr 28 10:04:41 Wirnet local1.err lorad[868]: <3> Failed to enqueue downlink message

Ping test from NS to GW when send downlink:
64 bytes from 172.30.19.9: icmp_seq=640 ttl=64 time=76.8 ms
64 bytes from 172.30.19.9: icmp_seq=641 ttl=64 time=78.8 ms
64 bytes from 172.30.19.9: icmp_seq=642 ttl=64 time=53.9 ms
64 bytes from 172.30.19.9: icmp_seq=643 ttl=64 time=97.9 ms
64 bytes from 172.30.19.9: icmp_seq=644 ttl=64 time=2446 ms
64 bytes from 172.30.19.9: icmp_seq=645 ttl=64 time=1454 ms
64 bytes from 172.30.19.9: icmp_seq=646 ttl=64 time=506 ms
64 bytes from 172.30.19.9: icmp_seq=647 ttl=64 time=95.2 ms
64 bytes from 172.30.19.9: icmp_seq=648 ttl=64 time=414 ms
64 bytes from 172.30.19.9: icmp_seq=649 ttl=64 time=567 ms
64 bytes from 172.30.19.9: icmp_seq=650 ttl=64 time=83.2 ms
64 bytes from 172.30.19.9: icmp_seq=651 ttl=64 time=217 ms
64 bytes from 172.30.19.9: icmp_seq=652 ttl=64 time=98.2 ms
64 bytes from 172.30.19.9: icmp_seq=653 ttl=64 time=203 ms

#### What do you want to see instead?

...

#### Environment

We test  with Lorawan stack 3.11.3 -> Lorawan stack 3.12.1
Gateway: Kerlink Wirnet Station, ver 3.6, cpf 1.1.6. We tried enable or disable "Schedule downlink late" 
Device: version MAC 1.0.2, regional parameters version PHY V1.0.2 REV A

#### How do you propose to implement this?

1. We can not know problem with Lorawan'config or not. When we use other provider with same infrastructure, this issue is disappear.
2. We must change parameter Lorawan'config, Gateway'config, clock ...or not  

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by johanstokking** [comment]
> Packet REJECTED, timestamp seems wrong, too much in advance (current=3138816049, packet=3138729107, type=0)

Looking at this difference, expressed in microseconds, the packet is 0.086942 ms too late. I'm afraid this is caused by spikes in the latency: up to 2.4 seconds in your excerpt of the ping output.

Indeed, the "schedule late" functionality is designed for this. By default, this is 800 milliseconds. For your backhaul, it should be somewhere closer to 2000 milliseconds. Now, this does mean that there is less time for the network and the application layer to generate downlink messages. You need an RX1 delay of at least 5 seconds (which is the default in The Things Stack).

**Comment by viethoa14** [comment]
Thanks for your support!
When packet don't send, delay for backhaul around 100ms but when we send downlink or end-device send uplink, sometime delay will increase.  
When delay 100ms, we still see error when schedule downlink.
(config for schedule:  
gs:
   ...........
  udp:
    rate-limiting:
      enable: 'true'
      messages: '10'
      threshold: '10ms'
    schedule-late-time: '2000ms'
)

Beside we see warning on server'log: "stack_1      | redis: 2021/04/29 10:38:43 commands.go:36: specified duration is 789ms, but minimal supported value is 1s - truncating to 1s" , now we are using redis server version 6.0.12 (Redis version=6.0.12, bits=64, commit=00000000, modified=0, pid=1, just started)
Is there any connection between the two problems?

**Comment by johanstokking** [comment]
> When packet don't send, delay for backhaul around 100ms but when we send downlink or end-device send uplink, sometime delay will increase.
> When delay 100ms, we still see error when schedule downlink.

The delay with cellular backhaul isn't constant. It isn't related to sending uplink and downlink messages. It's inherent to how 3G works.

> Beside we see warning on server'log: "stack_1 | redis: 2021/04/29 10:38:43 commands.go:36: specified duration is 789ms, but minimal supported value is 1s - truncating to 1s" , now we are using redis server version 6.0.12 (Redis version=6.0.12, bits=64, commit=00000000, modified=0, pid=1, just started)
> Is there any connection between the two problems?

Yes, but that's ok.
