### ISSUE TITLE
Change the pop-up message when deleting the device from the console.

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsNetwork/lorawan-stack#4100]
#### Summary
While deleting the end-device from the console, the pop-up message in the console displays that we cannot reuse the `device ID`.

#### Steps to Reproduce
1. Create a device in the console
2. Delete the device via console

#### What do you see now?
While deleting the device via console, you will observe the pop-up message as `Are you sure you want to delete "xxx"? This action cannot be undone and it will not be possible to reuse the end device ID`.
![device-id_deletion](https://user-images.githubusercontent.com/65446107/116532204-a1392080-a8fd-11eb-9643-b2aaede92dc0.png)

#### What do you want to see instead?
In TTS V3, when an end device is deleted, the ID and EUI are released, and we can reuse them. Remove the notification as it is no more needed.
Ref: https://www.thethingsindustries.com/docs/reference/id-eui-constraints/

#### Environment
TTS v3.12.1

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?
No. @kschiffer

**Comment by kschiffer** [comment]
As far as I understand, entity IDs should not be immediately reusable but only after a retention period. The notification itself is still necessary, since the action cannot be currently undone (at least not via the Console).

#4117 will change the wording to reflect that.
