### ISSUE TITLE
MIC check fails when sending application downlink after MAC downlink

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#414]
**Summary:** 

MIC check on the end device fails when an application downlink is queued after sending MAC layer downlink.

**Steps to Reproduce:** 

1. Join device in `1.0.2`
2. Have some MAC layer downlink happen (i.e. confirmed up, no app down)
3. Enable class C
4. Send an application downlink message

**What do you see now?**

MIC check fails on the end device.

This because currently, only when there's application payload queued, NS sends queue invalidation.

**What do you want to see instead?**

Successful downlink.

**How do you propose to implement this?**

1. NS should check whether the dequeued application downlink `FCnt` is higher than `LastNFCntDown` and if the session key ID equals
2. NS should check the pushed/replaced downlink messages also have higher `FCnt` than what's in `LastNFCntDown`
3. NS should send an invalidation event also with an empty application downlink queue so that AS has the right `NFCntDown`

**Can you do this yourself and submit a Pull Request?**

Yes, probably

**Comment by pdubois22** [comment]
related to #357 ?

**Comment by johanstokking** [comment]
@pdubois22 very likely the same thing indeed.
