### ISSUE TITLE
Accept and convert MAC address to Gateway EUI

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#4149]
#### Summary

Some (DIY) gateways don't come with an EUI. For these gateways it could be nice if the Console would let users enter the MAC address of the gateway instead, and would then automatically fill the `FFFE` in the middle.

#### Background

> A MAC address can be turned into an EUI by inserting `FFFE` in the middle (e.g., `HH:HH:HH:HH:HH:HH` → `HH-HH-HH-FF-FE-HH-HH-HH`).

Source: https://doc.sm.tc/station/glossary.html?highlight=fffe#term-mac

#### What is already there? What do you see now?

Only a field for the EUI, and lots of questions on the Forum.

#### What is missing? What do you want to see?

Some assistance

#### How do you propose to implement this?

Perhaps we can add an event listener, that, when the EUI field loses focus, checks the length of the field, and when it's 12, would show a "convert this MAC address to an EUI" that users can click. When clicked, this would fill the `FFFE` in the middle.

#### How do you propose to test this?

E2E tests perhaps?

**Comment by kschiffer** [comment]
Let's do as follows:

1. Debounce the EUI value using our `useDebounce` package, obtaining the current value from the form context
2. Use an effect hook to monitor the value having only 12 characters
3. This way, if the user stops entering the EUI after 12 characters (after debouncing for 3 seconds)
4. Show a warning under the field (using the field warning) `It looks like you have entered a MAC address instead`
5. Show button next to the field to show `Convert MAC to EUI`
6. When clicking it, the EUI will be augmented with the `FF FE` value in the middle
7. The button will disappear again

Here's a small mockup:
<img width="546" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/d8510881-108a-44b8-a133-d6d4144544c5">
<img width="573" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/39ed7671-98c9-4890-a9fd-63d83b718332">
Then, after clicking the button:
<img width="556" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/d87d718e-913a-4f09-b6f6-c98ad6f2683d">

**Comment by KrishnaIyer** [comment]
This can be a good first issue right @kschiffer?
