### ISSUE TITLE
Support re-using profiles from other vendors in Device Repository

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#4161]
#### Summary

Support re-using profiles from other vendors in Device Repository.

References https://github.com/TheThingsNetwork/lorawan-devices/issues/130 https://github.com/TheThingsNetwork/lorawan-devices/pull/162

#### Why do we need this?

See https://github.com/TheThingsNetwork/lorawan-devices/issues/130.

#### What is already there? What do you see now?

No support for `vendorID` in profiles.

#### What is missing? What do you want to see?

Support for `vendorID` in profiles.

#### Environment

3.12.3

#### How do you propose to implement this?

Extend internal structs that parse the device repo, use the `vendorID` field if present.

#### How do you propose to test this?

Unit tests.

#### Can you do this yourself and submit a Pull Request?

Yes. Targetting 3.13.0 as this is an API change and should be simple enough to implement.

**Comment by johanstokking** [comment]
You have too many issues assigned to 3.13.0; taking this over
