### ISSUE TITLE
Add "last X minutes" parameter to Storage Integration API

### ISSUE THREAD

**Issue by moramos13** [TheThingsNetwork/lorawan-stack#4198]
#### Summary

On V2 Storage Integration API it was possible to add a "last X minutes" parameter on the API call.
...

#### Why do we need this?

This will be a good feature because currently the LNS sends all the stored uplinks to application, where are processed and the redundant data is erased. Also, to send all the messages stored on the Storage Integration to the application on every API call is a waste network resources.
...

#### What is already there? What do you see now?

Currently, only this calls can be made: 

GET /api/v3/as/applications/{end_device_ids.application_ids.application_id}/devices/{end_device_ids.device_id}/packages/storage/{type}

GET /api/v3/as/applications/{application_ids.application_id}/packages/storage/{type}
...

#### What is missing? What do you want to see?

A parameter specifying that it's only needed to retrieve messages on the "last X minutes" .
...

#### Environment

...

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by descartes** [comment]
Whilst I can calculate the 'after' date, many of my more simplistic original scripts pull the data on a regular basis and just use a bit of overlap - so this would be useful. It also facilitiates a "I just want to see the last couple of hours uplinks for debugging purposes" type utility.

If this gets scheduled for a much later release, in the meanwhile I'll probably end up with some sample code to do this using the after field for Python, PHP & JavaScript anyway as I migrate my toolkit

**Comment by nejraselimovic** [comment]
@johanstokking what do you think about this?

**Comment by johanstokking** [comment]
I can imagine that this is very useful indeed.

@neoaggelos please triage.
