### ISSUE TITLE
Harmonize testing of RPC servers

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#42]
**Summary:** 

Harmonize testing of RPC servers.

**Why do we need this?**

To be consistent across the codebase.

**What is already there? What do you see now?**

Two classes of inconsistencies;

1. Direct invocation of RPC exposed methods vs creating a client to call RPC services
2. Overriding an RPC server by a test sink vs spawning mock cluster peers

**What is missing? What do you want to see?**

In general, I prefer a more "black box testing" approach; i.e. outside testing over inside hooks. This is still unit testing, but then the component from outside.

Regarding the two inconsistencies described above, I prefer;

1. Creating a client to call RPC servers, because this will include the interceptors for security, validation, etc. This may be or become functionally or non-functionally important to include in testing.
2. Spawning mock cluster peers, because this will include the asserting the outgoing context, again for security, and does not skip client RPC code that is relevant for testing

**How do you propose to implement this?**

The occurrences of 1 and 2 are only in the NS and JS. @rvolosatovs if you agree with this approach, please list the tests that are relevant, and work with @M-Gregoire or yourself to harmonize this.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1361 by @johanstokking

**Comment by johanstokking** [comment]
Blocks #192

**Comment by rvolosatovs** [comment]
@johanstokking the only tests blocking #192 are in AS, which according to the description of this issue should not have issues.
I don't think this issue has anything to do with #192

**Comment by johanstokking** [comment]
The main objective of this issue is harmonization. If the test implementation of AS needs to be changed to close this issue and resolve issues seen in #192, then that would be best.

**Comment by rvolosatovs** [comment]
@KrishnaIyer please take care of AS, GS
I will take care of NS and JS

**Comment by KrishnaIyer** [comment]
GS is already done. @adriansmares AS at your own leisure.. 💯

**Comment by johanstokking** [comment]
@adriansmares please check which parts of AS should be addressed. The explicit dialing of the linking is (partly) on purpose, to test an AS dialing to an external NS. However, for in cluster testing, you may want to use the loopback connection.

With @KrishnaIyer's comment, removing GS label.

@rvolosatovs please check if JS is still relevant; that one may be done as well?

**Comment by johanstokking** [comment]
Not blocking #192 anymore

**Comment by rvolosatovs** [comment]
NS part is done

**Comment by adriansmares** [comment]
AS done as of #898

**Comment by adriansmares** [comment]
Finished as of #898.
