### ISSUE TITLE
Console uplink data: show data rate in stead of bandwidth

### ISSUE THREAD

**Issue by kersing** [TheThingsNetwork/lorawan-stack#4219]
#### Summary
Please show the data rate in the live data summary of uplinks in the console. The data rate implies the bandwidth (because it is defined in the regional parameters) and additionally indicates the spreading factor.

#### Why do we need this?
Currently the only way to view the data rate and/or spreading factor is to open an uplink packet and search it in the huge amount of data shown. Reading and searching takes time when this is basic information regarding a nodes performance that should be available at a glance.

#### What is already there? What do you see now?
Currently the bandwidth is listed which is not very useful as it is (at least for EU868) fixed anyway.
Uplink line:

DevAddr 26014811 FCnt 10654 FPort   2 MAC payload 4FF554BE6C7B69 Bandwidth 125000 SNR 9.5 RSSI -85 Raw payload...

#### What is missing? What do you want to see?
The data rate.

#### Environment
N.a.

#### How do you propose to implement this?
Replace bandwidth with data rate.

#### How do you propose to test this?
Look at live data view of a gateway or an application/device

#### Can you do this yourself and submit a Pull Request?
Probably but I suspect the UI designers do it in <10% of the time it takes me.

**Comment by nejraselimovic** [comment]
@kersing this does seem useful! @kschiffer could we do this?

**Comment by htdvisser** [comment]
I think what's most useful for users is to combine the `bandwidth` and `spreading_factor` to a single string such as `SF7BW125`.
