### ISSUE TITLE
Proposed Url (link) to Storage Integration for Devices is incorrect (Console)

### ISSUE THREAD

**Issue by PeterH61** [TheThingsNetwork/lorawan-stack#4248]
**Summary**
The displayed url (link) for the access to the Storage Integration data concerning devices is incorrect on the console.

**Why do we need this**
Avoiding wrong access scripts, unnecessary user requests and forum entries.

**What is already there? What do you see now?**
„api/v3/as“ is generated twice, see marked area in the Storage Integration Console screenshot:

![Storage Integration](https://user-images.githubusercontent.com/48947269/121385484-6f2dcc00-c949-11eb-8054-449e0ddd46ae.jpeg)

**What is missing? What do you want to see?**
Correct url (link) generation.

**How do you propose to document this?**
As above.

**Can you do this yourself and submit a Pull Request?**
n.a.

**Comment by neoaggelos** [comment]
Thank you for filing this issue, the fix is merged and will be part of the 3.13.2 release.
