### ISSUE TITLE
Redirect user back to login page when an invalid token is detected

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#426]
**Summary:** 
The console should make sure the user is being sent back to the login screen once his token has expired or invalidated, as well as clearing all user data. This already happens on initial load, but since the console is a single page app, an invalid token can cause trouble at any point after the initial page load.

**Steps to Reproduce:** 
1. Log into the console
2. Open another console tab
3. Logout in one tab
4. In the other tab, try to perform any action that will trigger an API request (eg. list applications)
5. The requested action will result in an error

**What do you see now?**
The console stopping to work properly

**What do you want to see instead?**
The console redirecting the user back to the login page, once it notices that it can no longer obtain a valid token.

**Environment:**
Browser.

**How do you propose to implement this?**
We currently use the `with-auth.js` wrapper component to check whether the store has a `user` object. If the object is not present, and the tree is wrapped around the `<withAuth />`-component, he/she will be redirected to the login page via react router. We could make use of this logic by clearing the user store, once the token cannot be retrieved anymore.
One issue here would be that the store will still hold all (potentially sensitive) data associated with the user.
Alternatively, we could simply trigger a hard page reload, which would also result in a redirect to the login page, since the console would not be able to get the user data.
Another question to solve is where to make the token check and where to trigger the corresponding redirect/reload logic.

**Can you do this yourself and submit a Pull Request?**
I can do this, once we agreed on a way to go.

cc @bafonins

**Comment by johanstokking** [comment]
Consider using `exp` or something like that (time to expiration)
