### ISSUE TITLE
Handle rate limiting errors in JSSDK (Console) and CLI

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack#4270]
#### Summary

When receiving an error of type `ResourceExhausted` from a gRPC call, the CLI fails with an error message.

#### Steps to Reproduce

1. Configure TTS Rate limiting
2. Repeat an action and exceed the configured rate limit.

#### What do you see now?

The CLI fails with an error message. TTS returns `x-rate-limit-*` headers 

#### What do you want to see instead?

The CLI should be able to handle such a case.

#### Environment

3.13.1

#### How do you propose to implement this?

Wait for `x-rate-limit-retry` seconds and then retry the RPC. We can enforce this with flags (maybe `--retry N`) so that the CLI ultimately fails after N tries.

We might need to take some care into situations where this is not easy to enforce (e.g. setting a device on AS success but fails on NS).

#### How do you propose to test this?

Local testing.

#### Can you do this yourself and submit a Pull Request?

I can do the CLI part.

**Comment by johanstokking** [comment]
You probably also want to round up the `x-rate-limit-retry` value while you're at it. A value of `0.8` gets truncated to `0` which results in another 429.
