### ISSUE TITLE
Incorrect redirect URL for user profile settings in TTSC

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsNetwork/lorawan-stack#4275]
#### Summary
For TTS Cloud hosted deployments, if we click on `Profile settings` in the user dropdown, we will be redirected to a Cluster picker page. And, after entering the required details, we are seeing an error page with `The page you requested cannot be found` error message.

#### Steps to Reproduce
1. Under the User dropdown menu, select `Profile settings`
2. In the cluster picker page, enter the Tenant ID and choose a cluster.

#### What do you see now?
An error page with `The page you requested cannot be found` error message.
![image](https://user-images.githubusercontent.com/65446107/122186135-58d4c280-ceab-11eb-93e4-67252221c918.png)

#### What do you want to see instead?
Users should be able to access their profile settings.

#### Environment
The Things Stack Cloud v3.13.1

#### How do you propose to implement this?
We see that the current redirect URL from the cluster picker page is wrong and hence the reason for the error page. So, replacing the current redirect URL with the correct ones as below will resolve the issue.

Current redirect URL:
```
https://<tenant-id>.eu1.cloud.thethings.industries/console/oauth/profile-settings
```
Working redirect URL:
```
https://<tenant-id>.eu1.cloud.thethings.industries/oauth/profile-settings
```
2. Also, we don't think redirecting to a cluster picker to access the profile settings is a good way. Instead, we can redirect the users to the profile settings page just as we do in TTS CE `eu1` cluster.

#### How do you propose to test this?
...

#### Can you do this yourself and submit a Pull Request?
No, @kschiffer

**Comment by kschiffer** [comment]
This will be fixed via: TheThingsIndustries/lorawan-stack#2778 likely in the next release.

Closing this as such.
