### ISSUE TITLE
Error while starting the things stack "Cannot connect to idenity server"

### ISSUE THREAD

**Issue by justinbyerss** [TheThingsNetwork/lorawan-stack#4294]
#### Summary

Error connecting to identity server database

I previously had the TTS up and running, I reinstalled my OS on my PC and have used the same method I used before with no luck.

[ttn-lw-stack-docker.txt](https://github.com/TheThingsNetwork/lorawan-stack/files/6691269/ttn-lw-stack-docker.txt)
![tts error](https://user-images.githubusercontent.com/83960583/122868940-e4989400-d36e-11eb-997a-cb2c78bf36c7.JPG)

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?

...

**Comment by neoaggelos** [comment]
Hi @justinbyerss

This looks like an issue with the database container. Can you see if the database is running?

What's the output of the following commands?

```bash
$ sudo docker-compose ps
$ sudo docker-compose logs cockroach
```

It might help if you also run

```bash
$ sudo docker-compose up -d redis cockroach
```

before running any other commands, so that Redis and CockroachDB have time to properly start and become ready to accept connections.

**Comment by justinbyerss** [comment]
> Hi @justinbyerss
> 
> This looks like an issue with the database container. Can you see if the database is running?
> 
> What's the output of the following commands?
> 
> ```shell
> $ sudo docker-compose ps
> $ sudo docker-compose logs cockroach
> ```
> 
> It might help if you also run
> 
> ```shell
> $ sudo docker-compose up -d redis cockroach
> ```
> 
> before running any other commands, so that Redis and CockroachDB have time to properly start and become ready to accept connections.

Thanks for your assistance.  I did a clean install on my PC in hope to resolve the issue.  I have managed to get past that issue but now I cannot get past this.

I have followed the online procedure step by step.
![Capture](https://user-images.githubusercontent.com/83960583/122920736-0ca2ea00-d3a5-11eb-8f29-335bdc360b95.JPG)

**Comment by neoaggelos** [comment]
How are you trying to connect to the Console (`http` or `https`)? Also, which Docker tag are you using for the `thethingsnetwork/lorawan-stack` image?

**Comment by justinbyerss** [comment]
> How are you trying to connect to the Console (`http` or `https`)? Also, which Docker tag are you using for the `thethingsnetwork/lorawan-stack` image?

I am using the latest tag for all three containers.  I just tried using https and it worked.  It didn't seem to like Http.

**Comment by neoaggelos** [comment]
This should be fixed with https://github.com/TheThingsNetwork/lorawan-stack/pull/4303.

Closing the issue, please re-open if the issue persists with the new version.
