### ISSUE TITLE
DevNonce compared against MaxUint32 when it's a 16 bit field

### ISSUE THREAD

**Issue by Bwooce** [TheThingsNetwork/lorawan-stack#4307]
I'm not sure why the DevNonce gets uplifted to a 32bit int, but it surely shouldn't be compared to maxUint32 when it was originally a 16 bit field?

This'll fail safe on wrap around (if the device does that) anyway since it'll be < the last recorded DevNonce, but the error will be incorrect. 

https://github.com/TheThingsNetwork/lorawan-stack/blob/c10045bac4b699b3e89a175a2e3391555d2f6fc4/pkg/joinserver/joinserver.go#L370

**Comment by johanstokking** [comment]
You're right, thanks for reporting. The DevNonce is indeed 16 bits.

We're scaling it to `uint32` as that is how they're declared in our data structures; protocol buffers don't support 16 bits integers.

Now, that check is ineffective and can be removed. There's never a too high DevNonce.
