### ISSUE TITLE
Location setting doesn't allow longitude of selected position

### ISSUE THREAD

**Issue by aparcar** [TheThingsNetwork/lorawan-stack#4326]
#### Summary

I setup a node on Oahu, Hawaii and tried to add it's location via the web interface. Clicking at the destination results in a Longitude of ~200 something, while it's real location is on Longitude 157.x. The web interface doesn't support the input (must be within +/-180).

#### Steps to Reproduce

Try to use the map to set the location somewhere on the Hawaiian Islands.

#### What do you see now?

![image](https://user-images.githubusercontent.com/16000931/123577091-e4353a00-d76e-11eb-98d6-8ca0b69c4bff.png)

Setting the Longitude manually to the correct value results in a destination within the ocean (wrong):

![image](https://user-images.githubusercontent.com/16000931/123577206-13e44200-d76f-11eb-9551-fad1a26691f0.png)

#### What do you want to see instead?

The correct Longitude.

#### Environment

Latest Firefox.

#### How do you propose to implement this?

Fix the map data provider

#### How do you propose to test this?

-

#### Can you do this yourself and submit a Pull Request?

Not really, I'm not familiar with OSM/Leaflet.

**Comment by nejraselimovic** [comment]
@bafonins please check if there is a quick fix for this and if it can by any case be done by the v3.13.3 deadline

**Comment by bafonins** [comment]
Hey @aparcar! This issue will be fixed in the next release.

**Comment by aparcar** [comment]
Nice rtt, thanks
