### ISSUE TITLE
Improvise debug details of the gs.down.tx.fail event

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsNetwork/lorawan-stack#4336]
#### Summary
The “value” in the data object of the `gs.down.tx.fail` event currently doesn’t provide useful information to know/identify the cause of the failure.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/457

#### Steps to Reproduce
....

#### What do you see now?
The value in the data object of the `gs.down.tx.fail` event corresponds to the “Result” enum: https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.13.1/api/messages.proto#L153-L163

#### What do you want to see instead?
It should give the information on the cause for the downlink failure.

#### Environment
TTS V3.13.2

#### How do you propose to implement this?
...

#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No, @KrishnaIyer

**Comment by nejraselimovic** [comment]
@KrishnaIyer can you please triage this?
