### ISSUE TITLE
RSSI / SNR Sorted gateways

### ISSUE THREAD

**Issue by postman976** [TheThingsNetwork/lorawan-stack#4337]
#### Summary
I would be a advantage to have the gateway signals rssi / snr sorted from weakest to strongest in the end device metadata / JSON format. 
...

#### Why do we need this?
This is useful when the data is forwarded with a web hook to a 3rd party data server. In this way you can easy see what the signals are and deletes the need for signal interpretation. 

...

#### What is already there? What do you see now?
Gateways are now randomly in the JSON / meta data
...

#### What is missing? What do you want to see?
Sorted gateways for weakest to strongest (or other way around)

...

#### Environment

...

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?
No

...

**Comment by nejraselimovic** [comment]
@johanstokking what do you think of this proposal?

**Comment by johanstokking** [comment]
This sounds to me like presentation logic. This doesn't really belong in the API. It's also tricky to sort both by RSSI and by SNR.
