### ISSUE TITLE
Allow connecting existing devices to a device repository template

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#4382]
#### Summary
It is currently not possible to connect existing devices to a template in the device repository, e.g. to use their payload formatters, or apply their settings. This forces users to delete and re-register such devices.

#### Why do we need this?
To provide other ways to connect device templates to a device.

#### What is already there? What do you see now?
Device onboarding using the Device Repository

#### What is missing? What do you want to see?
Updating a device to apply version ids, when the device was onboarded manually

#### How do you propose to implement this?
There should be a config option in the end device general settings 

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by kschiffer** [comment]
This might actually be a bit more complicated than I initially though. We'll have to also apply all LW/MAC options when assigning the profile which could be problematic for devices with an active session. I don't think this is currently of high priority, so I will remove the milestone for now.

In any case, users can always delete and recreate their devices using the DR onboarding.

**Comment by KrishnaIyer** [comment]
Yeah this is quite tricky to execute properly. This issue is more than 2 years old and since then we've seen a big rise in the DR adoption. Let's close this for now.
