### ISSUE TITLE
Improvise the response for connection stats of a disconnected gateway

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsNetwork/lorawan-stack#4386]
#### Summary
The connection stats of a gateway shows an error message for the `disconnect` gateways. A gateway not being connected is not technically an error state. It is a valid and allowed state.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/473

#### Steps to Reproduce
1. Register a gateway in The Things Stack(TTS) console.
2. Execute the connection stats for the gateway not being connected. Ref: https://www.thethingsindustries.com/docs/reference/api/gateway_server/#a-namegsthe-gs-servicea

#### What do you see now?
Error message on querying the Connection Stats for the disconnect gateways.

#### What do you want to see instead?
A response with the `last received timestamp`(like in V2).

#### Environment
TTSC v3.13.3

#### How do you propose to implement this?
...

#### How do you propose to test this?
...

#### Can you do this yourself and submit a Pull Request?
No

**Comment by htdvisser** [comment]
This is working as intended. That API call is for fetching the statistics of the gateway connection. If there is no connection, it correctly returns a "connection not found" error.
