### ISSUE TITLE
Can’t exchange OAuth refresh token for an OAuth access token

### ISSUE THREAD

**Issue by romach** [TheThingsNetwork/lorawan-stack#4387]
#### Summary

Error occurs when trying to exchange OAuth refresh token for an OAuth access token according documentation https://www.thethingsindustries.com/docs/reference/api/authentication/#oauth-access-tokens

#### Steps to Reproduce

1. Create OAuth client with `GRANT_AUTHORIZATION_CODE` and `GRANT_REFRESH_TOKEN` grants
    ```
    ttn-lw-cli clients create tektelic-refresh-token --description "Description"  --organization-id tektelic-dev --redirect-uris <redirect_url> --rights RIGHT_APPLICATION_ALL,RIGHT_GATEWAY_ALL --grants GRANT_AUTHORIZATION_CODE,GRANT_REFRESH_TOKEN
    ```
2. Get authorization code opening page
    ```
    https://eu1.cloud.thethings.network/oauth/authorize?client_id=tektelic-refresh-token&redirect_uri=<redirect_uri>&state=roman_cherepanov&response_type=code
    ```
3. Exchange authorization code for an OAuth access token using `POST` request to `https://eu1.cloud.thethings.network/oauth/token`, use Basic Auth with the client ID as username and the client secret as password. Use payload `{ "code": "<AUTHORIZATION-CODE>", "grant_type": "authorization_code"}`

Got response:

```
{
    "access_token": "<ACCESS_TOKEN>",
    "expires_in": 3600,
    "token_type": "bearer",
    "refresh_token": "<REFRESH_TOKEN>",
}
```

4. Try to exchange OAuth refresh token for an OAuth access token using `POST` request to `https://eu1.cloud.thethings.network/oauth/token`, use Basic Auth with the client ID as username and the client secret as password. Use payload `{ "code": "<REFRESH-TOKEN>", "grant_type": "refresh_token"}`

#### What do you see now?

```
{
    "code": 3,
    "message": "error:pkg/oauth:missing_refresh_token (missing refresh token)",
    "details": [
        {
            "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
            "namespace": "pkg/oauth",
            "name": "missing_refresh_token",
            "message_format": "missing refresh token",
            "code": 3
        }
    ]
}
```

#### What do you want to see instead?

```
{
    "access_token": "<...>",
    "expires_in": 3600,
    "token_type": "bearer",
    "refresh_token": "<...>",
}
```

#### Environment

```
ttn-lw-cli version
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.13.2
Build date:          2021-06-17T12:36:42Z
Git commit:          4a2e92c4c
Go version:          go1.16.5
OS/Arch:             darwin/amd64
```

**Comment by htdvisser** [comment]
Hi @romach. Your request message seems to be incorrect:

```json
{ "code": "<REFRESH-TOKEN>", "grant_type": "refresh_token"}
```

When using `"grant_type": "refresh_token"` you should send the refresh token in the `refresh_token` field, not in `code`.

See https://datatracker.ietf.org/doc/html/rfc6749#section-6 for details.
