### ISSUE TITLE
Configure gateway visibility in Packet Broker (Console)

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#4409]
#### Summary

Configure gateway visibility.

#### Why do we need this?

For administrators to configure the visibility of gateways in Packet Broker.

#### What is already there? What do you see now?

Configuration of routing policies.

Since #4667, there is CLI support to manage default gateway visibility. See API here: https://github.com/TheThingsNetwork/lorawan-stack/blob/feature/4409-pba-gateway-visibility/api/packetbrokeragent.proto#L405-L432

#### What is missing? What do you want to see?

Configuration of gateway visibilities. This works very similar to routing policies: there is a default, and there are specific visibility settings per Home Network.

The first phase only tracks default gateway visibility. We should keep this issue open for per-network settings.

In the Console, just like we have a "Default routing policy" tab, we need to have a "Default gateway visibility" tab, which includes checkboxes for the fields. This seems pretty straight-forward to me, but I might be mistaken.

#### How do you propose to implement this?

1. ~Extend API; `Pba` service~ – #4667 
2. ~Implement CLI support~ – #4667 
3. Implement Console support

#### How do you propose to test this?

Local test setup with Packet Broker staging or even production. Packet Broker already provides all the required functionality.

#### Can you do this yourself and submit a Pull Request?

~Can do (1) and (2)~. Can review (3).

**Comment by johanstokking** [comment]
Updated the original comment and re-assigning to @kschiffer as Console is left for closing the first phase.

Also adding `needs/triage` so we can plan the exact milestone.

**Comment by kschiffer** [comment]
So per-network visibility settings are currently not implemented yet? If the plan is to include this short-term, we can already implement it as well in the Console.

Also, is it planned to inspect the gateway visibilities of other forwarder networks towards the own?

**Comment by johanstokking** [comment]
Let's keep it simple for now and set default gateway visibility only.

The rest is possible too but not needed for now. If we start with the default config checkboxes we're good and we can keep that if we expand functionality.
