### ISSUE TITLE
Make failed OTAA join event available via integrations

### ISSUE THREAD

**Issue by DvdGiessen** [TheThingsNetwork/lorawan-stack#4418]
### Summary

Failures with OTAA joins are currently only visible in the Console, when "verbose" data is toggled on. This feature request is about making a OTAA failure event available through integrations, to automatically detect such failures and then being able to do something to resolve them.

### Why do we need this?

Two use cases to do with having to set the correct frequency plan for a device:

-  A device migrated from TTNv2 doesn't have the correct frequency plan set. (In TTNv2, frequency plan was autodetected, but upon migrating it is required to be set explicitly.)
-  A device moves between multiple regions, making its configured frequency plan invalid.

These two use cases are new with V3: frequency didn't need to be configured in TTNv2 (it was autodetected).

Additional, more generic use case:

-  For large deployments, being able to detect when an OTAA join fails can help with solving problems. Instead of having go dig in the Console when an customer contacts support, we can actively detect issues.

The first use case described is my own: We have a few thousand devices I'm migrating to V3. For most we knew which frequency plan they use. For a few we didn't know but I was able to deduce their frequency plan based on previous connectivity data. There remain 279 devices for which I do not know which frequency plan to set. These devices are spread across the globe, so there is no way for me to inspect them. Once V2 goes down, these devices will all break.

The second use case is not one I currently have, but suspect other people may find useful. Imagine a device that has LoRaWAN connectivity and GPS: it may automatically determine which frequency plan it should use depending on where it is in the world. For example a device mounted in a boat, on a truck, etc. It can automatically do a new OTAA join whenever it enters a new region. But with V3 that no longer works, because then it would also be needed to set the new frequency plan on the TTN side.

The third case is a nice to have: Being able to actively flag potential problems would be greatly preferred over having to hear from customers that something is broken.

### What is already there? What do you see now?

If an incorrect frequency plan is set, OTAA joins coming from the device will be dropped: In the verbose events I'll see a `ns.up.join.receive` followed by a `ns.up.join.drop`, stating "The uplink channel was not found".

In V2 there used to be autodetection of the frequency plan. @htdvisser mentioned in [a Slack thread](https://thethingsnetwork.slack.com/archives/CFVF7R4AH/p1625484747082200) that this was the source of many problems, and it is currently not desired to implement this in V3.

### What is missing? What do you want to see?

Making OTAA failure events available via integrations would enable power users to implement some kind of "auto detection" for our own applications: If we can receive error events, such as the `ns.up.join.drop` that the network server generates when an device tries to join but has an incorrect frequency plan set, we can then try to automatically detect the correct frequency plan ourselves, and set it for that device via the API.

Implementing auto detection ourselves will not have some of the downsides that the autodetection in V2 had: because we're doing it in the application, we have way better ways of determining what the correct frequency should be (based on detailed knowledge of how our own devices work, historical data only available to us, etc). And since the logic is in our applications instead of in the V3 stack, the maintenance burden is shifted to the few power users who decide to implement something like this themselves. Other users are not impacted.

### How do you propose to implement this?

 - Defining a common data format for "OTAA join failures" such as the internal `ns.up.join.drop` event from the network server. Ideally these include as much context as possible (all the details such as `settings`, `rx_metadata`, etc from the OTAA join as currently in `ns.up.join.receive`), to enable consumers of this event to use that data to do the aforementioned correct frequency plan detection.
- Making these events available via all the default integrations (MQTT, webhooks, etc).

### How do you propose to test this?

I expect there are already automated tests for the existing events that can be extended to also test this new event.

From a practical perspective, it is easy to simulate: take any device that works in your current region, change the frequency plan in the Console to an incompatible one, and start an OTAA join. Observe in the Console Live data (be sure to enable the verbose option) that the OTAA join is dropped due to not being able to find a valid uplink channel in it's current incorrect frequency plan.

### Can you do this yourself and submit a Pull Request?

Currently, no. A quick search revealed that currently implemented events seem to be spread over quite a few places in this repository. Given I'm not familiar with Go or this codebase I estimate that implementing this new event would still require a non-significant amount of time from someone here who's more familiar.

(But if someone here estimates it isn't that hard and can point me in the right direction, I'd be happy to give it a try.)

**Comment by johanstokking** [comment]
It seems like there are two feature requests here:

1. Receiving failed device activations through Application Server integrations (webhooks, MQTT)
2. Support custom automatic detection of frequency plans

Feature (1) would help with feature (2).

I'm afraid we can do neither of these:

1. The event you mentioned is a Network Server (NS) event (starting with `ns.`). Network Server is not informing Application Server (AS) of failed device activations. In addition, integrations live in the Application Server domain, so failed device activations are NS domain and integrations are AS domain. We do not have an internal API to convey failed device activations from NS to AS, nor do we have a message type in AS to use in integrations. It's not impossible to implement this but it's quite some work. Conceptually, my opinion is that activation failures is _not_ LoRaWAN application layer, but network layer and if anything, events you can get from Network Server or Join Server. We are working on event middleware that allows you to configure actions for specific events, including these events, but again, not on the application layer and therefore not supported in integrations.

2. Detecting frequency plans is a bad idea: violation of spectrum regulations, mismatches with the "guessed" band and the one that the end device uses leading to MAC state corruptions, undefined results when (join) channels overlap, etc. You should always know the LoRaWAN band of each device, so you can always configure a frequency plan for that band.
