### ISSUE TITLE
Error missing_tenant_id

### ISSUE THREAD

**Issue by dhtek** [TheThingsNetwork/lorawan-stack#4490]
#### Summary
This message appears when trying to execute a command after a success login on the CLI.

#### Steps to Reproduce
1. Download the version 3.14 CLI for Windows amd64
2. Execute `ttn-lw-cli.exe use eu1.cloud.thethings.network`
3. Execute `ttn-lw-cli.exe login`
4. Execute `ttn-lw-cli.exe end-devices list my_application_id`
5. Got the error "error:pkg/tenant/middleware:missing_tenant_id (missing tenant ID) correlation_id=xxxxxxxxxx"

With CLI version 3.13, it's working.

Version: lorawan-stack-cli_3.14.0_windows_amd64
The Things Networks Community : v3.14.0

**Comment by KrishnaIyer** [comment]
I just closed this via https://github.com/TheThingsNetwork/lorawan-stack/pull/4507
