### ISSUE TITLE
Internal error server when max user limit is reached in create user API

### ISSUE THREAD

**Issue by ilcato** [TheThingsNetwork/lorawan-stack#4496]
#### Summary

Calling create user API after reaching max number of users for the tenant results in a generic _Internal Server Error_ instead of a managed error.

#### Steps to Reproduce

1. Create a new _The Things Stack Discovery - FREE TIER_ instance 
2. Create 3 users (the maximum) using the console
3. Try to create the fourth user via the REST API 

#### What do you see now?

The response body is similar to the following:
```
{
    "code": 13,
    "message": "error:pkg/identityserver/store:transaction_recovered (Internal Server Error)",
    "details": [
        {
            "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
            "namespace": "pkg/identityserver/store",
            "name": "transaction_recovered",
            "message_format": "Internal Server Error",
            "correlation_id": "1479de1787be438bb25961aa85aeaed6",
            "code": 13
        }
    ]
}
```

#### What do you want to see instead?

A clear error message stating the reason of the error (e.g: "Maximum number of users reached") instead of the generic "Internal Server Error".

#### Environment

The Things Stack Cloud v3.14

#### How do you propose to implement this?

.

#### How do you propose to test this?

Following the previous steps.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by htdvisser** [comment]
This should be fixed by https://github.com/TheThingsNetwork/lorawan-stack/pull/4511 and https://github.com/TheThingsIndustries/lorawan-stack/pull/2872
