### ISSUE TITLE
Expose `band` pkg via API to enable sourcing FP constraints

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#4518]
#### Summary
We need to come up with a way to expose the restrictions of frequency plans with regards to MAC/PHY versions.

#### Why do we need this?
E.g. the Australian FPs do not support MAC/PHY 1.0.0. However, the Console still allows setting this combination because the frontend is unaware of such restrictions. This leads to frustration when users fill out the end device registration form and hitting this limitation only upon submitting.

![image](https://user-images.githubusercontent.com/5710611/128998843-b1f29c30-c7f7-4734-96d5-28a6b9a362bd.png)

#### What is already there? What do you see now?
- End device registration form

#### What is missing? What do you want to see?
- API to query from the Console to get the `band -> regional parameters version -> available` mapping

#### How do you propose to implement this?
Probably trivial. cc @adriansmares 

#### How do you propose to test this?
Manual testing and updating e2es.

#### Can you do this yourself and submit a Pull Request?
Need help from @adriansmares (or whoever else feels confident with this).

**Comment by kschiffer** [comment]
Currently blocking #4519

**Comment by KrishnaIyer** [comment]
Moving this due to time constraints. Will pick it up early next milestone.

**Comment by KrishnaIyer** [comment]
This is actually related to https://github.com/TheThingsNetwork/lorawan-stack/pull/4591/files. We can add an RPC to the cluster package to fetch supported bands.

**Comment by adriansmares** [comment]
> This is actually related to https://github.com/TheThingsNetwork/lorawan-stack/pull/4591/files. We can add an RPC to the cluster package to fetch supported bands.

You can already build this using `band.All` - the usage won't change _too much_ after #4591 is done, so don't consider it blocking.
