### ISSUE TITLE
Console calls disabled APIs in JS-only deployments

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#4522]
#### Summary

The Console tries to call disabled APIs in JS-only deployments.

#### Steps to Reproduce

1. Go to https://sandbox.join.cloud.thethings.industries
2. Create an application
3. Try to create an end device

#### What do you see now?

- The Console tries to `GET /as/configuration` on an AS that does not exist.
- The Console tries to `GET /configuration/frequency-plans` on an NS that does not exist.

#### What do you want to see instead?

The Console should be smarter about deployments with only a Join Server.

#### Environment

Global Join Server of The Things Stack Cloud

**Comment by kschiffer** [comment]
Superseded by #4631

Note that the Console does not actually make the requests, but gets errors thrown back from the SDK because it tries to retrieve data originating from disabled components. Either way, this has to be fixed.
