### ISSUE TITLE
Prevent users from submitting zero or empty security keys

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#4539]
#### Summary
It is currently possible to submit the general settings form for ABP devices with empty security keys. This causes an [avoidable error](https://sentry.io/organizations/the-things-industries/issues/2298261705) when submitting the form.

#### Steps to Reproduce

1. Create an ABP device with MAC Version `1.1.0`
2. Go to the general settings form of the new device
3. Expand the network layer settings
4. Remove a security key (e.g. `FNwkSIntKey`, or any other key). Alternatively, enter an all-zero key.
5. Submit the form and observe the error
> invalid value of field `session.keys.f_nwk_s_int_key.key`

#### What do you see now?
Missing validation of required field (the field is also not marked as required)

#### What do you want to see instead?
- Field being marked as required
- Form validation catching empty or all-zero key values before submit

#### How do you propose to implement this?
- Update validation schema of the network layer form
- Add required prop to field

#### How do you propose to test this?
E2E

#### Can you do this yourself and submit a Pull Request?
@bafonins

**Comment by olicooper** [comment]
This has introduced a bug for me where I receive a message `Invalid value of field session.keys.nwk_s_enc_key.key` when saving Network Layer changes despite not changing anything and the `NwkSKey` field being correctly populated (I was only trying to edit the `Ping Slot Frequency` field at the time).

### Error details
```json
{
  "code": 3,
  "message": "error:pkg/networkserver:field_value (invalid value of field `session.keys.nwk_s_enc_key.key`)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/networkserver",
      "name": "field_value",
      "message_format": "invalid value of field `{field}`",
      "attributes": {
        "field": "session.keys.nwk_s_enc_key.key"
      },
      "correlation_id": "<ommitted>",
      "code": 3
    }
  ]
}
```

### PUT request
_Note: `f_nwk_s_int_key` and `session_key_id` modified with F's (but original lengths have been kept the same)_
```json
{
  "end_device": {
    "mac_settings": {
      "supports_32_bit_f_cnt": true,
      "ping_slot_frequency": 869525000,
      "ping_slot_periodicity": "PING_EVERY_16S"
    },
    "session": {
      "keys": {
        "f_nwk_s_int_key": { "key": "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" },
        "session_key_id": "FFFFFFFFFFFFFFFFFFFFFF=="
      }
    }
  },
  "field_mask": {
    "paths": [
      "mac_settings.supports_32_bit_f_cnt",
      "mac_settings.ping_slot_frequency",
      "mac_settings.ping_slot_periodicity",
      "session.keys.f_nwk_s_int_key.key",
      "session.keys.session_key_id"
    ]
  }
}
```

**Note:** I have been able to manually update the individual setting `mac_settings.ping_slot_frequency` via the API so this is not the problem.
