### ISSUE TITLE
Console - device/gateway - open in new tab

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#4641]
#### Summary

Currently one can't right click or middle click on a device/gateway in the end device and gateway lists, and then choose to open it in a new tab. On the V2 console this is possible.

When debugging devices (normally multiple at the same time), it is useful to have them open in different tabs and keeping it open for a long period to see live data. On the V2 console my workflow was to go to an application, list the devices, and then right click, open in new tab. This is not possible on the V3 console, as the devices in the device list are not `<a>`-links. It means one need to manually open a new tab and manually browse to the other device in the new tab. This becomes tedious if debugging or checking up on many devices/gateways.

#### Why do we need this?

Makes debugging multiple devices/gateways easier.

#### What is already there? What do you see now?

Currently we see a list of device, but can't open then in new tabs.

![Screenshot from 2021-09-20 14-59-14](https://user-images.githubusercontent.com/948278/134006480-00ef790c-9834-4168-b306-99b71c88902a.png)

#### What is missing? What do you want to see?

Add a `<a>`-tag around every device so that my browser will allow me to open a device in a new tab.

![Screenshot from 2021-09-20 15-01-16](https://user-images.githubusercontent.com/948278/134006667-bec00267-970d-4b58-9ee1-00cd9261841f.png)

#### Environment

Ubuntu 20.04
Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
TTS CE v3.15.0

#### How do you propose to implement this?

Add `<a>`-tag around a device.

#### How do you propose to test this?

Open console, go to list of end devices or gateways, right click and see if the open in new tab option is available.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by kschiffer** [comment]
Thanks for reporting this @jpmeijers. This is indeed a bug and needs to be fixed.

@bafonins can you take a look? We'd have to extend the `<Table />` component to render plain `<a />` within the table row instead of using a click handler. We'll probably want to retain both modes of interaction though (either/or), as I could imagine there are situations where the click handler is still necessary, but please check that. Likely a `basePath` prop will be enough so that the `href` can be generated via `${basePath}/${id}`. We are sort of doing that composition already but on the `<FetchTable />` level.

**Comment by kschiffer** [comment]
Using the middle mouse (or function key) to open the entity in a new row has been added in 3.15.2. For the remaining issue of refactoring the table component to use a `div` layout, see #4787

**Comment by jpmeijers** [comment]
No, the current behaviour is worse than before. Please reopen this issue.

What I currently see is that a right-click behaves like a left-click, opening the device/gateway in the current tab.

Middle mouse and ctrl+click will not work is all circumstances. Please implement this like it was in the V2 console where one can right-click - open in new tab.

**Comment by jpmeijers** [comment]
More context:
I broke my right arm while riding my bicycle (TTN Mapping). I now need to use my mouse in my left hand. It is almost impossible clicking on the wheel on my mouse without rolling it. Ctrl-click is also not possible as I only have one hand to work with: ie only mouse or only keyboard. The V2 behaviour of rightclick, then open in new tab is single (non dominant) hand friendly.

**Comment by kschiffer** [comment]
> What I currently see is that a right-click behaves like a left-click, opening the device/gateway in the current tab.

I can confirm and this change was not intended. We will fix that first and then work on the general refactor. Sorry for the trouble.

**Comment by jpmeijers** [comment]
Further testing indicates that none of my modifier keys plus a left-click opens the device in a new tab.

Modifier keys tested: Left Shift, Left Ctrl, Left Alt, Right Alt, Right Ctrl, Right Shift.
Operating system: Ubuntu 20.04
Browser: Chrome Version 95.0.4638.54 (Official Build) (64-bit)

And in case you were wondering, this is how I had to do this:

![20211026_143348](https://user-images.githubusercontent.com/948278/138879944-ee2c73ad-bdca-46eb-b916-4651ed8dec7a.jpg)

**Comment by jpmeijers** [comment]
This works as expected in v3.16.0. Thanks!
