### ISSUE TITLE
Warnings in the End Devices & Gateways live data of the TTS console

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#4648]
#### Summary
After the [scheduled maintenance](https://status.thethings.industries/incidents/5y0s5vkb2rr3) today, we are seeing a warning, i.e., `There was an error and the event cannot be displayed. The raw event can be viewed by clicking this row.` in the end-device and gateway live data of the TTSC Console.

#### Steps to Reproduce
1. Register an `End Device` and `Gateway` in TTSC Console.
2. Initiate the join procedure for the device.
3. Navigate to the gateway and end-device live data.

#### What do you see now?

- The warning is seen for the following observed events in the live data of the end-device and gateways of the TTSC console (refer to the images).
    - End-device:
        - `as.packages.azureiothub.fail`
        - `ns.up.data.drop`
    - Gateways:
        - `gs.up.drop`
- The CLI events doesn’t seem to report the warning. They include the above mentioned events and everything seems fine.
- Observed across all TTSC clusters.
![image](https://user-images.githubusercontent.com/9304207/134170324-51f7a020-716e-4154-86ef-cc51872f3b94.png)
![image](https://user-images.githubusercontent.com/9304207/134170342-660b252f-200d-4476-a229-be6441f77722.png)
![image](https://user-images.githubusercontent.com/9304207/134170353-71caba0e-c28f-435a-9a0a-d04eb044f783.png)

#### What do you want to see instead?
`No warnings` in the live data of the end-device and gateway of TTSC console

#### Environment
TTS v3.15.0 Cloud Hosted

### How do you propose to implement this?
...

#### How do you propose to test this?
...

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by kschiffer** [comment]
Thanks for reporting, will be fixed by #4665
