### ISSUE TITLE
Remove obsolete last invalidation keys

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4652]
#### Summary

https://github.com/TheThingsNetwork/lorawan-stack/pull/4651 removes the `ttn:v3:ns:application-uplinks:uid:<uid here>:last-invalidation` keys from the application uplink queue. These keys are now unused, and may be deleted.

#### Why do we need this?

In order to avoid storing unused keys.

#### What is already there? What do you see now?

Keys of the form `ttn:v3:ns:application-uplinks:uid:*:last-invalidation`

#### What is missing? What do you want to see?

These keys should be deleted.

#### Environment

`v3.15.0`

#### How do you propose to implement this?

`ns-db` migrate takes care of the `v3.10` -> `v3.11` migration. This migration needs to be extracted in a separate function / file, and a new one that ranges through the invalidation keys and deletes them should be added.

#### How do you propose to test this?

Manually set the key and make sure that the migration deletes it safely.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by htdvisser** [comment]
Doesn't look like this is going to get finished for v3.17.0, so pushing to v3.17.1.

**Comment by NicolasMrad** [comment]
This is created a while ago, can you advise on the importance of this?

**Comment by adriansmares** [comment]
I would say this is still relevant and that we can write a short migration for this. Assigning @cvetkovski98 to take a look into this for the next minor - let me know if you need extra details.
