### ISSUE TITLE
fPort 0 data confuses naive payload formatters

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#4668]
#### Summary

Example provided on forum: https://www.thethingsnetwork.org/forum/t/payload-decoder-check-the-port-number/51817

Naive payload formatters do not check the fPort value. This causes these formatters to decode mac commands as if they are valid application payloads, causing invalid data.

This was not a problem on TTN V2.

#### Steps to Reproduce

1. Set up a device to constantly send data
2. Set up a payload formatter that decodes the data without checking the fPort value.
3. Watch what happens when a mac command packet is received.

#### What do you see now?

fPort 0 packets are decoded and results in invalid data.

#### What do you want to see instead?

Either fPort 0 packets should not be delivered to the payload decoder, or this should be clearly documented. Users should be encouraged to check the fPort values in their payload formatters. 

#### Environment

TTS v3.15

#### How do you propose to implement this?

* Clearly document the behaviour
* Do not deliver fPort 0 to payload formatters and integrations.

#### How do you propose to test this?

Same as reproduction steps

#### Can you do this yourself and submit a Pull Request?

I can fix my own payload decoders, but there are too many out in the wild to retroactively fix.

**Comment by johanstokking** [comment]
> * Do not deliver fPort 0 to payload formatters ~and integrations~.

This is what should happen indeed.

@adriansmares please see if this fits in 3.15.1 or if we postpone this to 3.15.2. It doesn't feel urgent as we've always had this behavior in V3, but it's a small fix and it may lead to corrupt data going upstream.
