### ISSUE TITLE
Expose interop for Backend Interfaces on Identity Server

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#4678]
#### Summary

Expose interop for Backend Interfaces on Identity Server; at least to answer to `HomeNSReq`.

Blocked by https://github.com/TheThingsNetwork/lorawan-stack/issues/4677

#### Why do we need this?

For external services to get the home Network Server's NetID, tenant ID and cluster ID.

#### What is already there? What do you see now?

Interop is only exposed by Join Server to handle the join flow.

#### What is missing? What do you want to see?

Expose interop from Identity Server as well.

#### How do you propose to implement this?

Use existing `pkg/interop` server when it got a nice update (see referenced issue).

#### How do you propose to test this?

CI and integration testing

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by johanstokking** [comment]
Discussion point is what we do with the NetID and NSID that Identity Server returns.

For the NetID, there are three options:

1. Introduce new `is.network.net-id`. This is implemented in #4726 
2. Introduce `net-id` at the top-level and make NS's NetID fallback to that if empty. I think this is less clean than (1), as we still have two configuration fields, and now with weird config if the top-level `net-id` is different than the lower level `ns.net-id`. It's very much the same with all the host names that we have in TTS; they all have to be set likely to the same host for things to work.
3. Somehow get the value for `ns.net-id` when `is.net-id` is unset. This is dirty and adds coupling between IS and NS

The NSID needs to include the Tenant ID (optional) and Cluster ID. The implementation in #4726 returns the Network Server address as NSID, which may or may not include a Tenant ID. The tenant-less part is the Cluster ID.

In The Things Stack Open Source, we do not have a Tenant ID in the top-level config. We do have a Tenant ID in the Packet Broker Agent configuration. NSID has to include the Tenant ID if the TTSOS deployment uses a tenant in a host NetID. So, basically same issue as with NetID:

1. Introduce new `is.network.tenant-id`
2. Introduce `tenancy.default-id` to harmonize with TTSE config. PBA can also fallback to this value

@htdvisser thoughts? My preference would be (1) for NetID and (2) for Tenant ID.

**Comment by htdvisser** [comment]
I think we just need to accept that our configuration is getting messier as we add features or move them around. Eventually we'll just have to re-think our configuration system and make sure we do it better when we bump to V4.

Until now we've always added (duplicated) options in the components where we need them. Only if _really_ all components use something, we added "global" configuration.

So I think it would be better too add `is.network.net-id` and `is.network.tenant-id`.
