### ISSUE TITLE
Merge session fields correctly

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#4766]
#### Summary
When creating an ABP end device, the `session.started_at` property in the AS is set to `0001-01-01T00:00:00Z`. This is not a helpful value.

#### Steps to Reproduce

1. Go to the console
2. Using the manual creation, create an end device
3. Observe network tab of the browser, observe the response for the AS query of the end device
4. See that the `session.started_at` value is set to `0001-01-01T00:00:00Z`

#### What do you see now?
`started_at` value being stored as `0001-01-01T00:00:00Z`

#### What do you want to see instead?
`started_at` value being either omitted, or stored using the current timestamp of the creation time.

#### How do you propose to implement this?
Trivial.

#### How do you propose to test this?
I can test using the Console.

#### Can you do this yourself and submit a Pull Request?
@johanstokking or @adriansmares please coordinate and reassign accordingly.

**Comment by johanstokking** [comment]
`started_at` is currently non-nullable (refs #2798), so we can't really avoid returning an empty time. What we can do, however, is fix that AS sets `started_at` and returns a non-empty value for `started_at`.

According to API specification, `started_at` should only be observed from Network Server.

**Comment by johanstokking** [comment]
@kschiffer the best approach is to merge the session in a smarter way.

NS is in charge of lifetime (so `started_at`), `dev_addr`, `keys.{f,s}_nwk_s_int_key`, `keys.nwk_s_enc_key`, `last_f_cnt_up`, `last_n_f_cnt_down`, `last_conf_f_cnt_down`

AS is in charge of `keys.app_s_key`, `last_a_f_cnt_down` and you can best fetch `queued_application_downlinks` from AS.

The fix in #4791 only makes sure that AS never returns a non-empty value for `session.started_at` and `pending_session.started_at`.

**Comment by johanstokking** [comment]
I think this is resolved.
