### ISSUE TITLE
Gateway status is slow to be updated using LBS

### ISSUE THREAD

**Issue by sanijs** [TheThingsNetwork/lorawan-stack#4783]
#### Summary
When using LoRa Basics Station the status in the console is slow to update if the gateway gets disconnected.

#### Steps to Reproduce
1. Turn on gateway using LBS

2. Unplug the gateway and wait

3. Wait for the status in the console to update or use 
ttn-lw-cli gateway get-connection-stats <gtw_id> or 
TTI API: v3/gs/gateways/<gtw_id>/connection/stats 

to check when gateway goes offline.

#### What do you see now?
It takes around 18 min for the gateway to show up as disconnected after it has been unplugged.

#### What do you want to see instead?
A faster way to check if a gateway is offline. The problem does not exist when using udp.

#### Environment

The Things Stack Cloud v3.15.1
LBS both using LNS and CUPS.
This has been tested on multiple different gateway brands.

WisGate Edge Lite 2
MultiTech Conduit AP
Tektelic Kona Micro
Gemtek Indoor Femto Gateway

All running Basics Station v2.0.5

#### How do you propose to implement this?
Don't know

#### How do you propose to test this?
Turn on a gateway and then unplug it.

#### Can you do this yourself and submit a Pull Request?
no

**Comment by KrishnaIyer** [comment]
I can reproduce this. I'll get back here with some more details.

**Comment by KrishnaIyer** [comment]
The fix is now tested in our staging environment and will be available in the `v3.16.1` release.
