### ISSUE TITLE
Buttons on the gateway table cannot be pressed

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4784]
#### Summary

Clicking on the buttons in the gateways table opens the overview page for the gateway. I've tested this with the EUI copy button, and the admin purge / restore. 

#### Steps to Reproduce

1. Go to the gateways table in the Console.
2. Attempt to click on a gateway related button (let's say EUI)

#### What do you see now?

3. The action is not taken, and you are redirected to the gateway overview page

#### What do you want to see instead?

4. The button action is done (i.e. the EUI is copied)

#### Environment

`3.15.2` on `staging1`
Firefox Developer 94.0b9

#### How do you propose to implement this?

I don't know actually.

#### How do you propose to test this?

Check if the buttons work again. Also check other tables (applications seems to have the same behavior).

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by kschiffer** [comment]
@bafonins please have a look. I could imagine that this has to do with #4749.
