### ISSUE TITLE
Allow admins to list entities of a specific user or organization in Console

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#4833]
#### Summary

The Console should allow admins to list entities of a specific user or organization.

#### Why do we need this?

So that admins / support staff can see what the regular user sees without having to use the CLI.

#### What is already there? What do you see now?

There is API and the CLI already supports listing entities of users/organizations.

The Console only lets admins list their own entities, or search across all entities.

#### What is missing? What do you want to see?

@kschiffer should probably think about the UX design, but the way I see it, the `/console/admin/user-management/{username}` route should let you click through to application/gateway/... lists for that user.

#### How do you propose to implement this?

- I think we need support for this in the JS SDK
- I think we need additional routes in the Console
- what else?

**Comment by KrishnaIyer** [comment]
superseded by https://github.com/TheThingsNetwork/lorawan-stack/issues/6696
