### ISSUE TITLE
Parse QR code

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#4845]
#### Summary

Parse QR code via a new gRPC service

#### Why do we need this?

To not rely on QR code format implementations in the front-end

#### What is already there? What do you see now?

We have a `EndDeviceQRCodeGenerator` service that generates QR codes for end devices.

#### What is missing? What do you want to see?

We need a `QRCodeParser` service that can parse QR codes for anything it knows: end devices and gateways. This would basically parse known QR codes and return the result.

#### How do you propose to implement this?

Add `QRCodeParser` service with one `Parse` rpc. It returns a model that is a `oneof` with information about an end device or gateway. This should be extendible, not just identifiers. For instance, for end devices, it may contain the JoinEUI, DevEUI, numeric vendor ID, numeric profile ID, claim authentication code, checksum and serial number, per LoRa Alliance TR005 specification.

#### How do you propose to test this?

Unit testing

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by KrishnaIyer** [comment]
This is blocked on https://github.com/TheThingsIndustries/lorawan-stack/pull/3037
