### ISSUE TITLE
Gateway absolute time synchronization should taken into consideration timestamp granularity

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4853]
#### Summary

Our current Gateway absolute time synchronization logic is rather unapologetic - if `TxSettings.Time` is available, we consider that to be a gateway absolute timestamp:
https://github.com/TheThingsNetwork/lorawan-stack/blob/0b83c294b96458a47382fcdd373292187f6763f4/pkg/gatewayserver/io/io.go#L210-L224

We should not synchronize the gateway time if the accuracy is not known to be close to millisecond.

#### Why do we need this?

The problem is that this `Time` has undefined accuracy. TTKG has second accuracy associated with the reported `Time` - there is no fractional second. This will cause problems when the Network Server has to schedule an absolute time downlink without a pre-defined gateway. It will consider the recent downlink paths, and it may choose this TTKG. The TTKG has little chances of actually respecting the absolute timestamp, although it will try.

#### What is already there? What do you see now?

The Gateway Server always considers the `TxSettings.Time` to be a fine grained timestamp.

#### What is missing? What do you want to see?

The protocol frontends should communicate explicitly this fine grained timestamp to the `io.Server`. The frontends should also get to choose if synchronization should take place at all, since some frontends (i.e. BasicStation) handle synchronization on their own.

The NS also should have access to a fine grained timestamp somehow. I think that `Time` should be reserved only for GPS timestamps.

#### Environment

`v3.16`

#### How do you propose to implement this?

Add some options/settings to `io.Server.HandleUp` that allow the frontend to specify the time settings explicitly, or require that `TxSettings.Time` is always a GPS timestamp.

#### How do you propose to test this?

UT.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by johanstokking** [comment]
> The protocol frontends should communicate explicitly this fine grained timestamp to the `io.Server`. The frontends should also get to choose if synchronization should take place at all, since some frontends (i.e. BasicStation) handle synchronization on their own.

Yes I agree
