### ISSUE TITLE
End device last seen status is not updated on device activity

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#4871]
#### Summary

End device last seen status in the Console (end device table) is not updated when sending/receiving traffic. The last seen status is updated only on full page reload

#### Steps to Reproduce

1. Go to the staging environment and select any application with active end devices
2. Observe end devices sending/receiving traffic
3. Observe end device last seen status not updated and displaying the initial value

#### What do you see now?

End device last seen status is not updated live when sending/receiving traffic

#### What do you want to see instead?

End device last seen status should be updated live when sending/receiving traffic

#### Environment

tti staging/latest `v3.16` frontend and tti staging backend

#### How do you propose to implement this?

🤷‍♂️

#### How do you propose to test this?

See reproduce steps

#### Can you do this yourself and submit a Pull Request?

@kschiffer

**Comment by bafonins** [comment]
Same behavior is present on the end device overview page (frame counters are not updated as well)

**Comment by kschiffer** [comment]
I'll look into it today.
