### ISSUE TITLE
The end device reset command should also reset the Application Server and Join Server state

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4874]
#### Summary

The end device `reset` command should also reset the AS and JS states.

#### Why do we need this?

Because right now we reset the NS state, which is not sufficient.

#### What is already there? What do you see now?

Only the Network Server state is reset.

#### What is missing? What do you want to see?

For devices that do not `supports_join`, we should reset `session.last_a_f_cnt_down` in the AS end device, otherwise we may lose a significant chunk of downlinks.
For devices that do `supports_join`, we probably can reset the nonces stored in the JS end device.

We may consider adding a `ResetFactoryDefaults` RPC to the AS and JS end device stores, similar to how the NS one works.
For the AS, it should just reset the `session.last_a_f_cnt_down`, while for the JS it probably should reset `last_dev_nonce`, `used_dev_nonces`,`last_join_nonce`, `last_rj_count_0` and `last_rj_count_1`.

#### Environment

`v3.16.0`

#### How do you propose to implement this?

Make sure that the field mask contains `supports_join` while returning the NS end device. This allows the AS/JS logic to take place. Don't forget to remove the field at the end if it was not explicitly requested by the user.

Based on this, update the AS/JS end devices.

#### How do you propose to test this?

Reset an end device.

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by KrishnaIyer** [comment]
Is this still relevant @adriansmares? If yes, I'll pick it up the next milestone.

**Comment by adriansmares** [comment]
Yes, it is still relevant. You can easily test this by adding an ABP device, sending some downlinks, then resetting the MAC state. The frame counter for newer downlinks won't reset.

**Comment by KrishnaIyer** [comment]
Moving this to `v3.20.2` when I can have an end device to run tests.
