### ISSUE TITLE
Add absolute date to "Last activity"-tooltip

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#4910]
#### Summary

On a device page the Last Activity shows a human readable string like "2 hours ago". On V2 it was possible to click on this string to show the actual timestamp when it was last heard.

#### Why do we need this?

The accuracy of the string is not good enough.

#### What is already there? What do you see now?

![Screenshot from 2021-11-24 07-52-34](https://user-images.githubusercontent.com/948278/143183013-5690d539-843c-4a97-a5ca-9d21e88410b9.png)

`Last activity 2 hours ago` - Does this mean 2h59m ago, 1h59m ago, or 1h01m ago?

#### What is missing? What do you want to see?

Like on the V2 console, make this string clickable to change it into displaying the actual timestamp. Maybe as an ISO time string.

#### Environment

V3.16.0

#### How do you propose to implement this?

Use the same component as in the V2 console.

#### How do you propose to test this?

Open a device in the console and click on the last activity time

#### Can you do this yourself and submit a Pull Request?

No

**Comment by htdvisser** [comment]
The actual timestamp does appear when you hover over the "xx ago":

![hover mov](https://user-images.githubusercontent.com/181308/144031061-b6d446e3-af8a-4223-a7e6-4dbac0dfc2d5.gif)

But @kschiffer is going to think about how we can improve this.

**Comment by jpmeijers** [comment]
Thanks @htdvisser, somehow I missed that tooltip. It should actually be good enough in most situations. It's only on mobile where this tooltip doesn't work.

**Comment by kschiffer** [comment]
To improve the behavior here, the actual date should also be part of the info tooltip. We should simply append to the message

> The last activity was received at Dec 6, 2021 11:27:42.

If we do that, we can also get rid of the "regular title" on the date (the one that currently shows the date).

Can you take care of this @ryaplots ?
