### ISSUE TITLE
Let NS/AS update Last Seen of End Device in IS

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#4937]
#### Summary

It would be nice if the Network Server or Application Server could update the "LastSeen" of end devices in the Identity Server. 

#### Why do we need this?

Mostly because users want to sort their end devices on LastSeen, but it's also nice to have for network statistics.

#### What is already there? What do you see now?

LastSeen is tracked in the session of the Network Server.

#### What is missing? What do you want to see?

Either the Network Server or the Application Server should update the LastSeen of the end device in the Identity Server

#### How do you propose to implement this?

- We can add a `last_seen` to the EndDevice API and DB model.
- Since the Application Server already regularly fetches the end device from the Identity Server, I think it's easiest if the Application Server updated the LastSeen in the Identity Server using Cluster Auth. 
  - Updating should happen asynchronously (so not in hot-path)
  - Granularity should be limited; we shouldn't update on every uplink, perhaps only if the LastSeen is more than X hours ago.

**Comment by adriansmares** [comment]
This one is clear as well :+1:.

**Comment by pgalic96** [comment]
> LastSeen is tracked in the session of the Network Server.

@adriansmares Is this true ? Seems that the session only records the start time. Shouldn't we look at the most recent uplink to determine last seen?

**Comment by adriansmares** [comment]
> > LastSeen is tracked in the session of the Network Server.
> 
> @adriansmares Is this true ? Seems that the session only records the start time. Shouldn't we look at the most recent uplink to determine last seen?

Well, it is tracked indirectly indeed. If you look at the `recent_uplinks` in the current `session`, you can determine the last message from the end device.
