### ISSUE TITLE
Publish scheduling failure events

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#4953]
#### Summary

Publish scheduling failure events

#### Why do we need this?

To indicate why a downlink message was not scheduled on a particular gateway.

This provides transparency that is helpful. Some users just look at the RX metadata and see many gateways, but they don't know why the "best" gateway hasn't been used for downlink.

#### What is already there? What do you see now?

I believe that we do publish events on successful scheduling, and also if scheduling wasn't possible at all.

#### What is missing? What do you want to see?

I want to see events published by Gateway Server for each individual scheduling failure of each downlink path and each RX window. Especially conflicts and duty-cycle constraints are of interest here; maybe even show them as warning events for the gateway in the Console.

So these are gateway events, not application events. This is for gateway operators to see that downlink isn't possible, when and why.

#### How do you propose to implement this?

When scheduling downlink, besides explaining everything elaborately to `stdout`, also publish events.

The Console can then show some of these events, t.b.d. which ones, as warnings. 

#### How do you propose to test this?

Unit testing

#### Can you do this yourself and submit a Pull Request?

Can review and test

**Comment by KrishnaIyer** [comment]
Sounds good. I'll pick this up probably in the next milestone.

**Comment by KrishnaIyer** [comment]
This is closed by https://github.com/TheThingsNetwork/lorawan-stack/commit/84933ec479f70fd0ed333a43f5aaba64860a8b55
