### ISSUE TITLE
Upgrade to GoReleaser v1.0

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#5010]
#### Summary

GoReleaser has reached v1.0, so let's start using that instead of v0.x.

**Bonus:** hopefully this fixes the missing release notes in GitHub releases, otherwise this needs a separate bug issue.

#### Environment

CI

#### How do you propose to implement this?

- Check if we need to make any changes to our configs (https://goreleaser.com/deprecations/)
- Update the GoReleaser version

Maybe good to do this with a `v3.17.0-beta1` / `v3.17.0-rc1` release, so that we don't have any surprises when we tag the actual release.

#### Can you do this yourself and submit a Pull Request?

Assigning to @michalborkowski96 because this may be nice to do together with https://github.com/TheThingsNetwork/lorawan-stack/issues/4982

**Comment by michalborkowski96** [comment]
> You can check your use of deprecated configurations by running: `goreleaser check`

Checked, no warnings

> Since Go 1.16, darwin/arm64 is macOS on Apple Silicon instead of iOS.

Not used by us

Other behavior change information regards versions older than `v0.184.0`. Therefore I guess we can just bump the version and see what happens.
