### ISSUE TITLE
trouble connecting my LT-22222-L to ttn

### ISSUE THREAD

**Issue by ZEEC2958** [TheThingsNetwork/lorawan-stack#5022]
hi,
i want to connect my LT-22222-L to ttn but i dont what verif hardware or firmware it is. i only know via the serial communication that the image version is 1.5.6 and the class is A. where can i find those informations? and if i want to inport the end device where can i find the document to do that?

:rotating_light: :stop_sign: We do not accept questions on Github :stop_sign: :rotating_light:

Please raise your question on our community platforms:

- Forum: https://www.thethingsnetwork.org/forum/  
  We have a special category for The Things Stack: https://www.thethingsnetwork.org/forum/c/network-and-routing/v3
- Slack: https://thethingsnetwork.slack.com  
  We have a special channel for The Things Stack: #the-things-stack

**Comment by KrishnaIyer** [comment]
The links to the forum/slack are in the issue you created. Also check our docs: https://www.thethingsindustries.com/docs
