### ISSUE TITLE
EUIStore.CreateEUIBlock Updates Existing EUI Block

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#5045]
#### Summary

Unlike the name suggests, the `CreateEUIBlock` method of the current `EUIStore` implementation may change an existing EUI block.

#### What do you see now?

https://github.com/TheThingsNetwork/lorawan-stack/blob/dfa369c4457a74b0c04684684a6b8f522e83fb4d/pkg/identityserver/store/eui_block_store.go#L115-L140

#### What do you want to see instead?

A method that suggests we're creating something, shouldn't update something.

#### How do you propose to implement this?

Re-implement.

#### Can you do this yourself and submit a Pull Request?

Sure

**Comment by pgalic96** [comment]
@htdvisser What do you expect from this functionality?

The initial idea was to have a function that checks if the EUI block of the right type exists in the database, if it doesn't then it creates a new one (based on config), and if it does it checks whether the db block is the same as the one in config. If it is, we do nothing, and if it isn't, we update the block to match the config.

I would say this is just a naming issue. `InitializeEUIBlock` might be a better name. Then we can move these three functionalities (Get, Create, Update) to unexported functions which can then be exported (and tested) by whoever needs them when they are specifically needed (this is also related to the fact that right now we are focusing on DevEUI, even though we might expand it at some point). Right now we don't need these methods specifically.

**Comment by htdvisser** [comment]
Why wouldn't we make the EUI Store store multiple blocks? That way, when we (almost) exhausted all EUIs in the current block, we can add a new block and continue issuing EUIs without interruption.

**Comment by pgalic96** [comment]
That was the idea with changing the block in the config, but I agree, overwriting the existing block instead of just creating a new one is quite a messy procedure and it doesn't allow us to possibly reuse unused DevEUI's at a later stage.
