### ISSUE TITLE
Remove gateway location when not set to public

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#5079]
#### Summary

Remove gateway location when not set to public.

#### Why do we need this?

People expect that when unsetting public location of their gateway in the Console, that the location disappears from Packet Broker Mapper.

#### What is already there? What do you see now?

Currently, new location updates are not being sent to Mapper.

#### What is missing? What do you want to see?

The location must be deleted.

#### How do you propose to implement this?

When location public is set and false, explicitly unset the location in Packet Broker Mapper.

#### How do you propose to test this?

CI

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by mauro742** [comment]
After the deployment of v3.17.2 on TTS, I have tried to unset the public location on gateway general settings. The location is not removed from Packet Broker Mapper. The issue persists also deleting all the location data.
