### ISSUE TITLE
Pass device attributes into json uplink

### ISSUE THREAD

**Issue by hallard** [TheThingsNetwork/lorawan-stack#5120]
#### Summary

Allow the device attributes (and may be device description) to be read when received uplink data

#### Why do we need this?

I put information on these attributes to be able to do action on receive packet, that’s the goal indeed. I don’t want to request API to get these on each uplink I’m receiving.

#### What is already there? What do you see now?

We already receive a lot of information about device but no attributes nor device description.

#### What is missing? What do you want to see?

Feature implemented :-)

**Comment by KrishnaIyer** [comment]
This is a duplicate of https://github.com/TheThingsNetwork/lorawan-stack/issues/5879
