### ISSUE TITLE
Missing end devices when sorting by name

### ISSUE THREAD

**Issue by sanijs** [TheThingsNetwork/lorawan-stack#5133]
#### Summary

I have a lot of end devices with the same name, when I sort by name some of them will not appear in the list. It changes if I sort by ascending or descending. If I do a search by ID I can find the end device in my list. If I go trough all the pages of end devices and count them, I will get the correct number compared to the number that should be in the application. 

#### Steps to Reproduce

Create a lot of end devices in a application with the same name, or maybe do check in my application?

#### What do you see now?

If I sort by ascending, some of my end devices will not show up when I go through the pages of end devices in my application.

#### What do you want to see instead?

All my end devices when sorting by name

#### Environment

The Things Stack Cloud v3.16.2 (I think it should be higher, but version number is not updated in the console)

#### How do you propose to implement this?

don't know

#### How do you propose to test this?

Sort by name and see if all devices will show up

#### Can you do this yourself and submit a Pull Request?

no

**Comment by NicolasMrad** [comment]
Please submit a ticket using the support portal, attaching as well screenshots of the problem faced.

**Comment by sanijs** [comment]
Ticket submitted: TTS-4029
