### ISSUE TITLE
Improve webhook health status Console UX

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#5150]
#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/4526
References https://github.com/TheThingsNetwork/lorawan-stack/pull/5002

The Console should show information in a more contextual manner to the user. Specifically, the webhook should not be shown as 'pending' when the health checks are completely disabled.

#### Why do we need this?

Right now, even though the checks are completely disabled, the webhooks are shown as pending, and users are told that they will move from pending to healthy when the webhook will be executed. This is wrong, as no health check will take place if they are disabled.

#### What is already there? What do you see now?

The health status is pending in the webhook list, and editing the webhook tells the user that the status will change soon.

#### What is missing? What do you want to see?

I have described the UX that I had in mind at the bottom of [this](https://github.com/TheThingsNetwork/lorawan-stack/issues/4526#issuecomment-988697068) comment, specifically:

> The frontend may provide quite some contextual help.  For example, if `failed_attempts` is smaller than `unhealthy_attempts_threshold`, the Console may convey that the next HTTP request will be attempted, but if it fails the number of attempts will increase.

> If `failed_attempts` is greater or equal to `unhealthy_attempts_threshold`, then the `last_failed_attempt_at` can be used to relay what will happen to the next request. If `last_failed_attempt_at` + `unhealthy_retry_interval` is a moment in the past, the request will be executed, but if it is a moment in the future, the request will be dropped (no attempt will be made).

> It can also be the case that `unhealthy_attempts_threshold` is `0`. This means that the Application Server will be doing strictly book keeping - the number of attempts will increase, the timestamp will be updated, the last error will be stored, but the requests will always be made - basically we're only monitoring the webhook. In such cases I would recommend that the Console conveys a friendly message that tells the users to get their webhook fixed asap or at least delete it if it's not used.

To add to this, if both `unhealthy_attempts_threshold` and `unhealthy_retry_interval` are zero, the checks are completely disabled - we may put status as 'disabled there, and show no extra information in the webhook itself.

#### Environment

`3.17.2`

#### How do you propose to implement this?

First of all, backport the AS settings retrieval from enterprise:

https://github.com/TheThingsIndustries/lorawan-stack/blob/0906e8b33239cd4eff2769151fbf22e352a97835/pkg/webui/console/store/middleware/logics/application-server.js

This will allow the UI to have access to the health configuration, and in turn to provide this contextual information.

#### How do you propose to test this?

Edit the stack settings and send some successful/failed webhooks. I've given some advice in my above mentioned comment.

#### Can you do this yourself and submit a Pull Request?

I can review. @kschiffer if the proposed UX looks good, please remove the label.

**Comment by kschiffer** [comment]
Let's keep the UX simple.

We can distinguish four states:

*   If health status is enabled (`unhealthy_attempts_threshold` != 0 || `unhealthy_retry_interval` != 0)
    *   `Pending` if the webhook was created but has not made any request attempt yet (status = `null` / `undefined`)
    *   `Healthy` if the webhook has `failed_attempts` \< `unhealthy_attempts_threshold`
    *   `Requests failing` if the webhook has `failed_attemps` >= `unhealthy_attempts_threshold`
*   If the health status is disabled (`unhealthy_attempts_threshold` = 0 && `unhealthy_retry_interval` = 0)
    *   Do not show any status indication

Later, we can also provide further information for unhealthy webhooks.

ACK @adriansmares ?

**Comment by adriansmares** [comment]
This will hide the webhook as being possibly unhealthy until the threshold is hit, but that's ok.

**Comment by kschiffer** [comment]
We could add another `Recent failures` status when failures were detected but we're still under the threshold. How long are failures retained though? I would want to avoid to have the status being shown as such when there was one failed request one week ago.

Also, do I see correctly that the status will jump immediately to `unhealhy` if the very first request failed?

**Comment by adriansmares** [comment]
> How long are failures retained though?

Until a request is successful. You can always find when the last failure occurred using `last_failed_attempt_at`.

> Also, do I see correctly that the status will jump immediately to `unhealhy` if the very first request failed?

Yes, this is intended, and it will also jump immediately to `healthy` once a request goes through successfully.

**Comment by kschiffer** [comment]
Closing this via #5222, which resolves the immediate issue. We can look at providing more info to the user after evaluating the current solution.
