### ISSUE TITLE
If the Gateway Server Address contains a scheme or port, the UI thinks the Gateway is connected to a different cluster

### ISSUE THREAD

**Issue by onsolutionjames** [TheThingsNetwork/lorawan-stack#5198]
#### Summary
If the Gateway Server Address option on a Gateway contains a scheme or port (e.g. `wss://stack.example.com:8887`), the UI thinks the Gateway is connected to a different cluster and therefore doesn't show any activity, even though it could actually be connected to the same cluster. 

#### Steps to Reproduce
1. Set up a gateway and get it connected via Basics Station
2. Change the Gateway Server address from `stack.example.com` to `wss://stack.example.com:8887`
3. The UI now says that the Gateway is in a different cluster, even though it isn't

#### Environment
TTS v3.17.2 in Docker on a Ubuntu host (on EC2).

#### How do you propose to implement this?
By simply wrapping gateway.gateway_server_address in getHostFromUrl() (similarly to what is already done for gsConfig.base_url), this solves the issue, as it extracts the hostname from the full address and ignores the scheme and port. 

#### Can you do this yourself and submit a Pull Request?
I have created a branch that fixes this. Let me know if it's acceptable and I will make a PR. https://github.com/jameseden1/lorawan-stack/tree/fix/5198-gateway-server-address

**Comment by kschiffer** [comment]
Hey @onsolutionjames!

Thanks a lot for your issue and proposed solution. The solution looks good to me. If you want you can make a PR. :rocket:

**Comment by kschiffer** [comment]
Hey @onsolutionjames!

Thanks a lot for your issue and proposed solution. The solution looks good to me. If you want you can make a PR. :rocket:

**Comment by onsolutionjames** [comment]
@kschiffer Thanks! I just created a pull request for this. Let me know if it's fine or if I need to change anything. 

https://github.com/TheThingsNetwork/lorawan-stack/pull/5283
