### ISSUE TITLE
Unable to update multicast group

### ISSUE THREAD

**Issue by Oliv4945** [TheThingsNetwork/lorawan-stack#5237]
#### Summary
For multicast class B, new ping slot frequency, datarate and periodicity can not be changed from the GUI nor the CLI. What was first setup at multicast group creation seems to be kept internally.  
Same thing goes for multicast class C.

#### Steps to Reproduce

1. Setup a multicast group (B or C), use it
2. Change parameters on the GUI or the CLI
3. Those new parameters are correctly displayed in the GUI but the old ones are still used by the NS

CLI commands used:
```
ttn-lw-cli end-devices set 'd-test-app-1' 'multicast1' --mac-settings.rx2-data-rate-index 4
ttn-lw-cli end-devices set 'd-test-app-1' 'multicast1' --mac-settings.desired-rx2-data-rate-index 4
```

#### Environment
Tested on TTI v3.16.x and v3.17.2

**Comment by adriansmares** [comment]
See https://www.thethingsindustries.com/docs/devices/mac-settings/#mac-settings-and-mac-state - if you update these settings via `mac-settings`, you will need to reset the MAC state of the end device. If you need to update them at runtime, you should update the `mac-state.desired-parameters` fields most likely.

**Comment by Oliv4945** [comment]
Thanks @adriansmares, my colleagues confirmed that it resolved their issue
