### ISSUE TITLE
Console displays old version on release candidates

### ISSUE THREAD

**Issue by michalborkowski96** [TheThingsNetwork/lorawan-stack#5240]
#### Summary
Console displays old version on release candidates

#### Steps to Reproduce
Build a release candidate

#### What do you see now?
3.17.2

#### What do you want to see instead?
3.18.0

#### Environment
Github Actions

#### How do you propose to implement this?
No idea

#### How do you propose to test this?
Build a release candidate and deploy to staging

#### Can you do this yourself and submit a Pull Request?
@kschiffer

**Comment by kschiffer** [comment]
The package.json is currently the source of the version tag that is displayed in the Console. Where should I source it from instead?

It's e.g. possible to inject an environment variable into the bundle during the build process. Would that be a better option?

**Comment by michalborkowski96** [comment]
There's been a suggestion that it's about cache https://github.com/TheThingsIndustries/lorawan-stack/blob/release/v3.18.0/.github/workflows/release-rc.yml#L97
