### ISSUE TITLE
downlink_frequency error when create abp device . [this error also occured when a device join]

### ISSUE THREAD

**Issue by madjack101** [TheThingsNetwork/lorawan-stack#527]
Here's the detailed error log:

> ERROR Could not create end device, rolling back... error=error:pkg/errors:validation (invalid mac_state: embedded message failed validation) error_cause=error:pkg/errors:validation (invalid current_parameters: embedded message failed validation) error_cause_cause=error:pkg/errors:validation (invalid channels[48]: embedded message failed validation) error_cause_cause_cause=error:pkg/errors:validation (invalid downlink_frequency: value must be greater than or equal to 100000)
error:pkg/errors:validation (invalid mac_state: embedded message failed validation)
name=EndDeviceValidationError
field=mac_state
reason=embedded message failed validation
correlation_id=f53c4f9ee852407cab69bcc589bd3d59
--- error:pkg/errors:validation (invalid current_parameters: embedded message failed validation)
reason=embedded message failed validation
name=MACStateValidationError
field=current_parameters
--- error:pkg/errors:validation (invalid channels[48]: embedded message failed validation)
field=channels[48]
reason=embedded message failed validation
name=MACParametersValidationError
--- error:pkg/errors:validation (invalid downlink_frequency: value must be greater than or equal to 100000)
name=MACParameters_ChannelValidationError
field=downlink_frequency
reason=value must be greater than or equal to 100000

here's the device create command:
> docker-compose exec stack ttn-lw-cli end-devices create app1 test4 \
--dev-eui 0000000000000004 \
--join-eui 0000000000000001 \   
--frequency-plan-id CN_470_510_FSB_11 \   
--lorawan-version 1.1.0 \  
--lorawan-phy-version 1.1.0-b --abp \   
--session.dev-addr 00815bd6 \   
--session.keys.app-s-key.key bc97ea1ff11111111111111111111111 \
--session.keys.f-nwk-s-int-key.key bc97ea1ff11111111111111111111111 \
--session.keys.nwk-s-enc-key.key bc97ea1ff11111111111111111111111 \
--session.keys.s-nwk-s-int-key.key bc97ea1ff11111111111111111111111

**Comment by htdvisser** [comment]
Please fill the issue template that Github shows you when you create an issue.
