### ISSUE TITLE
Can not register end device on Frequency plan Asian 920_923 Mhz (AS923_2) 

### ISSUE THREAD

**Issue by viethoa14** [TheThingsNetwork/lorawan-stack#5285]
#### Summary

when i register end device on Frequency plan Asian 920_923 Mhz, sometime i can not see any thing on LoRaWAN version or there is warning "MAC V1.0.2 is not exist".
...

#### Steps to Reproduce

1. On web management End devices --> click Add end device
2. Then Select manually
3. After on Frequency click drop-down to choose Asian 920-923 Mhz (AS923 Group 2)
4. Then click drop-down on LoRaWAN version, sometime we can not see anything or there is warning "MAC V1.0.2 is not exist" when we click "Register end device" button.

#### What do you see now?

![Register](https://user-images.githubusercontent.com/58810284/156694303-c9bab705-4b54-4581-8df5-a9c3d96fc87a.PNG)
![Register2](https://user-images.githubusercontent.com/58810284/156694310-210ac5f3-a6ec-4132-b845-7ed6fc163a65.PNG)

#### What do you want to see instead?

...

#### Environment

now we just upgrade to version 3.18

Version:             3.18.0
Build date:          2022-02-23T12:41:51Z
Git commit:          81a677753
Go version:          go1.17.7
OS/Arch:             linux/amd64

...

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by adriansmares** [comment]
Hi @viethoa14,

The `AS_923_{2, 3, 4}` bands are available only using the RP2 regional parameter versions, and the same restriction applies to the frequency plans. I recommend trying this with LoRaWAN 1.0.4 + RP2 1.0.1
