### ISSUE TITLE
Able to register a gateway in TTS using CLI without a Frequency Plan

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#5292]
#### Summary
When registering a gateway in the TTS Console, one must select the Frequency Plan parameter. But, when using CLI, we are able to register a gateway in TTS without selecting the Frequency Plan.
#### Steps to Reproduce

1. Login to CLI
2. Follow the steps for [Adding Gateways using the CLI](https://www.thethingsindustries.com/docs/gateways/adding-gateways/) here. **Note:** Make sure to remove the `--frequency-plan-id` flag from the CLI command.
3. Check CLI output/TTS Console for the gateway registration status.

#### What do you see now?
We are able to create a gateway using the CLI in TTS without selecting Frequency Plan.
#### What do you want to see instead?

- Make the Frequency Plan value mandatory in the CLI.
- Display a warning if the Frequency Plan ID is set to an empty value like the console does.

#### Environment
TTS v3.18.0
#### How do you propose to implement this?
...
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by KrishnaIyer** [comment]
The issue here is that we do allow registering gateways without specifying frequency plans but we should return a warning to users via the CLI that such gateways will not be allowed to connect and forward traffic. I'll add the warning.
