### ISSUE TITLE
Feedback on the latest search feature for searching entities by ID, Name, Description, EUI

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#5296]
#### Summary
We have identified a few feedback points that can be improved in the[ latest search functionality](https://github.com/TheThingsNetwork/lorawan-stack/pull/5232) in TTS.
#### Steps to Reproduce
**Feedback 1:**
Create a device by specifying the name and description (with `space` between two words).
Search entities with a space between two words. (Eg: `out door`).
**Feedback 2:**
Use the above search condition in the `Overview` page of an application.
#### What do you see now?
**Feedback 1:**
While searching for entities by applying a space between two words, we got `error:pkg/identityserver/gormstore:database (database error)` error popup.

![image (9)](https://user-images.githubusercontent.com/9304207/157445735-cbd35887-724f-4151-9bfb-310885aabf83.png)

**Feedback 2:**
The error popup appeared as below.
![image (10)](https://user-images.githubusercontent.com/9304207/157445932-6aba9d66-a34d-4b02-a49e-69430e3ed060.png)

#### What do you want to see instead?
**Feedback 1:** Handle the case at the stack level or indicate with a warning message instead of a popup.
**Feedback 2:** Adjust the UI based on the error message.
#### Environment
TTS v3.18.1
#### How do you propose to implement this?
...
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by pgalic96** [comment]
Hey @ymgupta . This issue is resolved by db update. You can observe it on TTSCE where the db is already updated. Soon it is going to be reflected in TTSC as well. I will close the issue and if you observe it again feel free to re-open it.
