### ISSUE TITLE
`server_error` while logging into TTS CE

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#5298]
#### Summary
When a user deletes an account in TTN V2 and tries to log in with the same credentials in TTS CE, the below error appears, which is not helpful. Reference: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/641
```
error: server_error
error_description: oops! something went wrong
```
#### Steps to Reproduce

- Create an account in [TTN V2](https://account.thethingsnetwork.org/register).
- Login to [TTS CE](https://eu1.cloud.thethings.network/) using [TTN V2](https://account.thethingsnetwork.org/users/profile) credentials
- Delete the account from TTN V2.
- Log out of the [TTS CE](https://eu1.cloud.thethings.network/) and observe the error.
- Again try to login to [TTS CE](https://eu1.cloud.thethings.network/) using the same credentials.

#### What do you see now?
After logout (`Step 4`), the below error appears, and unable to login to the console (refer to the image).
```
error: server_error
error_description: oops! something went wrong
state: Y9zKLt5KcDxD9UwC
```
![image](https://user-images.githubusercontent.com/9304207/157598577-a096444c-6687-4d30-8f05-67253057adf5.png)

#### What do you want to see instead?
As per [#641](https://github.com/TheThingsIndustries/lorawan-stack-support/issues/641), @htdvisser suggested improving the user experience in displaying the error in this case.
#### Environment
TTS v3.18.1
#### How do you propose to implement this?
...
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by htdvisser** [comment]
This doesn't look like an issue in The Things Stack, but more in the OIDC provider (in this case: The Things ID).

\+ @nicholaspcr

**Comment by nicholaspcr** [comment]
This indeed is a issue with the The Things ID, its something I can do so I'll take a look into it.
Created the issue there and with that I'll close it here.
