### ISSUE TITLE
Unable to configure an LBS gateway in LNS mode on port 443

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#5299]
#### Summary
TTS Cloud and TTS Community Edition support connecting LBS gateways in LNS mode on port `443`. But, there is a bug on The Things Stack end that needs to be fixed to get this working.

Previous Context: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/724
#### Steps to Reproduce

- Connect gateway to TTS cloud using LBS by following the guide [here](https://www.thethingsindustries.com/docs/gateways/lora-basics-station/lns/).
- Enter the following in your gateway as the LNS Server Address: `wss://<server-address>:443`

#### What do you see now?

- LBS configuration worked correctly with LNS on the default port `8887`. But, haven’t had any success getting LNS to work on port `443`.
- Seeing the `2022-02-08 03:49:12.153 [AIO:ERRO] [3] WS upgrade failed with HTTP status code: 403` errors in the station logs when the port is configured as `443`.

##### What do you want to see instead?
Connect LBS gateway to TTS cloud in LNS mode on port 443.
#### Environment
TTS v3.18.1
#### How do you propose to implement this?
...
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by onsolutionjames** [comment]
Hi @ymgupta. I've been having similar issues with LNS on port 443 - I think it's two main things, see my existing Github issues and proposed fixes here: 

- Main issue: https://github.com/TheThingsNetwork/lorawan-stack/issues/5197
- Related, but non-critical issue: https://github.com/TheThingsNetwork/lorawan-stack/issues/5198

So from my testing I can get it to work on 443 on a local install, however a The Things Industries support person has suggested that they don't support LNS on port 443 for TTS Cloud and TTS Community Edition. See [this thread for some history](https://www.thethingsnetwork.org/forum/t/lns-on-different-port/54647/8).

See [this specific reply in the forum](https://www.thethingsnetwork.org/forum/u/htdvisser) about what you need to configure in your server/reverse-proxy to get it to work for self-hosted installs.

Perhaps after my fixes have gone through, they can make the additional changes needed that @htdvisser suggested in the forum (my guess is some kind of config changes to the Envoy proxy that they use?)

**Comment by KrishnaIyer** [comment]
I found the problem. It's an issue with our AWS configuration. This will be fixed as part of https://github.com/TheThingsIndustries/lorawan-stack-aws/issues/672

**Comment by KrishnaIyer** [comment]
The required change is merged to our infrastructure templates. This change will be deployed in `v3.23.0`
