### ISSUE TITLE
Fix toast queue

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#534]
**Summary:** 

We decided that at any given time there shouldnt be more than a single toast notification on the users screen. However, in some cases it can happen that several toasts can show up.

**Steps to Reproduce:** 

1. Go to the toast storybook
2. Try instantiating as many toasts as you can
3. See multiple of them showing up

**What do you see now?**

Multiple toasts shown

**What do you want to see instead?**

1 toast max

**Environment:**

Browser

**How do you propose to implement this?**

Fix the way toasts are queued

**Can you do this yourself and submit a Pull Request?**

I can fix it

**Comment by htdvisser** [comment]
@bafonins considering that there is a PR for this, I assume that we can put this in the April milestone, right?
