### ISSUE TITLE
Network Server should be aware of maximum downlink payload sizes and split MAC messages if appropriate

### ISSUE THREAD

**Issue by acutetech** [TheThingsNetwork/lorawan-stack#5370]
#### Summary
A device using AS923 region rules and DwellTime = 1 can receive only 11 bytes at DR2. I observe the TTN server sending 14 bytes of Frame Options. This packet is rejected by my device as violating the packet length rule, and consequently the device fails to operate.
Although later device software can fix the problem, it would be better if the server could split MAC messages so as not to exceed max payload sizes.

#### Why do we need this?
This would prevent devices that are perhaps not running the latest software from rejecting over-size downlink messages and consequently becomeing inoperable.

Also, the NS appears to be violating the spec.

#### What is already there? What do you see now?
This issue was raised and discussed at length here: https://www.thethingsnetwork.org/forum/t/frame-option-bytes-sent-by-server-are-too-long-and-are-rejected-work-around-please/56170

When my device (STM32WL5E running ST's stack derived from LoRaMac-Node v4.4.4) has operated without a gateway, it has tracked the data rate/spreading factor down to DR2 and stored this in flash memory. AS923 region, DwellTime=1, DR2 has an 11 byte application payload limit. When the device boots again with a gateway connected to TTN V3 it joins properly (using DR2) . However its next uplink message receives a downlink message response from the server with 26 bytes: 12 bytes of header/MIC and 14 bytes of Frame Options (Fopts) MAC commands.

The device firmware detects the 14 bytes as being illegal (greater than 11 bytes) and so rejects the downlink message. The device cannot function and cannot escape from this situation (every subsequent NS download sends the same 14 byte payload). 

The 14-byte Fopts field is as follows (raw data and parsed):
Raw data: 06 07 07 a0 af 8c 50 03 51 ff 00 01 09 35
06 = DevStatusReq (no payload)
07 = NewChannelReq (5 byte payload follows)
03 = LinkADRReq (4 byte payload follows)
09 = TxParamSetupReq (1 byte payload follows - including DwellTime = 1)

(Note: TxParamSetupReq sets DwellTime = 1 if the user selects “Asia 920-923 MHz” in the console and DwellTime = 0 for “Asia 920-923 MHz (used by TTN Australia)” through there is no simple way for the user to know this - better help on the console please!)

The forum discussion suggests the issue is not present with later software versions, as (if I understood correctly) in the later versions the device does not check downlink payload sizes. There is also a fix that involves changing the AS923_DEFAULT_DOWNLINK_DWELL_TIME definition from 1 to 0. However both these fixes involve changing device firmware which may not be practical.

The forum discussion references related topics, which anyoine who is attempting a fix should read and understand.

#### What is missing? What do you want to see?
The Network Server should be able to determine the maximum payload size of the device it is addressing, and limit downlink payload sizes accordingly. In this particular case, it seems to me benign if the NewChannelReq MAC was deferred to a later downlink message.

#### Environment
Device:  STM32WL5E running ST's stack derived from LoRaMac-Node v4.4.4
NS: TTN V3

#### How do you propose to implement this?
Adjust Network Server code so that the NS is aware of the region, DR, DwellTime and consequently message payload size (including MAC commands), and so adjusts the payload so it does not exceed the maximum downlink payload size limit. If appropriate, collections of MAC commands could be split between two or more download packets.

#### How do you propose to test this?
Unit testing

#### Can you do this yourself and submit a Pull Request?
No experience with NS codebase.

**Comment by adriansmares** [comment]
Hello, this functionality is already available. What LoRaWAN version and Regional Parameters version did you test this with ?

As mentioned in https://www.thethingsnetwork.org/forum/forum/t/frame-option-bytes-sent-by-server-are-too-long-and-are-rejected-work-around-please/56170/4 , you can use the CLI in order to setup the boot time dwell time configuration of the end device, specifically `--mac-settings.downlink-dwell-time`, which will cause the NS to emit downlinks that will respect the downlink limit.

Keep in mind that if you chose in the console LoRaWAN version 1.0.3 and higher, the NS will by default consider the downlink dwell time to be disabled, since the associated LoRaMac-node release (4.4.7) does this.
