### ISSUE TITLE
connect ETIMEDOUT 63.34.215.128:8333 in "MQTT Explorer" 

### ISSUE THREAD

**Issue by jayjupdhig** [TheThingsNetwork/lorawan-stack#5376]
MQTT Explorer (http://mqtt-explorer.com/ , https://github.com/thomasnordquist/MQTT-Explorer ) screenshot HERE:

![image](https://user-images.githubusercontent.com/42765391/162700887-d9a53e57-2f4f-4bcc-b150-570f10030f05.png)

**Questions:**

Get that message when i try to log in: "connect ETIMEDOUT 63.34.215.128:8333"

1.) Why? Is the TCP daemon at endpoint 63.34.215.128:8333 not available?

2.) Do i need to select "Validate Certificate" in MQTT Explorer or not?

Screenshot of my MQTT Explorer Configuration here is attached...

Thank you very very much for your feedbacks... :-)

With best regards,
Jan

**Comment by jayjupdhig** [comment]
Or is the encrypted connection currently not supported...?

**Comment by KrishnaIyer** [comment]
The TLS port is `8883`

**Comment by kosuodhmwa** [comment]
OH s**t, mea culpa - thank you very much!! :-)

"Validate Certificate" is also possible - because of that it's i.m.o. better to enable. :-) 

With best regards,
Jan
