### ISSUE TITLE
Cache result of version check

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#5394]
#### Summary

`ttn-lw-cli` should cache the result of the version check on disk, so that it doesn't have to do version check requests on _every_ call.

#### Why do we need this?

I'm working on a script that makes a batch of 100 devices claimable and generates QR codes for them. If the version check is enabled (which it is by default), I'm making 200 calls to the version check API, which is excessive.

#### Environment

ttn-lw-cli v3.18 on macOS

#### How do you propose to implement this?

Cache a successful version check response, together with a timestamp, in `os.UserCacheDir`. Only do a version check (1) if that file does not exists or (2) if the timestamp is too old.

**Comment by htdvisser** [comment]
CC @NicolasMrad for triage: this needs a milestone.

**Comment by michalborkowski96** [comment]
Why can't you just pass the `--skip-version-check` option?

**Comment by htdvisser** [comment]
Of course I can update my config to disable the version check, but I _do_ want to be notified about new versions. I just think the CLI shouldn't run the check 200 times in 10 seconds.

**Comment by michalborkowski96** [comment]
Yeah, you're right. I'll start working on this once I get through more important issues
