### ISSUE TITLE
Review event descriptions for consistency

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#540]
**Summary:** 

We need to review event (and perhaps also error) descriptions for consistency.

**Why do we need this?**

In #522 @rvolosatovs started a discussion about the consistency of event descriptions. After going through the codebase it looks like there are some inconsistencies between and within the different components.

**What is already there? What do you see now?**

| Event ID           | Description |
| ------------------ | ---------------------- |
| `oauth.user.login` | `successful user login` |
| `oauth.user.login_failed` | `failed user login` |
| `oauth.user.logout` | `user logout` |
| `oauth.authorize` | `authorize OAuth client` |
| `oauth.token.exchange` | `exchange OAuth access token` |
| `gateway.api-key.create` | `Create gateway API key` |
| `gateway.api-key.update` | `Update gateway API key` |
| `gateway.api-key.delete` | `Delete gateway API key` |
| `gateway.collaborator.update` | `Update gateway collaborator` |
| `gateway.collaborator.delete` | `Delete gateway collaborator` |
| `organization.api-key.create` | `Create organization API key` |
| `organization.api-key.update` | `Update organization API key` |
| `organization.api-key.delete` | `Delete organization API key` |
| `organization.collaborator.update` | `Update organization collaborator` |
| `organization.collaborator.delete` | `Delete organization collaborator` |
| `end_device.create` | `Create end device` |
| `end_device.update` | `Update end device` |
| `end_device.delete` | `Delete end device` |
| `application.create` | `Create application` |
| `application.update` | `Update application` |
| `application.delete` | `Delete application` |
| `gateway.create` | `Create gateway` |
| `gateway.update` | `Update gateway` |
| `gateway.delete` | `Delete gateway` |
| `organization.create` | `Create organization` |
| `organization.update` | `Update organization` |
| `organization.delete` | `Delete organization` |
| `user.create` | `Create user` |
| `user.update` | `Update user` |
| `user.delete` | `Delete user` |
| `user.update.incorrect_password` | `Incorrect password for user update` |
| `invitation.create` | `Create invitation` |
| `application.api-key.create` | `Create application API key` |
| `application.api-key.update` | `Update application API key` |
| `application.api-key.delete` | `Delete application API key` |
| `application.collaborator.update` | `Update application collaborator` |
| `application.collaborator.delete` | `Delete application collaborator` |
| `client.create` | `Create OAuth client` |
| `client.update` | `Update OAuth client` |
| `client.delete` | `Delete OAuth client` |
| `user.api-key.create` | `Create user API key` |
| `user.api-key.update` | `Update user API key` |
| `user.api-key.delete` | `Delete user API key` |
| `client.collaborator.update` | `Update client collaborator` |
| `client.collaborator.delete` | `Delete client collaborator` |
| `gs.gateway.connect` | `gateway connect` |
| `gs.gateway.disconnect` | `gateway disconnect` |
| `gs.status.receive` | `receive gateway status` |
| `gs.up.receive` | `receive uplink message` |
| `gs.up.drop` | `drop uplink message` |
| `gs.up.forward` | `forward uplink message` |
| `gs.down.send` | `send downlink message` |
| `gs.down.tx.success` | `downlink message transmit success` |
| `gs.down.tx.fail` | `downlink message transmit fail` |
| `js.join.reject` | `reject join-request` |
| `js.join.accept` | `accept join-request` |
| `ns.application.begin_link` | `begin application link` |
| `ns.application.end_link` | `end application link` |
| `ns.up.receive` | `receive uplink message` |
| `ns.up.receive_duplicate` | `receive duplicate uplink message` |
| `ns.up.merge_metadata` | `merge uplink message metadata` |
| `ns.up.data.drop` | `drop data message` |
| `ns.up.data.forward` | `forward data message` |
| `ns.up.join.drop` | `drop join-request` |
| `ns.up.join.forward` | `forward join-request` |
| `ns.up.rejoin.drop` | `drop rejoin-request` |
| `ns.up.rejoin.forward` | `forward rejoin-request` |
| `ns.mac.proprietary.receive` | `proprietary MAC command received` |
| `ns.mac.%s.answer.accept` | `%s accept received` |
| `ns.mac.%s.answer` | `%s answer received` |
| `ns.mac.%s.indication` | `%s indication received` |
| `ns.mac.%s.answer.reject` | `%s rejection received` |
| `ns.mac.%s.request` | `%s request received` |
| `ns.mac.%s.answer` | `%s answer enqueued` |
| `ns.mac.%s.confirmation` | `%s confirmation enqueued` |
| `ns.mac.%s.request` | `%s request enqueued` |
| `as.link.start` | `link start` |
| `as.link.stop` | `link stop` |
| `as.link.fail` | `link fail` |
| `as.application.subscribe` | `application subscribe` |
| `as.application.unsubscribe` | `application unsubscribe` |
| `as.up.data.receive` | `receive uplink data message` |
| `as.up.data.drop` | `drop uplink data message` |
| `as.up.data.forward` | `forward uplink data message` |
| `as.up.data.decode.fail` | `decode uplink data message fail` |
| `as.up.join.receive` | `receive join-accept message` |
| `as.up.join.drop` | `drop join-accept message` |
| `as.up.join.forward` | `forward join-accept message` |
| `as.down.data.receive` | `receive downlink data message` |
| `as.down.data.drop` | `drop downlink data message` |
| `as.down.data.forward` | `forward downlink data message` |
| `as.down.data.queue.lost` | `lost downlink data queue` |
| `as.down.data.queue.invalid` | `invalid downlink data queue` |

**What is missing? What do you want to see?**

- Consistent IDs - considering that events are not covered by our compatibility/stability commitment, we can still change these. Events to look at are `oauth.user.login_failed`, `*.api-key.*`, `ns.application.begin_link`/`as.link.start`, `ns.mac.%s.indication`, `ns.mac.%s.confirmation`.
- Consistently lowercase descriptions
- Consistently use imperative mood
- Consistently place verb in beginning

Note that all these events are intended to be shown to users

**How do you propose to implement this?**

Find all occurrences of `events.Define`, check if they match my "what do you want to see" above, and change them if necessary.

**Can you do this yourself and submit a Pull Request?**

I can, but I would prefer working on other things. If everyone agrees with my "what do you want to see", we can re-assign this issue.

**Comment by bafonins** [comment]
Nice!
I can take over this one since I am already working on adding events to the console
