### ISSUE TITLE
Configure NS address while claiming in DCS config

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#5404]
#### Summary

Configure NS address while claiming in DCS config

#### Why do we need this?

There is no real need for users to provide this field during claiming. The DCS will already deployed to each Cluster and hence knows to which NS to set for the device in TTJS.

#### What is already there? What do you see now?

`networkserveraddress` is part of the claiming API.

#### What is missing? What do you want to see?

Add an option to get this from the TTJS config and deprecate this field in the API.

#### Environment

TTS v3.19.1

#### How do you propose to implement this?

I think this can be easily done in the configuration. We currently have `home-ns-ids` fields as a map whose key is the Home NS.
```
home-ns-ids:
  thethings.localhost: "0000000000000000"
```

Instead of this being dynamically filled at config time and compared to the `networkserveraddress` from the client request, we just set the correct NSID to the NS and use that directly.

So there will be only one key in this map for each cluster and the value will be the globally agreed up hNSID for that Home NS.

#### How do you propose to test this?

Local + staging.

#### Can you do this yourself and submit a Pull Request?

Yes cc @johanstokking / @kschiffer

**Comment by kschiffer** [comment]
Reminder for me: this is to avoid specifying the NS address in the frontend request during device claiming.
