### ISSUE TITLE
Cannot update end device net ID via CLI

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#5428]
#### Summary

The end device `net-id`, and possibly other flags, can no longer be updated via CLI.

#### Steps to Reproduce

1. Attempt to use `end-devices set` with the `--net-id` flag

#### What do you see now?

```bash
adriansmares@A98BCD2222F1:~/go/src/go.thethings.network/lorawan-stack$ ttn-lw-cli end-devices set gnse-500-claim-pool eui-0004a310001ab0b1 --net-id 000013
flag "net_id" not found
exit status 255
```

#### What do you want to see instead?

```bash
adriansmares@A98BCD2222F1:~/go/src/go.thethings.network/lorawan-stack$ ttn-lw-cli end-devices set gnse-500-claim-pool eui-0004a310001ab0b1 --net-id 000013
{
  "ids": {
    "device_id": "eui-0004a310001ab0b1",
    "application_ids": {
      "application_id": "gnse-500-claim-pool"
    },
    "dev_eui": "0004A310001AB0B1",
    "join_eui": "70B3D57ED0000000"
  },
  "created_at": "2022-05-02T13:44:18.795Z",
  "updated_at": "2022-05-02T13:57:04.405708128Z",
  "net_id": "000013"
}
```

#### Environment

`5506c3d0ffe40a47f7b5ac2b9c9b1a513e149d1b`

#### How do you propose to implement this?

I couldn't trace where the `flag not found` error message is emitted, but that would be a good start.

#### How do you propose to test this?

Attempt to set the `net-id` of an end device via CLI.

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by KrishnaIyer** [comment]
This is fixed via https://github.com/TheThingsNetwork/lorawan-stack/pull/5441
