### ISSUE TITLE
Esp32 Single channel

### ISSUE THREAD

**Issue by utya** [TheThingsNetwork/lorawan-stack#5437]
Good afternoon. I need to deploy my network to study lorawan work at the university, since I use cheap modules based on esp32, I would like to use https://github.com/things4u/ESP-1ch-Gateway/ as a gateway.

So I want to know Can Iconnect these devices to this project?

**Comment by KrishnaIyer** [comment]
Please use [The Things Network Forum](https://www.thethingsnetwork.org/forum/) for questions.
