### ISSUE TITLE
Use more specific client rights to make it consistent with other entities

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#5447]
#### Summary
We should use specific client rights and not just rely on a single `RIGHT_CLIENT_ALL`, which looks like a pseudo-right but is actually an explicit right.

#### Why do we need this?
To correctly assign all client rights to admins. Currently all rights with the suffix `_ALL` will not be granted to admins, since they are considered to be pseudo-rights. This causes admins to not be allowed to watch some non-public data of foreign clients when `--is.admin-rights.all` is not set to true.

#### What is already there? What do you see now?
Rights composition of other clients, where several explicit rights are combined by an `_ALL` pseudo right.

#### What is missing? What do you want to see?
- A start point for explicit rights. Right now that could be a single `RIGHT_CLIENT_GENERAL_INFO`
- Evaluating the current `RIGHT_CLIENT_ALL` as a pseudo right
- Checking for `RIGHT_CLIENT_GENERAL_INFO` instead of `RIGHT_CLIENT_ALL` when accessing clients

#### How do you propose to implement this?
Can be followed from our other entities.

#### How do you propose to test this?
Unit tests should cover this.

#### Can you do this yourself and submit a Pull Request?
I don't really have time so I will assign to @htdvisser who might want to reassign.

This is currently blocking #5414

**Comment by htdvisser** [comment]
In the absence of a **How do you propose to implement this?** in the original issue:

- Define additional rights in `api/rights.proto` (start with copy-paste from other entity) and re-generate protos:
	- `RIGHT_CLIENT_INFO`
	- `RIGHT_CLIENT_SETTINGS_BASIC`
	- `RIGHT_CLIENT_SETTINGS_COLLABORATORS`
	- `RIGHT_CLIENT_DELETE`
- Define descriptions for the new rights in `pkg/ttnpb/i18n.go` (start with copy-paste from other entity)
- Update implied rights in `pkg/ttnpb/rights.go`
- Find all `RIGHT_CLIENT_ALL` in the codebase and replace with more specific right (see also the required rights for similar operations on other entities)
