### ISSUE TITLE
Missing field in MQTT json or 

### ISSUE THREAD

**Issue by pe1mew** [TheThingsNetwork/lorawan-stack#5453]
#### Summary
frm_payload is missing in MQTT json struct
...

#### Steps to Reproduce
Monitor MQTT data with NodeRed.

#### What do you see now?
In the json struct that is published over MQTT,  the field ```msg.payload.uplink_message.frm_payload``` is missing. 
It seems to be replaced with ```msg.payload.uplink_message.session_key_id``` the content is not a HEX number but seems base64 data: ```AYBH/WpoSmh/h0iI1kb39g==```.

![afbeelding](https://user-images.githubusercontent.com/11438883/168231547-3bf22f6c-eedd-4496-b210-2378d3a5234d.png)

#### Environment
MQTT node in NodeRed.
devID 58A0CB0000202E3A
appEUI 58A0CB0001500000

#### How do you propose to implement this?
Correct the error and reinsert the base64 encoder payload.

#### Can you do this yourself and submit a Pull Request?
NO

**Comment by johanstokking** [comment]
If the `frm_payload` is empty, the field is omitted in JSON messages. This is likely an empty uplink message on FPort 8.

We're currently undergoing a major refactor on the data structures side. When that is done, we have some room to start optimizing things, including making sure that some fields are always present in JSON messages even if they are empty. References #2798

**Comment by pe1mew** [comment]
I'm afraid I have to disagree with the assumption that this is an empty uplink message on FPort 8. 
Although it was not shown in the JSON struct, the payload was decoded correctly and populated with the information sent by the device. 

I suggest investigating the issue further.

**Comment by johanstokking** [comment]
Hmm, please paste the anonymized full JSON uplink message so we can investigate, and reopen the issue, thanks.
