### ISSUE TITLE
Add support for reading notifications in the Console

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#5458]
#### Summary

As a follow-up of https://github.com/TheThingsNetwork/lorawan-stack/issues/4935 we should add Console support for reading notifications and marking them as seen.

#### Why do we need this?

So that users can also see and manage notifications for which The Things Stack doesn't send emails.

#### What is already there? What do you see now?

API: `GET /users/{user_id}/notifications` to list notifications and `PATCH /users/{user_id}/notifications` to update the status of notifications. See `notification_service.proto` for more details.

#### What is missing? What do you want to see?

@kschiffer should probably come up with the UI/UX for this, but I'd like to see something similar to GitHub notifications:

- A "bell" icon with an indicator for unread notifications
- A table view of all (not archived) notifications, and on each row:
	- Indicator if status is unread
	- Checkbox for bulk update (status can be updated to unseen / seen / archived)
	- Icon for entity type
	- Entity ID
	- Notification type (until we can sync the "registry" with the frontend, I think we should just use the raw text here)
	- Time (ago)
	- Some way for the user to get the details (the full JSON) of the notification

#### Can you do this yourself and submit a Pull Request?

No. Let's start with some UI/UX ideas from @kschiffer.

**Comment by adriansmares** [comment]
I've moved this to `3.22.0`. While the implementation itself does not have to land in that release, please consider designing the UX for that release.

**Comment by KrishnaIyer** [comment]
Phase 3 of https://github.com/TheThingsIndustries/product-management/issues/29

**Comment by KrishnaIyer** [comment]
This is completed and deployed everywhere 🚀
