### ISSUE TITLE
Show end device status information as part of the end device overview

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#5465]
#### Summary

We should show device status information as part of the end device overview in the Console.

#### Why do we need this?

The background here is that we have a mechanism that exists at network layer (so between the Network Server and the end device) to find out a bit of information about the state of the end device. This information is periodically retrieved by the Network Server and stored in the following fields in the NS end device registry:
- `power_state` - an enum that basically allows the end device to signal where it is drawing power from (battery, wall socket, unknown)
- `battery_percentage` - battery percentage when a battery is used
- `downlink_margin` - signal to noise ratio, in dBm, of the last downlink received by the end device
- (optional) `last_dev_status_received_at` - the timestamp at which a device status response was received
- (optional) `last_dev_status_f_cnt_up` - the frame counter at which a device status response was received

#### What is already there? What do you see now?

The end device overview shows activation information, session information etc.

#### What is missing? What do you want to see?

Have the device status information available, maybe under the map ?

#### Environment

`v3.19.2`, but not relevant

#### How do you propose to implement this?

'Just show the fields.'

All UX jokes aside, I don't have more ideas other than having a device status paragraph in the overview.

#### How do you propose to test this?

Most of the end devices on `staging1` do have these fields filled in, so you can check the output there.

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by kschiffer** [comment]
Great idea. I'll wireframe something and schedule this.

**Comment by NicolasMrad** [comment]
Since now we have the NOC, can't we display the above there?

**Comment by adriansmares** [comment]
> Since now we have the NOC, can't we display the above there?

The information is complementary - the Console can show the latest information, while the NOC may show the historical evolution of said information.

**Comment by KrishnaIyer** [comment]
This is a good one indeed. Let's try to get the wireframes for Q3.

**Comment by kschiffer** [comment]
I've finished the design of this as part of the general Console UX update. Implementation planning follows.

<img width="472" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/bdaa6afb-0d6b-4ce5-b3cc-13d41612c4eb">

**Comment by KrishnaIyer** [comment]
This is done as part of the redesign
