### ISSUE TITLE
Unable to sort the API Key tables based on the `Granted Rights` in TTS Console

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#5541]
#### Summary
From `TTS v3.20.0` release, we see that Collaborator and API Key tables can now be sorted in the Console. Ref: [Status Page](https://status.thethings.industries/incidents/fbp0hcjy95qk)

While the API Key are sorted based on the `Granted Rights`, we see the below error.
```
{
  "code": 3,
  "message": "error:pkg/errors:validation (invalid `order`: value must be in list [ api_key_id -api_key_id name -name created_at -created_at expires_at -expires_at])",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/errors",
      "name": "validation",
      "message_format": "invalid `{field}`: {reason}",
      "attributes": {
        "field": "order",
        "name": "ListApplicationAPIKeysRequestValidationError",
        "reason": "value must be in list [ api_key_id -api_key_id name -name created_at -created_at expires_at -expires_at]"
      },
      "correlation_id": "b00ac498d9e7415282c84f5c2899351b",
      "code": 3
    }
  ]
}
```

#### Steps to Reproduce

1. Login to TTS Console
2. Navigate to Applications
3. Select an Application. Make sure the application has at least one API key created.
4. Sort based on the `Granted Rights`

#### What do you see now?
Unable to sort the API Keys in TTS Console based on `Granted Rights`.
![image](https://user-images.githubusercontent.com/9304207/174008154-889c46e0-4952-4ead-a41f-c8ef4aee362e.png)

#### What do you want to see instead?
Users should be able to sort API Keys based on the Granted Rights.

#### Environment
TTS Cloud & TTS CE v3.20.0

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by kschiffer** [comment]
Thanks for reporting this. Sorting on the associated rights should not actually be possible, so this is indeed a Console bug. I'll create a PR to remove the sort button on the rights column.
