### ISSUE TITLE
auto_update flag is not working in CLI

### ISSUE THREAD

**Issue by vkrasnhak** [TheThingsNetwork/lorawan-stack#5559]
#### Summary

Using auto_update flag is not working in CLI

#### Steps to Reproduce

1. Try to create a gateway with `gateways create`
2. Use the **auto_update** flag with value **false**

#### What do you see now?

error:cmd/ttn-lw-cli/commands:invalid_gateway_eui (invalid gateway EUI)
    correlation_id=744dc286a9374cf7b5b728592090d9f9
--- error:pkg/types:invalid_eui (invalid EUI)
    correlation_id=9458b2bb5baa425c9b7a7c90926d8306
--- encoding/hex: invalid byte: U+006C 'l'

#### What do you want to see instead?

...

#### Environment

Windows 64 bit
ttn-lw-cli version 3.20.0

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by NicolasMrad** [comment]
Thank you for submitting the issue @vkrasnhak , but can you please provide more information regarding this issue?
Either provide more logs or screenshots of the steps taken to reproduce this issue
