### ISSUE TITLE
Send ApplicationDownlinkSent event from Tx acknowledgement

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#56]
**Summary:** 

Send DownlinkSent event based on the Tx acknowledgement received from a Gateway Server.

**Why do we need this?**

To provide insight to the downstream to applications and integrations.

**What is already there? What do you see now?**

Tx acknowledgement is received by the GS.

**What is missing? What do you want to see?**

- The Tx acknowledgement should be sent from the GS to the NS
- The NS should figure out which application downlink belonged to that Tx acknowledgement, based on the correlation IDs. We probably need the GS to use (temporary) tokens to find the right correlation IDs

**How do you propose to implement this?**

- Add new rpc in `GsNs` for the Tx acknowledgement
- Send an event from GS to NS with the correlation IDs
- NS to send the DownlinkSent event to AS

**What can you do yourself and what do you need help with?**

@rvolosatovs if GS just gives you a correlation ID, you can't find the downlink message, right? I guess it's gone also anyway from the queue?

Should the GS hold the downlink message (in memory) and send the sent downlink message back to the NS?

How actually does the NS find the concerning downlink message in the case of a downlink NACK, because then it's also gone from the queue right?

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1476 by @johanstokking

**Comment by johanstokking** [comment]
Blocking #76

**Comment by neoaggelos** [comment]
This requires the API change of #76 which is going in 3.12, updated the milestone for this issue accordingly.

**Comment by neoaggelos** [comment]
Quote from https://github.com/TheThingsNetwork/lorawan-stack/issues/76#issuecomment-774503756

> .... NS omits fields from the DownlinkMessage that is sent to the Gateway Server (e.g. end device identifiers).
>
> So, I think it is best to keep all this information on the NS side instead: Have NS store scheduled downlinks temporarily. When GS reports a TxAcknowledgment, NS checks if there is a matching scheduled downlink. If there is no match, skip (maybe print a warning). Otherwise, retrieve the complete downlink message, merge the `TxSettings` reported by the GS and then take care of forwarding to the AS.

Is this still the way to go for this issue? Set `ttn:v3:ns:sent-downlink:<CorrelationID>`, try to match that when a TxAck arrives, merge the transmission metadata from GS and forward the ApplicationDownlinkSent message?

One minor issue with that would be that we need to specify a TTL for the Redis entry (otherwise we will have problems with downlinks that are never acknowledged). Should this be configurable per device, or can we start with a default value (e.g. 1 hour, 1 day, 1 week) and see in a next iteration if we want to do something more complex?

cc @johanstokking

**Comment by johanstokking** [comment]
Yeah I think this is still the way to go for this issue.

We'd have to pick one correlation ID (prefix) for this, probably the one that NS allocates to the downlink message.

Indeed there should be a TTL on the key. Since downlinks can be scheduled in advance, it can be in the order of hours, but let's not make it too crazy long. Also remove the key when the downlink message has been found.

**Comment by neoaggelos** [comment]
When Network Server forwards the ApplicationDownlinkSent message back to AS, the AS will have to decode the payload, for which the session key ID is required.

The NS does not include the session key ID in the scheduled downlink attempt. I have some work in https://github.com/TheThingsNetwork/lorawan-stack/blob/feature/ns-send-application-downlink-sent/pkg/networkserver/grpc_gsns.go#L1295-L1298 where the Network Server fetches the session key ID from the database when the TxAck message arrives, but that may not be correct (for example, if the device has re-joined in the meantime).

Nothing "breaks" if the session key ID has changed, the Application Server will simply fail to decode the payload of the downlink message and discard it.

Is this acceptable, or should we make sure to forward the session key id along with the downlink scheduled attempt? It need not be sent to GS, NS can store it itself. Perhaps setting this in a correction ID could be a simple solution here.

**Comment by johanstokking** [comment]
The approach of loading the latest session key ID isn't good enough I'm afraid.

> Nothing "breaks" if the session key ID has changed, the Application Server will simply fail to decode the payload of the downlink message and discard it.

It will break because the AS will use a different AppSKey to decrypt the message. There's no protection against that.

---

I think there are two options:

1. Add `session_key_id` to `DownlinkMessage` (as it belongs to `raw_payload`) or `TxRequest` (as that is the NS relevant representation of the downlink message). This way, it gets stored and loaded by `ScheduledDownlinkMatcher`
2. Let NS put the session key ID in a correlation ID which becomes part of `DownlinkMessage`

Which do you think is better and why?

**Comment by neoaggelos** [comment]
> The approach of loading the latest session key ID isn't good enough I'm afraid.
> 
> > Nothing "breaks" if the session key ID has changed, the Application Server will simply fail to decode the payload of the downlink message and discard it.
> 
> It will break because the AS will use a different AppSKey to decrypt the message. There's no protection against that.
> 
> I think there are two options:
> 
> 1. Add `session_key_id` to `DownlinkMessage` (as it belongs to `raw_payload`) or `TxRequest` (as that is the NS relevant representation of the downlink message). This way, it gets stored and loaded by `ScheduledDownlinkMatcher`
> 2. Let NS put the session key ID in a correlation ID which becomes part of `DownlinkMessage`
> 
> Which do you think is better and why?

I believe extending the `DownlinkMessage` is probably the cleanest thing to do (since the session key ID is part of `ApplicationDownlink` and `ApplicationUplink` already).

To me, it feels like correlation IDs are best used to help with tracing events and logs, and not carry "state" across components.
