### ISSUE TITLE
Support (or remove) GatewayAntenna attributes

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#5614]
### Summary

The GatewayStore in the Identity Server should support attributes on GatewayAntennas.

Or, if we decide not to do that, we should remove the `attributes` field from the API.

### Current Situation

The GatewayStore implementations in the Identity Server do not handle the attributes field of gateway antennas.

### Why do we need this? Who uses it, and when?

It's in the API, so it's confusing that the database doesn't support it.

### Proposed Implementation

Add a JSONB field to the model (in hindsight I think the `attributes` table that we use for other entities was perhaps not the best solution) and store the attributes in there.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [ ] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by nicholaspcr** [comment]
Updating the information on issue in regards to what was decided in the stack meeting on 26.07.22. 
The decision was to drop the gateway antenna attributes.
