### ISSUE TITLE
Use new ADR API for ADR settings in the Console

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#5628]
### Summary

The Console should use the new ADR settings API (`mac_settings.adr`) instead of the legacy `mac_settings.use_adr` and `mac_settings.adr_margin` fields.

### Current Situation

The Console provides the `mac_settings.use_adr` and `mac_settings.adr_margin` settings to users.

The problem with the `use_adr` field is that it is inherently flawed. https://github.com/TheThingsNetwork/lorawan-stack/pull/5326#issuecomment-1074989674 goes into the history of this field but the TL;DR is that setting `use_adr` to `false` does not actually disable ADR in any way, it just enables the manual mode, which is not what most users expect to happen.

### Why do we need this? Who uses it, and when?

Any user that would like to use static ADR settings or would like to really disable ADR completely via the Console MAC settings form.

### Proposed Implementation

The new ADR settings API has the concept of modes:
1. Dynamic Mode:
- Equivalent to the old `use_adr` = `true` mode.
- Example update request:
```json
{
	"end_device": {
		"mac_settings": {
			"use_adr": null,
			"adr_margin": null,
			"adr": {
				"dynamic": {
					"margin": 15.0,
					"min_data_rate_index": null,
					"max_data_rate_index": null,
					"min_tx_power_index": null,
					"max_tx_power_index": null,
					"min_nb_trans": null,
					"max_nb_trans": null
				}
			}
		}
	},
	"field_mask": {
		"paths": ["mac_settings.use_adr", "mac_settings.adr_margin", "mac_settings.adr.mode.dynamic"]
	}
}
```
- All of the fields are nullable, and you may use the `mac_settings.adr_margin` as a default for `mac_settings.adr.dynamic.margin`.
- While it would be nice to render all of the fields, just show the `margin` for now and leave the rest to be configured via CLI.
2. Static Mode
- It instructs the end device to always use the same settings. 
- Example update request:
```json
{
	"end_device": {
		"mac_settings": {
			"use_adr": null,
			"adr_margin": null,
			"adr": {
				"static": {
					"data_rate_index": 0,
					"tx_power_index": 1,
					"nb_trans": 2
				}
			}
		}
	},
	"field_mask": {
		"paths": ["mac_settings.use_adr", "mac_settings.adr_margin", "mac_settings.adr.mode.static"]
	}
}
```
- All of the fields are required, and no defaults are to be provided - the user should input everything themselves.
- Field descriptions:
   - `data_rate_index` - The data rate index to be used by the end device for uplink transmission.
   - `tx_power_index` - The transmission power index to be used by the end device for uplink transmission.
   - `nb_trans` - The number of uplink transmissions of the same physical frame.
4. Disabled Mode
- Disables ADR for good.
- Example update request:
```json
{
	"end_device": {
		"mac_settings": {
			"use_adr": null,
			"adr_margin": null,
			"adr": {
				"disabled": {}
			}
		}
	},
	"field_mask": {
		"paths": ["mac_settings.use_adr", "mac_settings.adr_margin", "mac_settings.adr.mode.disabled"]
	}
}
```

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by kschiffer** [comment]
Cool! Here's how I see this implemented as part of the network layer settings in the end device settings:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/5710611/179993911-cda5a8a3-505a-46de-b400-2e676887a0f1.png">

@ryaplots can you take a look? I'll assign you.
