### ISSUE TITLE
Gateway registration required EUI

### ISSUE THREAD

**Issue by kersing** [TheThingsNetwork/lorawan-stack#5736]
### Summary

When trying to register a new gateway the EUI field is required which makes no sense for the Kickstarter gateways or any other gateways using the ttn-gateway-connector protocol.

### Steps to Reproduce

1. Log into the console
2. Go to gateways
3. Click 'Add gateway'
4. Fill out all fields except EUI

### Current Result

Submit of the form fails with 'Gateway EUI is required'

### Expected Result

New gateway is registered

### Relevant Logs

```shell
n.a.
```

### Deployment

The Things Stack Community Edition

### The Things Stack Version

3.21.1

### Client Name and Version

```shell
n.a.
```

### Proposed Fix

Revert EUI field to not be mandatory.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by kschiffer** [comment]
This has already been resolved in the code. We're currently working on updating the snapshots on TTSCE and TTSC and the fix should be available shortly.
