### ISSUE TITLE
config command does not show empty maps and slices

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#576]
**Summary:** 

The `ttn-lw-stack config` command does not show empty maps and slices.

**Steps to Reproduce:** 

1. Run `ttn-lw-stack config`

**What do you see now?**

For example, the `--cluster.keys` flag is missing.

**What do you want to see instead?**

Empty flags should also be listed.

**Environment:**

`ttn-lw-stack` and `ttn-lw-cli` all versions.

**How do you propose to implement this?**

https://github.com/TheThingsNetwork/lorawan-stack/blob/d619af728c45a7a37fb613b8dcad428d7b8431f4/cmd/internal/commands/config.go#L106-L108

should just set `val` to an empty string.

**Can you do this yourself and submit a Pull Request?**

Yeah, but this is super easy, anyone can do it

**Comment by furtiman** [comment]
@htdvisser I'd like to give it a try.
