### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Isar97** [TheThingsNetwork/lorawan-stack#578]
**Summary:** 

...

**Steps to Reproduce:** 

1. ...
2. ...
3. ...

**What is already there? What do you see now?**

...

**What is missing? What do you want to see?**

...

**Environment:**

...

**How do you propose to implement this?**

...

**Can you do this yourself and submit a Pull Request?**

...

**Comment by kschiffer** [comment]
Hey @Isar97. It appears like you opened this issue by mistake. Feel free to reopen with updated description.
