### ISSUE TITLE
Add unique id to events

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#580]
**Summary:** 

We need to uniquely identify events.
References: https://github.com/TheThingsNetwork/lorawan-stack/pull/570

**Why do we need this?**

Currently a combination of time and name is used as the key, however this can cause overlaps.

**What is already there? What do you see now?**

1. The `Event` proto, see https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/events.proto

**What is missing? What do you want to see?**

1. The `id` entry that uniquely identifies the event

**Environment:**

stack

**Can you do this yourself and submit a Pull Request?**

I can do that with guidance from someone who is familiar with the way events work.

**Comment by kschiffer** [comment]
As far as I can see, events with the exact same timestamp should not happen, meaning that

*   we can use the timestamp as event key
*   the occasional events with duplicate timestamps need to be addressed in the backend (#3209)
*   we can use logic in the console to check for events with duplicate timestamps and discard those (#3098)
*   we might want to close this issue

cc @johanstokking

**Comment by johanstokking** [comment]
My proposal would be:

- Add a new field to `Event` proto
- Fill that when creating the event: https://github.com/TheThingsNetwork/lorawan-stack/blob/3c1ab3a4e8a443e8e28883bc05df27369e110c4a/pkg/events/builder.go#L45-L50
- With an ID that's like correlation ID: `ulid.MustNew(ulid.Now(), rand.Reader).String()`
