### ISSUE TITLE
Register End Device not working on web interface

### ISSUE THREAD

**Issue by EveUbees** [TheThingsNetwork/lorawan-stack#5849]
### Summary

Cannot add a new device via the web interface "Add end device" feature.
Every step is normal, but the "Register end device" button at the end has no effect.

### Steps to Reproduce

1. Create a new device in a TTN app with "+ Add end Device" in the web interface
2. Set up a manual device
3. Click the "Register end device" button
<img width="340" alt="Capture d’écran 2022-10-05 à 08 31 42" src="https://user-images.githubusercontent.com/115065058/193998547-e5b4cc08-ab54-43aa-b87d-f910269babed.png">

### Current Result

Nothing happens, no device added

### Expected Result

Device added and interface switches to new device

### Deployment

The Things Stack Community Edition

### The Things Stack Version

3.22.0

### Client Name and Version

```shell
- Firefox 105.0.1 on MacOS Big Sur 11.6.6
- Safari 14.1.2 on MacOS Big Sur 11.6.6
```

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by kschiffer** [comment]
This issue has since been resolved. Please reopen if you still experience this.
