### ISSUE TITLE
"Mac Payload" term shouldn't be used to indicate a "Frame Payload"

### ISSUE THREAD

**Issue by SylvainMontagny** [TheThingsNetwork/lorawan-stack#5882]
### Summary

In TTNv3, in the End Device Live data,  the term "MAC Payload" is used for the “user payload” whereas it should be written "Frame Payload" in accordance to the specification.

The TTN documentation also says so (obviously) : 
https://www.thethingsnetwork.org/docs/lorawan/message-types/#:~:text=MAC%20payload%20of%20the%20data%20messages 11](https://www.thethingsnetwork.org/docs/lorawan/message-types/#:~:text=MAC%20payload%20of%20the%20data%20messages

### Current Situation

"MAC Payload" term used instead of "Frame Payload"

### Desired Situation

Change "MAC Payload" by "Frame Payload" in the device live data.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Which event types are rendered like this ? Can you share a picture of the places where this is mislabeled ?

**Comment by SylvainMontagny** [comment]
oh, sorry. I should have updated my TTS version before.
![image](https://user-images.githubusercontent.com/34216773/197594201-411c81ae-bb8f-45b6-bd5d-c1fc182950ab.png)

Last version has corrected it :
![image](https://user-images.githubusercontent.com/34216773/197595072-4689297f-346b-4c0a-b340-f27c2f86732b.png)

You can close this issue.

Thanks for the nice work you are doing on this open-source stack.

Sylvain
