### ISSUE TITLE
Database Backup/Restore

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#6]
**Summary:** 

We should be able to backup/restore the databases/stores of a network (or a single cluster).

**What do you see now?**

We have multiple databases (IS has SQL, NS+AS+JS have Redis), but the only way to export data (for backup or transfer to a different store, or cloud registry) would be through the APIs. However, those APIs don't return private fields, so any such data exports may be incomplete.

**What do you want to see instead?**

I would like to see a program or command that is able to export the entire network, including all stored data in a format that can later be imported into a new installation. This would be executed by the network operator for backup or in order to transfer the data to a (cloud) data store.

At the same time I'd like to see a program that can, based on such an export, restore the data to a clean installation.

This program needs to work on complete networks (including IS/ER), but also on independent clusters (with only NS/AS/JS).

**How do you propose to implement this?**

I think we can assume that the network operator runs these backups/restores, and has direct access to te SQL/Redis databases. Therefore, the command could probably be implemented on top of the `pkg/identityserver/store` interfaces, `pkg/{networkserver,applicationserver,joinserver}.DeviceRegistry` and `pkg/applicationserver.LinkRegistry`. The export format would either be protobuf or jsonpb. 

Working with those interfaces allows us to build common import/export logic, while the implementation of those interfaces can talk to our usual databases/stores (SQL,Redis), but also to custom implementations (AWS IoT).

**What can you do yourself and what do you need help with?**

I could probably get started with this by building the "common" part on top of the interfaces, but as the Redis registries don't support ranging over all devices, we may have to add that. Perhaps @rvolosatovs can assist with that.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/304 by @htdvisser

**Comment by nejraselimovic** [comment]
@htdvisser is this somewhat covered by [this](https://www.thethingsindustries.com/docs/getting-started/upgrading/#backup)?

**Comment by KrishnaIyer** [comment]
I think that this issue can be closed. For production clusters, our cloud offering comes with backup/restore enabled for each registry individually. And I wrote [that doc](https://www.thethingsindustries.com/docs/getting-started/upgrading/#backup) for open source users. 
I don't see any use case right now to build our own tool that does a "master backup".

**Comment by htdvisser** [comment]
Okay yeah, I suppose that most networks will just backup the databases directly, instead of doing an export from The Things Stack, so this can indeed be closed.
