### ISSUE TITLE
Add some desired MAC parameters to MAC settings with opinionated defaults

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#60]
**Summary:** 

Add some desired MAC parameters to the end device's MAC settings with opinionated defaults.

**Why do we need this?**

1. For users to configure custom desired MAC parameters for each end device. This may be based on what's configured in the device repository
2. To fall back to sane defaults that we have identified based on progressive insight running LoRaWAN public and private networks

**What is already there? What do you see now?**

We currently allow a few MAC settings, like `use_adr`, `adr_margin`, `class_b_timeout`, etc.

**What is missing? What do you want to see?**

We need to support at least the following settings:

- `rx1_delay`; defaults to 5 seconds
- `rx2_data_rate_index`; defaults to what is in the frequency plan
- `rx2_frequency`; defaults to what is in the frequency plan

**How do you propose to implement this?**

The above fields to be added to the `MACSettings`, and set as desired parameters on device reset.

Note that the current parameters stay the band defaults, per spec. This means that we stay compliant with devices that have not received desired parameters yet (i.e. ABP devices).

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1544 by @johanstokking

**Comment by rvolosatovs** [comment]
Requires https://github.com/TheThingsIndustries/protoc-gen-fieldmask/issues/19
