### ISSUE TITLE
LoRaWAN Encoding/Decoding in the CLI

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#601]
#### Summary

It would be nice to be able to decode/encode LoRaWAN packets directly in the CLI.

#### Why do we need this?

Mostly for debugging purposes.

#### What is already there? What do you see now?

Most of the code needed to do this is already in the CLI for the simulation commands.

#### What is missing? What do you want to see?

Would be cool if you could pipe raw (binary/base64/hex) packets to the CLI, and print them as JSON.

#### How do you propose to implement this?

Create a `decode` command that does something similar to the `processDownlink` func in `simulate.go`, maybe we can even make the decoder call `processDownlink` for downlink messages.

#### Can you do this yourself and submit a Pull Request?

Yes, but no high priority.

**Comment by htdvisser** [comment]
@rvolosatovs I guess you overlooked this when you implemented https://github.com/rvolosatovs/lorawan-codec. Would be nice if you could add this to our own CLI instead of having a separate tool for it.

**Comment by rvolosatovs** [comment]
I think it's out-of-scope of the CLI, but I will add it.

**Comment by neoaggelos** [comment]
Quite a lot of initial work for LoRaWAN decoding in https://github.com/TheThingsNetwork/lorawan-stack/tree/cli-decode-lorawan

**Comment by htdvisser** [comment]
Since @neoaggelos isn't going to finish this before the v3.14.1 deadline, I'll move it to v3.14.2.

**Comment by neoaggelos** [comment]
LoRaWAN encoding is already implemented and present in the `ttn-lw-cli simulate join-request --dry-run` family of commands (also for uplink and downlink messages), so focusing on decoding only.
