### ISSUE TITLE
https://account.thethingsnetwork.org/ -> broken url

### ISSUE THREAD

**Issue by xmariopereira** [TheThingsNetwork/lorawan-stack#6073]
### Summary

Since I can't create posts in your forum. 

https://account.thethingsnetwork.org/ is broken. It should point to the page where we can create slack accounts.

### Steps to Reproduce

1 - open https://www.thethingsnetwork.org/docs/
2 - click on slack 

### Current Result

![Screenshot 2023-02-24 at 16 58 38](https://user-images.githubusercontent.com/6067469/221227812-7f0ac820-602d-40eb-80aa-a3590aaaa0fc.png)

### Expected Result

slack account?

### Deployment

The Things Stack Enterprise (self-hosted)

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Thanks. I have opened an issue in the docs which point to the old URL - https://github.com/TheThingsNetwork/lorawan-stack/issues/6073.
