### ISSUE TITLE
incorrect display of "downlink_count" on console and API

### ISSUE THREAD

**Issue by sjunger** [TheThingsNetwork/lorawan-stack#6094]
### Summary

Hello,
the "downlink_count" currently has a bug. The display in the console fluctuates between "3" and the actual continuous value.

### Steps to Reproduce

The effect can be seen in the "Gateway" console.
After a few reloads of the page, the value jumps back and forth.
This also happens in the query via API.

### Current Result

Screenshots on Slack #support.

### Expected Result

Of course, only the correct current value should be displayed here.

### URL

https://eu1.cloud.thethings.network/console/gateways/<Gateway-ID>

### Deployment

The Things Stack Community Edition

### The Things Stack Version

3.24.2

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
This requires more information. Can you please post screenshots/API responses? 
Please hide information such as EUIs when doing so. Thanks.

**Comment by sjunger** [comment]
here are the missing screenshots:
![62CED81F-E385-49BC-A48F-B2F6F6AB0A7A](https://user-images.githubusercontent.com/65541010/223730351-ee271a78-3b01-4faa-88f6-05cd66264cbb.jpeg)
![82BEA8D4-9F83-40CA-A0F8-5CED3FFEC842](https://user-images.githubusercontent.com/65541010/223730364-f58f545f-8413-4e47-938b-5f01e398c897.jpeg)

**Comment by KrishnaIyer** [comment]
Ok thanks. @kschiffer can you take a look?

**Comment by sjunger** [comment]
Hi,

I have no idea what's going on here.

Yesterday at 2pm the connection was reset and now the data is reliable again. The bug was "silently" fixed.

I will now inevitably process my previous statistics data again and import them into a new influxdb table.
I hereby close the ticket.

Greetings Stefan

![A2BB6776-5F77-4A2E-A391-3B13377228A9](https://user-images.githubusercontent.com/65541010/223970768-af2b379a-8e0c-439f-8683-d9fd4b9f8a1d.png)
