### ISSUE TITLE
Support additional format of field mask in query parameters

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#61]
**Summary:** 

At the moment there are two formats to pass the field mask for get requests:
1. `?field_mask.paths=field1&field_mask.paths=field2`
2. `?field_mask.paths[]=field1&field_mask.paths[]=field2`

It might be convenient to introduce the comma-separated version:
`?field_mask.paths=field1,field2`

**Why do we need this?**

* Short and readable endpoints.
* The process of constructing the url becomes easier

**What is already there? What do you see now?**

All parameters in the comma-separated format are stored as a single value in the `FieldMask.Paths` slice.

**What is missing? What do you want to see?**

Thread every comma-separated field name individually 

**How do you propose to implement this?**

-

**What can you do yourself and what do you need help with?**

File the feature request

@htdvisser please fill the milestone

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1564 by @bafonins

**Comment by kschiffer** [comment]
From what I see, this issue is resolved, or there is a third option that we overlooked.
Following formats are possible:
* `?field_mask.paths=field1&field_mask.paths=field2`
* `?field_mask.paths[]=field1&field_mask.paths[]=field2`
* `?field_mask=field1,field2`, easily the most convenient

Tested in the IS device registry.

**Comment by htdvisser** [comment]
That third option is indeed the best. Seems to be supported by grpc-gateway since https://github.com/grpc-ecosystem/grpc-gateway/pull/529. Not sure why it wasn't working before.
