### ISSUE TITLE
MLME_PING_SLOT_INFO Response

### ISSUE THREAD

**Issue by wm-eisos** [TheThingsNetwork/lorawan-stack#6118]
### Summary

im using the code from LoRaMac-Node to develop and end device and i see that for class b the stack is waiting for this response before it completes the switch to class b but the NS isnt sending this response

```
case MLME_PING_SLOT_INFO:

              {
#if ( LORAMAC_CLASSB_ENABLED == 1 )
                if( mlmeConfirm->Status == LORAMAC_EVENT_INFO_STATUS_OK )
                {
                    MibRequestConfirm_t mibReq;
                    mibReq.Type = MIB_DEVICE_CLASS;
                    mibReq.Param.Class = CLASS_B;
                    LoRaMacMibSetRequestConfirm( &mibReq );
                    /* Notify upper layer */
                    if( LmHandlerCallbacks->OnClassChange != NULL )
                    {
                        LmHandlerCallbacks->OnClassChange( CLASS_B );
                    }
                    IsClassBSwitchPending = false;
                }
                else
                {
                    LmHandlerPingSlotReq( LmHandlerParams.PingSlotPeriodicity );
                }
#endif
            }
```

i can see that iststaus isnt ok so it keepscalling pingslotreq

### Steps to Reproduce

Use LoraMac Node stack with class b

### Current Result

Stuck waiting for reponse from NS for pingslotreq

### Expected Result

receive a responseon the end node

### Deployment

The Things Stack Community Edition

### The Things Stack Version

3.24.2

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by wm-eisos** [comment]
Here is an example when there is a device time request it enqueues the answer but not whenit receives a ping slot info request

![Capture1](https://user-images.githubusercontent.com/100835487/226599445-557880a0-2cf1-4dc3-8082-01223a2c1bf9.PNG)

![Capture](https://user-images.githubusercontent.com/100835487/226599433-446fc216-ae28-4ad5-8cf6-959e8027d735.PNG)

**Comment by adriansmares** [comment]
Hi @wm-eisos,

The device needs to be in class A while submitting a ping slot info request. Are you doing these requests while being in class B/C by any chance ?

It would be helpful if you could post a full set of events, starting from the device joining the network.

**Comment by wm-eisos** [comment]
it is in class A the stack doesnt fully switch to class B untill it receives this ping slot info answer

**Comment by adriansmares** [comment]
> it is in class A the stack doesnt fully switch to class B untill it receives this ping slot info answer

That should be the case indeed, but also the Network Server may not send a ping slot info response if the device is not known to operate in class A. 

Is this a 1.0.4 device that you've marked as both `Supports class B` and `Supports class C` ? If yes, could you please untick `Supports class C` and re-join ?

**Comment by wm-eisos** [comment]
okay yes i did tick both since the end device does actually support both i will untick supports class c and try to rejoin with class A and then switch to class B

**Comment by adriansmares** [comment]
Just so you understand the problem here - in LoRaWAN 1.0.x there is no mechanism through which the end device can signal that it has entered or left class C. As such, it is assumed to be in class C perpetually after sending the first uplink.

Since a ping slot info request can only be served while being in class A, and the device is considered to be perpetually in class C, the ping slot info response is not sent.

**Comment by wm-eisos** [comment]
Okay i tried and it is working as expected i was confused because it says supports class C instead of is class C
