### ISSUE TITLE
Provide send failure notification if publish multicast downlink with an incorrect gateway name.

### ISSUE THREAD

**Issue by adammeggitt** [TheThingsNetwork/lorawan-stack#6130]
### Summary

Feature Request: Generate MQTT failed topic if publish MQTT downlink with an invalid gateway serial number.

A gateway_id is included in the downlink message for a multicast message.
        let msg5 = {
            "downlinks": [{
                "priority": "NORMAL",
                "f_port": 201,
                "frm_payload": Buffer.from(p).toString('base64'),
                "class_b_c": {
                    "gateways": [{
                        "gateway_ids": {
                            "gateway_id": gateway
                        }
                    }]
                }
            }]
        };

The MQTT interface does not generate a send failure when publishing multicast downlinks with an invalid gateway name, i.e. does not match the regex expression \"^[a-z0-9](?:[-]?[a-z0-9]){2,}$.  In my particular case, the gateway serial number had an upper-case H in it, 918100H66010812110.  This is the serial number returned from the QR code on the gateway.

### Current Situation

If you publish a multicast with an improperly formatted gateway_id, the message is not sent and there is no notification that it was dropped.

### Why do we need this? Who uses it, and when?

It is easy to get the gateway_id wrong.  In fact, the QR code on RAK gateways returns upper-case alpha values which don't work with TTS.  There is no notification that the message was dropped so debugging the failure takes longer than it should.

### Proposed Implementation

Generate an MQTT failed topic message if the gateway_id is formatted incorrectly.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [ ] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Hey, thank you for your feature request.

In general PubSub protocols (like MQTT) do not have feedback mechanisms like the one you mention here (validation feedback). Publication can be done by any publisher, and depending on the semantics, any/all subscribers may receive the message.

We would need to introduce the concept of requests such that you could match your request to enqueue the downlink with a response that would tell you that the validation failed. If we keep going on this flow of ideas, we're re-inventing HTTP for no reason. I would say this is not needed, and the built-in MQTT server should stay as simply a source of streaming data, in both directions.

If feedback for downlink queue operations is needed, the [`AppAs`](https://www.thethingsindustries.com/docs/reference/api/application_server/#the-appas-service) service can be used to push/replace the downlink queue via HTTP calls, which do have a response which can be inspected.
