### ISSUE TITLE
Show conflicting identifiers information in the AS/NS/JS end device registries

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#6165]
### Summary

The End Device Registries enforce a globally unique constraint on the `(join_eui, dev_eui)` pair for each individual end device. This means that even if someone registers the end device in with another device ID, in perhaps another application or another tenant, the `(join_eui, dev_eui)` unique constraint cannot be violated.

The AS/NS/JS end device registries do enforce this uniqueness constraint, but their error message is very raw, containing only the fact that a conflict exists, but not with whom.

The IS end device registry is a lot more friendly and on end device creation actually provides all of the conflicting information to the caller. We should do the same in the AS/NS/JS registries.

### Current Situation

The IS will provide the caller with the conflicting end device ID, application ID and even tenant ID if needed. See the following logic:

https://github.com/TheThingsIndustries/lorawan-stack/blob/84ad8dc3a911fa686c9eda00e45aa7107b7a9bc1/pkg/identityserver/end_device_registry.go#L218-L251

### Why do we need this? Who uses it, and when?

The AS/NS/JS do have access to this information:
https://github.com/TheThingsNetwork/lorawan-stack/blob/ac161143c2f27e9266416f5353b50b6d09bb71c5/pkg/networkserver/redis/registry.go#L782-L795

Right now an `EXISTS` command is used, but if we would use a `GET`, we would know the full end device UID, which can be parsed back to the identifiers using `unique.ToDeviceID` and `unique.ToTenantID`.

### Proposed Implementation

Instead of `EXISTS`, use `GET` and parse the end device UID using `unique.ToDeviceID` and `unique.ToTenantID`. Try to keep the returned errors similar to the IS format, and avoid code duplication. There is a `pkg/internal/registry` which can serve as a common root for the logic if needed.

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
I'm currently working on the End Device Registries for a separate item and this is related. So I'll pick this up.

**Comment by KrishnaIyer** [comment]
> Instead of EXISTS, use GET and parse the end device UID using unique.ToDeviceID and unique.ToTenantID. Try to keep the returned errors similar to the IS format, and avoid code duplication. There is a pkg/internal/registry which can serve as a common root for the logic if needed.

I think we should only return the device/app ID if it's registered by the same tenant.

**Comment by adriansmares** [comment]
> I think we should only return the device/app ID if it's registered by the same tenant.

Edited - I misread the comment. 

I think it would be helpful to keep the device ID and application ID in order to help the tenant in which the conflicting end device is found. I don't think that these identifiers are necessarily secret, but I've seen application IDs which contain location information too.

The problem with not showing the identifiers is that in a scenario in which the tenant in which the conflict takes place did not completely clean up after himself, deletion is much harder. I am thinking of the following scenario:

1. Tenant A deletes the end device from the IS, NS, JS but forgets AS accidentally (or it timeouts, or fails for whatever reason).
2. Tenant B takes the end device, but cannot register it in his tenant.
3. Tenant B contacts tenant A, but tenant A forgot the application ID / device ID for this particular set of EUIs.

The only solution here is for tenant A to attempt to create the end device, meet the error again, then actually delete the end device. It is error prone and generally will require API access, which not many people use. If we show the identifiers, the user in which the partial end device is still registered can still do `ttn-lw-cli dev delete` with the identifiers and clean up completely.
