### ISSUE TITLE
Streamline page titles in console

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#619]
#### Summary
We currently don't use page titles consistently in the console. This should be fixed, and there should be a clear pattern on how to use page titles.

#### Why do we need this?
Descriptive page titles help users understanding what page is behind a browser tab.

#### What is already there? What do you see now?
Scattered, inconsistent usage of page titles using `<ReactHelmet />`.

#### What is missing? What do you want to see?
Page titles for 
- `applications/add`
- `applications/{app-id}`
- `applications/{app-id}/data`
- `applications/{app-id}/general-settings`

Additionally, page titles should follow the following templates:
For entity views: `{view_title} - {entity_id/entity_name} - TTN Stack Console`, e.g. `Data - My App - TTN Stack Console`
For all other views: `{view_title} - TTN Stack Console`

#### Environment
Console in browser.

#### How do you propose to implement this?
We can use the `titleTemplate` prop of `<ReactHelmet />` to simplify. See e.g. [here](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/device/index.js#L99).

Additionally, we should make sure to check whether we added a helmet component for every new view we add.

#### Can you do this yourself and submit a Pull Request?
Yes.

cc @bafonins

**Comment by bafonins** [comment]
Dont forget about `/applications/add`
