### ISSUE TITLE
Remove Network Server application uplink queue

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#6217]
### Summary

We should remove the individual (per application) uplink queues and instead have a per-cluster NS shared queue that only serves as a redundancy layer in case the Application Server peer is not available.

### Current Situation

The Network Server has the concept of per-application uplink queue, which exists for historical reasons. A short history is as follows:
1. The traffic flow between the Network Server and Application Server used to be done via subscriptions: an Application Server would subscribe for traffic with a Network Server - we called this _linking_. The idea was that linking would allow people to run their own Application Server. There are problems with this model, specifically the fact that traffic flows only as long as the link is active, and in general we lacked subscription group semantics such that you could have multiple parallel instances linking to the Network Server. It was also pretty bad UX - creating an application required you to create an API key just for linking, and virtually nobody actually ran their own Application Server.
2. In order to account for the periods in which the link was down, the per-application uplink queue was introduced. Initially it was a very simple Redis stream per application. Once a link was established, you would `XREAD`/`XACK`/`XDEL` and that was it. This scaled poorly because it needs one connection per application (because we used blocking `XREAD`, and polling would've been terrible).
3. In order to overcome the one-connection-per-link limitation, a token system was introduced. The idea was that we would drain the the queues, or at least block, only if an uplink was available. This was achieved by adding a token to a channel, which in turn triggered the queue to be cleaned. Initially we got this wrong, and if you would push two uplinks really fast, only one uplink would be popped - this in turn caused the uplink queues to build up in even mediocre throughput applications.
4. We removed linking, and instead started pushing uplinks to the Application Server via RPCs. The queue was not removed yet, as during upgrades it was still the case that the Application Server may not be available. 
5. Some optimizations related to downlink queue invalidation happened. In short, this allowed the uplink queue to be lost without causing issues with downlinks, by allowing the Application Server to recover the minimum downlink frame counter.
6. We started to skip sending the uplinks via the queue if we could just connect to the Application Server directly (i.e. the peer is available and the RPC worked). If we failed, only then we would queue and let the queue try again later.

This isn't short. Sorry.

---

If you made it through the history, you would see that there are incremental 'it kinda makes sense that this was added', but generally we don't really need these queues anymore - the only remaining use case for a queue in the NS is to handle the situations in which the AS is temporarily not available.

### Why do we need this? Who uses it, and when?

In order to simplify the NS code base, storage and in general to remove quite old debt for a traffic path that is barely used.

### Proposed Implementation

1. Introduce a mechanism that won't enqueue uplinks indefinitely. Right now on every single `err != nil` we enqueue, even if the error is not retryable. We should enqueue or re-enqueue only if the error is retryable.
2. Remove the application uplink queue mechanism, and introduce a shared queue at NS level. The shared queue should have the same retry semantics.
3. Introduce a `ns-db` migration which removes the remaining queues.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
This won't make the `v3.27.1` milestone. Moving to the next one.
