### ISSUE TITLE
API endpoint for Last Activity for device

### ISSUE THREAD

**Issue by absalom86** [TheThingsNetwork/lorawan-stack#6283]
### Summary

Writing a monitoring program for a solution that utilizes TTN and wanted to alert if a endpoint device has not sent a message in the last hour or two, cannot find any documentation about an API for the last activity of a device as displayed on the website so I assume it is does not exist yet.

### Current Situation

Currently you must keep the website itself open and monitor it throughout the day to make sure a device does not disconnect, this is a problem because we don't want to be stuck at our computers the whole day. 

### Why do we need this? Who uses it, and when?

This is useful for monitoring and alerting about the status of end point devices and creating companion apps to interact with the TTN.

### Proposed Implementation

Adding an API that lists how long it has been since the device was last seen, this could also just be implemented into the /devices/{device} api call as one of the fields. Right now it only lists date created and last edited, it would be very useful to have access to when it was last seen as well.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Hi @absalom86,

For the record the Console and the CLI use the same API that is available publicly for integrations. The field that you are looking for is `last_seen_at`, which is available both for individual end devices and the end devices listing endpoint.

With that being said, I don't recommend polling our API for this information - I recommend receiving the messages (via a webhook perhaps) and doing the book keeping yourself. Polling the API is subject to rate limiting and it is limited by the polling interval.

I also recommend looking into [field masks](https://www.thethingsindustries.com/docs/reference/api/field-mask/#field-masks), as there are more fields available than just the timestamps already.
