### ISSUE TITLE
3rd party customer support on device level

### ISSUE THREAD

**Issue by maebli** [TheThingsNetwork/lorawan-stack#6339]
### Summary

3rd party support for DUT integration into TTN with ease with new feature

### Current Situation

A customer is using your portal, The Things Network (TTN), and is having an issue with a device from us. We would like to find out what the problem is as quickly as possible, which can be achieved most rapidly with comprehensive log data.

### Why do we need this? Who uses it, and when?

- To efficiently help customers with DUT problems
- DUT suppliers could use this regularly

### Proposed Implementation

-     Dump of device history, configuration / commissioning, and other DUT-specific information (ZIP or similar)
-     Temporary access to the DUT via TTN frontend

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Professional support is not available for The Things Network (The Things Stack Community Edition). 

If you are a device manufacturer, please [contact our sales team](https://www.thethingsindustries.com/contact/) to see if we can provide you some assistance.
