### ISSUE TITLE
Webpage expanding horizonal menu structure swapped for end devices

### ISSUE THREAD

**Issue by jezdd** [TheThingsNetwork/lorawan-stack#6441]
### Summary

Menu expands but end devices link gets swapped with the device name...?

![Screenshot 2023-08-03 003255](https://github.com/TheThingsNetwork/lorawan-stack/assets/31295778/24f01d34-b556-420b-8021-0d6fa93f3e85)

### Steps to Reproduce

Open applications, open end devices, open any device, check horizontal menu structure. 

### Current Result

Horizontal menu structure back to from on the last two items  

### Expected Result

Applications > Apiary Sensors > End devices > "device name"

### Deployment

The Things Stack Enterprise (self-hosted)

### The Things Stack Version

3.27.0

### Client Name and Version

```shell
Chrome browser
```

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Yup this is valid. @ryaplots: Is this a result of how we setup the breadcrumb thing?

**Comment by ryaplots** [comment]
> Yup this is valid. @ryaplots: Is this a result of how we setup the breadcrumb thing?

Yeah, indeed. It uses the render order, so maybe at some point the render order does not correspond to the order of the actual components. I'll need to debug
