### ISSUE TITLE
Driver error

### ISSUE THREAD

**Issue by techworldthink** [TheThingsNetwork/lorawan-stack#6462]
### Summary

After the installation of The Things Stack in Docker, I tried to create an account and got this error. any idea?

{ "code": 2, "message": "error:pkg/util/store:driver (driver error)", "details": [ { "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails", "namespace": "pkg/util/store", "name": "driver", "message_format": "driver error", "correlation_id": "*************", "code": 2 } ] }

### Current Situation

Error

### Desired Situation

Accound will be created.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Please check the [Forum](https://www.thethingsnetwork.org/forum/) or [Slack](https://www.thethingsnetwork.org/docs/) for troubleshooting or debugging support.
