### ISSUE TITLE
Define frequency channels per device 

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#65]
**Summary:**
Some devices have fixed channels frequencies, even if it against regional parameters. A way for user to choose which channels to use on a specific device would be welcomed.

**Why do we need this?**
To make certification easier manufacturers choose to limit the channel plan of the device

**What is already there? What do you see now?**
None

**What is missing? What do you want to see?**
A list of available channels for the frequency plan of the device and select which channels to use.

**How do you propose to implement this?**
This would require implementation on the MAC level and the Console

**Environment:**
Any

**What can you do yourself and what do you need help with?**
Help with everything

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1585 by @Sypheos

**Comment by johanstokking** [comment]
@rvolosatovs to which extent do we support this already?

**Comment by htdvisser** [comment]
When registering a device, we can already set the `factory_preset_frequencies` field to indicate which channels/frequencies are preconfigured by the end device on reset.

This, combined with the channels in desired parameters, should be sufficient to close this issue. What's still missing is a way for device manufacturers to provide us with the preconfigured channels/frequencies for a specific device model. We'll need the device repository for that.

Refs #263

**Comment by johanstokking** [comment]
Updated #263 with this info
