### ISSUE TITLE
Update User's `PrimaryEmailAddress` leads to restricted rights for user 

### ISSUE THREAD

**Issue by nicholaspcr** [TheThingsNetwork/lorawan-stack#6516]
### Summary

When we create a new user we take its `PrimaryEmailAddress` and if its value is not present on the list of `ContactInfo` we add it to the list.  From this we send an email to admin users asking them to approve the new user, the problem here is that when an user decides to update its `PrimaryEmailAddress` if the new value is not present in the `ContactInfo` the email is marked as not validated and no email is sent (besides the `entity_state_changed`). 

This changes the state of the previously approved user to a limited access user and notifies nobody, leaving the user to get in contact with the admin by himself and trying to solve this.

Relates to #6498 since users who interact with the Stack via the Console would not be able to request the email validation

### Steps to Reproduce

1. Create user with admin 
   - values used: `usr-1` and `usr-1@test.com`
2. Update user's `PrimaryEmailAddress` to a new value
   - value used:  `usr-1-test@test.com`
3. Fetch user information
   - using CLI command: `ttn-lw-cli usr get usr-1 --primary-email-address --primary-email-address-validated-at`
4. The `primary-email-address-validated-at` is empty
5. If the stack has the configuration enabled to write emails to disk it is possible to validate that no email re-requesting email validation were sent.

### Current Result

User's `PrimaryEmailAddr` is marked as not validated uppon its change an no email requesting its validation is sent.

### Expected Result

From my understanding the most appropriate behavior would be to use the `validate` email template to request the user to confirm the change of the `primary_email_address` change.

### Deployment

The Things Stack Enterprise (self-hosted)

### The Things Stack Version

3.27.1-dev

### Client Name and Version

```shell
3.27.1-dev
```

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Blocking https://github.com/TheThingsNetwork/lorawan-stack/issues/6498

**Comment by nicholaspcr** [comment]
Does it block the request for validation? 

Updating the user's primary email address makes it so that requesting a validation is necessary, the validation request from the console should be helpful on this scenario.

**Comment by KrishnaIyer** [comment]
> Relates to https://github.com/TheThingsNetwork/lorawan-stack/issues/6498 since users who interact with the Stack via the Console would not be able to request the email validation

I'm basing this on your comment

**Comment by nicholaspcr** [comment]
I see, my mistake. 

I meant to express that it is related to the issue due to the lack of ability of re-validating the email after the update, so currently if an user does the update of its `PrimaryEmailAddress` he has to trigger the validation via the CLI.

I also did not make it clear on the summary of the issue but even requesting the validation via the CLI does not work, since the validation procedure from the store checks if an `contact_info` with the email value exists before making `PrimaryEmailAddress` as validated.

**Comment by nicholaspcr** [comment]
Actually this is a mistake on my end, there is no bug.

The section of the code referenced below does, as a matter of a fact, nothing when passing a new `PrimaryEmailAddress` while updating but it serves a mitigation for a scenario where an user didn't have a `PrimaryEmailAddress` and would set it for the first time to one of the `ContactInfo` items.

```go
if updatingPrimaryEmailAddress {
  if !updatingContactInfo {
    contactInfo, err = st.GetContactInfo(ctx, req.User.GetIds())
    if err != nil {
      return err
    }
  }
  if !ttnpb.HasAnyField(req.FieldMask.GetPaths(), "primary_email_address_validated_at") {
    for _, contactInfo := range contactInfo {
      if contactInfo.ContactMethod == ttnpb.ContactMethod_CONTACT_METHOD_EMAIL && contactInfo.Value == req.User.PrimaryEmailAddress {
        req.User.PrimaryEmailAddressValidatedAt = contactInfo.ValidatedAt
        req.FieldMask.Paths = append(req.FieldMask.GetPaths(), "primary_email_address_validated_at")
        break
      }
    }
  }
}
``` 

I'll be closing the issue since the reason I thought there was a bug was due to me making an mistake when setting up the User for a test, it wasn't properly validated after creating it. 

One thing that it might be worth doing it is sending another validation email when a user updates its `PrimaryEmailAddress` but I'll create another issue for that as it implies in a warning on the Console.
