### ISSUE TITLE
Console gateway entity purge is not purging

### ISSUE THREAD

**Issue by onizmx** [TheThingsNetwork/lorawan-stack#6570]
### Summary

When deleting a gateway with the purging option, it only deletes gateway and not releasing the unique id (purge).
Looks like `/purge` is not getting appened to the path.

### Steps to Reproduce

1. Delete gateway via console.
2. Tick release entity ids.
3. Check network tab to confirm it's only sending delete request

### Current Result

Gateway get's deleted but id is not released.

### Expected Result

Gateway id is released so new create gateway request with the same id is accepted.
Discovered during load testing where we occasionally clean up / re-setup entities.

### Deployment

The Things Stack Open Source (self-hosted)

### The Things Stack Version

3.27.2

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
I can reproduce this issue. This is not only for gateways but also for applications. It seems like the `/purge` path is not called when the checkbox to purge the IDs is selected.
