### ISSUE TITLE
Add error code to ErrorDetails

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#669]
#### Summary

Add `code` to `ErrorDetails`

#### Why do we need this?

To inform clients what the code is of errors and their causes, without knowing the TTN errors by namespace and name.

#### What is already there? What do you see now?

`ErrorDetails` with everything but the code.

The reason that the code isn't there, is that it's part of the `google.rpc.Status`, that's only returned on RPC and HTTP calls.

#### What is missing? What do you want to see?

We don't have `google.rpc.Status` available everywhere (i.e. event error payload) and we don't have the error code of the causes.

#### How do you propose to implement this?

Add `code` to `ErrorDetails` and fill out the field.

#### Can you do this yourself and submit a Pull Request?

Can do and can review.

**Comment by johanstokking** [comment]
@rvolosatovs consider making this part of #967 as well

**Comment by rvolosatovs** [comment]
I opened a draft PR for this https://github.com/TheThingsNetwork/lorawan-stack/pull/976, but testing blew up.
I will not make this part of #967
