### ISSUE TITLE
ABP Device Activation.

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [TheThingsNetwork/lorawan-stack#6704]
### Summary

Last week I opened an issue which was quickly dismissed and I was reffered to documentation that did not answer my question. I am looking to activate a device via ABP, the old way of doing it which is in the documentation seems to not be available anymore in v3.28

![image](https://github.com/TheThingsNetwork/lorawan-stack/assets/45296244/a67f4056-f3e4-471e-8f1b-7e066c709982)

I cannot find a place when I can choose Activation by Personalization. Could you please point me on how I can register my device via ABP?

### Current Situation

Still waiting

### Desired Situation

To register a device by ABP

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Please do not create repeated issues on the same topic. If the original does not solve your question, please add new comments to it even if it's closed. They are still visible.
I have restructured the documentation for adding devices [ in a pull request in the documentation repository](https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1210). This will be merged in a couple of days. If you still have questions, please file a documentation request in the [documentation repository](https://github.com/TheThingsIndustries/lorawan-stack-docs/issues). Note that this repo does not contain and documentation and is the codebase for The Things Stack.
