### ISSUE TITLE
Fix positioning of modal when scrolling

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#682]
#### Summary
If a page is scrollable, a it can happen that a modal displays out of view. This can be fixed by setting the position value of the modal to `fixed`.

#### Steps to Reproduce
1. Go to a long page
2. Open a modal
3. See it (partially) scrolled out of view

#### What do you see now?
Bad modal behavior

#### What do you want to see instead?
A modal that stays in the center of the screen regardless of page length.

#### Environment
Console in browser.

#### How do you propose to implement this?
See above. Additionally, it would be good to prevent scrolling when the modal is visible.

#### Can you do this yourself and submit a Pull Request?
@pgalic96

**Comment by johanstokking** [comment]
@pgalic96 any update here?
