### ISSUE TITLE
Manage application webhooks in Console

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#686]
#### Summary

Manage application webhooks in the Console.

#### Why do we need this?

Webhooks are a powerful way to work with application data. It's on either side more scalable than MQTT. Also, webhooks allow for serverless applications.

#### What is already there? What do you see now?

AS supports webhooks natively. There's also management through API and CLI.

#### What is missing? What do you want to see?

Console support.

#### How do you propose to implement this?

Per application, be able to manage webhooks. This is CRUD, see: https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#ttn.lorawan.v3.ApplicationWebhookRegistry

Per webhook, be able to manage the webhook (see https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#ttn.lorawan.v3.ApplicationWebhook). In a presentable manner that is:
- Webhook ID, a user defined ID that uses the same rules for all our other IDs
- Format, get options through the `get-formats` endpoint, see API
- The base URL, to which paths are appended for specific message types. These message types are optional. I think we should have some kind of checkboxes per message type. When enabled, the path is optional too (can be empty), for example:
   - [ ] Uplink messages: ` ` (= disabled, so `uplink-message: null`)
   - [x] Join-accept messages: ` ` (= enabled, so `join-accept: { path: "" }`)
   - [x] Downlink queued: `/down/queued` (= enabled, so `downlink-queued: { path: "/down/queued" }`)
   - [ ] Downlink sent: see above
   - [ ] Downlink failed: see above
   - [ ] Downlink acknowledged: see above
   - [ ] Downlink not acknowledged: see above
   - [ ] Location solved: see above

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by kschiffer** [comment]
Is this console MVP?

**Comment by johanstokking** [comment]
It would be _very_ nice to have.

**Comment by kschiffer** [comment]
So, will these be treated as an integration, or should it be a dedicated section?

**Comment by johanstokking** [comment]
Can you elaborate a bit?

**Comment by kschiffer** [comment]
In the console, under single applications, we have an `Integrations` section. Should the webhooks functionality be made available under this section. Or should webhooks be treated in their own sub section.
![image](https://user-images.githubusercontent.com/5710611/58180372-3f4ff500-7caa-11e9-803f-173b6cb5d5c7.png)

So basically the question is: Are webhooks an »integration«?

**Comment by johanstokking** [comment]
Ah, no that would be integrations
