### ISSUE TITLE
Flaky NS test

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#690]
#### Summary

NS test is flaky.

#### Steps to Reproduce

Run CI

#### What do you see now?

https://gist.github.com/johanstokking/45bde10bb3bf6f8636eea7972c4beade

#### What do you want to see instead?

Successful NS test.

**Comment by rvolosatovs** [comment]
Should be closed by https://github.com/TheThingsNetwork/lorawan-stack/pull/705

**Comment by johanstokking** [comment]
It happened again; https://gist.github.com/johanstokking/36dc73023c5b26d49132790875c77578

**Comment by rvolosatovs** [comment]
Should be fixed by #756
