### ISSUE TITLE
Allow filtering an entity's collaborators when searching for accounts

### ISSUE THREAD

**Issue by nicholaspcr** [TheThingsNetwork/lorawan-stack#6908]
### Summary

As pointed out in the release testing discussion, when we attempt to search for accounts to add as collaborator we list existing accounts to the search bar on the console. 

This has unintended side effects since it allows users to update collaborators permissions via the `Add collaborator` button. For example:
- Click `Add collaborator`, select `user-X` with only `delete entity` permission.
- Click `Add collaborator` again, select the same user and grant all rights. 
  - The collaborator `user-x` was updated via the `add collaborator` button

### Current Situation

When searching for accounts the requests supports the following:
- search for only users via the `onlyUsers` by specifying as `true`. 
- search for collaborators of a specific entity via the `CollaboratorOf` field.

### Why do we need this? Who uses it, and when?

If we were to filter out the collaborators from an account's search request with the current implement, we would need to perform two requests:
- One with the `onlyUsers` set as `true` and no entity specified.
- Another request with `onlyUsers` set as `true` and with an entity specified. 

Afterwards we would need to remove the results of the second requests from the first.

All of this is inefficient.

### Proposed Implementation

Add an additional field to the `SearchAccountsRequest`. Something like:
```proto
message SearchAccountsRequest {
  option (thethings.flags.message) = {
    select: false,
    set: true
  };

  string query = 1 [(validate.rules).string = {max_len: 50}];

  bool only_users = 2;

  oneof collaborator_of {
    ApplicationIdentifiers application_ids = 3;
    ClientIdentifiers client_ids = 4;
    GatewayIdentifiers gateway_ids = 5;
    OrganizationIdentifiers organization_ids = 6;
  }

  message ExcludeFrom {
    oneof entity {
      ApplicationIdentifiers application_ids = 1;
      ClientIdentifiers client_ids = 2;
      GatewayIdentifiers gateway_ids = 3;
      OrganizationIdentifiers organization_ids = 4;
    }
  }
  ExcludeFrom exclude_from = 7;
  // NOTE: This request intentionally does not support pagination.
}
```

From this we could add additional binding to the `SearchAccounts` method in the `EntityRegistrySearch`.
```
  // Search for accounts that match the conditions specified in the request.
  rpc SearchAccounts(SearchAccountsRequest) returns (SearchAccountsResponse) {
    option (google.api.http) = {
      get: "/search/accounts"
      additional_bindings {get: "/applications/{application_ids.application_id}/collaborators/search"}
      additional_bindings {get: "/clients/{client_ids.client_id}/collaborators/search"}
      additional_bindings {get: "/gateways/{gateway_ids.gateway_id}/collaborators/search"}
      additional_bindings {get: "/organizations/{organization_ids.organization_id}/collaborators/search"}

      additional_bindings {get: "/applications/collaborators/exclude/{exclude_from.application_ids.application_id}/search"}
      additional_bindings {get: "/clients/collaborators/exclude/{exclude_from.clients_ids.clients_id}/search"}
      additional_bindings {get: "/gateways/collaborators/exclude/{exclude_from.gateway_ids.gateway_id}/search"}
      additional_bindings {get: "/organizations/collaborators/exclude/{exclude_from.organization_ids.organization_id}/search"}
    };
  }
```
Allowing the console to specify that it wants accounts outside of an specific entity.

On the storage side of the implementation we could fetch the direct_memberships of the specified entity and then Add the condition on `NOT IN (accounts_ids)`.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Does this need a discussion or can this be picked up as it is?

**Comment by nicholaspcr** [comment]
I left the `needs triage` label in order for it to show up at the weekly meeting just so that the front-end team knows that this is being changed but on the PR that would already happen. So indeed it is not necessary.
