### ISSUE TITLE
Console icon library

### ISSUE THREAD

**Issue by pierrephz** [TheThingsNetwork/lorawan-stack#6956]
### Summary

Find the right icon library

### Current Situation

Currently, for the console redesign, we chose to use [Google Material Symbols](https://fonts.google.com/icons?icon.set=Material+Symbols&icon.style=Rounded).

For some reasons, we face issues with some icons, for example the _star_ icon and the _plus_ icon. They look a bit off on development.

### Why do we need this? Who uses it, and when?

Enhance and smooth UX, give visual cues and add personality to the console

### Proposed Implementation

We can look for another icon library: first find consistent, trustable, professional look icon library. And then test them.

I can do researches, submit a list of icon libraries that would match with our product. Then we should agree on 1 or 2, then test them.

### Contributing

- [X] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by pierrephz** [comment]
Here is a selection of Icon library that could potentially match our product:

[Font Awsome](https://fontawesome.com/search?s=regular&f=classic&o=r)
- 3281 icons
- Paid

[Mingcute](https://www.mingcute.com/)
- 2810 icons
- Open source

[Tabler icons](https://tabler.io/icons)
- 4962 icons
- Open source

[Iconic](https://iconic.app/)
- 1328 icons
- Paid

those are 4 libraries that I think could match, especially Tabler icons. I can find more if we don't agree on one of them

cc @kschiffer

**Comment by kschiffer** [comment]
We decided on the frontend meeting today to use Tabler icons.

**Comment by KrishnaIyer** [comment]
Since #6996 is merged, we can close this.
