### ISSUE TITLE
Remove otto module import on private fork

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#7]
Blocked by https://github.com/robertkrimen/otto/pull/283

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/452 by @johanstokking

**Comment by nejraselimovic** [comment]
@johanstokking what is the status here? The blocking issue doesn't have any assignees, who could pick it up?

**Comment by johanstokking** [comment]
This has been resolved with https://github.com/TheThingsNetwork/lorawan-stack/pull/3152
