### ISSUE TITLE
Validate entities after setting fields in registries

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#70]
**Summary:** 

Validate entities after setting fields in registries, before storing it.

**Why do we need this?**

We need to verify that an entity doesn't get in an invalid state after setting individual fields, i.e. depending fields or conflicting things.

**What is already there? What do you see now?**

No validation in the registries.

**What is missing? What do you want to see?**

Validation in each registry.

**How do you propose to implement this?**

After `SetFields()`, call `Validate()` and return the error if any.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1348 by @johanstokking

**Comment by htdvisser** [comment]
@rvolosatovs says we already do this 👍
