### ISSUE TITLE
local error: tls: bad record MAC

### ISSUE THREAD

**Issue by jaydshelar** [TheThingsNetwork/lorawan-stack#7102]
### Summary

Above error appear while installing esp32 drivers

### Current Situation

not able to do further process

### Desired Situation

na

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
This repository is for The Things Stack (Network Server) and not for drivers. Is this an issue on The Things Stack or on a device?

**Comment by KrishnaIyer** [comment]
Closing the issue due to a lack of input.
