### ISSUE TITLE
UX: Change priority of "Simulate uplink" and "Schedule downlink"

### ISSUE THREAD

**Issue by eggfriedrice** [TheThingsNetwork/lorawan-stack#7188]
### Summary

In the console when you choose the messaging tab in a device, you get two options, "Simulate uplink" and "Schedule downlink". Simulate uplink is pre-selected, but I almost always want to send a downlink.

### Current Situation

When you choose the messaging tab in a device, you get two options, "Simulate uplink" and "Schedule downlink". Simulate uplink is pre-selected, but I almost always want to send a downlink.

It's also not visually very clear which tab you're on - OK, it says the words, but there's no obvious visual indicator for the direction of the message.

I've hit this a couple of times where I send my downlink and wonder why it doesn't work, and a customer of ours just has too.

Aside from testing a new decoder/integration, I never really want to simulate an uplink. I would suggest most people want to send downlinks from this tab.

### Desired Situation

Swap the order, or selectedness, of the tabs so Schedule downlink is what you see first. Possibly add some visual indicator to clarify which way the message is going to go.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
Good one. @kschiffer, I think this is good to do indeed.
