### ISSUE TITLE
Extend IS API to fetch single collaborator

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#721]
#### Summary

Recently we added server-side pagination for collaborators without providing api to fetch a single collaborator.

#### Why do we need this?

Users of the api should be able to fetch/check a single collaborator without fetching all of them. For example, this is needed in the console.

#### What is already there? What do you see now?

API to fetch a paginated list of collaborators per entity.

#### What is missing? What do you want to see?

API to fetch a single collaborator per entity (e.g. application/gateway/...)

#### Environment

IS

#### How do you propose to implement this?

1. Extend `membership_store.go` with the `FindMember` method
2. Extend `{Application,Gateway,User,Organization}Access` rpcs with `Get{Entity}Collaborator` methods.
3. Extend respective protos with the new message:
```
message Get{Entity}CollaboratorRequest {
  {Entity}Identifiers {entity}_ids = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false, (validate.rules).message.required = true];
  OrganizationOrUserIdentifiers ids = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false, (validate.rules).message.required = true];
}
```

#### Can you do this yourself and submit a Pull Request?

I can do the 2,3 steps, while the first step requires more insights into the is.

**Comment by htdvisser** [comment]
Blocking #722
