### ISSUE TITLE
Separate ui reducers from entities

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#724]
#### Summary

Currently, we store ui related data together with 

#### Why do we need this?

Cleaner store structure.
Delegate handling of the fetching/error states to scoped reducers.

#### What is already there? What do you see now?

UI related entries stored together with entities, for example,
```
{
...
  applications : {
    applications: [],
    fetching: ...,
    error: ...,
    totalCount: ...,
  }
}
```

#### What is missing? What do you want to see?

```
{
...
  applications : {
    applications: [],
    totalCount: ...,
  },
  ui: {
    fetching: {
      {base-action}: true/false,
    },
    error: {
      {base-action}: error object/undefined,
    }
  }
}
```
Where `base-action` is the action type string without the intent, for example, if the type dispatched to fetch a list of applications is `GET_APPLICATIONS_LIST_REQUEST`, then the base type would be `GET_APPLICATIONS_LIST`.
Note, that we will have to change the types of all the _request_ actions to the the `_REQUEST` postfix.

The reducers can looks something like this:
```
const fetching = function (state = {}, action) {
  const { type } = action
  const matches = /(.*)_(REQUEST|SUCCESS|FAILURE)/.exec(type)

  if (!matches) {
    return state
  }

  const [ , key, status ] = matches
  return {
    ...state,
    [key]: status === 'REQUEST',
  }
}
```
With such implementation the fetching value is automatically stored in the store for every _request_ action and reset by every _success_ or _failure_ action.
Similar logic applies to the `error` reducer with only difference that the error value is set by the _failure_ action and reset by all others.

 The fetching value for a certain action(s) could be received via appropriate selector:
```
const selectFetchingStore = state => state.ui.fetching

const selectFetchingEntry = (state, baseActionType) =>
  selectFetchingStore(state)[baseActionType] || false

export const createFetchingSelector = actions => function (state) {
  if (!Array.isArray(actions)) {
    return selectFetchingEntry(state, actions)
  }

  return actions.some(action => selectFetchingEntry(state, action))
}
```
#### Environment

browser (console)

#### How do you propose to implement this?

See above

#### Can you do this yourself and submit a Pull Request?

Yes

Let me know what you think @kschiffer

**Comment by kschiffer** [comment]
Yes, sounds very good to me!
