### ISSUE TITLE
Change delete button behavior in applications that still have devices

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#726]
#### Summary
At the moment, deleting an application in the console will not work when the application still has end devices. This is correct behavior, however, there is no proper feedback for the user to hint him towards this constraint.
Related: #369 

#### Why do we need this?
Improve/fix UX.

#### What is already there? What do you see now?
Hitting the delete button will not yield any reaction when the application still has devices.

#### What is missing? What do you want to see?
A warning telling the user that the device cannot be deleted as long as it still has end devices registered.

#### Environment
Console in browser.

#### How do you propose to implement this?
We could use the modal to give this info to the user. I was thinking also about disabling the button, but that would leave the user unclear as to why.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by htdvisser** [comment]
As discussed in the v3 meeting, we won't be doing this. Console is not responsible for preventing backend errors.
