### ISSUE TITLE
Replace hard-coded console routes with APP_ROOT config value

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#727]
#### Summary
We currently still use hard coded `console` values inside routes, when these should be replaced with the `window.APP_ROOT` value to enable configurations with root URI other than `console`.

#### Steps to Reproduce
1. Configure the stack to have a `--console.mount` other than `console`
2. See the console not working

#### What do you see now?
Console not working when the mount is different than `console`

#### What do you want to see instead?
Console working regardless.

#### Environment
Console in browser.

#### How do you propose to implement this?
Replace all occurrences of `console` inside routes (and similar props) with `window.APP_ROOT`

#### Can you do this yourself and submit a Pull Request?
Yes but help welcome.

**Comment by htdvisser** [comment]
Also OAuth app
