### ISSUE TITLE
Add simple "logged in" screen and branding to OAuth app

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#730]
#### Summary
The oauth app is currently not properly branded. It needs to be branded dynamically based on the stack configuration.
Related: https://github.com/TheThingsIndustries/lorawan-stack/issues/1041

#### Why do we need this?
Basic functionality. Unbranded OAuth app leaves users unclear about the proper context.

#### What is already there? What do you see now?
Some OAuth app pages with no logos, brand titles or whatsoever.

#### What is missing? What do you want to see?
At least a configurable logo and title, together with header and/or footer.

#### Environment
OAuth provider in browser.

#### How do you propose to implement this?
Subject of discussion.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by johanstokking** [comment]
@kschiffer please indicate what the discussion is and mention people to loop them in

**Comment by kschiffer** [comment]
Closing in favor of #1422
