### ISSUE TITLE
Update GH Actions runner to Ubuntu 24

### ISSUE THREAD

**Issue by happyRip** [TheThingsNetwork/lorawan-stack#7323]
### Summary

There was a new runner released. We should upgrade to it. https://github.blog/changelog/2024-06-24-github-actions-ubuntu-24-04-image-now-available-for-arm64-runners/

### Current Situation

Currently we use the `ubuntu-22.04-4core` for running our actions. We should switch to the newest available runner.

### Why do we need this? Who uses it, and when?

Upgrading to the new runner will make the actions run faster.

### Proposed Implementation

Update the runner and test action execution.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Validation

- [ ] The feature is tested in a staging environment.
- [ ] The feature is documented in [The Things Stack Documentation](https://www.thethingsindustries.com/docs/)

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
This is completed via #7360
