### ISSUE TITLE
OAuth client authorizations state not updated on delete

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-stack#7350]
### Summary

When you delete an OAuth client from `/console/user-settings/authorizations` the state fails to update and refresh is required

### Steps to Reproduce

Open the console at `/console/user-settings/authorizations`
Click on one of the clients and click `Revoke authorization`

### Current Result

The list page will open with the same result, but refreshing the page will remove the one you deleted

### Expected Result

After clicking `Revoke authorization` the client should not be in the list

### Deployment

The Things Stack Cloud

### The Things Stack Version

3.32

### Proposed Fix

<img width="509" alt="Screenshot 2024-10-21 at 12 02 23" src="https://github.com/user-attachments/assets/42740430-e3ae-421c-8fcc-e744e07d2a50">

It looks like the list request is made for awaiting the delete to succeed. I would start by checking out why

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Validation

- [ ] The fix is tested in a staging environment.
- [ ] The fix is documented in [The Things Stack Documentation](https://www.thethingsindustries.com/docs/)

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by KrishnaIyer** [comment]
So based on the Slack thread here: https://thethingsindustries.slack.com/archives/C06UQSMPB/p1729502918133949

Seems like we don't wait for the success of the DELETE request before requesting a GET. @mjamescompton I guess the implementation here is straightforward?
