### ISSUE TITLE
pkg/rpcserver does not have unit tests

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#740]
#### Summary

The package `pkg/rpcserver` does not have any unit tests.

#### What do you want to see instead?

We should test that

1. The loopback connection behaves as expected
2. The server options are applied as expected

#### Can you do this yourself and submit a Pull Request?

Yes, but if anyone else wants to take this, go ahead, because I have enough other things to do...

**Comment by KrishnaIyer** [comment]
I'll take this one.. :)
