### ISSUE TITLE
Console 404 not found

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/lorawan-stack#750]
#### Summary

After clean installation of the stack, following the guide of DEVELOPMENT.md, while trying to open the console, the server replies with 404.

`"error:pkg/errors/web:http (HTTP error: code=404, message=Not Found)"`

#### Steps to Reproduce

1. `git clone ...`
2. `make init`
3. `./mage init`
4. `/mage js:build`
4. `make dev.databases.start`
5. `go run ./cmd/ttn-lw-stack start`
6. In browser -> `http://localhost:1885/console` || `https://localhost:8885/console`

.envrc file:

```
export TTN_LW_CA=cert.pem
export TTN_LW_OAUTH_SERVER_ADDRESS=http://localhost:1885/oauth
export TTN_LW_EVENTS_BACKEND=redis
```

#### What do you see now?

Stack info: 
```
INFO Request handled                          
duration=15.661µs error=error:pkg/errors/web:http (HTTP error: code=404, message=Not Found) error_cause=code=404, message=Not Found method=GET namespace=web remote_addr=[::1]:52323 request_id=01DBMM9JWEW4MWA7HDX07TDQC0 status=404 url=/console
```

Browser message: 
`"error:pkg/errors/web:http (HTTP error: code=404, message=Not Found)"`
#### What do you want to see instead?

Console working

#### Environment

NPM 11.10.0
lw-stack 3.0.3

Safari && Chrome

#### How do you propose to implement this?

Find out what causes the error?
I am happy to participate in the discussion and find what causes the issue, because it seems like this does not happen all the time and to all the users

**Comment by htdvisser** [comment]
This is working as intended.

Until we've reached the console MVP milestone, the console is not started by default. You need to explicitly start all components with `ttn-lw-stack start all`.
