### ISSUE TITLE
Console Add Device page scrolling issue

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/lorawan-stack#752]
#### Summary

While trying to add a device to an application on small screen (13"), not all the settings are seen, as well as the button `Create Device` to finish adding the device,  but scrolling is not possible (does not work).

On a big screen (27"), all the settings and the button are seen without the need to scroll.

#### Steps to Reproduce

1. Create an application
2. "Add Device"
3. ...

#### What do you see now?

13" screen: 
<img width="1440" alt="Screenshot 2019-05-24 at 13 19 08" src="https://user-images.githubusercontent.com/37446624/58324461-359fcc00-7e27-11e9-91d1-302a77fb419b.png">

27" screen:
![Screenshot 2019-05-24 at 13 19 29](https://user-images.githubusercontent.com/37446624/58324466-3df80700-7e27-11e9-8a5f-8cc2d7469fe9.png)

#### What do you want to see instead?

Scrolling enabled on the page

#### Environment

Safari

**Comment by bafonins** [comment]
The issue seems to happen only when using safari.

Chaning [L25 app.styl](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/webui/console/views/app/app.styl#L25) to `overflow: overlay` fixes the issue. This was changed in [this commit](https://github.com/TheThingsNetwork/lorawan-stack/commit/1ae922785dd2a9ea14b649107d2e6758b6652bdf#diff-0c75926bf7ddd31eca43d047867cf78c). @kschiffer could you justify the change?

**Comment by kschiffer** [comment]
`overlay` is not a valid property for `overflow`. If I remember correctly, this was changed due to multiple scrollbars being visible otherwise.

**Comment by kschiffer** [comment]
So seems like this needs a little more fiddling to get it right in all browsers.

**Comment by bafonins** [comment]
> overlay is not a valid property for overflow.

Sort of. It is not standardized and works only in webkit based browsers, in others it fallbacks to `auto` as far as i understand.

That was the issue:
<img width="811" alt="Screenshot 2019-03-29 at 16 03 21" src="https://user-images.githubusercontent.com/16374166/58326915-75b67d00-7e2e-11e9-8178-ebbae302a8b9.png">

I checked latest versions of firefox/chrome and safari with `overflow: auto` - it solves the scrolling issue and doesnt revoke the 'multiple scrollba' issue

**Comment by kschiffer** [comment]
I believe I also tried `auto` there but it was leading to some other problem. Maybe open a PR with it and I will double check.
