### ISSUE TITLE
Improve error handling in forms / avoid out-of-view error messages

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#774]
#### Summary
Submit error messages in our forms appear at the top of the form, which is potentially out-of-view in longer forms. This leads to users not getting proper error feedback from form submits. We have this problem e.g. in the device data forms (Add Device, Device General Settings)

#### Why do we need this?
Is bad UX

#### What is already there? What do you see now?
Frontend error handling; error messages appearing at the top of the form

#### What is missing? What do you want to see?
Making sure the error message can be seen by the user

#### Environment
Console in browser.

#### How do you propose to implement this?
We can apply two measures here:
1. Make sure that all mappable error message will be mapped to a form field (and not be set as generic error message at the top of the form)
2. Make sure that the viewport will scroll to a error message, or validation error, in case it is out of view.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
Resolved in https://github.com/TheThingsNetwork/lorawan-stack/pull/931
