### ISSUE TITLE
Search content in the documentation

### ISSUE THREAD

**Issue by Sypheos** [TheThingsNetwork/lorawan-stack#782]
#### Summary
Search function is common and essential function for any documentation.
...

#### Why do we need this?
The documentation must be searchable to help finding document related to a topic and find problem solving solution faster.

...

#### What is already there? What do you see now?
Nothing
...

#### What is missing? What do you want to see?
A search bar proposing result based on the input
...

#### Environment
Hugo, HTML, JS
...

#### How do you propose to implement this?
Hugo propose several option on there website.
https://gohugo.io/tools/search/
Algolia looks like a good choice for the doc hosted on github, they a free Community tiers that can fit.
A local search for offline documentation would be interesting too.
...

#### Can you do this yourself and submit a Pull Request?
Yes
...

**Comment by Sypheos** [comment]
Blocked by #395

**Comment by benolayinka** [comment]
Closed by #2588
