### ISSUE TITLE
Support Unmarshalling of SX1301 Conf

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#808]
#### Summary

Support Unmarshalling of SX1301 Conf

#### Why do we need this?

To un-marshal SX1301 Configuration when used stand-alone or as part of packet-forwarder/router config.

#### What is already there? What do you see now?

Not Implemented `errUnmarshalNotImplemented `

#### What is missing? What do you want to see?

Implement it.

#### Environment

`ttn-lw-stack v3.03`

#### How do you propose to implement this?

- Multi-stage un-marshaling due to the sub-messages.

#### Can you do this yourself and submit a Pull Request?

Yup

**Comment by KrishnaIyer** [comment]
Closing this since we don't really need this.

**Comment by KrishnaIyer** [comment]
As discussed in the previous status meeting, I'm implementing a simple un-marshaler to support Basic Station tests. 
If we need to optimize it,

**Comment by johanstokking** [comment]
Please consider a `map[string]interface{}` for testing and keep it simple. At runtime I don't see a reason to unmarshal the SX1301 configuration.

**Comment by KrishnaIyer** [comment]
Yeah that's the plan. This is only for testing so I don't plan to spend time on optimizing it.
