### ISSUE TITLE
Add flag to CLI to dump requests

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#816]
#### Summary

It would be nice to have a flag in the CLI that dumps request payloads for RPCs.

#### Why do we need this?

This could help with debugging potential CLI problems, or could help developers that want to call the API endpoints directly from their own scripts

#### What is already there? What do you see now?

The typical behavior is for the CLI to make a request and print the response JSON to stdout.

#### What is missing? What do you want to see?

A flag to print the request JSON to stderr.

#### Environment

ttn-lw-cli <= v3.0.3

#### How do you propose to implement this?

This could perhaps be implemented as a gRPC interceptor. If a `--dump-requests` flag is provided, the interceptor would print which RPC is being called, and the JSON-encoded request payload.

#### Can you do this yourself and submit a Pull Request?

Yes. In any case I will look into the possibility of doing this in an interceptor. When that's easily doable, I can reassign the issue to someone else.

**Comment by johanstokking** [comment]
@neoaggelos please triage issue when you start working on it
