### ISSUE TITLE
Fill issued JoinEUIs and DevAddrs on Device create

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#820]
#### Summary
With #661 #758 being implemented, we can use the new RPCs to obtain the JoinEUI prefixes of the JS configuration and get a DevAddr from the NS. In the console this info should be used to prefill the value of the JoinEUI and DevAddr fields.

#### Why do we need this?
Reduce input errors and assist users when creating devices.

#### What is already there? What do you see now?
- The [`Js.GetJoinEUIPrefixes` RPC](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#service-js)
- The [`Ns.GenerateDevAddr` RPC](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/api/api.md#service-ns)
- The "Add new end device" form in the console

#### What is missing? What do you want to see?
Functionality to fetch the JoinEUIs and prefill the value in the form.

#### Environment
Console, js SDK

#### How do you propose to implement this?
A little button in the form field that can be clicked to fill an issued JoinEUI/DevAddr.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by bafonins** [comment]
taking over this one, since working on improving the device form - https://github.com/TheThingsNetwork/lorawan-stack/issues/579
