### ISSUE TITLE
Restructure applications redux store for pagination

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#825]
#### Summary

Currently, we have redux files related to applications scattered across `store/**/application.js` and `store/**/applications.js` files which it problematic to combine redux primitives together related to applications. Besides that, the structure of the store is not effective at the moment.

Moreover, the strategy I propose here makes implementation of https://github.com/TheThingsNetwork/lorawan-stack/issues/723 straightforward and gives opportunity to add caching.

#### Why do we need this?

Cleaner store structure, reuse pagination logic across the app.

#### What is already there? What do you see now?

* `application`/`applications` reducers
* `application`/`applications` action creators
* `application`/`applications` selectors

#### What is missing? What do you want to see?

* All redux primitives for applications moved to `store/{selectors/reducers/actions/middleware}/applications.js`
* Introduce reusable pagination redux primitives 

#### Environment

console (browser)

#### How do you propose to implement this?

I propose such store structure to store paginated data:
```
{
  applications: {
    entities: {
      id: app,
      ...,
    },
    selected: id, // currently selected application
  },
  pagination: {
    applications: {
      ids: [], //  ids of entities on the current page
      totalCount: 0,
    }
  }
}
```
Then, selecting entities per page becomes: 
```
// /selectors/pagination.js
export const createPaginationIdsSelectorByEntity = function (entity) {
  const storeSelector = createStoreSelectorByEntity(entity)

  return function (state) {
    return storeSelector(state).ids || []
  }
}

// /selectors/applications.js
const selectApplicationStore = state => state.applications
const selectApplicationEntitiesStore = state => selectApplicationStore(state).entities
const selectAppsIds = createPaginationIdsSelectorByEntity(ENTITY)
const selectApplicationById = (state, id) => selectApplicationEntitiesStore(state)[id]

export const selectApplications = state => selectAppsIds(state).map(id => selectApplicationById(state, id))
```

For `api-keys`/`collaborators`:
```
/**
{
  apiKeys: { // api keys have globally unique ids
    entities: {
      id: { ...entity, appId },
      ...
    },
    selected: id,
  },
  collaborators: {
    entities: {
      id: { ...entity, gtwId },
      ...
    },
    selected: id,
  },
  pagination: {
    keysByApplication: {
      app-id: {
        ids: [ ids of the current page ],
        totalCount: 0,
      },
    },
    collaboratorsByApplication: {
      app-id: {
        ids: [ ids of the current page ],
        totalCount: 0,
      },
    }
  }
}
*/
```
This would work because ids for both collaborators/api-keys are globally unique. All we have to do is check whether a particular collaborator/api-key belongs to its parent entity. This is why we store additional parent entity identifier with each collaborator/api-key and select it using this approach:
```
// /selectors/api-keys.js
export const selectSelectedApplicationApiKey = function (state, keyId) {
  const selectedKeyId = selectSelectedKeyId(state)
  const selectedAppId = selectSelectedApplicationId(state)

  if (key.appId === selectedAppId) {
    return selectApiKeyById(state, selectedKeyId)
  }
}
```

Similar approach can be used for `devices` and other entities that do not have unique ids globally but only within the scope of the parent entity. The main difference would be to use the parent id in the store.

```
{
  devices: {
    app-id: {
      entities: {}.
      selected: id,
    }
  },
  devicesByApplication: {
    ....
  }
}
```

#### Can you do this yourself and submit a Pull Request?

yes

cc @kschiffer  let me know what you think

**Comment by kschiffer** [comment]
Thanks for the descriptive write up.
I agree with solving the issue as you suggested. 

What I am a little worried about is performance, as this involves quite some marshaling. However, I think as long as we don't notice any problem resulting from this, we can neglect this issue.

I second the need for a clearer relationship between different parts of related primitives. Especially as we are successively increasing the abstraction level of the store. We do a lot of stuff cross-sectioning different file names inside `store/{selectors/reducers/actions/middleware}` and it's becoming hard (for me at least) to scan relationships in there. 
Adding to your suggestion of removing scattered parts in different files, I would also suggest differentiating between higher-order/thunked primitives and plain ones. A directory structure I could see helping with this is:
```
├── store
│   ├── actions
│   │   ├── creators
│   │   │   ├── api-keys.js
│   │   │   ├── collaborators.js
│   │   │   ├── ...
│   │   ├── applications.js
│   │   ├── configuration.js
│   │   ├── ...
```
And then following this structure also for reducers, logics, selectors.
