### ISSUE TITLE
Document creating API key for webhooks

### ISSUE THREAD

**Issue by ecities** [TheThingsNetwork/lorawan-stack#845]
#### Summary

Problem when downlink message via webhooks:
**error:pkg/auth/rights:no_application_rights (no rights for application `app3`)**

...

#### Steps to Reproduce

1. ...Clone lorawan-stack from github (as 24.06.2019) + gettingstarted instruction
2. ... add app, dev, webhook, key as in gettingstarted
3. ... add all ACLs to application
4... webhook successfully send POST data
5.. Insufficient access rights to put data

root@propc:/home/robert# **ttn-lw-cli applications create app3 --user-id admin**

{
  "ids": {
    "application_id": "app3"
  },
  "created_at": "2019-06-24T12:21:16.862Z",
  "updated_at": "2019-06-24T12:21:16.862Z"
}

root@propc:/home/robert# **ttn-lw-cli end-devices create app3 dev4 --dev-eui 10217E00000003FF --app-eui A000000000000002 --frequency-plan-id EU_863_870 --root-keys.app-key.key 44D70CFA703C740D8EAB6A2811732B76 --lorawan-version 1.0.2 --lorawan-phy-version 1.0.2-b**

Flag --app-eui has been deprecated, use the join-eui flag

{
  "ids": {
    "device_id": "dev4",
    "application_ids": {
      "application_id": "app3"
    },
    "dev_eui": "10217E00000003FF",
    "join_eui": "A000000000000002"
  },
  "created_at": "2019-06-24T12:21:34.430Z",
  "updated_at": "2019-06-24T12:21:34.667620964Z",
  "attributes": {
  },
  "network_server_address": "localhost",
  "application_server_address": "localhost",
  "join_server_address": "localhost",
  "lorawan_version": "1.0.2",
  "lorawan_phy_version": "1.0.2-b",
  "frequency_plan_id": "EU_863_870",
  "supports_join": true,
  "root_keys": {
    "app_key": {
      "key": "44D70CFA703C740D8EAB6A2811732B76"
    }
  }
}

root@propc:/home/robert# **ttn-lw-cli applications api-keys create --name link --application-id app3 --right-application-link --right-application-all --right-application-delete --right-application-devices-read --right-application-devices-read-keys --right-application-devices-write --right-application-devices-write-keys --right-application-info --right-application-link --right-application-settings-api-keys --right-application-settings-basic --right-application-settings-collaborators --right-application-traffic-down-write --right-application-traffic-read --right-application-traffic-up-write**

  INFO API key ID: 4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ
  INFO API key value: NNSXS.4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ.KNZJFT6R3DYLI5N5XZJFWCXDDYJBF2HAXHOCK2TXDBMTFCET3KFQ
  WARN The API key value will never be shown again
  WARN Make sure to copy it to a safe place
{
  "id": "4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ",
  "key": "NNSXS.4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ.KNZJFT6R3DYLI5N5XZJFWCXDDYJBF2HAXHOCK2TXDBMTFCET3KFQ",
  "name": "link",
  "rights": [
    "RIGHT_APPLICATION_DEVICES_WRITE",
    "RIGHT_APPLICATION_SETTINGS_BASIC",
    "RIGHT_APPLICATION_SETTINGS_COLLABORATORS",
    "RIGHT_APPLICATION_TRAFFIC_UP_WRITE",
    "RIGHT_APPLICATION_DELETE",
    "RIGHT_APPLICATION_DEVICES_READ",
    "RIGHT_APPLICATION_LINK",
    "RIGHT_APPLICATION_TRAFFIC_READ",
    "RIGHT_APPLICATION_DEVICES_READ_KEYS",
    "RIGHT_APPLICATION_DEVICES_WRITE_KEYS",
    "RIGHT_APPLICATION_ALL",
    "RIGHT_APPLICATION_INFO",
    "RIGHT_APPLICATION_SETTINGS_API_KEYS",
    "RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE"
  ]
}

 

root@propc:/home/robert# **ttn-lw-cli applications link set app3 --api-key** NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ

{
  "api_key": "NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ"
}

 
 

root@propc:/home/robert# **ttn-lw-cli applications webhooks set --application-id app3 --webhook-id wh4 --format json   --base-url http://192.168.0.8/IoT/   --join-accept.path up.php   --uplink-message.path up.php**

{
  "ids": {
    "application_ids": {
     "application_id": "app3"
    },
    "webhook_id": "wh4"
  },
  "created_at": "2019-06-24T12:34:24.986984352Z",
  "updated_at": "2019-06-24T12:34:37.766238582Z",
  "base_url": "http://192.168.0.8/IoT/",
  "format": "json",
  "uplink_message": {
    "path": "up.php"
  },
  "join_accept": {
    "path": "up.php"
  }
}

 

root@propc:/home/robert# **curl http://localhost:1885/api/v3/as/applications/app3/webhooks/wh4/devices/dev4/down/push -X POST   -H 'Authorization: Bearer "NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ'  --data '{"downlinks":[{"frm_payload":"vu8=","f_port":15,"priority":"NORMAL"}]}'**

**_error:pkg/auth/rights:no_application_rights (no rights for application `app3`)_**

                                               --as.link-mode="all"
                                                --as.mqtt.listen=":1883"
                                            --as.mqtt.listen-tls=":8883"
                                        --as.webhooks.queue-size="16"
                                            --as.webhooks.target="direct"
                                           --as.webhooks.timeout="5s"
                                           --as.webhooks.workers="16"
                                        --blob.aws.access-key-id=""
                                             --blob.aws.endpoint=""
                                               --blob.aws.region=""
                                    --blob.aws.secret-access-key=""
                                        --blob.aws.session-token=""
                                          --blob.gcp.credentials=""
                                     --blob.gcp.credentials-file=""
                                          --blob.local.directory="./public/blob"
                                                 --blob.provider="local"
                                               --cluster.address=""
                                    --cluster.application-server=""
                                        --cluster.gateway-server=""
                                       --cluster.identity-server=""
                                                  --cluster.join=""
                                           --cluster.join-server=""
                                                  --cluster.keys="db114f80fd0ebf2a7b69db7e5a56fce248e53600e256b3a85d5b0ab844bc1aa8"
                                                  --cluster.name=""
                                        --cluster.network-server=""
                                                   --cluster.tls="false"
                                                        --config="/root/.ttn-lw-stack.yml"
                                                 --console.mount=""
                                   --console.oauth.authorize-url="http://localhost:1885/oauth/authorize"
                                       --console.oauth.client-id="console"
                                   --console.oauth.client-secret="console"
                                       --console.oauth.token-url="http://localhost:1885/oauth/token"
                                        --console.ui.as.base-url="http://localhost:1885/api/v3"
                                         --console.ui.as.enabled="true"
                                    --console.ui.assets-base-url="/assets"
                                      --console.ui.canonical-url="http://localhost:1885/console"
                                           --console.ui.css-file="console.css"
                                       --console.ui.descriptions=""
                                        --console.ui.gs.base-url="http://localhost:1885/api/v3"
                                         --console.ui.gs.enabled="true"
                                        --console.ui.icon-prefix="console-"
                                        --console.ui.is.base-url="http://localhost:1885/api/v3"
                                         --console.ui.is.enabled="true"
                                            --console.ui.js-file="console.js"
                                        --console.ui.js.base-url="http://localhost:1885/api/v3"
                                         --console.ui.js.enabled="true"
                                           --console.ui.language="en"
                                        --console.ui.ns.base-url="http://localhost:1885/api/v3"
                                         --console.ui.ns.enabled="true"
                                          --console.ui.site-name="The Things Network Stack for LoRaWAN"
                                          --console.ui.sub-title="The official configuration platform for The Things Network"
                                        --console.ui.theme-color=""
                                              --console.ui.title="Console"
                                   --device-repository.directory=""
                                         --device-repository.url=""
                                                --events.backend="internal"
                                      --events.cloud.publish-url=""
                                    --events.cloud.subscribe-url=""
                                          --events.redis.address=""
                                         --events.redis.database="0"
                                        --events.redis.namespace=""
                                         --events.redis.password=""
                                     --frequency-plans.directory=""
                                           --frequency-plans.url="https://raw.githubusercontent.com/TheThingsNetwork/lorawan-frequency-plans/master"
                       --gcs.basic-station.allow-cups-uri-update="false"
              --gcs.basic-station.owner-for-unknown.account-type=""
                   --gcs.basic-station.owner-for-unknown.api-key=""
                        --gcs.basic-station.owner-for-unknown.id=""
                     --gcs.basic-station.require-explicit-enable="false"
                                              --gcs.require-auth="true"
                   --gcs.the-things-gateway.default.firmware-url="https://thethingsproducts.blob.core.windows.net/the-things-gateway/v1"
                    --gcs.the-things-gateway.default.mqtt-server=""
                 --gcs.the-things-gateway.default.update-channel="stable"
                           --grpc.allow-insecure-for-credentials="false"
                                                   --grpc.listen=":1884"
                                               --grpc.listen-tls=":8884"
                                             --gs.mqtt-v2.listen=""
                                         --gs.mqtt-v2.listen-tls=""
                                                --gs.mqtt.listen=":1882"
                                            --gs.mqtt.listen-tls=":8882"
                                --gs.require-registered-gateways="false"
                                      --gs.udp.addr-change-block="5m0s"
                                     --gs.udp.connection-expires="5m0s"
                                  --gs.udp.downlink-path-expires="30s"
                                              --gs.udp.listeners=":1700="
                                          --gs.udp.packet-buffer="50"
                                        --gs.udp.packet-handlers="10"
                                     --gs.udp.schedule-late-time="800ms"
                                         --http.cookie.block-key="38E31BCAD8CFC067ABC9F2988967E387E15DF9ADDA14E63F446ED955EEEA4637"
                                          --http.cookie.hash-key="40847E55ED0CB34B3D491DC557326BF875FCE34EE0C8F50194E1BB3488055FA96D5CC4F3CF6C30C5F4922D8CEB4F72A1FE61317E1A7BC88619617AD6CEA983B3"
                                            --http.health.enable="true"
                                          --http.health.password=""
                                                   --http.listen=":1885"
                                               --http.listen-tls=":8885"
                                           --http.metrics.enable="true"
                                         --http.metrics.password=""
                                             --http.pprof.enable="true"
                                           --http.pprof.password=""
                                             --http.static.mount="/assets"
                                       --http.static.search-path="public,/srv/ttn-lorawan/public"
                                  --is.auth-cache.membership-ttl="10m0s"
                                               --is.database-uri="postgresql://root@localhost:26257/ttn_lorawan_dev?sslmode=disable"
                                  --is.email.network.console-url="http://localhost:1885/console"
                          --is.email.network.identity-server-url="http://localhost:1885/oauth"
                                         --is.email.network.name="The Things Network Stack for LoRaWAN"
                                             --is.email.provider=""
                                       --is.email.sender-address=""
                                          --is.email.sender-name=""
                                     --is.email.sendgrid.api-key=""
                                     --is.email.sendgrid.sandbox="false"
                                         --is.email.smtp.address=""
                                     --is.email.smtp.connections="0"
                                        --is.email.smtp.password=""
                                        --is.email.smtp.username=""
                                                --is.oauth.mount=""
                                   --is.oauth.ui.assets-base-url="/assets"
                                     --is.oauth.ui.canonical-url="http://localhost:1885/oauth"
                                          --is.oauth.ui.css-file="oauth.css"
                                      --is.oauth.ui.descriptions=""
                                       --is.oauth.ui.icon-prefix="oauth-"
                                           --is.oauth.ui.js-file="oauth.js"
                                          --is.oauth.ui.language="en"
                                         --is.oauth.ui.site-name="The Things Network Stack for LoRaWAN"
                                         --is.oauth.ui.sub-title=""
                                       --is.oauth.ui.theme-color=""
                                             --is.oauth.ui.title=""
                                     --is.profile-picture.bucket="profile_pictures"
                                 --is.profile-picture.bucket-url="/assets/blob/profile_pictures"
                               --is.profile-picture.use-gravatar="true"
                  --is.user-registration.admin-approval.required="false"
         --is.user-registration.contact-info-validation.required="false"
                      --is.user-registration.invitation.required="false"
                     --is.user-registration.invitation.token-ttl="168h0m0s"
         --is.user-registration.password-requirements.min-digits="1"
         --is.user-registration.password-requirements.min-length="8"
        --is.user-registration.password-requirements.min-special="0"
      --is.user-registration.password-requirements.min-uppercase="1"
                                            --js.join-eui-prefix="0000000000000000/0"
                                              --key-vault.static=""
                                                     --log.level="info"
                                            --ns.cooldown-window="1s"
                                       --ns.deduplication-window="200ms"
                            --ns.default-mac-settings.adr-margin="15"
                       --ns.default-mac-settings.class-b-timeout="1m0s"
                       --ns.default-mac-settings.class-c-timeout="15s"
                     --ns.default-mac-settings.desired-rx1-delay="5"
              --ns.default-mac-settings.status-count-periodicity="20"
               --ns.default-mac-settings.status-time-periodicity="1h0m0s"
                                          --ns.dev-addr-prefixes=""
                            --ns.downlink-priorities.join-accept="highest"
                           --ns.downlink-priorities.mac-commands="highest"
               --ns.downlink-priorities.max-application-downlink="high"
                                                     --ns.net-id="000000"
                                                 --redis.address="localhost:6379"
                                                --redis.database="0"
                                               --redis.namespace="ttn,v3"
                                                --redis.password=""
                                                    --rights.ttl="2m0s"
                                                    --sentry.dsn=""
                                                  --tls.acme.dir=""
                                                --tls.acme.email=""
                                               --tls.acme.enable="false"
                                             --tls.acme.endpoint="https://acme-v01.api.letsencrypt.org/directory"
                                                --tls.acme.hosts=""
                                               --tls.certificate="cert.pem"
                                                       --tls.key="key.pem"
                                                   --tls.root-ca=""

#### What do you see now?

root@propc:/home/robert# curl http://localhost:1885/api/v3/as/applications/app3/webhooks/wh4/devices/dev4/down/push -X POST   -H 'Authorization: Bearer "NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ'  --data '{"downlinks":[{"frm_payload":"vu8=","f_port":15,"priority":"NORMAL"}]}'

error:pkg/auth/rights:no_application_rights (no rights for application `app3`)

...

#### What do you want to see instead?

...

#### Environment

UBUNTU 16.04LTS/FF/iFemtoCell+ SPF/TELIT RE866
...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by johanstokking** [comment]
Thanks @ecities, we'll have a look at this

**Comment by johanstokking** [comment]
How did you create API key with value `NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ` ?

Because the one you mention in your steps is different and that one has all the rights.

For sending downlink, you need `RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE`.

**Comment by ecities** [comment]
Hi Johan,
Thank you very much for fast replay.

**It looks I have this right listed.**
What I did:
I get --help info for command, and display all rights available and add all of it to the command:

 **ttn-lw-cli applications api-keys create --name link --application-id app3 --right-application-link --right-application-all --right-application-delete --right-application-devices-read --right-application-devices-read-keys --right-application-devices-write --right-application-devices-write-keys --right-application-info --right-application-link --right-application-settings-api-keys --right-application-settings-basic --right-application-settings-collaborators --right-application-traffic-down-write --right-application-traffic-read --right-application-traffic-up-write**

INFO API key ID: 4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ
INFO API key value: NNSXS.4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ.KNZJFT6R3DYLI5N5XZJFWCXDDYJBF2HAXHOCK2TXDBMTFCET3KFQ
WARN The API key value will never be shown again
WARN Make sure to copy it to a safe place
{
"id": "4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ",
"key": "NNSXS.4DU2SXFXICLJUGHJPAC6BUFYFHZSKT6SOBXABUQ.KNZJFT6R3DYLI5N5XZJFWCXDDYJBF2HAXHOCK2TXDBMTFCET3KFQ",
"name": "link",
"rights": [
"RIGHT_APPLICATION_DEVICES_WRITE",
"RIGHT_APPLICATION_SETTINGS_BASIC",
"RIGHT_APPLICATION_SETTINGS_COLLABORATORS",
"RIGHT_APPLICATION_TRAFFIC_UP_WRITE",
"RIGHT_APPLICATION_DELETE",
"RIGHT_APPLICATION_DEVICES_READ",
"RIGHT_APPLICATION_LINK",
"RIGHT_APPLICATION_TRAFFIC_READ",
"RIGHT_APPLICATION_DEVICES_READ_KEYS",
"RIGHT_APPLICATION_DEVICES_WRITE_KEYS",
"RIGHT_APPLICATION_ALL",
"RIGHT_APPLICATION_INFO",
"RIGHT_APPLICATION_SETTINGS_API_KEYS",
**"RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE"**
]
}

root@propc:/home/robert# **ttn-lw-cli applications link set app3 --api-key** NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ

{
"api_key": "NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ"
}

All commands i performed are above (from gettingstarted manual).

For **TTN service cloud** we tested & developed "HTTP Integration" and works OK for common work uplink/downlink.

**I see some other issues LW-stack:**
- **TTN service cloud** seams to work very stabile almost any data passing trough but lorawan-stack missing a lot of data (device not found messages) after 2-5 data uplink (no re-join is possible - sometimes reset to factory defaults of modem and repeat all initializations steps from the begining helps).

What we are testing now is firmware update via LoraWAN so there are big data thrughput not conforming "Fair data transfers" for TTN service cloud.

**Comment by adriansmares** [comment]
I've been unable to reproduce this on the latest release (which I suppose you are using since you've mentioned that you are following the getting started guide). My logs are the [here](https://pastebin.com/JPa2Cd6A).

Your answer regarding `NNSXS.GIPVAVIAO77RFBOWTDO43XIZ5SDTRPDX7QKOGCQ.EJJRVXWEX7LIFSPYMT4WBPPSCIMIJEXTRMFOSRNT47RPF6KTWCJQ` still does not answer what rights does this key have. You need two API keys - one for linking, which should have only `--right-application-link` and one for Webhooks, which should have `--right-application-traffic-read` and `--right-application-traffic-down-write`.

**Comment by johanstokking** [comment]
@ecities I still see two different API keys. If you are using the one you mention in your last post for linking _and_ for sending downlink, it probably doesn't have the right rights. The one you created will have the right rights. Apart from that, there may be a formatting issue as @adriansmares points out above.

> * **TTN service cloud** seams to work very stabile almost any data passing trough but lorawan-stack missing a lot of data (device not found messages) after 2-5 data uplink (no re-join is possible - sometimes reset to factory defaults of modem and repeat all initializations steps from the begining helps).

We need a bit more context for this. Best is to open a new issue. Mention MAC version, OTAA vs ABP, whether you reset nonces because (OTAA) or reset frame counters (ABP) on factory reset, etc.

**Comment by ecities** [comment]
Thanks a lot 
 it looks that complete clearing all apps, gws, api-keys, devices and 
following Adrian's instructions in log file from the beginning
did the trick and **downlink working OK**

**I think adding this to getting started is crucial - it's not there :)**
`ttn-lw-cli applications api-keys create \
  --name wh-client \
  --application-id app3 \
  --right-application-traffic-read \
  --right-application-traffic-down-write`

**Comment by johanstokking** [comment]
Glad to hear. And thanks for the suggestion, that's a fair point. We'll pick that up.

**Comment by ecities** [comment]
I created second app,api-keys,webhook, etc for the same device (dev1) (for Firmware UPGRADE) and it have the same error (403) on server console - and access rights problems. 
**But when I use docker-compose down & up it starts working OK.
Does  webhooks operations requires server down/up or some time delay?**

**Comment by johanstokking** [comment]
No, those changes are effective immediately.

**Comment by ecities** [comment]
ok, thanks

**Comment by ecities** [comment]
Hi,
I'm testing webhooks for LoRaWAN firmware update and it seems downlink have very small size limit
for 26B downlink data is working
for 57B  downlink is too big - got message on server console:
**WARN: Application downlink present, but the payload is too long.**

**What is the limit and? Can it be adjusted to send as big packet as possible?**
We must update at least 64kB so packet size really matters.

**Comment by johanstokking** [comment]
The maximum payload size depends on the PHY (regional parameters) and data rate. Please see the LoRaWAN Regional Parameters for your version, for example [1.0.3 rev A](https://lora-alliance.org/resource-hub/lorawan-regional-parameters-v103reva).

**Comment by ecities** [comment]
Johan thanks for replay and pointing out data rate but default settings of modem looks OK

I'm on Telit re866 module which is 1.0.2 ClassA/C certified & check LoRaWAN 1.0.2 for regional parameters.
I'm using Class A (unable to switch to class C)

Default settings datarate (sf12/125kHz) - rx2datarate (default as for lora 1.0.2 spec)
Testing conditions: -90dBM
I also set other datarate (sf7/125) (adoptive dr=on) kerlink femtocell shows in logs (sf7bw125) - according to lora specs max. payload size is 230/222. I tested other values with the same payload size and sf12 (not defined).

The biggest downlink size transfer I manage to send is 54B (binary) - base 64 coded (72)

**Comment by johanstokking** [comment]
@ecities can you file a separate issue for this and fill out the issue template?

Let's keep this issue specific to documenting creating an API key for working with webhooks. That's now burried in the MQTT section.

**Comment by ecities** [comment]
OK thanks,

**Comment by johanstokking** [comment]
We did not finish documenting creating an API key for working with webhooks.

**Comment by ecities** [comment]
OK, sorry wrong button
