### ISSUE TITLE
Time Synchronization of Node devices

### ISSUE THREAD

**Issue by ecities** [TheThingsNetwork/lorawan-stack#871]
Is there a way of time synchronization of nodes from the Network Server?

We have tested downlink "set time info packet" but it always arrives next upload time (no matter downlink priority is set) - so is very inacurate.

**Comment by KrishnaIyer** [comment]
@ecities: Thanks for the issue but please update your issue description with our feature/bug request template. We only consider issues with the proper fields filled in.

**Comment by KrishnaIyer** [comment]
closed in favour of #873
