### ISSUE TITLE
Readme.md typos

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/lorawan-stack#896]
#### Summary

Readme.ms of the repo root has two minor typos

#### Steps to Reproduce

1. Read root Readme.md

#### What do you see now?

In ***Getting Started***:

> Do you want to set ***op*** a local development environment? ...

In ***Support***:

> The forums contain a massive amount of information and ***has*** great search

#### What do you want to see instead?

In ***Getting Started***:

> Do you want to set ***up*** a local development environment? ...

In ***Support***:

> The forums contain a massive amount of information and ***have*** great search

#### How do you propose to implement this?

Correct the typos

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by KrishnaIyer** [comment]
> The forum contains a large amount of information and has great search support.
