### ISSUE TITLE
Adapt gateway registration process to reflect new workflow

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#9]
**Summary:** 

In v3, we will change some important details in the logic of **gateway information**. To reflect those changes, it will be better if we change the gateway registration experience.

**Gateway EUI and legacy protocols**
Each gateway can have, on a very high logic level, two identifiers. It has a **gateway ID** (e.g. `laurens-rockstart-roof`), to identify it in TTN's database. It can also have a **gateway EUI**, made of 8 bytes (e.g. `0000024B08030C5F` in hex) - indeed, in the legacy non-TTN protocol, this was how gateways identified themselves. Gateway EUIs are usually attributed by manufacturers, but since there is no way to verify it, we have always accepted entering arbitrary EUIs as long as they were unique.

In v2, IDs and EUIs were intertwined: if a user wanted to use legacy protocols with their gateway, the ID was generated from the ID. For example, `laurens-rockstart-roof` was a valid ID for gateways exchanging with modern protocols - but for gateways using legacy protocol, the ID was generated from the EUI, in a `eui-<hex EUI>` pattern (e.g. `eui-0000024b08030c5f`). To understand this better, you can try to register gateways on the [current console](https://console.thethingsnetwork.org/gateways).

**Why do we need this?**
In v3, IDs will no longer be tied to the EUI - the user can use any possible ID for any gateway. However, **when registering a gateway**, the user also has the possibility of specifying an EUI that can identify this gateway: see [the API](https://github.com/TheThingsIndustries/ttn/blob/issue/352-gateway-eui/api/identifiers.proto#L23-L29). This EUI cannot be changed or removed after registration, nor can an EUI be added after registration is complete. This change of modus operandi should be clear to the user.

Furthermore, if a gateway owner wants to add an EUI, this means that they might use legacy protocols. In that case, they should be offered additional gateway options specific to legacy protocols. The first one that comes to mind is the TX delay option, about which you can find [more details here](https://github.com/TheThingsIndustries/ttn/blob/feature/documentation/doc/gateway-server.md#udp-protocol) and here: https://github.com/TheThingsIndustries/ttn/issues/378.

**What is already there? What do you see now?**
- The registration process of v2 console

**What is missing? What do you want to see?**
- Gateway registration flow in the v3 console
  - UX strategy
  - Designs

**How do you propose to implement this?**
> Regarding the EUIs: all gateways now have an ID and optionally an EUI. We should not imply that when entering an EUI, that people are using legacy protocols – these things are not related. Many manufacturers simply think in terms of EUIs, serial numbers, MAC addresses, etc. So the flow that we have in V2 (either ID or EUI, and EUI is legacy) changes: it will be ID and optionally an EUI, without any reference to protocols because it's irrelevant.

**What can you do yourself and what do you need help with?**
Needs to be worked out by @kschiffer @bafonins

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/579 by @egourlao

**Comment by bafonins** [comment]
@johanstokking is it still relevant?

> when registering a gateway, the user also has the possibility of specifying an EUI that can identify this gateway: see the API. This EUI cannot be changed or removed after registration, nor can an EUI be added after registration is complete.

note that this is not true, it is possible to change the EUI after gateway creation.

> Furthermore, if a gateway owner wants to add an EUI, this means that they might use legacy protocols.

what about this?

**Comment by johanstokking** [comment]
This is not relevant anymore indeed.
