### ISSUE TITLE
Increase page size of entity tables to 20

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-stack#907]
#### Summary
The entity tables currently have a page size of 5, which is a bit low. 20 is a better value that will fill a usual browser window (16:9) better.

#### Why do we need this?
Improve UX. Page sizes that are too small are hard to navigate through. Whether 20 is indeed the optimal default needs some progressive insight.

#### What is already there? What do you see now?
- Functionality to set the page size in our `<Pagination />` component.
- Various default value constants for page sizes, set to 5

#### What is missing? What do you want to see?
A unified default value constant of 20 items per page for all entity tables. (Except for the device table in the application overview)

#### Environment
Console.

#### How do you propose to implement this?
Trivial.

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by johanstokking** [comment]
I'm opting for 20, 25 or 30, potentially making the table a bit more condense.

**Comment by kschiffer** [comment]
Ok, let's use 20 then. Anything higher makes the page already quite long. We can later provide a `Show all items` button.
