### ISSUE TITLE
Improve Network Server test coverage and consistency

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#918]
#### Summary

Improve Network Server test coverage and consistency

#### Why do we need this?

To ensure correctness

#### What is already there? What do you see now?

Coverage of `73.3%`

#### What is missing? What do you want to see?

Coverage of `90%` or more

#### How do you propose to implement this?

Add test cases for uncovered parts.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by nejraselimovic** [comment]
@htdvisser #960 looks the same to me, so can we close this issue? If that's not the case, can you explain what's the difference here?

**Comment by htdvisser** [comment]
Yeah, that's pretty much the umbrella issue for this one. I don't think this one adds a lot of value over #960, so we can close this one and track progress there.
