### ISSUE TITLE
Incorrect handling of RSSIC/RSSIS

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#927]
#### Summary

After investigating https://github.com/TheThingsNetwork/gateway-connector-bridge/issues/35 I discovered that we've been handling the RSSIC and RSSIS fields incorrectly. This results in incorrect RSSI values.

#### What do you see now?

1. https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/ttnpb/udp/translation.go#L135-L136
2. https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/gatewayserver/io/mqtt/format_protobufv2.go#L170-L174

#### What do you want to see instead?

The real "RSSI" value should be `RSSIC` or ChannelRSSI.

#### How do you propose to implement this?

I think the cleanest way to fix this is to add a `SignalRSSI` field to `ttnpb.RxMetadata`, and always copy the value of `ChannelRSSI` to `RSSI` when converting.

#### Can you do this yourself and submit a Pull Request?

Let's discuss the best way forward first and then work on fixing it

**Comment by johanstokking** [comment]
> I think the cleanest way to fix this is to add a `SignalRSSI` field to `ttnpb.RxMetadata`, and always copy the value of `ChannelRSSI` to `RSSI` when converting.

Sounds good. I can't think of a cleaner option that won't break API to gateways (gRPC) and applications (metadata).
