### ISSUE TITLE
Show sub-band channel utilization of gateways

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#933]
#### Summary

We would like to see channel utilization in the gateway connection stats.

Originally requested by @ajovertoom

#### Why do we need this?

It's helpful for users to see how much their gateway is used, how much each sub-band is used and how much each channel is used. 

#### What is already there? What do you see now?

We have the `uplink_count` and `downlink_count` in the API, and those fields are filled by the GS. The GS also keeps track of downlink utilization of sub-bands.

#### What is missing? What do you want to see?

To have the (downlink) utilization of a gateway's sub bands exposed through API.

#### How do you propose to implement this?

- [X] Expose utilization from scheduling package (@neoaggelos)
- [X] Add utilization to GatewayConnectionStats API (@neoaggelos)
- [X] Fill utilization fields into GatewayConnectionStats (@neoaggelos)
- [ ] Update view in Console (@bafonins or @kschiffer)

**Comment by neoaggelos** [comment]
For this one, I would suggest we add a new SubBandUtilizations map[string]float32 field. For each subband, we can get the duty cycle from https://github.com/TheThingsNetwork/lorawan-stack/blob/13d2f9d6ccd7ffac56b144507e3a5ac65d464717/pkg/gatewayserver/scheduling/sub_band.go#L107.

**Comment by johanstokking** [comment]
I would go with a `SubBandStatistics` struct which includes a float for duty-cycle, but potentially also other stats in the future, like SNR per DR, number of packets sent/received etc.

What would your proposal be for the `string` key? Sub-bands don't really have a name; they merely have a lower and upper frequency.

**Comment by neoaggelos** [comment]
I was thinking `MinFrequency-MaxFrequency` (e.g. `863000000-865000000`) Since we are in MHz territory though, we could drop the extra zeros to make this more readable, e.g. `863-865`. Ι think that it looks OK with a single decimal too (e.g. `868.7-869.2`).

It makes more sense to go with a struct, in order to make adding more stats in the future.

**Comment by johanstokking** [comment]
> to make this more readable, e.g. `863-865`. Ι think that it looks OK with a single decimal too (e.g. `868.7-869.2`).

This is not the job of the API for many reasons, including that the API doesn't know how the client will visualize this or what the decimal separator of the client is, see comments in #2513.

**Comment by neoaggelos** [comment]
Reopening because we still need the Console part

**Comment by johanstokking** [comment]
@neoaggelos please update issue comment

**Comment by kschiffer** [comment]
Moved this to Next Up, since it is goldplating and I have too many upcoming issues already.

**Comment by htdvisser** [comment]
This is now covered by the NOC.
