### ISSUE TITLE
Restructure Integrations

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#935]
#### Summary

The integrations should be restructured in the sidebar

#### What is already there? What do you see now?

<img width="258" alt="Screenshot 2019-07-04 at 16 06 56" src="https://user-images.githubusercontent.com/181308/60672496-c7aee180-9e75-11e9-8a9a-3f450c90ecd0.png">

#### What is missing? What do you want to see?

- Integrations
  - MQTT overview page with basic connection info as suggested by @wienke (probably requires #138 or configuration)
  - Webhooks (what we have now)
  - Pubsub (to be built into #883)

**Comment by adriansmares** [comment]
#883 has been merged.
