### ISSUE TITLE
Optimize downlink task starting times

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#936]
#### Summary

Network Server should smarter choosing the starting time of downlink tasks

#### Why do we need this?

To ensure we don't miss downlink slots and not waste resources generating downlinks, when we know it's impossible to schedule

#### What is already there? What do you see now?

Apart from uplink-triggered downlink tasks, they're added at `time.Now()`

#### What is missing? What do you want to see?

For Class B/C:
- Add downlink task after downlink timing-related MAC settings are changed(e.g. `status_count_periodicity`) via registry
- Compute precisely when should the downlink task be added if possible

#### How do you propose to implement this?

When `lorawan_phy_version`, `frequency_plan_id`, `mac_state`, `mac_settings`, `last_dev_status_received_at` and `recent_uplinks` are available, NS can determine precisely when should the downlink task be added, if it's time-bound.

The downlink tasks adding after downlink queue update should be changed.

In fact, for all classes NS should only add a downlink task after an uplink, if there's application downlink that can be scheduled or MAC commands to schedule.
After the app queue or the downlink-related device settings are updated, NS shall look at the proto to determine if a downlink can be scheduled and depending on that, add a downlink task.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by rvolosatovs** [comment]
Blocked by #631 (implementing this without properly failing downlinks will result in nasty infinite loops)
