### ISSUE TITLE
Missing headers from Webhook configuration

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#938]
#### Summary

We can't set headers (such as Authorization) when configuring webhooks

#### Steps to Reproduce

1. Go to Application > Integrations > Add

#### What do you see now?

![image](https://user-images.githubusercontent.com/181308/60672980-f5e0f100-9e76-11e9-8268-3ca92f84799d.png)

#### What do you want to see instead?

Some way to configure the request headers

#### How do you propose to implement this?

Leaving that to @kschiffer

**Comment by johanstokking** [comment]
Even though important; let's not block `v3.1.0` for this. Console is really "community technology preview"

**Comment by htdvisser** [comment]
Same for CLI

**Comment by htdvisser** [comment]
Added to CLI in #1002.

**Comment by adriansmares** [comment]
Blocked by #1072
