### ISSUE TITLE
Generic device format conversion

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#949]
#### Summary

Generic device format conversion.

References https://github.com/TheThingsIndustries/lorawan-stack/issues/1672

#### Why do we need this?

To import devices from other sources in various formats.

#### What is already there? What do you see now?

JS `Provision()` rpc to turn provisioning data into a stream of `EndDevice` templates

#### What is missing? What do you want to see?

The idea of turning a binary file in a template of `EndDevice` that can be created on the concerning components is good, but this endpoint is not specific to Join Server. There can also be a (standardized) device exchange format with NS and AS specific entries.

#### How do you propose to implement this?

New gRPC service;
- Returns list of supported formats by the server configuration
- Converts a binary file into a stream of `EndDevice` that can either be created directly and/or be altered by the client (i.e. setting/overriding fields)

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by htdvisser** [comment]
What component(s) would expose this new service? I think it would be a bit strange to expose it on the full stack (including GS), but on the other hand, we already do the same with the frequency plans RPC (expose it on the JS).

**Comment by johanstokking** [comment]
This service is helpful for any component with a device registry (IS, JS, NS and AS). Some converters will only return fields for one of these components (i.e. secure element manifests typically only JS), some for multiple (i.e. import files all components).

So I'd suggest just like GCS a dedicated component that starts with IS, JS, NS and AS.
