### ISSUE TITLE
Release from release branches

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#970]
#### Summary

Release from release branches.

#### Why do we need this?

To avoid triggering releases from anyone pushing tags accidentally.

#### What is already there? What do you see now?

Trigger releases on pushed tags in `master` branch.

#### What is missing? What do you want to see?

Trigger releases on release tags.

#### How do you propose to implement this?

- [x] Setup branch protection for release branches on GitHub
- [ ] ~Apply release rules for Travis on release branches (i.e. `branch =~ /^release\/v.*/`)~
- [ ] Only release if tag name is like `^v3\.[0-9]+\.[0-9]+`

#### Can you do this yourself and submit a Pull Request?

Will review

**Comment by adriansmares** [comment]
Should we clean dependency caches for release builds as well ?
https://github.com/TheThingsNetwork/lorawan-stack/blob/4163efd780040e5d04b35fc7d6c68d443258ebd9/.travis.yml#L37-L43

**Comment by htdvisser** [comment]
As already discussed on Slack, tags aren't pushed on branches, so you can't _"Trigger releases on pushed tags in `release/v*` branches"_.

If the goal is to only trigger releases on actual release tags (and not other tags), we can make Travis check that the release tags are the same as we'd expect from a release tag generated by our Mage tooling:

```
% git tag -v $TRAVIS_TAG 2> /dev/null | grep -E '^tagger'
tagger Johan Stokking <johan@thethingsnetwork.org> 1557491575 +0200
```

```
% git tag -v $TRAVIS_TAG 2> /dev/null | grep -E '^(Pre-r|R)elease'
Release version 3.0.3
```

**Comment by johanstokking** [comment]
@adriansmares stiped out the second checkbox; this doesn't work when combining Travis and GoReleaser apparently. So it's just a small clarification in Travis to regex the tag name.
