### ISSUE TITLE
Switch to lyft/protoc-gen-validate

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#98]
**Summary:** 

Switch to https://github.com/lyft/protoc-gen-validate for validation instead of https://github.com/mwitkow/go-proto-validators

**Why do we need this?**

1. Validators generated for languages besides Go
2. Support for `gogo` extensions
3. Way more features
4. Proper tagged builds
5. Backed by a known company

**What is already there? What do you see now?**

https://github.com/mwitkow/go-proto-validators

**What is missing? What do you want to see?**

https://github.com/lyft/protoc-gen-validate

**How do you propose to implement this?**

- [x] Add https://github.com/lyft/protoc-gen-validate to https://github.com/TheThingsIndustries/docker-protobuf
- [ ] Switch the `protoc` flags to call https://github.com/lyft/protoc-gen-validate

**What can you do yourself and what do you need help with?**

~I'll take care of adding https://github.com/lyft/protoc-gen-validate to https://github.com/TheThingsIndustries/docker-protobuf.
Possibly reuse https://github.com/znly/docker-protobuf/pull/54~ The protoc image contains the plugin since version `3.0.26`

**Comment by htdvisser** [comment]
I think we can remove the discussion label here. This is clearly something we need to do.

**Comment by KrishnaIyer** [comment]
This looks very promising but 
a. It's still in the `alpha` stage.
b. has the following issues with  `go` and`gogoproto`.
https://github.com/lyft/protoc-gen-validate/issues?q=is%3Aopen+is%3Aissue+label%3AGo

**Comment by johanstokking** [comment]
@rvolosatovs looks like you did your contribution for this issue, are you still assigned?

**Comment by rvolosatovs** [comment]
Nope.

**Comment by htdvisser** [comment]
We're closing this. Refer to https://github.com/TheThingsIndustries/protoc-gen-fieldmask/issues/21
