### ISSUE TITLE
Generic logging in to a remote stack from local CLI

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#99]
**Summary:** 

Logging into a remotely-deployed stack from locally-running CLI should be supported without binding to port 11885.
Also see #88
cc @johanstokking 

**Why do we need this?**

Users should be able to use CLI locally to manage their devices, applications and whatnot in TTN

**What is already there? What do you see now?**

https://github.com/TheThingsNetwork/lorawan-stack/blob/257f2821768159b0210a981eae6fb540854d6c5f/cmd/ttn-lw-cli/commands/login.go#L33-L73
Support for logins only when CLI uses port `11885`

**What is missing? What do you want to see?**

Support for remote logins regardless of whether port `11885` is used or not on user's machine

**How do you propose to implement this?**

Show a token during login in the browser, which the user can copy or allow specifying the callback URL in the frontend itself during login.

**Environment:**

Any

**Comment by rvolosatovs** [comment]
@proffalken I updated the issue - I was wrong, the remote logins are already supported for callback URL `http://localhost:11885/oauth/callback`

**Comment by pdubois22** [comment]
the call back to localhost may need the certificate or the ca certificate to validate the return token: go run ./cmd/ttn-lw-cli login --ca="/home/thethings/lorawan-stack/cert.pem" ...

**Comment by johanstokking** [comment]
Looping in @bafonins because I'm quite sure we need some subtle frontend engineering here.

**Comment by htdvisser** [comment]
We could implement this as follows:

1. The OAuth Client for the CLI will be registered in the IS with an extra whitelisted redirect URI: `<OAuthServerAddress>/oauth/code`
2. We add a `--copy-code` flag to the CLI that sets the redirect URI in the authorize link to `<OAuthServerAddress>/oauth/code`
3. We add a little frontend page on `/oauth/code` that displays the `code` from the query and tells the user to copy-paste it into the CLI. I think we no longer need the `state` param.
4. The CLI will interactively take the authorization code and do the exchange as usual.

**Comment by htdvisser** [comment]
In progress: https://github.com/TheThingsNetwork/lorawan-stack/tree/feature/99-copy-paste-oauth

**Comment by johanstokking** [comment]
@htdvisser shouldn't the `--copy-code` flag be default? I think this behavior is expected.

**Comment by rvolosatovs** [comment]
Can we do both?
So try sending the request from frontend to CLI first and if that fails - show the code to copy-paste.
The CLI simply always reads stdin after `login` and if the request arrives from frontend - proceeds immediately

**Comment by johanstokking** [comment]
That would make it time-dependent, and how would the frontend need to deal with this? The browser doesn't know if the redirect works.

Let's continue the discussion in #128. I made another suggestion there.

**Comment by Oliv4945** [comment]
> @htdvisser shouldn't the `--copy-code` flag be default? I think this behavior is expected.

I second that
