### ISSUE TITLE
Increase clickable area

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#997]
#### Summary

Increase clickable area

cc @janjongboom

#### Why do we need this?

Guide users

#### What is already there? What do you see now?

Small margins on primary buttons

#### What is missing? What do you want to see?

Higher margins, bigger buttons

Potentially also a color shade for other actions/buttons that are not primary, i.e. copy EUI/key buttons, navigation, breadcrumbs, etc

#### How do you propose to implement this?

Probably some CSS

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by kschiffer** [comment]
I disagree here. The margins/paddings we are using on buttons are not any smaller than, say, on GitHub. For users that would like bigger dimensions, there is always the option to zoom via the browser. 
Also, we have primary and secondary (and even more) button and link colors, which we use consistently (e.g. secondary button colors for EUI/key copy buttons).

**Comment by johanstokking** [comment]
Imho the difference is quite big;

GitHub:

<img width="285" alt="Screenshot 2019-07-17 at 12 57 23" src="https://user-images.githubusercontent.com/13334001/61370326-713c9c80-a892-11e9-842d-1f14d4035cf5.png">

V3 Console:

<img width="147" alt="Screenshot 2019-07-17 at 12 57 13" src="https://user-images.githubusercontent.com/13334001/61370322-6eda4280-a892-11e9-9965-467b4a9e5492.png">

It's probably a combination of font, font size, font weight and padding, but the GitHub buttons are definitely more friendly to click on.

**Comment by kschiffer** [comment]
In terms of height, they're exactly the same. Only the left/right paddings are smaller which I can adjust. Font size and weight might need some adjustments towards better legibility, but they don't influence the clickable area.

**Comment by johanstokking** [comment]
We don't consider this a problem
